#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel) <https://github.com/BTSpaniel>
#
# SPDX-License-Identifier: LicenseRef-ParticleRealms-Alpha
"""Hybrid API-reference extractor (Python-only, no Node).

Walks the JavaScript source of each subsystem and generates per-file reference
Markdown under ``MD/<subsystem>/reference/`` plus a ``_index.json`` consumed by
all three viewers.

Hybrid workflow:
  * The WHOLE page (signatures AND the Notes & Examples section) is regenerated
    every run, so the 1600+ reference files stay purely generated.
  * Hand-authored prose/examples live OUTSIDE the pages in an overlay tree and
    are injected below the ``<!-- HUMAN-NOTES -->`` marker on every run:
      - ``_notes/<subsystem>/<module>.md``  per-page notes (write for one page)
      - ``_notes/_shared.json``             reusable blocks applied to many pages
                                            by glob (write once, apply everywhere)
    Because notes are separate files, regenerating from scratch never clobbers
    them, and common context is authored once instead of copied onto every page.

Usage:
    python tools/extract_api.py                 # all subsystems
    python tools/extract_api.py webgpu-os agi   # only the named subsystems

Author: Jake Wehmeier (BTSpaniel) — https://github.com/BTSpaniel
"""
import fnmatch
import hashlib
import json
import re
import sys
from pathlib import Path

MD = Path(__file__).resolve().parents[1]
REPO = MD.parent

HUMAN_MARKER = "<!-- HUMAN-NOTES -->"
GEN_HEADER = "<!-- AUTOGENERATED by tools/extract_api.py — content above HUMAN-NOTES is overwritten -->"

# Hand-authored notes live OUTSIDE the generated pages, in an overlay tree, so
# the 1600+ reference files stay purely generated (regenerable from scratch) and
# notes are never at risk of being clobbered:
#   _notes/<subsystem>/<module>.md   per-page notes (e.g. _notes/engine/math/Vec3.md)
#   _notes/_shared.json              reusable blocks applied to many pages by glob
# The extractor injects the per-page overlay + any matching shared blocks below
# the HUMAN-NOTES marker on every run.
NOTES_DIR = MD / "_notes"
SHARED_NOTES = NOTES_DIR / "_shared.json"
NOTES_PLACEHOLDER = (
    "_No hand-authored notes yet. Add page notes in "
    "`_notes/" + "{subsystem}/{module}.md`" + " or a reusable block in "
    "`_notes/_shared.json` — see [API Reference Standard]"
    "(../../contributing/api-reference-standard.md)._"
)
LEGACY_GPU_NOTE_SENTENCE = (
    "never call `navigator.gpu.requestDevice()` yourself, since a second device "
    "causes context loss and detached buffers"
)

# subsystem -> {source root, included subdirs (None = all), label}
SUBSYSTEMS = {
    "engine": {"root": REPO / "engine", "include": None},
    "editor": {"root": REPO / "editor" / "js", "include": None},
    "plauna": {"root": REPO / "plauna", "include": None},
    "agi": {"root": REPO / "agi", "include": None},
    "webgpu-os": {
        "root": REPO / "webgpu-os",
        "include": ["kernel", "shell", "packages", "storage", "drivers",
                     "browser-bridge", "browser-extension"],
    },
}

EXCLUDE_DIRS = {"node_modules", "vendor", "dist", "build", ".git", "__pycache__",
                "docs", "tests", "test", "examples"}
EXCLUDE_FILE_RE = re.compile(r"\.(min|generated|bundle)\.js$|\.test\.js$|\.spec\.js$")

METHOD_KEYWORDS = {"if", "for", "while", "switch", "catch", "return", "function",
                   "do", "else", "await", "typeof", "new", "super", "delete", "void"}
IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][\w$]*$")


# --------------------------------------------------------------------------- #
# small JS parsing helpers (regex + brace matching, good enough for reference)  #
# --------------------------------------------------------------------------- #
def balanced_block(text: str, brace_pos: int) -> str:
    """Return the substring of the balanced { ... } starting at brace_pos."""
    depth, i, n = 0, brace_pos, len(text)
    while i < n:
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[brace_pos:i + 1]
        i += 1
    return text[brace_pos:]


def jsdoc_before(text: str, pos: int):
    """Return the JSDoc block immediately preceding `pos`, if any.

    Only matches a single, well-formed ``/** ... */`` whose closing marker is
    immediately before `pos` (separated by whitespace only). The inner
    ``(?:(?!\\*/).)*`` forbids crossing a ``*/`` so the match never spans code
    or an earlier comment.
    """
    head = text[:pos]
    m = re.search(r"/\*\*((?:(?!\*/).)*)\*/\s*$", head, re.DOTALL)
    return m.group(1) if m else None


def parse_jsdoc(doc: str):
    """Return (summary, [(param, type, desc)], returns_desc)."""
    if not doc:
        return "", [], ""
    lines = [re.sub(r"^\s*\*?\s?", "", ln) for ln in doc.splitlines()]
    summary_parts, params, returns = [], [], ""
    for ln in lines:
        pm = re.match(r"@param\s+(?:\{([^}]*)\}\s+)?(\[?[\w.$]+\]?)\s*-?\s*(.*)", ln)
        rm = re.match(r"@returns?\s+(?:\{[^}]*\}\s*)?-?\s*(.*)", ln)
        if pm:
            params.append((pm.group(2), pm.group(1) or "", pm.group(3).strip()))
        elif rm:
            returns = rm.group(1).strip()
        elif ln.startswith("@"):
            continue
        elif not params and not returns:
            summary_parts.append(ln.strip())
    summary = " ".join(p for p in summary_parts if p).strip()
    return summary, params, returns


def file_description(text: str) -> str:
    # License headers identify the file but are not API descriptions. Remove the
    # standard SPDX preamble before looking for a module-level comment so it
    # cannot become the generated page summary.
    text = re.sub(
        r"\A\s*(?:(?://[^\n]*SPDX[^\n]*\n)|(?://\s*\n))*",
        "",
        text,
        flags=re.IGNORECASE,
    )
    m = re.match(r"\s*(?:#![^\n]*\n)?\s*/\*\*?(.*?)\*/", text, re.DOTALL)
    if m:
        summary, _, _ = parse_jsdoc(m.group(1))
        if summary:
            return summary
    # fall back to leading // comment lines
    lead = []
    for ln in text.splitlines():
        s = ln.strip()
        if s.startswith("//"):
            lead.append(s.lstrip("/ ").strip())
        elif s == "":
            if lead:
                break
        else:
            break
    return " ".join(lead).strip()


def export_descriptors(info: dict) -> list:
    """Return a stable, JSON-safe public export catalog for one module.

    The catalog deliberately includes only syntax the extractor positively
    identifies. It never guesses aliases, runtime types, or undocumented
    behavior. Consumers can use ``source`` and ``sourceHash`` from the index to
    verify the result against the exact source revision.
    """
    exports = []
    for cls in info["classes"]:
        signature = f"class {cls['name']}"
        if cls["extends"]:
            signature += f" extends {cls['extends']}"
        exports.append({
            "name": cls["name"],
            "kind": "class",
            "signature": signature,
            "summary": cls["summary"] or "",
        })
    for func in info["functions"]:
        prefix = "async " if func["async"] else ""
        exports.append({
            "name": func["name"],
            "kind": "function",
            "signature": f"{prefix}{func['name']}({func['args']})",
            "summary": func["summary"] or "",
        })
    for const in info["consts"]:
        exports.append({
            "name": const["name"],
            "kind": "constant",
            "signature": const["name"],
            "summary": const["summary"] or "",
        })
    for name in sorted(set(info["reexports"])):
        if any(item["name"] == name for item in exports):
            continue
        exports.append({
            "name": name,
            "kind": "re-export",
            "signature": name,
            "summary": "",
        })
    return exports


def module_summary(description: str, exports: list) -> str:
    """Choose a source-backed summary without inventing module behavior."""
    if description and "SPDX-" not in description:
        return description
    for item in exports:
        if item["summary"]:
            return item["summary"]
    return ""


def extract_methods(body: str):
    """Extract method-like declarations from a class body."""
    methods = []
    pat = re.compile(
        r"(?:^|\n)[ \t]*((?:static\s+|async\s+|get\s+|set\s+|\*\s*)*)"
        r"([A-Za-z_$][\w$]*)\s*\(([^)]*)\)\s*\{")
    for m in pat.finditer(body):
        name = m.group(2)
        if name in METHOD_KEYWORDS:
            continue
        mods = m.group(1).strip()
        args = re.sub(r"\s+", " ", m.group(3).strip())
        summary, _, _ = parse_jsdoc(jsdoc_before(body, m.start()))
        methods.append((mods, name, args, summary))
    return methods


def parse_file(text: str):
    info = {"classes": [], "functions": [], "consts": [], "reexports": []}

    for m in re.finditer(
            r"export\s+(?:default\s+)?class\s+([A-Za-z_$][\w$]*)"
            r"(?:\s+extends\s+([\w.$]+))?\s*\{", text):
        name, extends = m.group(1), m.group(2)
        brace = text.index("{", m.start())
        body = balanced_block(text, brace)
        summary, _, _ = parse_jsdoc(jsdoc_before(text, m.start()))
        info["classes"].append({
            "name": name, "extends": extends, "summary": summary,
            "methods": extract_methods(body),
        })

    for m in re.finditer(
            r"export\s+(?:default\s+)?(async\s+)?function\s+\*?([A-Za-z_$][\w$]*)"
            r"\s*\(([^)]*)\)", text):
        summary, params, returns = parse_jsdoc(jsdoc_before(text, m.start()))
        info["functions"].append({
            "name": m.group(2), "async": bool(m.group(1)),
            "args": re.sub(r"\s+", " ", m.group(3).strip()),
            "summary": summary, "params": params, "returns": returns,
        })

    for m in re.finditer(
            r"export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*(async\s*)?"
            r"(\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>", text):
        summary, params, returns = parse_jsdoc(jsdoc_before(text, m.start()))
        args = m.group(3)
        info["functions"].append({
            "name": m.group(1), "async": bool(m.group(2)),
            "args": args.strip("()"), "summary": summary,
            "params": params, "returns": returns,
        })

    for m in re.finditer(r"export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*(?![^\n=]*=>)", text):
        name = m.group(1)
        if name not in [f["name"] for f in info["functions"]]:
            summary, _, _ = parse_jsdoc(jsdoc_before(text, m.start()))
            info["consts"].append({"name": name, "summary": summary})

    for m in re.finditer(r"export\s*\{([^}]*)\}", text):
        # Comments inside a barrel export are not symbols. Strip them before
        # splitting and accept only valid JavaScript identifiers. For
        # ``sourceName as publicName``, catalog the public export name.
        block = re.sub(r"/\*[\s\S]*?\*/|//[^\r\n]*", "", m.group(1))
        for raw in block.split(","):
            candidate = re.sub(r"\s+", " ", raw.strip())
            if not candidate:
                continue
            alias = re.fullmatch(
                r"([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?",
                candidate,
            )
            if not alias:
                continue
            public_name = alias.group(2) or alias.group(1)
            if IDENTIFIER_RE.fullmatch(public_name):
                info["reexports"].append(public_name)

    return info


# --------------------------------------------------------------------------- #
# markdown rendering                                                            #
# --------------------------------------------------------------------------- #
def render_markdown(module_path: str, src_rel: str, desc: str, info, notes_body: str) -> str:
    # Stable frontmatter only (no volatile timestamp) so regeneration is churn-free.
    out = ["---", f"title: {module_path}", "kind: reference",
           f"source: {src_rel}", "---", "",
           GEN_HEADER, "", f"# `{module_path}`", "",
           f"> **Source:** `{src_rel}`", ""]
    out.append(desc if desc else "_No file-level description found in source. "
               "Add one as a leading `/** ... */` JSDoc comment, or document it below._")
    out.append("")

    total = (len(info["classes"]) + len(info["functions"]) +
             len(info["consts"]) + len(info["reexports"]))
    if total == 0:
        out += ["## Exports", "", "_No ES module exports detected in this file._", ""]

    if info["classes"]:
        out += ["## Classes", ""]
        for c in info["classes"]:
            sig = f"class {c['name']}" + (f" extends {c['extends']}" if c["extends"] else "")
            out += [f"### `{sig}`", ""]
            if c["summary"]:
                out += [c["summary"], ""]
            if c["methods"]:
                out += ["| Method | Signature | Summary |", "| --- | --- | --- |"]
                for mods, name, args, msum in c["methods"]:
                    label = (mods + " " if mods else "") + name
                    out.append(f"| `{name}` | `{label}({args})` | {msum or ''} |")
                out.append("")

    if info["functions"]:
        out += ["## Functions", ""]
        for f in info["functions"]:
            prefix = "async " if f["async"] else ""
            out += [f"### `{prefix}{f['name']}({f['args']})`", ""]
            if f["summary"]:
                out += [f["summary"], ""]
            if f["params"]:
                out += ["**Parameters:**", ""]
                for pname, ptype, pdesc in f["params"]:
                    t = f" *({ptype})*" if ptype else ""
                    out.append(f"- `{pname}`{t} — {pdesc or '_No description in source JSDoc._'}")
                out.append("")
            if f["returns"]:
                out += [f"**Returns:** {f['returns']}", ""]

    if info["consts"]:
        out += ["## Constants", ""]
        for c in info["consts"]:
            out.append(f"- `{c['name']}`" + (f" — {c['summary']}" if c["summary"] else ""))
        out.append("")

    if info["reexports"]:
        out += ["## Re-exports", "",
                ", ".join(f"`{n}`" for n in sorted(set(info["reexports"]))), ""]

    out += ["", HUMAN_MARKER, "",
            "## Notes & Examples", "",
            notes_body, ""]
    return "\n".join(out)


def load_shared_blocks():
    """Reusable note blocks — write once, apply to many pages.

    Schema in ``_notes/_shared.json``::

        {"blocks": [
          {"id": "gpu-device", "title": "Shared GPU device",
           "applies": ["engine/reference/**", "webgpu-os/reference/drivers/*"],
           "body": "Markdown body ..."}
        ]}

    Each ``applies`` glob is matched (fnmatch) against a page's reference path,
    e.g. ``engine/reference/core/gpu/VirtualGPU``.
    """
    if not SHARED_NOTES.exists():
        return []
    try:
        data = json.loads(SHARED_NOTES.read_text(encoding="utf-8"))
    except Exception as exc:  # report and continue — notes are best-effort
        print(f"  ! _notes/_shared.json parse error: {exc}")
        return []
    return data.get("blocks", [])


def overlay_path(subsystem: str, module_path: str) -> Path:
    """Path of the per-page hand-notes overlay file."""
    return NOTES_DIR / subsystem / (module_path + ".md")


def remove_legacy_materialized_gpu_note(path: Path) -> bool:
    """Remove an obsolete shared GPU block copied into a per-page overlay.

    An early migration materialized the old reusable block into hundreds of
    otherwise-empty overlays. Keeping those copies would place the obsolete,
    invented API beside the corrected shared block forever. Delete only files
    that contain that exact legacy claim and no second note section; any mixed
    or independently authored overlay is preserved for manual review.
    """
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace").strip()
    if (
        text.startswith("### Shared GPU device")
        and LEGACY_GPU_NOTE_SENTENCE in text
        and len(re.findall(r"(?m)^###\s+", text)) == 1
    ):
        path.unlink()
        return True
    return False


def matching_shared_sections(ref_path: str, shared) -> list[str]:
    """Render the reusable sections that apply to one reference path."""
    sections = []
    for block in shared:
        applies = block.get("applies") or []
        if not any(fnmatch.fnmatch(ref_path, pattern) for pattern in applies):
            continue
        title = block.get("title") or block.get("id") or "Note"
        body = (block.get("body") or "").strip()
        sections.append(f"### {title}\n\n{body}".rstrip())
    return sections


def strip_shared_suffix(body: str, ref_path: str, shared) -> str:
    """Remove generated shared sections appended to an old reference page."""
    remainder = body.strip()
    for section in reversed(matching_shared_sections(ref_path, shared)):
        if remainder == section:
            remainder = ""
        elif remainder.endswith("\n\n" + section):
            remainder = remainder[:-(len(section) + 2)].rstrip()
    return remainder


def remove_materialized_shared_overlay(path: Path, ref_path: str, shared) -> bool:
    """Delete an overlay that is only a generated copy of shared sections."""
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace").strip()
    generated = "\n\n".join(matching_shared_sections(ref_path, shared)).strip()
    if generated and text == generated:
        path.unlink()
        return True
    return False


def compose_notes(subsystem: str, module_path: str, ref_path: str, shared) -> str:
    """Assemble the Notes & Examples body: the per-page overlay first, then any
    matching shared blocks. Falls back to the placeholder when nothing applies."""
    parts = []
    ov = overlay_path(subsystem, module_path)
    remove_legacy_materialized_gpu_note(ov)
    remove_materialized_shared_overlay(ov, ref_path, shared)
    if ov.exists():
        txt = ov.read_text(encoding="utf-8", errors="replace").strip()
        if txt:
            parts.append(txt)
    parts.extend(matching_shared_sections(ref_path, shared))
    if not parts:
        return NOTES_PLACEHOLDER.replace("{subsystem}", subsystem).replace("{module}", module_path)
    return "\n\n".join(parts)


def migrate_inline_to_overlay(
        out_path: Path, subsystem: str, module_path: str, ref_path: str, shared) -> None:
    """One-time safety net: if a page still carries custom (non-placeholder)
    inline notes and no overlay exists yet, move them into the overlay so the
    switch to file-based notes never loses hand-written prose."""
    if not out_path.exists():
        return
    old = out_path.read_text(encoding="utf-8", errors="replace")
    if HUMAN_MARKER not in old:
        return
    tail = old.split(HUMAN_MARKER, 1)[1]
    body = re.sub(r"^\s*##\s+Notes\s*&\s*Examples\s*", "", tail, flags=re.I).strip()
    body = strip_shared_suffix(body, ref_path, shared)
    if not body or "Hand-authored context, usage examples" in body or "No hand-authored notes yet" in body:
        return
    ov = overlay_path(subsystem, module_path)
    if ov.exists():
        return
    ov.parent.mkdir(parents=True, exist_ok=True)
    ov.write_text(body + "\n", encoding="utf-8")
    print(f"  migrated inline notes -> {ov.relative_to(MD)}")


# --------------------------------------------------------------------------- #
# driver                                                                        #
# --------------------------------------------------------------------------- #
def iter_sources(root: Path, include):
    roots = [root / d for d in include] if include else [root]
    for base in roots:
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.js")):
            if any(part in EXCLUDE_DIRS for part in path.relative_to(root).parts):
                continue
            if EXCLUDE_FILE_RE.search(path.name):
                continue
            yield path


def process_subsystem(name: str, cfg: dict, shared) -> int:
    root = cfg["root"]
    if not root.exists():
        print(f"  ! source root missing: {root}")
        return 0
    ref_dir = MD / name / "reference"
    ref_dir.mkdir(parents=True, exist_ok=True)
    index = []
    count = 0
    noted = 0
    modules_with_summary = 0
    exports_total = 0
    exports_with_summary = 0
    for src in iter_sources(root, cfg["include"]):
        rel = src.relative_to(root).as_posix()
        module_path = rel[:-3]  # drop .js
        out_path = ref_dir / (module_path + ".md")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        ref_path = f"{name}/reference/{module_path}"
        migrate_inline_to_overlay(out_path, name, module_path, ref_path, shared)
        text = src.read_text(encoding="utf-8", errors="replace")
        desc = file_description(text)
        info = parse_file(text)
        src_rel = src.relative_to(REPO).as_posix()
        exports = export_descriptors(info)
        summary = module_summary(desc, exports)
        modules_with_summary += int(bool(summary))
        exports_total += len(exports)
        exports_with_summary += sum(bool(item["summary"]) for item in exports)
        notes_body = compose_notes(name, module_path, ref_path, shared)
        if "No hand-authored notes yet" not in notes_body:
            noted += 1
        md = render_markdown(rel, src_rel, desc, info, notes_body)
        out_path.write_text(md, encoding="utf-8")
        index.append({
            "schemaVersion": 1,
            "title": module_path,
            "path": f"{name}/reference/{module_path}.md",
            "source": src_rel,
            "import": f"/{src_rel}",
            "sourceHash": hashlib.sha256(text.encode("utf-8")).hexdigest(),
            "summary": summary,
            "exports": exports,
        })
        count += 1
    index.sort(key=lambda x: x["title"])
    (ref_dir / "_index.json").write_text(json.dumps(index, ensure_ascii=False, indent=2),
                                         encoding="utf-8")
    module_coverage = (modules_with_summary / count * 100) if count else 0.0
    export_coverage = (exports_with_summary / exports_total * 100) if exports_total else 0.0
    print(
        f"  {name}: {count} reference pages ({noted} with hand/shared notes); "
        f"source summary coverage {modules_with_summary}/{count} ({module_coverage:.1f}% modules), "
        f"{exports_with_summary}/{exports_total} ({export_coverage:.1f}% exports) "
        f"-> {ref_dir.relative_to(MD)}"
    )
    return count


def main(argv) -> int:
    targets = argv or list(SUBSYSTEMS.keys())
    unknown = [t for t in targets if t not in SUBSYSTEMS]
    if unknown:
        print(f"Unknown subsystem(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"Known: {', '.join(SUBSYSTEMS)}", file=sys.stderr)
        return 2
    print("Generating API reference (hybrid: auto signatures + overlay notes)")
    shared = load_shared_blocks()
    if shared:
        print(f"  loaded {len(shared)} shared note block(s) from _notes/_shared.json")
    total = 0
    for name in targets:
        total += process_subsystem(name, SUBSYSTEMS[name], shared)
    print(f"\nDone. {total} reference pages generated/updated.")
    print("Next: run `python tools/build_docs.py` to refresh the search index.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
