// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
@binding(10) @group(0) var colorIn_0 : texture_2d<f32>;

struct ImguiRendererParams_std140_0
{
    @align(16) numVertices_0 : u32,
    @align(4) numIndices_0 : u32,
    @align(8) numDrawCmds_0 : u32,
    @align(4) numBlocks_0 : u32,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) tileGridDim_x_0 : u32,
    @align(4) tileGridDim_y_0 : u32,
    @align(8) tileGridDim_xy_0 : u32,
    @align(4) tileDimBits_0 : u32,
    @align(16) maxTriangles_0 : u32,
    @align(4) tileNumTrianglesOffset_0 : u32,
    @align(8) tileLocalScanOffset_0 : u32,
    @align(4) tileLocalTotalOffset_0 : u32,
    @align(16) tileGlobalScanOffset_0 : u32,
    @align(4) numTileBuckets_0 : u32,
    @align(8) numTileBucketPasses_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : ImguiRendererParams_std140_0;
@binding(9) @group(0) var<storage, read> triangleRangeIn_0 : array<vec2<u32>>;

@binding(8) @group(0) var<storage, read> triangleIn_0 : array<u32>;

struct ImguiRendererDrawCmd_std430_0
{
    @align(16) clipRect_0 : vec4<f32>,
    @align(16) elemCount_0 : u32,
    @align(4) userTexture_0 : u32,
    @align(8) vertexOffset_0 : u32,
    @align(4) indexOffset_0 : u32,
};

@binding(4) @group(0) var<storage, read> drawCmdsIn_0 : array<ImguiRendererDrawCmd_std430_0>;

@binding(3) @group(0) var<storage, read> indicesIn_0 : array<u32>;

@binding(1) @group(0) var<storage, read> vertexPosTexCoordIn_0 : array<vec4<f32>>;

@binding(2) @group(0) var<storage, read> vertexColorIn_0 : array<u32>;

@binding(5) @group(0) var<storage, read> textureTableIn_0 : array<u32>;

@binding(6) @group(0) var textureIn_0 : texture_2d<f32>;

@binding(7) @group(0) var samplerIn_0 : sampler;

@binding(11) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

fn edgeTest_0( edgeA_fp_0 : vec2<f32>,  edgeB_fp_0 : vec2<f32>,  inside_fp_0 : vec2<f32>,  pt_fp_0 : vec2<f32>) -> bool
{
    var _S1 : vec2<i32> = vec2<i32>(edgeA_fp_0);
    var _S2 : vec2<i32> = vec2<i32>(edgeB_fp_0);
    var _S3 : vec2<i32> = vec2<i32>(inside_fp_0);
    var _S4 : vec2<i32> = vec2<i32>(pt_fp_0);
    var m_0 : vec2<i32> = _S2 - _S1;
    var _S5 : i32 = m_0.y;
    var _S6 : i32 = m_0.x;
    var isBelow_0 : bool;
    if((abs(_S5)) > (abs(_S6)))
    {
        var _S7 : i32 = _S2.y;
        var _S8 : i32 = _S3.y;
        var _S9 : i32 = _S1.x;
        var _S10 : i32 = _S1.y;
        var _S11 : i32 = _S2.x;
        var _S12 : f32 = f32(_S5);
        var _S13 : i32 = _S4.y;
        var cmpX_0 : i32 = i32(f32((_S7 - _S13) * _S9 - (_S10 - _S13) * _S11) / _S12);
        if((_S3.x) < i32(f32((_S7 - _S8) * _S9 - (_S10 - _S8) * _S11) / _S12))
        {
            isBelow_0 = (_S4.x) < cmpX_0;
        }
        else
        {
            isBelow_0 = (_S4.x) >= cmpX_0;
        }
    }
    else
    {
        var _S14 : i32 = _S2.x;
        var _S15 : i32 = _S3.x;
        var _S16 : i32 = _S1.y;
        var _S17 : i32 = _S1.x;
        var _S18 : i32 = _S2.y;
        var _S19 : f32 = f32(_S6);
        var _S20 : i32 = _S4.x;
        var cmpY_0 : i32 = i32(f32((_S14 - _S20) * _S16 - (_S17 - _S20) * _S18) / _S19);
        if((_S3.y) < i32(f32((_S14 - _S15) * _S16 - (_S17 - _S15) * _S18) / _S19))
        {
            isBelow_0 = (_S4.y) < cmpY_0;
        }
        else
        {
            isBelow_0 = (_S4.y) >= cmpY_0;
        }
    }
    return isBelow_0;
}

fn computeBary_0( p1_0 : vec2<f32>,  p2_0 : vec2<f32>,  p3_0 : vec2<f32>,  p_0 : vec2<f32>) -> vec3<f32>
{
    var _S21 : f32 = p3_0.y;
    var _S22 : f32 = p2_0.y - _S21;
    var _S23 : f32 = p3_0.x;
    var _S24 : f32 = p1_0.x - _S23;
    var _S25 : f32 = _S23 - p2_0.x;
    var _S26 : f32 = p1_0.y;
    var det_0 : f32 = _S22 * _S24 + _S25 * (_S26 - _S21);
    var _S27 : f32 = p_0.x - _S23;
    var _S28 : f32 = p_0.y - _S21;
    var b1_0 : f32 = (_S22 * _S27 + _S25 * _S28) / det_0;
    var b2_0 : f32 = ((_S21 - _S26) * _S27 + _S24 * _S28) / det_0;
    return vec3<f32>(b1_0, b2_0, 1.0f - b1_0 - b2_0);
}

fn convertColor_0( val_0 : u32) -> vec4<f32>
{
    return vec4<f32>(f32((((val_0 >> (u32(0)))) & (u32(255)))) * 0.00392156885936856f, f32((((val_0 >> (u32(8)))) & (u32(255)))) * 0.00392156885936856f, f32((((val_0 >> (u32(16)))) & (u32(255)))) * 0.00392156885936856f, f32((((val_0 >> (u32(24)))) & (u32(255)))) * 0.00392156885936856f);
}

fn texture_sample_0( uv_0 : vec2<f32>,  texId_0 : u32) -> vec4<f32>
{
    var _S29 : bool;
    var tableSize_0 : u32 = textureTableIn_0[u32(0)];
    var atlasGridWidthBits_0 : u32 = textureTableIn_0[u32(1)];
    var atlasWidthInv_0 : f32 = (bitcast<f32>((textureTableIn_0[u32(2)])));
    var atlasHeightInv_0 : f32 = (bitcast<f32>((textureTableIn_0[u32(3)])));
    const _S30 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var tableIdx_0 : u32 = u32(0);
    for(;;)
    {
        var _S31 : bool = tableIdx_0 < tableSize_0;
        _S29 = _S31;
        if(_S31)
        {
        }
        else
        {
            break;
        }
        if(textureTableIn_0[u32(4) + tableIdx_0] == texId_0)
        {
            break;
        }
        tableIdx_0 = tableIdx_0 + u32(1);
    }
    var value_0 : vec4<f32>;
    if(_S29)
    {
        var _S32 : u32 = u32(4) + tableSize_0 + u32(4) * tableIdx_0;
        var texCoordf_0 : vec2<f32> = vec2<f32>(f32(textureTableIn_0[_S32]), f32(textureTableIn_0[_S32 + u32(1)])) * fract(uv_0);
        var _S33 : vec2<u32> = vec2<u32>(u32(4));
        var _S34 : vec2<u32> = vec2<u32>((vec2<i32>(floor(texCoordf_0)) >> (_S33)));
        var tileCoord1D_0 : u32 = _S34.y * textureTableIn_0[_S32 + u32(2)] + _S34.x + textureTableIn_0[_S32 + u32(3)];
        value_0 = (textureSampleLevel((textureIn_0), (samplerIn_0), ((texCoordf_0 - vec2<f32>((_S34 << (_S33))) + vec2<f32>(18.0f) * vec2<f32>(vec2<u32>((tileCoord1D_0 & ((((u32(1) << (atlasGridWidthBits_0))) - u32(1)))), (tileCoord1D_0 >> (atlasGridWidthBits_0)))) + vec2<f32>(1.0f)) * vec2<f32>(atlasWidthInv_0, atlasHeightInv_0)), (0.0f)));
    }
    else
    {
        value_0 = _S30;
    }
    return value_0;
}

fn leaf_0( p_1 : vec2<f32>,  triangleIdx_0 : u32,  texId_1 : u32) -> vec4<f32>
{
    var indexOffsetLocal_0 : u32 = u32(3) * triangleIdx_0;
    var idx0_0 : u32 = indicesIn_0[indexOffsetLocal_0];
    var idx1_0 : u32 = indicesIn_0[indexOffsetLocal_0 + u32(1)];
    var idx2_0 : u32 = indicesIn_0[indexOffsetLocal_0 + u32(2)];
    var pos0_0 : vec4<f32> = vertexPosTexCoordIn_0[idx0_0];
    var pos1_0 : vec4<f32> = vertexPosTexCoordIn_0[idx1_0];
    var pos2_0 : vec4<f32> = vertexPosTexCoordIn_0[idx2_0];
    var _S35 : vec2<f32> = vec2<f32>(16.0f);
    var p1_1 : vec2<f32> = _S35 * pos0_0.xy;
    var p2_1 : vec2<f32> = _S35 * pos1_0.xy;
    var p3_1 : vec2<f32> = _S35 * pos2_0.xy;
    var passed_0 : bool;
    if(edgeTest_0(p1_1, p2_1, p3_1, p_1))
    {
        passed_0 = edgeTest_0(p2_1, p3_1, p1_1, p_1);
    }
    else
    {
        passed_0 = false;
    }
    if(passed_0)
    {
        passed_0 = edgeTest_0(p3_1, p1_1, p2_1, p_1);
    }
    else
    {
        passed_0 = false;
    }
    const _S36 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var c_0 : vec4<f32>;
    if(passed_0)
    {
        var b_0 : vec3<f32> = computeBary_0(p1_1, p2_1, p3_1, p_1);
        var _S37 : f32 = b_0.x;
        var _S38 : f32 = b_0.y;
        var _S39 : f32 = b_0.z;
        c_0 = (vec4<f32>(_S37) * convertColor_0(vertexColorIn_0[idx0_0]) + vec4<f32>(_S38) * convertColor_0(vertexColorIn_0[idx1_0]) + vec4<f32>(_S39) * convertColor_0(vertexColorIn_0[idx2_0])) * texture_sample_0(vec2<f32>(_S37) * pos0_0.zw + vec2<f32>(_S38) * pos1_0.zw + vec2<f32>(_S39) * pos2_0.zw, texId_1);
    }
    else
    {
        c_0 = _S36;
    }
    return c_0;
}

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var _S40 : vec2<i32> = vec2<i32>(dispatchThreadID_0.xy);
    var _S41 : vec2<u32> = vec2<u32>(_S40);
    var _S42 : vec3<i32> = vec3<i32>(vec3<u32>(_S41, u32(0)));
    var color_0 : vec4<f32> = (textureLoad((colorIn_0), ((_S42)).xy, ((_S42)).z));
    var _S43 : i32 = _S40.x;
    var _S44 : i32 = _S40.y;
    var _S45 : i32 = (_S44 >> ((paramsIn_0.tileDimBits_0)));
    var tileIdx1D_0 : i32 = i32(u32(_S45) * paramsIn_0.tileGridDim_x_0 + u32((_S43 >> ((paramsIn_0.tileDimBits_0)))));
    if(_S45 >= i32(paramsIn_0.tileGridDim_y_0))
    {
        color_0[i32(1)] = 1.0f;
    }
    var _S46 : vec2<u32> = triangleRangeIn_0[tileIdx1D_0];
    var _S47 : vec2<f32> = vec2<f32>(16.0f) * (vec2<f32>(_S40) + vec2<f32>(0.5f, 0.5f));
    var _S48 : u32 = _S46.y;
    var _S49 : u32 = _S46.x;
    var _S50 : f32 = f32(_S43);
    var _S51 : f32 = f32(_S44);
    var listIdx_0 : u32 = u32(0);
    for(;;)
    {
        if(listIdx_0 < _S48)
        {
        }
        else
        {
            break;
        }
        var triangleIdxRaw_0 : u32 = triangleIn_0[_S49 + listIdx_0];
        var drawCmdIdx_0 : u32 = (triangleIdxRaw_0 >> (u32(24)));
        var c_1 : vec4<f32> = leaf_0(_S47, (triangleIdxRaw_0 & (u32(16777215))), drawCmdsIn_0[drawCmdIdx_0].userTexture_0);
        var _S52 : vec4<f32> = drawCmdsIn_0[drawCmdIdx_0].clipRect_0;
        var _S53 : bool;
        if(_S50 >= (drawCmdsIn_0[drawCmdIdx_0].clipRect_0.x))
        {
            _S53 = _S51 >= (_S52.y);
        }
        else
        {
            _S53 = false;
        }
        var _S54 : bool;
        if(_S53)
        {
            _S54 = _S50 < (_S52.z);
        }
        else
        {
            _S54 = false;
        }
        var _S55 : bool;
        if(_S54)
        {
            _S55 = _S51 < (_S52.w);
        }
        else
        {
            _S55 = false;
        }
        if(_S55)
        {
            var _S56 : f32 = c_1.w;
            color_0 = vec4<f32>((1.0f - _S56)) * color_0 + vec4<f32>(_S56) * c_1;
        }
        listIdx_0 = listIdx_0 + u32(1);
    }
    textureStore((colorOut_0), (_S41), (color_0));
    return;
}

