// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct ImguiRendererParams_std140_0
{
    @align(16) numVertices_0 : u32,
    @align(4) numIndices_0 : u32,
    @align(8) numDrawCmds_0 : u32,
    @align(4) numBlocks_0 : u32,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) tileGridDim_x_0 : u32,
    @align(4) tileGridDim_y_0 : u32,
    @align(8) tileGridDim_xy_0 : u32,
    @align(4) tileDimBits_0 : u32,
    @align(16) maxTriangles_0 : u32,
    @align(4) tileNumTrianglesOffset_0 : u32,
    @align(8) tileLocalScanOffset_0 : u32,
    @align(4) tileLocalTotalOffset_0 : u32,
    @align(16) tileGlobalScanOffset_0 : u32,
    @align(4) numTileBuckets_0 : u32,
    @align(8) numTileBucketPasses_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : ImguiRendererParams_std140_0;
@binding(3) @group(0) var<storage, read> indicesIn_0 : array<u32>;

@binding(1) @group(0) var<storage, read> vertexPosTexCoordIn_0 : array<vec4<f32>>;

@binding(5) @group(0) var<storage, read_write> treeOut_0 : array<vec4<i32>>;

@binding(2) @group(0) var<storage, read> vertexColorIn_0 : array<u32>;

struct ImguiRendererDrawCmd_std430_0
{
    @align(16) clipRect_0 : vec4<f32>,
    @align(16) elemCount_0 : u32,
    @align(4) userTexture_0 : u32,
    @align(8) vertexOffset_0 : u32,
    @align(4) indexOffset_0 : u32,
};

@binding(4) @group(0) var<storage, read> drawCmdsIn_0 : array<ImguiRendererDrawCmd_std430_0>;

var<workgroup> sdata0_0 : array<vec4<i32>, i32(256)>;

fn accumMinMax_0( a_0 : vec4<i32>,  b_0 : vec4<i32>) -> vec4<i32>
{
    var _S1 : bool;
    if((b_0.x) == (b_0.z))
    {
        _S1 = (b_0.y) == (b_0.w);
    }
    else
    {
        _S1 = false;
    }
    if(_S1)
    {
        return a_0;
    }
    else
    {
        return vec4<i32>(min(a_0.xy, b_0.xy), max(a_0.zw, b_0.zw));
    }
}

var<workgroup> sdata1_0 : array<vec4<i32>, i32(64)>;

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var tidx_0 : i32 = i32(dispatchThreadID_0.x);
    var _S2 : u32 = u32(tidx_0);
    var threadIdx_0 : u32 = (_S2 & (u32(255)));
    const _S3 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
    var minMaxPos_0 : vec4<i32>;
    if((i32(3) * tidx_0) < i32(paramsIn_0.numIndices_0))
    {
        var indexOffset_1 : u32 = u32(3) * _S2;
        var pos0_0 : vec2<f32> = vertexPosTexCoordIn_0[indicesIn_0[indexOffset_1]].xy;
        var pos1_0 : vec2<f32> = vertexPosTexCoordIn_0[indicesIn_0[indexOffset_1 + u32(1)]].xy;
        var pos2_0 : vec2<f32> = vertexPosTexCoordIn_0[indicesIn_0[indexOffset_1 + u32(2)]].xy;
        minMaxPos_0 = vec4<i32>(vec2<i32>(floor(min(pos0_0, min(pos1_0, pos2_0)))), vec2<i32>(- floor(- max(pos0_0, max(pos1_0, pos2_0))) + vec2<f32>(1.0f, 1.0f)));
    }
    else
    {
        minMaxPos_0 = _S3;
    }
    var treeBaseIdx_0 : u32 = u32(341) * u32((tidx_0 >> (u32(8))));
    sdata0_0[threadIdx_0] = minMaxPos_0;
    var _S4 : u32 = treeBaseIdx_0 + threadIdx_0;
    treeOut_0[_S4 + u32(85)] = minMaxPos_0;
    workgroupBarrier();
    if(threadIdx_0 < u32(64))
    {
        var _S5 : u32 = u32(4) * threadIdx_0;
        var minMaxPos_1 : vec4<i32> = accumMinMax_0(accumMinMax_0(accumMinMax_0(sdata0_0[_S5], sdata0_0[_S5 + u32(1)]), sdata0_0[_S5 + u32(2)]), sdata0_0[_S5 + u32(3)]);
        sdata1_0[threadIdx_0] = minMaxPos_1;
        treeOut_0[_S4 + u32(21)] = minMaxPos_1;
    }
    workgroupBarrier();
    if(threadIdx_0 < u32(16))
    {
        var _S6 : u32 = u32(4) * threadIdx_0;
        var minMaxPos_2 : vec4<i32> = accumMinMax_0(accumMinMax_0(accumMinMax_0(sdata1_0[_S6], sdata1_0[_S6 + u32(1)]), sdata1_0[_S6 + u32(2)]), sdata1_0[_S6 + u32(3)]);
        sdata0_0[threadIdx_0] = minMaxPos_2;
        treeOut_0[_S4 + u32(5)] = minMaxPos_2;
    }
    workgroupBarrier();
    if(threadIdx_0 < u32(4))
    {
        var _S7 : u32 = u32(4) * threadIdx_0;
        var minMaxPos_3 : vec4<i32> = accumMinMax_0(accumMinMax_0(accumMinMax_0(sdata0_0[_S7], sdata0_0[_S7 + u32(1)]), sdata0_0[_S7 + u32(2)]), sdata0_0[_S7 + u32(3)]);
        sdata1_0[threadIdx_0] = minMaxPos_3;
        treeOut_0[_S4 + u32(1)] = minMaxPos_3;
    }
    workgroupBarrier();
    if(threadIdx_0 < u32(1))
    {
        var _S8 : u32 = u32(4) * threadIdx_0;
        treeOut_0[_S4] = accumMinMax_0(accumMinMax_0(accumMinMax_0(sdata1_0[_S8], sdata1_0[_S8 + u32(1)]), sdata1_0[_S8 + u32(2)]), sdata1_0[_S8 + u32(3)]);
    }
    return;
}

