// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct ImguiRendererParams_std140_0
{
    @align(16) numVertices_0 : u32,
    @align(4) numIndices_0 : u32,
    @align(8) numDrawCmds_0 : u32,
    @align(4) numBlocks_0 : u32,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) tileGridDim_x_0 : u32,
    @align(4) tileGridDim_y_0 : u32,
    @align(8) tileGridDim_xy_0 : u32,
    @align(4) tileDimBits_0 : u32,
    @align(16) maxTriangles_0 : u32,
    @align(4) tileNumTrianglesOffset_0 : u32,
    @align(8) tileLocalScanOffset_0 : u32,
    @align(4) tileLocalTotalOffset_0 : u32,
    @align(16) tileGlobalScanOffset_0 : u32,
    @align(4) numTileBuckets_0 : u32,
    @align(8) numTileBucketPasses_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : ImguiRendererParams_std140_0;
@binding(1) @group(0) var<storage, read> treeIn_0 : array<vec4<i32>>;

@binding(2) @group(0) var<storage, read_write> tileCountOut_0 : array<u32>;

fn overlapTest_0( minMaxA_0 : vec4<i32>,  minMaxB_0 : vec4<i32>) -> bool
{
    var _S1 : i32 = minMaxB_0.x;
    var _S2 : i32 = minMaxB_0.z;
    var ret_0 : bool;
    if(_S1 == _S2)
    {
        ret_0 = (minMaxB_0.y) == (minMaxB_0.w);
    }
    else
    {
        ret_0 = false;
    }
    if(ret_0)
    {
        ret_0 = false;
    }
    else
    {
        if((minMaxA_0.x) > _S2)
        {
            ret_0 = true;
        }
        else
        {
            ret_0 = _S1 > (minMaxA_0.z);
        }
        if(ret_0)
        {
            ret_0 = true;
        }
        else
        {
            ret_0 = (minMaxA_0.y) > (minMaxB_0.w);
        }
        if(ret_0)
        {
            ret_0 = true;
        }
        else
        {
            ret_0 = (minMaxB_0.y) > (minMaxA_0.w);
        }
        ret_0 = !ret_0;
    }
    return ret_0;
}

fn countHits_0( hitIdx_0 : ptr<function, u32>,  idxMinMax_0 : vec4<i32>,  blockIdx_0 : u32)
{
    var treeBaseOffset_0 : u32 = u32(341) * blockIdx_0;
    if(overlapTest_0(idxMinMax_0, treeIn_0[treeBaseOffset_0]))
    {
        var _S3 : u32 = treeBaseOffset_0 + u32(1);
        var _S4 : u32 = treeBaseOffset_0 + u32(5);
        var _S5 : u32 = treeBaseOffset_0 + u32(21);
        var _S6 : u32 = treeBaseOffset_0 + u32(85);
        var childIdx0_0 : u32 = u32(0);
        for(;;)
        {
            if(childIdx0_0 < u32(4))
            {
            }
            else
            {
                break;
            }
            if(overlapTest_0(idxMinMax_0, treeIn_0[childIdx0_0 + _S3]))
            {
                var _S7 : u32 = u32(4) * childIdx0_0;
                var childIdx1_0 : u32 = u32(0);
                for(;;)
                {
                    if(childIdx1_0 < u32(4))
                    {
                    }
                    else
                    {
                        break;
                    }
                    var idx1_0 : u32 = _S7 + childIdx1_0;
                    if(overlapTest_0(idxMinMax_0, treeIn_0[idx1_0 + _S4]))
                    {
                        var _S8 : u32 = u32(4) * idx1_0;
                        var childIdx2_0 : u32 = u32(0);
                        for(;;)
                        {
                            if(childIdx2_0 < u32(4))
                            {
                            }
                            else
                            {
                                break;
                            }
                            var idx2_0 : u32 = _S8 + childIdx2_0;
                            if(overlapTest_0(idxMinMax_0, treeIn_0[idx2_0 + _S5]))
                            {
                                var _S9 : u32 = u32(4) * idx2_0;
                                var childIdx3_0 : u32 = u32(0);
                                for(;;)
                                {
                                    if(childIdx3_0 < u32(4))
                                    {
                                    }
                                    else
                                    {
                                        break;
                                    }
                                    if(overlapTest_0(idxMinMax_0, treeIn_0[_S9 + childIdx3_0 + _S6]))
                                    {
                                        (*hitIdx_0) = (*hitIdx_0) + u32(1);
                                    }
                                    childIdx3_0 = childIdx3_0 + u32(1);
                                }
                            }
                            childIdx2_0 = childIdx2_0 + u32(1);
                        }
                    }
                    childIdx1_0 = childIdx1_0 + u32(1);
                }
            }
            childIdx0_0 = childIdx0_0 + u32(1);
        }
    }
    return;
}

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

var<workgroup> stotalCount_0 : u32;

fn blockScan_0( threadIdx_0 : u32,  val_0 : u32) -> u32
{
    sdata0_0[threadIdx_0] = val_0;
    workgroupBarrier();
    var localVal_0 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_0 = val_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_0 = val_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(2)];
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(3)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(4)];
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(8)];
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(12)];
    }
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(16)];
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(32)];
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(48)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(64)];
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(128)];
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(192)];
    }
    if(threadIdx_0 == u32(0))
    {
        stotalCount_0 = sdata1_0[i32(63)] + sdata1_0[i32(127)] + sdata1_0[i32(191)] + sdata1_0[i32(255)];
    }
    return localVal_0;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var tidx_0 : i32 = i32(dispatchThreadID_0.x);
    var _S10 : u32 = u32(tidx_0);
    var threadIdx_1 : u32 = (_S10 & (u32(255)));
    var _S11 : u32 = _S10 % paramsIn_0.tileGridDim_x_0;
    var _S12 : i32 = i32(_S11);
    var _S13 : u32 = _S10 / paramsIn_0.tileGridDim_x_0;
    var tileIdx_0 : vec2<i32> = vec2<i32>(_S12, i32(_S13));
    var hitIdx_1 : u32 = u32(0);
    if(tidx_0 < i32(paramsIn_0.tileGridDim_xy_0))
    {
        var _S14 : vec2<u32> = vec2<u32>(((u32(1) << ((paramsIn_0.tileDimBits_0)))));
        var _S15 : vec2<u32> = vec2<u32>(tileIdx_0) * _S14;
        const _S16 : vec2<u32> = vec2<u32>(vec2<i32>(i32(1), i32(1)));
        var _S17 : vec4<i32> = vec4<i32>(vec2<i32>(_S15 - _S16), vec2<i32>(_S15 + _S14 - _S16));
        var blockIdx_1 : u32 = u32(0);
        for(;;)
        {
            if(blockIdx_1 < (paramsIn_0.numBlocks_0))
            {
            }
            else
            {
                break;
            }
            countHits_0(&(hitIdx_1), _S17, blockIdx_1);
            blockIdx_1 = blockIdx_1 + u32(1);
        }
        tileCountOut_0[_S10 + paramsIn_0.tileNumTrianglesOffset_0] = hitIdx_1;
    }
    var scanVal_0 : u32 = blockScan_0(threadIdx_1, hitIdx_1);
    var allocIdx_0 : u32 = scanVal_0 - hitIdx_1;
    if(tidx_0 < i32(paramsIn_0.tileGridDim_xy_0))
    {
        tileCountOut_0[_S10 + paramsIn_0.tileLocalScanOffset_0] = allocIdx_0;
    }
    if(threadIdx_1 == u32(0))
    {
        tileCountOut_0[u32((tidx_0 >> (u32(8)))) + paramsIn_0.tileLocalTotalOffset_0] = stotalCount_0;
    }
    return;
}

