// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
@binding(0) @group(0) var<storage, read> uploadIn_0 : array<u32>;

@binding(1) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var _S1 : u32 = dispatchThreadID_0.x;
    var tileIdx1D_0 : u32 = (_S1 >> (u32(7)));
    var _S2 : u32 = tileIdx1D_0 * u32(18) * u32(18);
    var _S3 : vec2<i32> = vec2<i32>(i32(18)) * vec2<i32>(i32((tileIdx1D_0 & (u32(511)))), i32((tileIdx1D_0 >> (u32(9)))));
    var subIdx1D_0 : u32 = (_S1 & (u32(127)));
    for(;;)
    {
        if(subIdx1D_0 < u32(324))
        {
        }
        else
        {
            break;
        }
        var colorRaw_0 : u32 = uploadIn_0[_S2 + subIdx1D_0];
        textureStore((colorOut_0), (vec2<u32>(_S3 + vec2<i32>(i32(subIdx1D_0 % u32(18)), i32(subIdx1D_0 / u32(18))))), (vec4<f32>(f32((((colorRaw_0 >> (u32(0)))) & (u32(255)))) * 0.00392156885936856f, f32((((colorRaw_0 >> (u32(8)))) & (u32(255)))) * 0.00392156885936856f, f32((((colorRaw_0 >> (u32(16)))) & (u32(255)))) * 0.00392156885936856f, f32((((colorRaw_0 >> (u32(24)))) & (u32(255)))) * 0.00392156885936856f)));
        subIdx1D_0 = subIdx1D_0 + u32(128);
    }
    return;
}

