// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct ImguiRendererParams_std140_0
{
    @align(16) numVertices_0 : u32,
    @align(4) numIndices_0 : u32,
    @align(8) numDrawCmds_0 : u32,
    @align(4) numBlocks_0 : u32,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) tileGridDim_x_0 : u32,
    @align(4) tileGridDim_y_0 : u32,
    @align(8) tileGridDim_xy_0 : u32,
    @align(4) tileDimBits_0 : u32,
    @align(16) maxTriangles_0 : u32,
    @align(4) tileNumTrianglesOffset_0 : u32,
    @align(8) tileLocalScanOffset_0 : u32,
    @align(4) tileLocalTotalOffset_0 : u32,
    @align(16) tileGlobalScanOffset_0 : u32,
    @align(4) numTileBuckets_0 : u32,
    @align(8) numTileBucketPasses_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : ImguiRendererParams_std140_0;
@binding(1) @group(0) var<storage, read_write> tileCountOut_0 : array<u32>;

@binding(2) @group(0) var<storage, read_write> totalCountOut_0 : array<u32>;

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

var<workgroup> stotalCount_0 : u32;

fn blockScan_0( threadIdx_0 : u32,  val_0 : u32) -> u32
{
    sdata0_0[threadIdx_0] = val_0;
    workgroupBarrier();
    var localVal_0 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_0 = val_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_0 = val_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(2)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(3)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(4)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(8)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(12)];
    }
    else
    {
    }
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(16)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(32)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(48)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(64)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(128)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(192)];
    }
    else
    {
    }
    if(threadIdx_0 == u32(0))
    {
        stotalCount_0 = sdata1_0[i32(63)] + sdata1_0[i32(127)] + sdata1_0[i32(191)] + sdata1_0[i32(255)];
    }
    return localVal_0;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var threadIdx_1 : u32 = (u32(i32(dispatchThreadID_0.x)) & (u32(255)));
    var _S1 : bool = threadIdx_1 == u32(0);
    var passIdx_0 : u32 = u32(0);
    var accumIdx_0 : u32 = u32(0);
    for(;;)
    {
        if(passIdx_0 < (paramsIn_0.numTileBucketPasses_0))
        {
        }
        else
        {
            break;
        }
        var tileBucketIdx_0 : u32 = ((passIdx_0 << (u32(8)))) + threadIdx_1;
        var bucketValue_0 : u32;
        if(tileBucketIdx_0 < (paramsIn_0.numTileBuckets_0))
        {
            bucketValue_0 = tileCountOut_0[tileBucketIdx_0 + paramsIn_0.tileLocalTotalOffset_0];
        }
        else
        {
            bucketValue_0 = u32(0);
        }
        var scanVal_0 : u32 = blockScan_0(threadIdx_1, bucketValue_0);
        var allocIdx_0 : u32 = scanVal_0 - bucketValue_0;
        if(tileBucketIdx_0 < (paramsIn_0.numTileBuckets_0))
        {
            tileCountOut_0[tileBucketIdx_0 + paramsIn_0.tileGlobalScanOffset_0] = allocIdx_0 + accumIdx_0;
        }
        workgroupBarrier();
        var accumIdx_1 : u32 = accumIdx_0 + stotalCount_0;
        passIdx_0 = passIdx_0 + u32(1);
        accumIdx_0 = accumIdx_1;
    }
    if(_S1)
    {
        totalCountOut_0[u32(0)] = accumIdx_0;
    }
    return;
}

