// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct ShapeRendererParams_std140_0
{
    @align(16) projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) view_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) projectionInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) viewInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) rayDir00_0 : vec4<f32>,
    @align(16) rayDir10_0 : vec4<f32>,
    @align(16) rayDir01_0 : vec4<f32>,
    @align(16) rayDir11_0 : vec4<f32>,
    @align(16) rayOrigin00_0 : vec4<f32>,
    @align(16) rayOrigin10_0 : vec4<f32>,
    @align(16) rayOrigin01_0 : vec4<f32>,
    @align(16) rayOrigin11_0 : vec4<f32>,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) numSpheres_0 : u32,
    @align(4) clearDepth_0 : f32,
    @align(8) isReverseZ_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) clearColor_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : ShapeRendererParams_std140_0;
@binding(1) @group(0) var<storage, read> spherePositionRadiusIn_0 : array<vec4<f32>>;

@binding(2) @group(0) var depthOut_0 : texture_storage_2d<r32float, write>;

@binding(3) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

fn raySphereIntersection_0( o_0 : vec3<f32>,  d_0 : vec3<f32>,  c_0 : vec3<f32>,  r_0 : f32,  t_0 : ptr<function, f32>) -> bool
{
    var l_0 : vec3<f32> = c_0 - o_0;
    var s_0 : f32 = dot(l_0, d_0);
    var l2_0 : f32 = dot(l_0, l_0);
    var r2_0 : f32 = r_0 * r_0;
    var ret_0 : bool;
    if(s_0 >= 0.0f)
    {
        ret_0 = true;
    }
    else
    {
        ret_0 = l2_0 <= r2_0;
    }
    if(ret_0)
    {
        var m2_0 : f32 = l2_0 - s_0 * s_0;
        if(m2_0 <= r2_0)
        {
            var q_0 : f32 = sqrt(r2_0 - m2_0);
            if(l2_0 > r2_0)
            {
                (*t_0) = s_0 - q_0;
            }
            else
            {
                (*t_0) = s_0 + q_0;
            }
            ret_0 = (*t_0) > 0.0f;
        }
        else
        {
            ret_0 = false;
        }
    }
    else
    {
        ret_0 = false;
    }
    return ret_0;
}

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var _S2 : vec2<i32> = vec2<i32>(dispatchThreadID_0.xy);
    var inUV_0 : vec2<f32> = (vec2<f32>(_S2) + vec2<f32>(0.5f)) * vec2<f32>(paramsIn_0.widthInv_0, paramsIn_0.heightInv_0);
    var _S3 : f32 = inUV_0.x;
    var _S4 : f32 = 1.0f - _S3;
    var _S5 : f32 = inUV_0.y;
    var _S6 : f32 = 1.0f - _S5;
    var _S7 : vec3<f32> = vec3<f32>((_S4 * _S6));
    var _S8 : vec3<f32> = vec3<f32>((_S3 * _S6));
    var _S9 : vec3<f32> = vec3<f32>((_S4 * _S5));
    var _S10 : vec3<f32> = vec3<f32>((_S3 * _S5));
    var _S11 : vec3<f32> = normalize(_S7 * paramsIn_0.rayDir00_0.xyz + _S8 * paramsIn_0.rayDir10_0.xyz + _S9 * paramsIn_0.rayDir01_0.xyz + _S10 * paramsIn_0.rayDir11_0.xyz);
    var _S12 : vec3<f32> = _S7 * paramsIn_0.rayOrigin00_0.xyz + _S8 * paramsIn_0.rayOrigin10_0.xyz + _S9 * paramsIn_0.rayOrigin01_0.xyz + _S10 * paramsIn_0.rayOrigin11_0.xyz;
    var _S13 : vec4<f32> = paramsIn_0.clearColor_0;
    var _S14 : vec2<u32> = vec2<u32>(_S2);
    var globalDepth_0 : f32 = paramsIn_0.clearDepth_0;
    var globalColor_0 : vec4<f32> = _S13;
    var sphereIdx_0 : u32 = u32(0);
    for(;;)
    {
        if(sphereIdx_0 < (paramsIn_0.numSpheres_0))
        {
        }
        else
        {
            break;
        }
        var spherePositionRadius_0 : vec4<f32> = spherePositionRadiusIn_0[sphereIdx_0];
        var hitT_0 : f32 = -1.0f;
        var _S15 : vec3<f32> = spherePositionRadius_0.xyz;
        var _S16 : bool = raySphereIntersection_0(_S12, _S11, _S15, spherePositionRadius_0.w, &(hitT_0));
        if(_S16)
        {
            var worldPos_0 : vec4<f32> = vec4<f32>(_S11 * vec3<f32>(hitT_0) + _S12, 1.0f);
            var clipPos_0 : vec4<f32> = (((unpackStorage_0(paramsIn_0.projection_0)) * ((((unpackStorage_0(paramsIn_0.view_0)) * (worldPos_0))))));
            var depth_0 : f32 = clipPos_0.z / clipPos_0.w;
            var isVisible_0 : bool;
            if(bool(paramsIn_0.isReverseZ_0))
            {
                isVisible_0 = depth_0 > globalDepth_0;
            }
            else
            {
                isVisible_0 = depth_0 < globalDepth_0;
            }
            var globalDepth_1 : f32;
            var globalColor_1 : vec4<f32>;
            if(isVisible_0)
            {
                var color_0 : vec4<f32> = vec4<f32>(abs(normalize(worldPos_0.xyz - _S15)), 1.0f);
                globalDepth_1 = depth_0;
                globalColor_1 = color_0;
            }
            else
            {
                globalDepth_1 = globalDepth_0;
                globalColor_1 = globalColor_0;
            }
            globalDepth_0 = globalDepth_1;
            globalColor_0 = globalColor_1;
        }
        sphereIdx_0 = sphereIdx_0 + u32(1);
    }
    textureStore((depthOut_0), (_S14), vec4<f32>((globalDepth_0), 0, 0, 1));
    textureStore((colorOut_0), (_S14), (globalColor_0));
    return;
}

