// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct AdvectionVelocityCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableDensity_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : AdvectionVelocityCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

struct SemiLagrangianParams_std430_0
{
    @align(16) valueToVelocityBlockScale_0 : vec3<f32>,
    @align(4) globalFetch_0 : u32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) maxDisplacement_0 : vec3<f32>,
    @align(4) pad0_1 : f32,
};

struct MacCormackParams_std430_0
{
    @align(16) base_0 : SemiLagrangianParams_std430_0,
    @align(16) blendThreshold_0 : vec4<f32>,
    @align(16) blendFactor_0 : vec4<f32>,
    @align(16) dampingRate_0 : vec4<f32>,
    @align(16) fadeRate_0 : vec4<f32>,
};

struct AdvectionCombustionParams_std430_0
{
    @align(16) gravity_0 : vec3<f32>,
    @align(4) burnPerFuel_0 : f32,
    @align(16) ignitionTemp_0 : f32,
    @align(4) burnPerTemp_0 : f32,
    @align(8) fuelPerBurn_0 : f32,
    @align(4) tempPerBurn_0 : f32,
    @align(16) smokePerBurn_0 : f32,
    @align(4) divergencePerBurn_0 : f32,
    @align(8) buoyancyPerTemp_0 : f32,
    @align(4) coolingRate_0 : f32,
    @align(16) buoyancyPerSmoke_0 : f32,
    @align(4) buoyancyMaxSmoke_0 : f32,
    @align(8) combustionEnabled_0 : u32,
    @align(4) pad3_1 : f32,
};

struct AdvectionVelocityCS_LayerParams_std430_0
{
    @align(16) advectParams_0 : MacCormackParams_std430_0,
    @align(16) combustParams_0 : AdvectionCombustionParams_std430_0,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) pad0_2 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<AdvectionVelocityCS_LayerParams_std430_0>;

@binding(4) @group(0) var predictIn_0 : texture_3d<f32>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(6) @group(0) var valueSampler_0 : sampler;

@binding(5) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(8) @group(0) var densityCoarseOut_0 : texture_storage_3d<rgba32float, write>;

@binding(7) @group(0) var velocityOut_0 : texture_storage_3d<rgba32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

struct SemiLagrangianParams_0
{
     valueToVelocityBlockScale_0 : vec3<f32>,
     globalFetch_0 : u32,
     cellSizeInv_0 : vec3<f32>,
     deltaTime_0 : f32,
     maxDisplacement_0 : vec3<f32>,
     pad0_1 : f32,
};

fn unpackStorage_1( _S5 : SemiLagrangianParams_std430_0) -> SemiLagrangianParams_0
{
    var _S6 : SemiLagrangianParams_0 = SemiLagrangianParams_0( _S5.valueToVelocityBlockScale_0, _S5.globalFetch_0, _S5.cellSizeInv_0, _S5.deltaTime_0, _S5.maxDisplacement_0, _S5.pad0_1 );
    return _S6;
}

struct MacCormackParams_0
{
     base_0 : SemiLagrangianParams_0,
     blendThreshold_0 : vec4<f32>,
     blendFactor_0 : vec4<f32>,
     dampingRate_0 : vec4<f32>,
     fadeRate_0 : vec4<f32>,
};

fn unpackStorage_2( _S7 : MacCormackParams_std430_0) -> MacCormackParams_0
{
    var _S8 : MacCormackParams_0 = MacCormackParams_0( unpackStorage_1(_S7.base_0), _S7.blendThreshold_0, _S7.blendFactor_0, _S7.dampingRate_0, _S7.fadeRate_0 );
    return _S8;
}

struct AdvectionCombustionParams_0
{
     gravity_0 : vec3<f32>,
     burnPerFuel_0 : f32,
     ignitionTemp_0 : f32,
     burnPerTemp_0 : f32,
     fuelPerBurn_0 : f32,
     tempPerBurn_0 : f32,
     smokePerBurn_0 : f32,
     divergencePerBurn_0 : f32,
     buoyancyPerTemp_0 : f32,
     coolingRate_0 : f32,
     buoyancyPerSmoke_0 : f32,
     buoyancyMaxSmoke_0 : f32,
     combustionEnabled_0 : u32,
     pad3_1 : f32,
};

fn unpackStorage_3( _S9 : AdvectionCombustionParams_std430_0) -> AdvectionCombustionParams_0
{
    var _S10 : AdvectionCombustionParams_0 = AdvectionCombustionParams_0( _S9.gravity_0, _S9.burnPerFuel_0, _S9.ignitionTemp_0, _S9.burnPerTemp_0, _S9.fuelPerBurn_0, _S9.tempPerBurn_0, _S9.smokePerBurn_0, _S9.divergencePerBurn_0, _S9.buoyancyPerTemp_0, _S9.coolingRate_0, _S9.buoyancyPerSmoke_0, _S9.buoyancyMaxSmoke_0, _S9.combustionEnabled_0, _S9.pad3_1 );
    return _S10;
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S11 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S11, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S11 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowFloor_i_0( v_1 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_1));
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn computeDisplacement_0( params_0 : SemiLagrangianParams_0,  velocity_0 : vec3<f32>) -> vec3<f32>
{
    var displacement_0 : vec3<f32> = vec3<f32>(params_0.deltaTime_0) * params_0.cellSizeInv_0 * velocity_0;
    var displacement_1 : vec3<f32>;
    if((params_0.globalFetch_0) == u32(0))
    {
        displacement_1 = min(max(displacement_0, - params_0.maxDisplacement_0), params_0.maxDisplacement_0);
    }
    else
    {
        displacement_1 = displacement_0;
    }
    return displacement_1;
}

fn minmax4_0( minVal_0 : ptr<function, vec4<f32>>,  maxVal_0 : ptr<function, vec4<f32>>,  val_0 : vec4<f32>)
{
    (*minVal_0) = min((*minVal_0), val_0);
    (*maxVal_0) = max((*maxVal_0), val_0);
    return;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S12 : i32 = threadIdx_1.x;
    if(_S12 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S12 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S13 : i32 = threadIdx_1.y;
    if(_S13 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S13 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S14 : i32 = threadIdx_1.z;
    if(_S14 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S14 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn combustVelocity_0( combustParams_1 : AdvectionCombustionParams_0,  velocity4_0 : vec4<f32>,  density4_0 : vec4<f32>,  deltaTime_1 : f32) -> vec4<f32>
{
    var _S15 : vec4<f32> = velocity4_0;
    var temp_0 : f32 = density4_0.x;
    var burn_0 : f32 = density4_0.z;
    var smoke_0 : f32 = density4_0.w;
    if((combustParams_1.combustionEnabled_0) != u32(0))
    {
        var _S16 : vec3<f32> = _S15.xyz - vec3<f32>((deltaTime_1 * combustParams_1.buoyancyPerTemp_0 * temp_0)) * combustParams_1.gravity_0;
        _S15.x = _S16.x;
        _S15.y = _S16.y;
        _S15.z = _S16.z;
        _S15[i32(3)] = combustParams_1.divergencePerBurn_0 * burn_0;
    }
    if((combustParams_1.buoyancyPerSmoke_0) != 0.0f)
    {
        var _S17 : vec3<f32> = _S15.xyz - vec3<f32>((deltaTime_1 * combustParams_1.buoyancyPerSmoke_0 * clamp(smoke_0, 0.0f, combustParams_1.buoyancyMaxSmoke_0))) * combustParams_1.gravity_0;
        _S15.x = _S17.x;
        _S15.y = _S17.y;
        _S15.z = _S17.z;
    }
    return _S15;
}

fn NvFlowGetLayerParamIdx_0( _S18 : NvFlowSparseLevelParams_0,  _S19 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S19 < (_S18.numLocations_0))
    {
        layerParamIdx_0 = tableIn_0[_S19 + _S18.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowSingleVirtualToReal_0( _S20 : NvFlowSparseLevelParams_0,  _S21 : u32,  _S22 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S22, tableIn_0[NvFlowSingleToIdx_0(_S21) + _S20.blockLevelOffsetLocal_0]);
}

fn advectSingleRead4f_0( _S23 : texture_3d<f32>,  _S24 : NvFlowSparseLevelParams_0,  _S25 : u32,  _S26 : vec3<i32>) -> vec4<f32>
{
    var _S27 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(NvFlowSingleVirtualToReal_0(_S24, _S25, _S26).xyz), u32(0)));
    return (textureLoad((_S23), ((_S27)).xyz, ((_S27)).w));
}

fn NvFlowBlockIdxToLocation_0( _S28 : NvFlowSparseLevelParams_0,  _S29 : u32,  _S30 : ptr<function, vec4<i32>>) -> bool
{
    var _S31 : bool = _S29 < (_S28.numLocations_0);
    if(_S31)
    {
        var locationIdx_0 : u32 = ((_S29 << (u32(2)))) + _S28.locationOffset_0;
        (*_S30)[i32(0)] = i32(tableIn_0[locationIdx_0]);
        (*_S30)[i32(1)] = i32(tableIn_0[locationIdx_0 + u32(1)]);
        (*_S30)[i32(2)] = i32(tableIn_0[locationIdx_0 + u32(2)]);
        (*_S30)[i32(3)] = i32(tableIn_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S30)[i32(0)] = i32(1073741824);
        (*_S30)[i32(1)] = i32(1073741824);
        (*_S30)[i32(2)] = i32(1073741824);
        (*_S30)[i32(3)] = i32(1073741824);
    }
    return _S31;
}

fn NvFlowLocationToBlockIdx_0( _S32 : NvFlowSparseLevelParams_0,  _S33 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S33.xyz) & ((_S32.tableDimLessOne_0)));
    var _S34 : u32 = ((((((((bucketIdx_0.z) << ((_S32.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S32.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S35 : u32 = tableIn_0[_S34 + u32(1)];
    var _S36 : i32 = _S33.x;
    var _S37 : i32 = _S33.y;
    var _S38 : i32 = _S33.z;
    var _S39 : i32 = _S33.w;
    var blockIdx_2 : u32 = tableIn_0[_S34];
    for(;;)
    {
        if(blockIdx_2 < _S35)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_2 << (u32(2)))) + _S32.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(3)]);
        var _S40 : bool;
        if(i32(tableIn_0[compareLocationIdx_0]) == _S36)
        {
            _S40 = compareLocation_y_0 == _S37;
        }
        else
        {
            _S40 = false;
        }
        var _S41 : bool;
        if(_S40)
        {
            _S41 = compareLocation_z_0 == _S38;
        }
        else
        {
            _S41 = false;
        }
        var _S42 : bool;
        if(_S41)
        {
            _S42 = compareLocation_w_0 == _S39;
        }
        else
        {
            _S42 = false;
        }
        if(_S42)
        {
            outBlockIdx_0 = blockIdx_2;
            break;
        }
        blockIdx_2 = blockIdx_2 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToReal_0( _S43 : NvFlowSparseLevelParams_0,  _S44 : vec4<i32>) -> vec4<i32>
{
    var _S45 : vec3<i32> = _S44.xyz;
    var _S46 : u32 = NvFlowLocationToBlockIdx_0(_S43, vec4<i32>((_S45 >> (vec3<u32>(vec3<i32>(_S43.blockDimBits_0)))), _S44.w));
    var tableValue_0 : u32;
    if(_S46 != u32(4294967295))
    {
        tableValue_0 = tableIn_0[_S46 + _S43.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S45 & (vec3<i32>(_S43.blockDimLessOne_0))), tableValue_0);
}

fn NvFlowLocalReadLinearSafe4f_0( _S47 : texture_3d<f32>,  _S48 : sampler,  _S49 : NvFlowSparseLevelParams_0,  _S50 : u32,  _S51 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S51);
    var location_0 : vec4<i32>;
    var _S52 : bool = NvFlowBlockIdxToLocation_0(_S49, _S50, &(location_0));
    var _S53 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S49, vec4<i32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(_S49.blockDimBits_0))))) + threadIdx_3, location_0.w));
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S53.xyz) + _S51 - vec3<f32>(threadIdx_3);
    var _S54 : vec4<f32>;
    if(bool(_S53.w))
    {
        _S54 = (textureSampleLevel((_S47), (_S48), (readIdxf_0 * _S49.dimInv_0), (0.0f)));
    }
    else
    {
        _S54 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S54;
}

fn NvFlowLocalVirtualToReal_0( _S55 : NvFlowSparseLevelParams_0,  _S56 : u32,  _S57 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S57 >> (vec3<u32>(vec3<i32>(_S55.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S57, tableIn_0[NvFlowNeighborToIdx_0(_S56, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S55.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalReadLinear4f_0( _S58 : texture_3d<f32>,  _S59 : sampler,  _S60 : NvFlowSparseLevelParams_0,  _S61 : u32,  _S62 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_4 : vec3<i32> = NvFlowFloor_i_0(_S62);
    var _S63 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S60, _S61, threadIdx_4);
    var readIdxf_1 : vec3<f32> = vec3<f32>(_S63.xyz) + _S62 - vec3<f32>(threadIdx_4);
    var _S64 : vec4<f32>;
    if(bool(_S63.w))
    {
        _S64 = (textureSampleLevel((_S58), (_S59), (readIdxf_1 * _S60.dimInv_0), (0.0f)));
    }
    else
    {
        _S64 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S64;
}

fn advectReadLinear4f_0( _S65 : u32,  _S66 : texture_3d<f32>,  _S67 : sampler,  _S68 : NvFlowSparseLevelParams_0,  _S69 : u32,  _S70 : vec3<f32>) -> vec4<f32>
{
    var ret_0 : vec4<f32>;
    if(_S65 != u32(0))
    {
        ret_0 = NvFlowLocalReadLinearSafe4f_0(_S66, _S67, _S68, _S69, _S70);
    }
    else
    {
        ret_0 = NvFlowLocalReadLinear4f_0(_S66, _S67, _S68, _S69, _S70);
    }
    return ret_0;
}

fn NvFlowLocalVirtualToRealSafef_0( _S71 : NvFlowSparseLevelParams_0,  _S72 : u32,  _S73 : vec3<f32>) -> vec3<f32>
{
    var threadIdx_5 : vec3<i32> = NvFlowFloor_i_0(_S73);
    var location_1 : vec4<i32>;
    var _S74 : bool = NvFlowBlockIdxToLocation_0(_S71, _S72, &(location_1));
    return vec3<f32>(NvFlowGlobalVirtualToReal_0(_S71, vec4<i32>((((location_1.xyz) << (vec3<u32>(vec3<i32>(_S71.blockDimBits_0))))) + threadIdx_5, location_1.w)).xyz) + _S73 - vec3<f32>(threadIdx_5);
}

fn NvFlowLocalVirtualToRealf_0( _S75 : NvFlowSparseLevelParams_0,  _S76 : u32,  _S77 : vec3<f32>) -> vec3<f32>
{
    var threadIdx_6 : vec3<i32> = NvFlowFloor_i_0(_S77);
    return vec3<f32>(NvFlowLocalVirtualToReal_0(_S75, _S76, threadIdx_6).xyz) + _S77 - vec3<f32>(threadIdx_6);
}

fn advectVirtualToRealf_0( _S78 : u32,  _S79 : NvFlowSparseLevelParams_0,  _S80 : u32,  _S81 : vec3<f32>) -> vec3<f32>
{
    var ret_1 : vec3<f32>;
    if(_S78 != u32(0))
    {
        ret_1 = NvFlowLocalVirtualToRealSafef_0(_S79, _S80, _S81);
    }
    else
    {
        ret_1 = NvFlowLocalVirtualToRealf_0(_S79, _S80, _S81);
    }
    return ret_1;
}

fn macCormackCorrection4f_0( _S82 : texture_3d<f32>,  _S83 : texture_3d<f32>,  _S84 : texture_3d<f32>,  _S85 : sampler,  _S86 : sampler,  _S87 : sampler,  _S88 : NvFlowSparseLevelParams_0,  _S89 : NvFlowSparseLevelParams_0,  _S90 : MacCormackParams_0,  _S91 : u32,  _S92 : vec3<i32>) -> vec4<f32>
{
    var _S93 : vec4<f32> = advectSingleRead4f_0(_S82, _S88, _S91, _S92);
    var shouldCorrect_0 : bool;
    if((abs(_S93.x)) >= (_S90.blendThreshold_0.x))
    {
        shouldCorrect_0 = true;
    }
    else
    {
        shouldCorrect_0 = (abs(_S93.y)) >= (_S90.blendThreshold_0.y);
    }
    if(shouldCorrect_0)
    {
        shouldCorrect_0 = true;
    }
    else
    {
        shouldCorrect_0 = (abs(_S93.z)) >= (_S90.blendThreshold_0.z);
    }
    if(shouldCorrect_0)
    {
        shouldCorrect_0 = true;
    }
    else
    {
        shouldCorrect_0 = (abs(_S93.w)) >= (_S90.blendThreshold_0.w);
    }
    var value_0 : vec4<f32>;
    if(shouldCorrect_0)
    {
        const _S94 : vec3<f32> = vec3<f32>(0.5f, 0.5f, 0.5f);
        var _S95 : vec3<f32> = vec3<f32>(_S92) + _S94;
        var _S96 : vec3<f32> = computeDisplacement_0(_S90.base_0, advectReadLinear4f_0(_S90.base_0.globalFetch_0, _S84, _S87, _S89, _S91, _S90.base_0.valueToVelocityBlockScale_0 * _S95).xyz);
        var value_1 : vec4<f32> = _S93 + vec4<f32>(0.5f) * _S90.blendFactor_0 * (advectSingleRead4f_0(_S83, _S88, _S91, _S92) - advectReadLinear4f_0(_S90.base_0.globalFetch_0, _S82, _S85, _S88, _S91, _S95 + _S96));
        var c_0 : vec3<i32> = NvFlowFloor_i_0(advectVirtualToRealf_0(_S90.base_0.globalFetch_0, _S88, _S91, _S95 - _S96) - _S94);
        var _S97 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0), u32(0)));
        var _S98 : vec4<f32> = (textureLoad((_S83), ((_S97)).xyz, ((_S97)).w));
        var minVal_1 : vec4<f32> = _S98;
        var maxVal_1 : vec4<f32> = _S98;
        var _S99 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(1), i32(0), i32(0))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S99)).xyz, ((_S99)).w)));
        var _S100 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(0), i32(1), i32(0))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S100)).xyz, ((_S100)).w)));
        var _S101 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(1), i32(1), i32(0))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S101)).xyz, ((_S101)).w)));
        var _S102 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(0), i32(0), i32(1))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S102)).xyz, ((_S102)).w)));
        var _S103 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(1), i32(0), i32(1))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S103)).xyz, ((_S103)).w)));
        var _S104 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(0), i32(1), i32(1))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S104)).xyz, ((_S104)).w)));
        var _S105 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(c_0 + vec3<i32>(i32(1), i32(1), i32(1))), u32(0)));
        minmax4_0(&(minVal_1), &(maxVal_1), (textureLoad((_S83), ((_S105)).xyz, ((_S105)).w)));
        value_0 = min(maxVal_1, max(minVal_1, value_1));
    }
    else
    {
        value_0 = _S93;
    }
    return value_0 - vec4<f32>(sign(value_0)) * min(abs(value_0), max(abs(value_0 * _S90.dampingRate_0), abs(vec4<f32>(_S90.base_0.deltaTime_0) * _S90.fadeRate_0)));
}

fn NvFlowLocalWriteNeighbor4f_0( _S106 : NvFlowSparseLevelParams_0,  _S107 : i32,  _S108 : i32,  _S109 : i32,  _S110 : u32,  _S111 : vec3<i32>,  _S112 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S111, tableIn_0[NvFlowNeighborToIdx_0(_S110, _S107, _S108, _S109) + _S106.blockLevelOffsetLocal_0], _S107, _S108, _S109);
    var _S113 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S114 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S114 = _S112;
    }
    else
    {
        _S114 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((densityCoarseOut_0), (_S113), (_S114));
    return;
}

fn NvFlowLocalWrite4f_0( _S115 : NvFlowSparseLevelParams_0,  _S116 : u32,  _S117 : vec3<i32>,  _S118 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S115, _S117);
    NvFlowLocalWriteNeighbor4f_0(_S115, i32(0), i32(0), i32(0), _S116, _S117, _S118);
    var _S119 : i32 = neighbor_2.x;
    var _S120 : bool = _S119 != i32(0);
    if(_S120)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, _S119, i32(0), i32(0), _S116, _S117, _S118);
    }
    var _S121 : i32 = neighbor_2.y;
    var _S122 : bool = _S121 != i32(0);
    if(_S122)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, i32(0), _S121, i32(0), _S116, _S117, _S118);
    }
    var _S123 : i32 = neighbor_2.z;
    var _S124 : bool = _S123 != i32(0);
    if(_S124)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, i32(0), i32(0), _S123, _S116, _S117, _S118);
    }
    var _S125 : bool;
    if(_S120)
    {
        _S125 = _S122;
    }
    else
    {
        _S125 = false;
    }
    if(_S125)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, _S119, _S121, i32(0), _S116, _S117, _S118);
    }
    if(_S122)
    {
        _S125 = _S124;
    }
    else
    {
        _S125 = false;
    }
    if(_S125)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, i32(0), _S121, _S123, _S116, _S117, _S118);
    }
    if(_S120)
    {
        _S125 = _S124;
    }
    else
    {
        _S125 = false;
    }
    if(_S125)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, _S119, i32(0), _S123, _S116, _S117, _S118);
    }
    if(_S120)
    {
        _S125 = _S122;
    }
    else
    {
        _S125 = false;
    }
    if(_S125)
    {
        _S125 = _S124;
    }
    else
    {
        _S125 = false;
    }
    if(_S125)
    {
        NvFlowLocalWriteNeighbor4f_0(_S115, _S119, _S121, _S123, _S116, _S117, _S118);
    }
    return;
}

fn NvFlowLocalWriteNeighbor4f_1( _S126 : NvFlowSparseLevelParams_0,  _S127 : i32,  _S128 : i32,  _S129 : i32,  _S130 : u32,  _S131 : vec3<i32>,  _S132 : vec4<f32>)
{
    var index_1 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S131, tableIn_0[NvFlowNeighborToIdx_0(_S130, _S127, _S128, _S129) + _S126.blockLevelOffsetLocal_0], _S127, _S128, _S129);
    var _S133 : vec3<u32> = vec3<u32>(index_1.xyz);
    var _S134 : vec4<f32>;
    if(bool(index_1.w))
    {
        _S134 = _S132;
    }
    else
    {
        _S134 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((velocityOut_0), (_S133), (_S134));
    return;
}

fn NvFlowLocalWrite4f_1( _S135 : NvFlowSparseLevelParams_0,  _S136 : u32,  _S137 : vec3<i32>,  _S138 : vec4<f32>)
{
    var neighbor_3 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S135, _S137);
    NvFlowLocalWriteNeighbor4f_1(_S135, i32(0), i32(0), i32(0), _S136, _S137, _S138);
    var _S139 : i32 = neighbor_3.x;
    var _S140 : bool = _S139 != i32(0);
    if(_S140)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, _S139, i32(0), i32(0), _S136, _S137, _S138);
    }
    var _S141 : i32 = neighbor_3.y;
    var _S142 : bool = _S141 != i32(0);
    if(_S142)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, i32(0), _S141, i32(0), _S136, _S137, _S138);
    }
    var _S143 : i32 = neighbor_3.z;
    var _S144 : bool = _S143 != i32(0);
    if(_S144)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, i32(0), i32(0), _S143, _S136, _S137, _S138);
    }
    var _S145 : bool;
    if(_S140)
    {
        _S145 = _S142;
    }
    else
    {
        _S145 = false;
    }
    if(_S145)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, _S139, _S141, i32(0), _S136, _S137, _S138);
    }
    if(_S142)
    {
        _S145 = _S144;
    }
    else
    {
        _S145 = false;
    }
    if(_S145)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, i32(0), _S141, _S143, _S136, _S137, _S138);
    }
    if(_S140)
    {
        _S145 = _S144;
    }
    else
    {
        _S145 = false;
    }
    if(_S145)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, _S139, i32(0), _S143, _S136, _S137, _S138);
    }
    if(_S140)
    {
        _S145 = _S142;
    }
    else
    {
        _S145 = false;
    }
    if(_S145)
    {
        _S145 = _S144;
    }
    else
    {
        _S145 = false;
    }
    if(_S145)
    {
        NvFlowLocalWriteNeighbor4f_1(_S135, _S139, _S141, _S143, _S136, _S137, _S138);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_7 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), dispatchThreadID_0.x);
    var blockIdx_3 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S146 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_3);
    var _S147 : vec4<f32> = macCormackCorrection4f_0(predictIn_0, velocityIn_0, velocityIn_0, valueSampler_0, valueSampler_0, valueSampler_0, unpackStorage_0(globalParamsIn_0.table_0), unpackStorage_0(globalParamsIn_0.table_0), unpackStorage_2(layerParamsIn_0[_S146].advectParams_0), blockIdx_3, threadIdx_7);
    var _S148 : vec4<f32> = NvFlowLocalReadLinear4f_0(densityIn_0, valueSampler_0, unpackStorage_0(globalParamsIn_0.tableDensity_0), blockIdx_3, layerParamsIn_0[_S146].velocityToDensityBlockScale_0 * (vec3<f32>(threadIdx_7) + vec3<f32>(0.5f, 0.5f, 0.5f)));
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_3, threadIdx_7, _S148);
    NvFlowLocalWrite4f_1(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_3, threadIdx_7, combustVelocity_0(unpackStorage_3(layerParamsIn_0[_S146].combustParams_0), _S147, _S148, layerParamsIn_0[_S146].advectParams_0.base_0.deltaTime_0));
    return;
}

