// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct AdvectionVelocityCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableDensity_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : AdvectionVelocityCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

struct SemiLagrangianParams_std430_0
{
    @align(16) valueToVelocityBlockScale_0 : vec3<f32>,
    @align(4) globalFetch_0 : u32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) maxDisplacement_0 : vec3<f32>,
    @align(4) pad0_1 : f32,
};

struct MacCormackParams_std430_0
{
    @align(16) base_0 : SemiLagrangianParams_std430_0,
    @align(16) blendThreshold_0 : vec4<f32>,
    @align(16) blendFactor_0 : vec4<f32>,
    @align(16) dampingRate_0 : vec4<f32>,
    @align(16) fadeRate_0 : vec4<f32>,
};

struct AdvectionCombustionParams_std430_0
{
    @align(16) gravity_0 : vec3<f32>,
    @align(4) burnPerFuel_0 : f32,
    @align(16) ignitionTemp_0 : f32,
    @align(4) burnPerTemp_0 : f32,
    @align(8) fuelPerBurn_0 : f32,
    @align(4) tempPerBurn_0 : f32,
    @align(16) smokePerBurn_0 : f32,
    @align(4) divergencePerBurn_0 : f32,
    @align(8) buoyancyPerTemp_0 : f32,
    @align(4) coolingRate_0 : f32,
    @align(16) buoyancyPerSmoke_0 : f32,
    @align(4) buoyancyMaxSmoke_0 : f32,
    @align(8) combustionEnabled_0 : u32,
    @align(4) pad3_1 : f32,
};

struct AdvectionVelocityCS_LayerParams_std430_0
{
    @align(16) advectParams_0 : MacCormackParams_std430_0,
    @align(16) combustParams_0 : AdvectionCombustionParams_std430_0,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) pad0_2 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<AdvectionVelocityCS_LayerParams_std430_0>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var valueSampler_0 : sampler;

@binding(5) @group(0) var velocityOut_0 : texture_storage_3d<rgba32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

struct SemiLagrangianParams_0
{
     valueToVelocityBlockScale_0 : vec3<f32>,
     globalFetch_0 : u32,
     cellSizeInv_0 : vec3<f32>,
     deltaTime_0 : f32,
     maxDisplacement_0 : vec3<f32>,
     pad0_1 : f32,
};

fn unpackStorage_1( _S5 : SemiLagrangianParams_std430_0) -> SemiLagrangianParams_0
{
    var _S6 : SemiLagrangianParams_0 = SemiLagrangianParams_0( _S5.valueToVelocityBlockScale_0, _S5.globalFetch_0, _S5.cellSizeInv_0, _S5.deltaTime_0, _S5.maxDisplacement_0, _S5.pad0_1 );
    return _S6;
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S7 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S7, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S7 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn computeDisplacement_0( params_0 : SemiLagrangianParams_0,  velocity_0 : vec3<f32>) -> vec3<f32>
{
    var displacement_0 : vec3<f32> = vec3<f32>(params_0.deltaTime_0) * params_0.cellSizeInv_0 * velocity_0;
    var displacement_1 : vec3<f32>;
    if((params_0.globalFetch_0) == u32(0))
    {
        displacement_1 = min(max(displacement_0, - params_0.maxDisplacement_0), params_0.maxDisplacement_0);
    }
    else
    {
        displacement_1 = displacement_0;
    }
    return displacement_1;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S8 : i32 = threadIdx_1.x;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S9 : i32 = threadIdx_1.y;
    if(_S9 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S9 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S10 : i32 = threadIdx_1.z;
    if(_S10 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S10 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S12 < (_S11.numLocations_0))
    {
        layerParamIdx_0 = tableIn_0[_S12 + _S11.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowBlockIdxToLocation_0( _S13 : NvFlowSparseLevelParams_0,  _S14 : u32,  _S15 : ptr<function, vec4<i32>>) -> bool
{
    var _S16 : bool = _S14 < (_S13.numLocations_0);
    if(_S16)
    {
        var locationIdx_0 : u32 = ((_S14 << (u32(2)))) + _S13.locationOffset_0;
        (*_S15)[i32(0)] = i32(tableIn_0[locationIdx_0]);
        (*_S15)[i32(1)] = i32(tableIn_0[locationIdx_0 + u32(1)]);
        (*_S15)[i32(2)] = i32(tableIn_0[locationIdx_0 + u32(2)]);
        (*_S15)[i32(3)] = i32(tableIn_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S15)[i32(0)] = i32(1073741824);
        (*_S15)[i32(1)] = i32(1073741824);
        (*_S15)[i32(2)] = i32(1073741824);
        (*_S15)[i32(3)] = i32(1073741824);
    }
    return _S16;
}

fn NvFlowLocationToBlockIdx_0( _S17 : NvFlowSparseLevelParams_0,  _S18 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S18.xyz) & ((_S17.tableDimLessOne_0)));
    var _S19 : u32 = ((((((((bucketIdx_0.z) << ((_S17.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S17.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S20 : u32 = tableIn_0[_S19 + u32(1)];
    var _S21 : i32 = _S18.x;
    var _S22 : i32 = _S18.y;
    var _S23 : i32 = _S18.z;
    var _S24 : i32 = _S18.w;
    var blockIdx_1 : u32 = tableIn_0[_S19];
    for(;;)
    {
        if(blockIdx_1 < _S20)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S17.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(3)]);
        var _S25 : bool;
        if(i32(tableIn_0[compareLocationIdx_0]) == _S21)
        {
            _S25 = compareLocation_y_0 == _S22;
        }
        else
        {
            _S25 = false;
        }
        var _S26 : bool;
        if(_S25)
        {
            _S26 = compareLocation_z_0 == _S23;
        }
        else
        {
            _S26 = false;
        }
        var _S27 : bool;
        if(_S26)
        {
            _S27 = compareLocation_w_0 == _S24;
        }
        else
        {
            _S27 = false;
        }
        if(_S27)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToReal_0( _S28 : NvFlowSparseLevelParams_0,  _S29 : vec4<i32>) -> vec4<i32>
{
    var _S30 : vec3<i32> = _S29.xyz;
    var _S31 : u32 = NvFlowLocationToBlockIdx_0(_S28, vec4<i32>((_S30 >> (vec3<u32>(vec3<i32>(_S28.blockDimBits_0)))), _S29.w));
    var tableValue_0 : u32;
    if(_S31 != u32(4294967295))
    {
        tableValue_0 = tableIn_0[_S31 + _S28.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S30 & (vec3<i32>(_S28.blockDimLessOne_0))), tableValue_0);
}

fn NvFlowLocalReadLinearSafe4f_0( _S32 : texture_3d<f32>,  _S33 : sampler,  _S34 : NvFlowSparseLevelParams_0,  _S35 : u32,  _S36 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S36);
    var location_0 : vec4<i32>;
    var _S37 : bool = NvFlowBlockIdxToLocation_0(_S34, _S35, &(location_0));
    var _S38 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S34, vec4<i32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(_S34.blockDimBits_0))))) + threadIdx_3, location_0.w));
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S38.xyz) + _S36 - vec3<f32>(threadIdx_3);
    var _S39 : vec4<f32>;
    if(bool(_S38.w))
    {
        _S39 = (textureSampleLevel((_S32), (_S33), (readIdxf_0 * _S34.dimInv_0), (0.0f)));
    }
    else
    {
        _S39 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S39;
}

fn NvFlowLocalVirtualToReal_0( _S40 : NvFlowSparseLevelParams_0,  _S41 : u32,  _S42 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S42 >> (vec3<u32>(vec3<i32>(_S40.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S42, tableIn_0[NvFlowNeighborToIdx_0(_S41, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S40.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalReadLinear4f_0( _S43 : texture_3d<f32>,  _S44 : sampler,  _S45 : NvFlowSparseLevelParams_0,  _S46 : u32,  _S47 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_4 : vec3<i32> = NvFlowFloor_i_0(_S47);
    var _S48 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S45, _S46, threadIdx_4);
    var readIdxf_1 : vec3<f32> = vec3<f32>(_S48.xyz) + _S47 - vec3<f32>(threadIdx_4);
    var _S49 : vec4<f32>;
    if(bool(_S48.w))
    {
        _S49 = (textureSampleLevel((_S43), (_S44), (readIdxf_1 * _S45.dimInv_0), (0.0f)));
    }
    else
    {
        _S49 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S49;
}

fn advectReadLinear4f_0( _S50 : u32,  _S51 : texture_3d<f32>,  _S52 : sampler,  _S53 : NvFlowSparseLevelParams_0,  _S54 : u32,  _S55 : vec3<f32>) -> vec4<f32>
{
    var ret_0 : vec4<f32>;
    if(_S50 != u32(0))
    {
        ret_0 = NvFlowLocalReadLinearSafe4f_0(_S51, _S52, _S53, _S54, _S55);
    }
    else
    {
        ret_0 = NvFlowLocalReadLinear4f_0(_S51, _S52, _S53, _S54, _S55);
    }
    return ret_0;
}

fn semiLagrangian4f_0( _S56 : texture_3d<f32>,  _S57 : texture_3d<f32>,  _S58 : sampler,  _S59 : sampler,  _S60 : NvFlowSparseLevelParams_0,  _S61 : NvFlowSparseLevelParams_0,  _S62 : SemiLagrangianParams_0,  _S63 : u32,  _S64 : vec3<i32>) -> vec4<f32>
{
    var _S65 : vec3<f32> = vec3<f32>(_S64) + vec3<f32>(0.5f, 0.5f, 0.5f);
    return advectReadLinear4f_0(_S62.globalFetch_0, _S56, _S58, _S60, _S63, _S65 - computeDisplacement_0(_S62, advectReadLinear4f_0(_S62.globalFetch_0, _S57, _S59, _S61, _S63, _S62.valueToVelocityBlockScale_0 * _S65).xyz));
}

fn NvFlowLocalWriteNeighbor4f_0( _S66 : NvFlowSparseLevelParams_0,  _S67 : i32,  _S68 : i32,  _S69 : i32,  _S70 : u32,  _S71 : vec3<i32>,  _S72 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S71, tableIn_0[NvFlowNeighborToIdx_0(_S70, _S67, _S68, _S69) + _S66.blockLevelOffsetLocal_0], _S67, _S68, _S69);
    var _S73 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S74 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S74 = _S72;
    }
    else
    {
        _S74 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((velocityOut_0), (_S73), (_S74));
    return;
}

fn NvFlowLocalWrite4f_0( _S75 : NvFlowSparseLevelParams_0,  _S76 : u32,  _S77 : vec3<i32>,  _S78 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S75, _S77);
    NvFlowLocalWriteNeighbor4f_0(_S75, i32(0), i32(0), i32(0), _S76, _S77, _S78);
    var _S79 : i32 = neighbor_2.x;
    var _S80 : bool = _S79 != i32(0);
    if(_S80)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, _S79, i32(0), i32(0), _S76, _S77, _S78);
    }
    var _S81 : i32 = neighbor_2.y;
    var _S82 : bool = _S81 != i32(0);
    if(_S82)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, i32(0), _S81, i32(0), _S76, _S77, _S78);
    }
    var _S83 : i32 = neighbor_2.z;
    var _S84 : bool = _S83 != i32(0);
    if(_S84)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, i32(0), i32(0), _S83, _S76, _S77, _S78);
    }
    var _S85 : bool;
    if(_S80)
    {
        _S85 = _S82;
    }
    else
    {
        _S85 = false;
    }
    if(_S85)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, _S79, _S81, i32(0), _S76, _S77, _S78);
    }
    if(_S82)
    {
        _S85 = _S84;
    }
    else
    {
        _S85 = false;
    }
    if(_S85)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, i32(0), _S81, _S83, _S76, _S77, _S78);
    }
    if(_S80)
    {
        _S85 = _S84;
    }
    else
    {
        _S85 = false;
    }
    if(_S85)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, _S79, i32(0), _S83, _S76, _S77, _S78);
    }
    if(_S80)
    {
        _S85 = _S82;
    }
    else
    {
        _S85 = false;
    }
    if(_S85)
    {
        _S85 = _S84;
    }
    else
    {
        _S85 = false;
    }
    if(_S85)
    {
        NvFlowLocalWriteNeighbor4f_0(_S75, _S79, _S81, _S83, _S76, _S77, _S78);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_5 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_2, threadIdx_5, semiLagrangian4f_0(velocityIn_0, velocityIn_0, valueSampler_0, valueSampler_0, unpackStorage_0(globalParamsIn_0.table_0), unpackStorage_0(globalParamsIn_0.table_0), unpackStorage_1(layerParamsIn_0[NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_2)].advectParams_0.base_0), blockIdx_2, threadIdx_5));
    return;
}

