// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct PressureDivergenceParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) dextScale_0 : f32,
    @align(8) pad1_1 : u32,
    @align(4) pad2_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> gParams_0 : PressureDivergenceParams_std140_0;
@binding(1) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(2) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(3) @group(0) var pressureOut_0 : texture_storage_3d<rg32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_1 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_1) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowSingleVirtualToReal_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32,  _S11 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S11, gTable_0[NvFlowSingleToIdx_0(_S10) + _S9.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalWriteNeighbor2f_0( _S12 : NvFlowSparseLevelParams_0,  _S13 : i32,  _S14 : i32,  _S15 : i32,  _S16 : u32,  _S17 : vec3<i32>,  _S18 : vec2<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S17, gTable_0[NvFlowNeighborToIdx_0(_S16, _S13, _S14, _S15) + _S12.blockLevelOffsetLocal_0], _S13, _S14, _S15);
    var _S19 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S20 : vec2<f32>;
    if(bool(index_0.w))
    {
        _S20 = _S18;
    }
    else
    {
        _S20 = vec2<f32>(0.0f, 0.0f);
    }
    textureStore((pressureOut_0), (_S19), vec4<f32>((_S20), 0, 1));
    return;
}

fn NvFlowLocalWrite2f_0( _S21 : NvFlowSparseLevelParams_0,  _S22 : u32,  _S23 : vec3<i32>,  _S24 : vec2<f32>)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S21, _S23);
    NvFlowLocalWriteNeighbor2f_0(_S21, i32(0), i32(0), i32(0), _S22, _S23, _S24);
    var _S25 : i32 = neighbor_1.x;
    var _S26 : bool = _S25 != i32(0);
    if(_S26)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, _S25, i32(0), i32(0), _S22, _S23, _S24);
    }
    var _S27 : i32 = neighbor_1.y;
    var _S28 : bool = _S27 != i32(0);
    if(_S28)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, i32(0), _S27, i32(0), _S22, _S23, _S24);
    }
    var _S29 : i32 = neighbor_1.z;
    var _S30 : bool = _S29 != i32(0);
    if(_S30)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, i32(0), i32(0), _S29, _S22, _S23, _S24);
    }
    var _S31 : bool;
    if(_S26)
    {
        _S31 = _S28;
    }
    else
    {
        _S31 = false;
    }
    if(_S31)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, _S25, _S27, i32(0), _S22, _S23, _S24);
    }
    if(_S28)
    {
        _S31 = _S30;
    }
    else
    {
        _S31 = false;
    }
    if(_S31)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, i32(0), _S27, _S29, _S22, _S23, _S24);
    }
    if(_S26)
    {
        _S31 = _S30;
    }
    else
    {
        _S31 = false;
    }
    if(_S31)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, _S25, i32(0), _S29, _S22, _S23, _S24);
    }
    if(_S26)
    {
        _S31 = _S28;
    }
    else
    {
        _S31 = false;
    }
    if(_S31)
    {
        _S31 = _S30;
    }
    else
    {
        _S31 = false;
    }
    if(_S31)
    {
        NvFlowLocalWriteNeighbor2f_0(_S21, _S25, _S27, _S29, _S22, _S23, _S24);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(gParams_0.table_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var readIdx_0 : vec3<i32> = NvFlowSingleVirtualToReal_0(unpackStorage_0(gParams_0.table_0), blockIdx_2, threadIdx_3).xyz;
    var _S32 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(1), i32(0), i32(0))), u32(0)));
    var _S33 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(-1), i32(0), i32(0))), u32(0)));
    var _S34 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(1), i32(0))), u32(0)));
    var _S35 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(-1), i32(0))), u32(0)));
    var _S36 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(0), i32(1))), u32(0)));
    var _S37 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(0), i32(-1))), u32(0)));
    var _S38 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0), u32(0)));
    NvFlowLocalWrite2f_0(unpackStorage_0(gParams_0.table_0), blockIdx_2, threadIdx_3, vec2<f32>(0.0f, 0.5f * ((textureLoad((velocityIn_0), ((_S32)).xyz, ((_S32)).w)).x - (textureLoad((velocityIn_0), ((_S33)).xyz, ((_S33)).w)).x + (textureLoad((velocityIn_0), ((_S34)).xyz, ((_S34)).w)).y - (textureLoad((velocityIn_0), ((_S35)).xyz, ((_S35)).w)).y + (textureLoad((velocityIn_0), ((_S36)).xyz, ((_S36)).w)).z - (textureLoad((velocityIn_0), ((_S37)).xyz, ((_S37)).w)).z) - gParams_0.dextScale_0 * (textureLoad((velocityIn_0), ((_S38)).xyz, ((_S38)).w)).w));
    return;
}

