// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct NvFlowSparseNanoVdbParams_std140_0
{
    @align(16) nanovdb_size_without_leaves_0 : vec2<u32>,
    @align(8) nanovdb_size_with_leaves_0 : vec2<u32>,
    @align(16) list_tile_offset_0 : vec2<u32>,
    @align(8) list_upper_offset_0 : vec2<u32>,
    @align(16) list_lower_offset_0 : vec2<u32>,
    @align(8) list_leaf_offset_0 : vec2<u32>,
    @align(16) cache_tile_offset_0 : vec2<u32>,
    @align(8) cache_upper_offset_0 : vec2<u32>,
    @align(16) cache_lower_offset_0 : vec2<u32>,
    @align(8) cache_leaf_offset_0 : vec2<u32>,
    @align(16) list_tile_count_0 : u32,
    @align(4) list_upper_count_0 : u32,
    @align(8) list_lower_count_0 : u32,
    @align(4) list_leaf_count_0 : u32,
    @align(16) cache_tile_count_0 : u32,
    @align(4) cache_upper_count_0 : u32,
    @align(8) cache_lower_count_0 : u32,
    @align(4) cache_leaf_count_0 : u32,
    @align(16) cache_size_0 : vec2<u32>,
    @align(8) grid_count_0 : u32,
    @align(4) grid_type_0 : u32,
    @align(16) subGridDimLessOne_0 : vec3<u32>,
    @align(4) pad3_0 : u32,
    @align(16) subGridDimBits_0 : vec3<u32>,
    @align(4) pad4_0 : u32,
};

struct SparseNanoVdbExportParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_1 : u32,
    @align(16) tableVelocity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableDensity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) velocityFloat_0 : NvFlowSparseNanoVdbParams_std140_0,
    @align(16) velocityVec3_0 : NvFlowSparseNanoVdbParams_std140_0,
    @align(16) densityFloat_0 : NvFlowSparseNanoVdbParams_std140_0,
    @align(16) rgba_0 : NvFlowSparseNanoVdbParams_std140_0,
    @align(16) rgb_0 : NvFlowSparseNanoVdbParams_std140_0,
    @align(16) temperatureEnabled_0 : u32,
    @align(4) fuelEnabled_0 : u32,
    @align(8) burnEnabled_0 : u32,
    @align(4) smokeEnabled_0 : u32,
    @align(16) velocityEnabled_0 : u32,
    @align(4) divergenceEnabled_0 : u32,
    @align(8) rgbaEnabled_0 : u32,
    @align(4) rgbEnabled_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : SparseNanoVdbExportParams_std140_0;
@binding(1) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(2) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(3) @group(0) var<storage, read_write> temperatureOut_0 : array<u32>;

@binding(4) @group(0) var<storage, read_write> fuelOut_0 : array<u32>;

@binding(5) @group(0) var<storage, read_write> burnOut_0 : array<u32>;

@binding(6) @group(0) var<storage, read_write> smokeOut_0 : array<u32>;

@binding(7) @group(0) var<storage, read_write> rgbaOut_0 : array<u32>;

@binding(8) @group(0) var<storage, read_write> rgbOut_0 : array<u32>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S3 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S3, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S3 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

struct pnanovdb_address_t_0
{
     byte_offset_0 : u32,
};

fn pnanovdb_address_t_x24init_0( byte_offset_1 : u32) -> pnanovdb_address_t_0
{
    var _S4 : pnanovdb_address_t_0;
    _S4.byte_offset_0 = byte_offset_1;
    return _S4;
}

fn pnanovdb_address_null_0() -> pnanovdb_address_t_0
{
    return pnanovdb_address_t_x24init_0(u32(0));
}

fn pnanovdb_address_offset_0( address_0 : pnanovdb_address_t_0,  byte_offset_2 : u32) -> pnanovdb_address_t_0
{
    var ret_0 : pnanovdb_address_t_0 = address_0;
    ret_0.byte_offset_0 = ret_0.byte_offset_0 + byte_offset_2;
    return ret_0;
}

struct pnanovdb_grid_handle_t_0
{
     address_1 : pnanovdb_address_t_0,
};

fn pnanovdb_grid_handle_t_x24init_0( address_2 : pnanovdb_address_t_0) -> pnanovdb_grid_handle_t_0
{
    var _S5 : pnanovdb_grid_handle_t_0;
    _S5.address_1 = address_2;
    return _S5;
}

struct pnanovdb_tree_handle_t_0
{
     address_3 : pnanovdb_address_t_0,
};

fn pnanovdb_tree_handle_t_x24init_0( address_4 : pnanovdb_address_t_0) -> pnanovdb_tree_handle_t_0
{
    var _S6 : pnanovdb_tree_handle_t_0;
    _S6.address_3 = address_4;
    return _S6;
}

fn pnanovdb_grid_get_tree_0( buf_0 : u32,  grid_0 : pnanovdb_grid_handle_t_0) -> pnanovdb_tree_handle_t_0
{
    var tree_0 : pnanovdb_tree_handle_t_0 = pnanovdb_tree_handle_t_x24init_0(grid_0.address_1);
    tree_0.address_3 = pnanovdb_address_offset_0(tree_0.address_3, u32(672));
    return tree_0;
}

struct pnanovdb_root_handle_t_0
{
     address_5 : pnanovdb_address_t_0,
};

fn pnanovdb_root_handle_t_x24init_0( address_6 : pnanovdb_address_t_0) -> pnanovdb_root_handle_t_0
{
    var _S7 : pnanovdb_root_handle_t_0;
    _S7.address_5 = address_6;
    return _S7;
}

fn pnanovdb_buf_read_uint32_0( buf_1 : u32,  byte_offset_3 : u32) -> u32
{
    if(buf_1 == u32(0))
    {
        return temperatureOut_0[(byte_offset_3 >> (u32(2)))];
    }
    else
    {
        if(buf_1 == u32(1))
        {
            return fuelOut_0[(byte_offset_3 >> (u32(2)))];
        }
        else
        {
            if(buf_1 == u32(2))
            {
                return burnOut_0[(byte_offset_3 >> (u32(2)))];
            }
            else
            {
                if(buf_1 == u32(3))
                {
                    return smokeOut_0[(byte_offset_3 >> (u32(2)))];
                }
                else
                {
                    if(buf_1 == u32(4))
                    {
                        return rgbaOut_0[(byte_offset_3 >> (u32(2)))];
                    }
                    else
                    {
                        return rgbOut_0[(byte_offset_3 >> (u32(2)))];
                    }
                }
            }
        }
    }
}

fn pnanovdb_buf_read_uint64_0( buf_2 : u32,  byte_offset_4 : u32) -> vec2<u32>
{
    var ret_1 : vec2<u32>;
    ret_1[i32(0)] = pnanovdb_buf_read_uint32_0(buf_2, byte_offset_4);
    ret_1[i32(1)] = pnanovdb_buf_read_uint32_0(buf_2, byte_offset_4 + u32(4));
    return ret_1;
}

fn pnanovdb_read_uint64_0( buf_3 : u32,  address_7 : pnanovdb_address_t_0) -> vec2<u32>
{
    return pnanovdb_buf_read_uint64_0(buf_3, address_7.byte_offset_0);
}

fn pnanovdb_tree_get_node_offset_root_0( buf_4 : u32,  p_0 : pnanovdb_tree_handle_t_0) -> vec2<u32>
{
    return pnanovdb_read_uint64_0(buf_4, pnanovdb_address_offset_0(p_0.address_3, u32(24)));
}

fn pnanovdb_uint64_low_0( v_1 : vec2<u32>) -> u32
{
    return v_1.x;
}

fn pnanovdb_address_offset64_0( address_8 : pnanovdb_address_t_0,  byte_offset_5 : vec2<u32>) -> pnanovdb_address_t_0
{
    var ret_2 : pnanovdb_address_t_0 = address_8;
    ret_2.byte_offset_0 = ret_2.byte_offset_0 + pnanovdb_uint64_low_0(byte_offset_5);
    return ret_2;
}

fn pnanovdb_tree_get_root_0( buf_5 : u32,  tree_1 : pnanovdb_tree_handle_t_0) -> pnanovdb_root_handle_t_0
{
    var root_0 : pnanovdb_root_handle_t_0 = pnanovdb_root_handle_t_x24init_0(tree_1.address_3);
    root_0.address_5 = pnanovdb_address_offset64_0(root_0.address_5, pnanovdb_tree_get_node_offset_root_0(buf_5, tree_1));
    return root_0;
}

struct pnanovdb_leaf_handle_t_0
{
     address_9 : pnanovdb_address_t_0,
};

struct pnanovdb_lower_handle_t_0
{
     address_10 : pnanovdb_address_t_0,
};

struct pnanovdb_upper_handle_t_0
{
     address_11 : pnanovdb_address_t_0,
};

struct pnanovdb_readaccessor_t_0
{
     key_0 : vec3<i32>,
     leaf_0 : pnanovdb_leaf_handle_t_0,
     lower_0 : pnanovdb_lower_handle_t_0,
     upper_0 : pnanovdb_upper_handle_t_0,
     root_1 : pnanovdb_root_handle_t_0,
};

fn pnanovdb_readaccessor_init_0( acc_0 : ptr<function, pnanovdb_readaccessor_t_0>,  root_2 : pnanovdb_root_handle_t_0)
{
    (*acc_0).key_0[i32(0)] = i32(2147483647);
    (*acc_0).key_0[i32(1)] = i32(2147483647);
    (*acc_0).key_0[i32(2)] = i32(2147483647);
    var _S8 : pnanovdb_address_t_0 = pnanovdb_address_null_0();
    (*acc_0).leaf_0.address_9 = _S8;
    (*acc_0).lower_0.address_10 = _S8;
    (*acc_0).upper_0.address_11 = _S8;
    (*acc_0).root_1 = root_2;
    return;
}

fn pnanovdb_readaccessor_computedirty_0( acc_1 : ptr<function, pnanovdb_readaccessor_t_0>,  ijk_0 : vec3<i32>) -> i32
{
    return ((((((ijk_0.x) ^ (((*acc_1).key_0.x)))) | ((((ijk_0.y) ^ (((*acc_1).key_0.y))))))) | ((((ijk_0.z) ^ (((*acc_1).key_0.z))))));
}

fn pnanovdb_address_is_null_0( address_12 : pnanovdb_address_t_0) -> bool
{
    return (address_12.byte_offset_0) == u32(0);
}

fn pnanovdb_readaccessor_iscached0_0( acc_2 : ptr<function, pnanovdb_readaccessor_t_0>,  dirty_0 : i32) -> bool
{
    if(pnanovdb_address_is_null_0((*acc_2).leaf_0.address_9))
    {
        return false;
    }
    if(((u32(dirty_0) & (u32(4294967288)))) != u32(0))
    {
        (*acc_2).leaf_0.address_9 = pnanovdb_address_null_0();
        return false;
    }
    return true;
}

fn pnanovdb_leaf_coord_to_offset_0( ijk_1 : vec3<i32>) -> u32
{
    return u32((((((((ijk_1.x) & (i32(7)))) >> (u32(0)))) << (u32(6)))) + (((((((ijk_1.y) & (i32(7)))) >> (u32(0)))) << (u32(3)))) + (((((ijk_1.z) & (i32(7)))) >> (u32(0)))));
}

struct pnanovdb_grid_type_constants_t_0
{
     root_off_background_0 : u32,
     root_off_min_0 : u32,
     root_off_max_0 : u32,
     root_off_ave_0 : u32,
     root_off_stddev_0 : u32,
     root_size_0 : u32,
     value_stride_bits_0 : u32,
     table_stride_0 : u32,
     root_tile_off_value_0 : u32,
     root_tile_size_0 : u32,
     upper_off_min_0 : u32,
     upper_off_max_0 : u32,
     upper_off_ave_0 : u32,
     upper_off_stddev_0 : u32,
     upper_off_table_0 : u32,
     upper_size_0 : u32,
     lower_off_min_0 : u32,
     lower_off_max_0 : u32,
     lower_off_ave_0 : u32,
     lower_off_stddev_0 : u32,
     lower_off_table_0 : u32,
     lower_size_0 : u32,
     leaf_off_min_0 : u32,
     leaf_off_max_0 : u32,
     leaf_off_ave_0 : u32,
     leaf_off_stddev_0 : u32,
     leaf_off_table_0 : u32,
     leaf_size_0 : u32,
};

fn pnanovdb_grid_type_constants_t_x24init_0( root_off_background_1 : u32,  root_off_min_1 : u32,  root_off_max_1 : u32,  root_off_ave_1 : u32,  root_off_stddev_1 : u32,  root_size_1 : u32,  value_stride_bits_1 : u32,  table_stride_1 : u32,  root_tile_off_value_1 : u32,  root_tile_size_1 : u32,  upper_off_min_1 : u32,  upper_off_max_1 : u32,  upper_off_ave_1 : u32,  upper_off_stddev_1 : u32,  upper_off_table_1 : u32,  upper_size_1 : u32,  lower_off_min_1 : u32,  lower_off_max_1 : u32,  lower_off_ave_1 : u32,  lower_off_stddev_1 : u32,  lower_off_table_1 : u32,  lower_size_1 : u32,  leaf_off_min_1 : u32,  leaf_off_max_1 : u32,  leaf_off_ave_1 : u32,  leaf_off_stddev_1 : u32,  leaf_off_table_1 : u32,  leaf_size_1 : u32) -> pnanovdb_grid_type_constants_t_0
{
    var _S9 : pnanovdb_grid_type_constants_t_0;
    _S9.root_off_background_0 = root_off_background_1;
    _S9.root_off_min_0 = root_off_min_1;
    _S9.root_off_max_0 = root_off_max_1;
    _S9.root_off_ave_0 = root_off_ave_1;
    _S9.root_off_stddev_0 = root_off_stddev_1;
    _S9.root_size_0 = root_size_1;
    _S9.value_stride_bits_0 = value_stride_bits_1;
    _S9.table_stride_0 = table_stride_1;
    _S9.root_tile_off_value_0 = root_tile_off_value_1;
    _S9.root_tile_size_0 = root_tile_size_1;
    _S9.upper_off_min_0 = upper_off_min_1;
    _S9.upper_off_max_0 = upper_off_max_1;
    _S9.upper_off_ave_0 = upper_off_ave_1;
    _S9.upper_off_stddev_0 = upper_off_stddev_1;
    _S9.upper_off_table_0 = upper_off_table_1;
    _S9.upper_size_0 = upper_size_1;
    _S9.lower_off_min_0 = lower_off_min_1;
    _S9.lower_off_max_0 = lower_off_max_1;
    _S9.lower_off_ave_0 = lower_off_ave_1;
    _S9.lower_off_stddev_0 = lower_off_stddev_1;
    _S9.lower_off_table_0 = lower_off_table_1;
    _S9.lower_size_0 = lower_size_1;
    _S9.leaf_off_min_0 = leaf_off_min_1;
    _S9.leaf_off_max_0 = leaf_off_max_1;
    _S9.leaf_off_ave_0 = leaf_off_ave_1;
    _S9.leaf_off_stddev_0 = leaf_off_stddev_1;
    _S9.leaf_off_table_0 = leaf_off_table_1;
    _S9.leaf_size_0 = leaf_size_1;
    return _S9;
}

fn pnanovdb_leaf_get_table_address_0( grid_type_1 : u32,  buf_6 : u32,  node_0 : pnanovdb_leaf_handle_t_0,  n_0 : u32) -> pnanovdb_address_t_0
{
    var _S10 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S11 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S12 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S13 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S14 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_0 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S10, _S11, _S12, _S10, _S11, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S12, _S10, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S10, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S13, _S13, _S14, _S14, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_0.address_9, pnanovdb_grid_type_constants_0[grid_type_1].leaf_off_table_0 + (((pnanovdb_grid_type_constants_0[grid_type_1].value_stride_bits_0 * n_0) >> (u32(3)))));
}

fn pnanovdb_leaf_get_value_address_and_cache_0( grid_type_2 : u32,  buf_7 : u32,  leaf_1 : pnanovdb_leaf_handle_t_0,  ijk_2 : vec3<i32>,  acc_3 : ptr<function, pnanovdb_readaccessor_t_0>) -> pnanovdb_address_t_0
{
    return pnanovdb_leaf_get_table_address_0(grid_type_2, buf_7, leaf_1, pnanovdb_leaf_coord_to_offset_0(ijk_2));
}

fn pnanovdb_readaccessor_iscached1_0( acc_4 : ptr<function, pnanovdb_readaccessor_t_0>,  dirty_1 : i32) -> bool
{
    if(pnanovdb_address_is_null_0((*acc_4).lower_0.address_10))
    {
        return false;
    }
    if(((u32(dirty_1) & (u32(4294967168)))) != u32(0))
    {
        (*acc_4).lower_0.address_10 = pnanovdb_address_null_0();
        return false;
    }
    return true;
}

fn pnanovdb_lower_coord_to_offset_0( ijk_3 : vec3<i32>) -> u32
{
    return u32((((((((ijk_3.x) & (i32(127)))) >> (u32(3)))) << (u32(8)))) + (((((((ijk_3.y) & (i32(127)))) >> (u32(3)))) << (u32(4)))) + (((((ijk_3.z) & (i32(127)))) >> (u32(3)))));
}

fn pnanovdb_read_uint32_0( buf_8 : u32,  address_13 : pnanovdb_address_t_0) -> u32
{
    return pnanovdb_buf_read_uint32_0(buf_8, address_13.byte_offset_0);
}

fn pnanovdb_lower_get_child_mask_0( buf_9 : u32,  p_1 : pnanovdb_lower_handle_t_0,  bit_index_0 : u32) -> bool
{
    return (((((pnanovdb_read_uint32_0(buf_9, pnanovdb_address_offset_0(p_1.address_10, u32(544) + u32(4) * ((bit_index_0 >> (u32(5))))))) >> (((bit_index_0 & (u32(31))))))) & (u32(1)))) != u32(0);
}

fn pnanovdb_leaf_handle_t_x24init_0( address_14 : pnanovdb_address_t_0) -> pnanovdb_leaf_handle_t_0
{
    var _S15 : pnanovdb_leaf_handle_t_0;
    _S15.address_9 = address_14;
    return _S15;
}

fn pnanovdb_lower_get_table_address_0( grid_type_3 : u32,  buf_10 : u32,  node_1 : pnanovdb_lower_handle_t_0,  n_1 : u32) -> pnanovdb_address_t_0
{
    var _S16 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S17 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S18 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S19 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S20 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_1 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S16, _S17, _S18, _S16, _S17, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S18, _S16, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S16, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S19, _S19, _S20, _S20, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_1.address_10, pnanovdb_grid_type_constants_1[grid_type_3].lower_off_table_0 + pnanovdb_grid_type_constants_1[grid_type_3].table_stride_0 * n_1);
}

fn pnanovdb_uint64_as_int64_0( v_2 : vec2<u32>) -> vec2<i32>
{
    return vec2<i32>(v_2);
}

fn pnanovdb_read_int64_0( buf_11 : u32,  address_15 : pnanovdb_address_t_0) -> vec2<i32>
{
    return pnanovdb_uint64_as_int64_0(pnanovdb_read_uint64_0(buf_11, address_15));
}

fn pnanovdb_lower_get_table_child_0( grid_type_4 : u32,  buf_12 : u32,  node_2 : pnanovdb_lower_handle_t_0,  n_2 : u32) -> vec2<i32>
{
    return pnanovdb_read_int64_0(buf_12, pnanovdb_lower_get_table_address_0(grid_type_4, buf_12, node_2, n_2));
}

fn pnanovdb_int64_as_uint64_0( v_3 : vec2<i32>) -> vec2<u32>
{
    return vec2<u32>(v_3);
}

fn pnanovdb_lower_get_child_0( grid_type_5 : u32,  buf_13 : u32,  lower_1 : pnanovdb_lower_handle_t_0,  n_3 : u32) -> pnanovdb_leaf_handle_t_0
{
    var leaf_2 : pnanovdb_leaf_handle_t_0 = pnanovdb_leaf_handle_t_x24init_0(lower_1.address_10);
    leaf_2.address_9 = pnanovdb_address_offset64_0(leaf_2.address_9, pnanovdb_int64_as_uint64_0(pnanovdb_lower_get_table_child_0(grid_type_5, buf_13, lower_1, n_3)));
    return leaf_2;
}

fn pnanovdb_lower_get_value_address_and_level_and_cache_0( grid_type_6 : u32,  buf_14 : u32,  lower_2 : pnanovdb_lower_handle_t_0,  ijk_4 : vec3<i32>,  acc_5 : ptr<function, pnanovdb_readaccessor_t_0>,  level_0 : ptr<function, u32>) -> pnanovdb_address_t_0
{
    var n_4 : u32 = pnanovdb_lower_coord_to_offset_0(ijk_4);
    var value_address_0 : pnanovdb_address_t_0;
    if(pnanovdb_lower_get_child_mask_0(buf_14, lower_2, n_4))
    {
        var child_0 : pnanovdb_leaf_handle_t_0 = pnanovdb_lower_get_child_0(grid_type_6, buf_14, lower_2, n_4);
        (*acc_5).leaf_0 = child_0;
        (*acc_5).key_0 = ijk_4;
        var _S21 : pnanovdb_address_t_0 = pnanovdb_leaf_get_value_address_and_cache_0(grid_type_6, buf_14, child_0, ijk_4, &((*acc_5)));
        (*level_0) = u32(0);
        value_address_0 = _S21;
    }
    else
    {
        var _S22 : pnanovdb_address_t_0 = pnanovdb_lower_get_table_address_0(grid_type_6, buf_14, lower_2, n_4);
        (*level_0) = u32(1);
        value_address_0 = _S22;
    }
    return value_address_0;
}

fn pnanovdb_readaccessor_iscached2_0( acc_6 : ptr<function, pnanovdb_readaccessor_t_0>,  dirty_2 : i32) -> bool
{
    if(pnanovdb_address_is_null_0((*acc_6).upper_0.address_11))
    {
        return false;
    }
    if(((u32(dirty_2) & (u32(4294963200)))) != u32(0))
    {
        (*acc_6).upper_0.address_11 = pnanovdb_address_null_0();
        return false;
    }
    return true;
}

fn pnanovdb_upper_coord_to_offset_0( ijk_5 : vec3<i32>) -> u32
{
    return u32((((((((ijk_5.x) & (i32(4095)))) >> (u32(7)))) << (u32(10)))) + (((((((ijk_5.y) & (i32(4095)))) >> (u32(7)))) << (u32(5)))) + (((((ijk_5.z) & (i32(4095)))) >> (u32(7)))));
}

fn pnanovdb_upper_get_child_mask_0( buf_15 : u32,  p_2 : pnanovdb_upper_handle_t_0,  bit_index_1 : u32) -> bool
{
    return (((((pnanovdb_read_uint32_0(buf_15, pnanovdb_address_offset_0(p_2.address_11, u32(4128) + u32(4) * ((bit_index_1 >> (u32(5))))))) >> (((bit_index_1 & (u32(31))))))) & (u32(1)))) != u32(0);
}

fn pnanovdb_lower_handle_t_x24init_0( address_16 : pnanovdb_address_t_0) -> pnanovdb_lower_handle_t_0
{
    var _S23 : pnanovdb_lower_handle_t_0;
    _S23.address_10 = address_16;
    return _S23;
}

fn pnanovdb_upper_get_table_address_0( grid_type_7 : u32,  buf_16 : u32,  node_3 : pnanovdb_upper_handle_t_0,  n_5 : u32) -> pnanovdb_address_t_0
{
    var _S24 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S25 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S26 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S27 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S28 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_2 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S24, _S25, _S26, _S24, _S25, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S26, _S24, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S24, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S27, _S27, _S28, _S28, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_3.address_11, pnanovdb_grid_type_constants_2[grid_type_7].upper_off_table_0 + pnanovdb_grid_type_constants_2[grid_type_7].table_stride_0 * n_5);
}

fn pnanovdb_upper_get_table_child_0( grid_type_8 : u32,  buf_17 : u32,  node_4 : pnanovdb_upper_handle_t_0,  n_6 : u32) -> vec2<i32>
{
    return pnanovdb_read_int64_0(buf_17, pnanovdb_upper_get_table_address_0(grid_type_8, buf_17, node_4, n_6));
}

fn pnanovdb_upper_get_child_0( grid_type_9 : u32,  buf_18 : u32,  upper_1 : pnanovdb_upper_handle_t_0,  n_7 : u32) -> pnanovdb_lower_handle_t_0
{
    var lower_3 : pnanovdb_lower_handle_t_0 = pnanovdb_lower_handle_t_x24init_0(upper_1.address_11);
    lower_3.address_10 = pnanovdb_address_offset64_0(lower_3.address_10, pnanovdb_int64_as_uint64_0(pnanovdb_upper_get_table_child_0(grid_type_9, buf_18, upper_1, n_7)));
    return lower_3;
}

fn pnanovdb_upper_get_value_address_and_level_and_cache_0( grid_type_10 : u32,  buf_19 : u32,  upper_2 : pnanovdb_upper_handle_t_0,  ijk_6 : vec3<i32>,  acc_7 : ptr<function, pnanovdb_readaccessor_t_0>,  level_1 : ptr<function, u32>) -> pnanovdb_address_t_0
{
    var n_8 : u32 = pnanovdb_upper_coord_to_offset_0(ijk_6);
    var value_address_1 : pnanovdb_address_t_0;
    if(pnanovdb_upper_get_child_mask_0(buf_19, upper_2, n_8))
    {
        var child_1 : pnanovdb_lower_handle_t_0 = pnanovdb_upper_get_child_0(grid_type_10, buf_19, upper_2, n_8);
        (*acc_7).lower_0 = child_1;
        (*acc_7).key_0 = ijk_6;
        var _S29 : pnanovdb_address_t_0 = pnanovdb_lower_get_value_address_and_level_and_cache_0(grid_type_10, buf_19, child_1, ijk_6, &((*acc_7)), &((*level_1)));
        value_address_1 = _S29;
    }
    else
    {
        var _S30 : pnanovdb_address_t_0 = pnanovdb_upper_get_table_address_0(grid_type_10, buf_19, upper_2, n_8);
        (*level_1) = u32(2);
        value_address_1 = _S30;
    }
    return value_address_1;
}

fn pnanovdb_root_get_tile_count_0( buf_20 : u32,  p_3 : pnanovdb_root_handle_t_0) -> u32
{
    return pnanovdb_read_uint32_0(buf_20, pnanovdb_address_offset_0(p_3.address_5, u32(24)));
}

fn pnanovdb_uint32_as_int32_0( v_4 : u32) -> i32
{
    return i32(v_4);
}

struct pnanovdb_root_tile_handle_t_0
{
     address_17 : pnanovdb_address_t_0,
};

fn pnanovdb_root_tile_handle_t_x24init_0( address_18 : pnanovdb_address_t_0) -> pnanovdb_root_tile_handle_t_0
{
    var _S31 : pnanovdb_root_tile_handle_t_0;
    _S31.address_17 = address_18;
    return _S31;
}

fn pnanovdb_root_get_tile_zero_0( grid_type_11 : u32,  root_3 : pnanovdb_root_handle_t_0) -> pnanovdb_root_tile_handle_t_0
{
    var tile_0 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_tile_handle_t_x24init_0(root_3.address_5);
    var _S32 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S33 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S34 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S35 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S36 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_3 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S32, _S33, _S34, _S32, _S33, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S34, _S32, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S32, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S35, _S35, _S36, _S36, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    tile_0.address_17 = pnanovdb_address_offset_0(tile_0.address_17, pnanovdb_grid_type_constants_3[grid_type_11].root_size_0);
    return tile_0;
}

fn pnanovdb_int32_as_uint32_0( v_5 : i32) -> u32
{
    return u32(v_5);
}

fn pnanovdb_uint32_as_uint64_0( x_0 : u32,  y_0 : u32) -> vec2<u32>
{
    return vec2<u32>(x_0, y_0);
}

fn pnanovdb_coord_to_key_0( ijk_7 : vec3<i32>) -> vec2<u32>
{
    var ju_0 : u32 = ((pnanovdb_int32_as_uint32_0(ijk_7.y)) >> (u32(12)));
    return pnanovdb_uint32_as_uint64_0(((((pnanovdb_int32_as_uint32_0(ijk_7.z)) >> (u32(12)))) | (((ju_0 << (u32(21)))))), ((((((pnanovdb_int32_as_uint32_0(ijk_7.x)) >> (u32(12)))) << (u32(10)))) | (((ju_0 >> (u32(11)))))));
}

fn pnanovdb_root_tile_get_key_0( buf_21 : u32,  p_4 : pnanovdb_root_tile_handle_t_0) -> vec2<u32>
{
    return pnanovdb_read_uint64_0(buf_21, pnanovdb_address_offset_0(p_4.address_17, u32(0)));
}

fn pnanovdb_uint64_is_equal_0( a_0 : vec2<u32>,  b_0 : vec2<u32>) -> bool
{
    var _S37 : bool;
    if((a_0.x) == (b_0.x))
    {
        _S37 = (a_0.y) == (b_0.y);
    }
    else
    {
        _S37 = false;
    }
    return _S37;
}

fn pnanovdb_root_find_tile_0( grid_type_12 : u32,  buf_22 : u32,  root_4 : pnanovdb_root_handle_t_0,  ijk_8 : vec3<i32>) -> pnanovdb_root_tile_handle_t_0
{
    var _S38 : u32 = u32(pnanovdb_uint32_as_int32_0(pnanovdb_root_get_tile_count_0(buf_22, root_4)));
    var tile_1 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_get_tile_zero_0(grid_type_12, root_4);
    var _S39 : vec2<u32> = pnanovdb_coord_to_key_0(ijk_8);
    var null_handle_0 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_tile_handle_t_x24init_0(pnanovdb_address_null_0());
    var _S40 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S41 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S42 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S43 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S44 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_4 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S40, _S41, _S42, _S40, _S41, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S42, _S40, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S40, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S43, _S43, _S44, _S44, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    var i_0 : u32 = u32(0);
    for(;;)
    {
        if(i_0 < _S38)
        {
        }
        else
        {
            break;
        }
        if(pnanovdb_uint64_is_equal_0(_S39, pnanovdb_root_tile_get_key_0(buf_22, tile_1)))
        {
            return tile_1;
        }
        tile_1.address_17 = pnanovdb_address_offset_0(tile_1.address_17, pnanovdb_grid_type_constants_4[grid_type_12].root_tile_size_0);
        i_0 = i_0 + u32(1);
    }
    return null_handle_0;
}

fn pnanovdb_root_tile_get_child_0( buf_23 : u32,  p_5 : pnanovdb_root_tile_handle_t_0) -> vec2<i32>
{
    return pnanovdb_read_int64_0(buf_23, pnanovdb_address_offset_0(p_5.address_17, u32(8)));
}

fn pnanovdb_int64_is_zero_0( a_1 : vec2<i32>) -> bool
{
    var _S45 : bool;
    if((a_1.x) == i32(0))
    {
        _S45 = (a_1.y) == i32(0);
    }
    else
    {
        _S45 = false;
    }
    return _S45;
}

fn pnanovdb_upper_handle_t_x24init_0( address_19 : pnanovdb_address_t_0) -> pnanovdb_upper_handle_t_0
{
    var _S46 : pnanovdb_upper_handle_t_0;
    _S46.address_11 = address_19;
    return _S46;
}

fn pnanovdb_root_get_child_0( grid_type_13 : u32,  buf_24 : u32,  root_5 : pnanovdb_root_handle_t_0,  tile_2 : pnanovdb_root_tile_handle_t_0) -> pnanovdb_upper_handle_t_0
{
    var upper_3 : pnanovdb_upper_handle_t_0 = pnanovdb_upper_handle_t_x24init_0(root_5.address_5);
    upper_3.address_11 = pnanovdb_address_offset64_0(upper_3.address_11, pnanovdb_int64_as_uint64_0(pnanovdb_root_tile_get_child_0(buf_24, tile_2)));
    return upper_3;
}

fn pnanovdb_root_get_value_address_and_level_and_cache_0( grid_type_14 : u32,  buf_25 : u32,  root_6 : pnanovdb_root_handle_t_0,  ijk_9 : vec3<i32>,  acc_8 : ptr<function, pnanovdb_readaccessor_t_0>,  level_2 : ptr<function, u32>) -> pnanovdb_address_t_0
{
    var tile_3 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_find_tile_0(grid_type_14, buf_25, root_6, ijk_9);
    var ret_3 : pnanovdb_address_t_0;
    if(pnanovdb_address_is_null_0(tile_3.address_17))
    {
        var _S47 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
        var _S48 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
        var _S49 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
        var _S50 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
        var _S51 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
        var pnanovdb_grid_type_constants_5 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S47, _S48, _S49, _S47, _S48, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S49, _S47, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S47, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S50, _S50, _S51, _S51, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
        var _S52 : pnanovdb_address_t_0 = pnanovdb_address_offset_0(root_6.address_5, pnanovdb_grid_type_constants_5[grid_type_14].root_off_background_0);
        (*level_2) = u32(4);
        ret_3 = _S52;
    }
    else
    {
        if(pnanovdb_int64_is_zero_0(pnanovdb_root_tile_get_child_0(buf_25, tile_3)))
        {
            var _S53 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
            var _S54 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
            var _S55 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
            var _S56 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
            var _S57 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
            var pnanovdb_grid_type_constants_6 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S53, _S54, _S55, _S53, _S54, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S55, _S53, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S53, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S56, _S56, _S57, _S57, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
            var _S58 : pnanovdb_address_t_0 = pnanovdb_address_offset_0(tile_3.address_17, pnanovdb_grid_type_constants_6[grid_type_14].root_tile_off_value_0);
            (*level_2) = u32(3);
            ret_3 = _S58;
        }
        else
        {
            var child_2 : pnanovdb_upper_handle_t_0 = pnanovdb_root_get_child_0(grid_type_14, buf_25, root_6, tile_3);
            (*acc_8).upper_0 = child_2;
            (*acc_8).key_0 = ijk_9;
            var _S59 : pnanovdb_address_t_0 = pnanovdb_upper_get_value_address_and_level_and_cache_0(grid_type_14, buf_25, child_2, ijk_9, &((*acc_8)), &((*level_2)));
            ret_3 = _S59;
        }
    }
    return ret_3;
}

fn pnanovdb_readaccessor_get_value_address_and_level_0( grid_type_15 : u32,  buf_26 : u32,  acc_9 : ptr<function, pnanovdb_readaccessor_t_0>,  ijk_10 : vec3<i32>,  level_3 : ptr<function, u32>) -> pnanovdb_address_t_0
{
    var dirty_3 : i32 = pnanovdb_readaccessor_computedirty_0(&((*acc_9)), ijk_10);
    var _S60 : bool = pnanovdb_readaccessor_iscached0_0(&((*acc_9)), dirty_3);
    var value_address_2 : pnanovdb_address_t_0;
    if(_S60)
    {
        var _S61 : pnanovdb_address_t_0 = pnanovdb_leaf_get_value_address_and_cache_0(grid_type_15, buf_26, (*acc_9).leaf_0, ijk_10, &((*acc_9)));
        (*level_3) = u32(0);
        value_address_2 = _S61;
    }
    else
    {
        var _S62 : bool = pnanovdb_readaccessor_iscached1_0(&((*acc_9)), dirty_3);
        if(_S62)
        {
            var _S63 : pnanovdb_address_t_0 = pnanovdb_lower_get_value_address_and_level_and_cache_0(grid_type_15, buf_26, (*acc_9).lower_0, ijk_10, &((*acc_9)), &((*level_3)));
            value_address_2 = _S63;
        }
        else
        {
            var _S64 : bool = pnanovdb_readaccessor_iscached2_0(&((*acc_9)), dirty_3);
            if(_S64)
            {
                var _S65 : pnanovdb_address_t_0 = pnanovdb_upper_get_value_address_and_level_and_cache_0(grid_type_15, buf_26, (*acc_9).upper_0, ijk_10, &((*acc_9)), &((*level_3)));
                value_address_2 = _S65;
            }
            else
            {
                var _S66 : pnanovdb_address_t_0 = pnanovdb_root_get_value_address_and_level_and_cache_0(grid_type_15, buf_26, (*acc_9).root_1, ijk_10, &((*acc_9)), &((*level_3)));
                value_address_2 = _S66;
            }
        }
    }
    return value_address_2;
}

fn pnanovdb_readaccessor_get_value_address_0( grid_type_16 : u32,  buf_27 : u32,  acc_10 : ptr<function, pnanovdb_readaccessor_t_0>,  ijk_11 : vec3<i32>) -> pnanovdb_address_t_0
{
    var level_4 : u32;
    var _S67 : pnanovdb_address_t_0 = pnanovdb_readaccessor_get_value_address_and_level_0(grid_type_16, buf_27, &((*acc_10)), ijk_11, &(level_4));
    return _S67;
}

fn pnanovdb_float_as_uint32_0( v_6 : f32) -> u32
{
    return (bitcast<u32>((v_6)));
}

fn pnanovdb_buf_write_uint32_0( buf_28 : u32,  byte_offset_6 : u32,  value_0 : u32)
{
    if(buf_28 == u32(0))
    {
        temperatureOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
    }
    else
    {
        if(buf_28 == u32(1))
        {
            fuelOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
        }
        else
        {
            if(buf_28 == u32(2))
            {
                burnOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
            }
            else
            {
                if(buf_28 == u32(3))
                {
                    smokeOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
                }
                else
                {
                    if(buf_28 == u32(4))
                    {
                        rgbaOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
                    }
                    else
                    {
                        rgbOut_0[(byte_offset_6 >> (u32(2)))] = value_0;
                    }
                }
            }
        }
    }
    return;
}

fn pnanovdb_write_uint32_0( buf_29 : u32,  address_20 : pnanovdb_address_t_0,  value_1 : u32)
{
    pnanovdb_buf_write_uint32_0(buf_29, address_20.byte_offset_0, value_1);
    return;
}

fn pnanovdb_write_float_0( buf_30 : u32,  address_21 : pnanovdb_address_t_0,  value_2 : f32)
{
    pnanovdb_write_uint32_0(buf_30, address_21, pnanovdb_float_as_uint32_0(value_2));
    return;
}

fn pnanovdb_write_coord_0( buf_31 : u32,  address_22 : pnanovdb_address_t_0,  value_3 : vec3<i32>)
{
    pnanovdb_write_uint32_0(buf_31, pnanovdb_address_offset_0(address_22, u32(0)), pnanovdb_int32_as_uint32_0(value_3.x));
    pnanovdb_write_uint32_0(buf_31, pnanovdb_address_offset_0(address_22, u32(4)), pnanovdb_int32_as_uint32_0(value_3.y));
    pnanovdb_write_uint32_0(buf_31, pnanovdb_address_offset_0(address_22, u32(8)), pnanovdb_int32_as_uint32_0(value_3.z));
    return;
}

fn pnanovdb_leaf_set_bbox_min_0( buf_32 : u32,  p_6 : pnanovdb_leaf_handle_t_0,  bbox_min_0 : vec3<i32>)
{
    pnanovdb_write_coord_0(buf_32, pnanovdb_address_offset_0(p_6.address_9, u32(0)), bbox_min_0);
    return;
}

fn pnanovdb_leaf_set_bbox_dif_and_flags_0( buf_33 : u32,  p_7 : pnanovdb_leaf_handle_t_0,  bbox_dif_and_flags_0 : u32)
{
    pnanovdb_write_uint32_0(buf_33, pnanovdb_address_offset_0(p_7.address_9, u32(12)), bbox_dif_and_flags_0);
    return;
}

fn writeChannel_0( channel_0 : u32,  threadIdx1D_0 : u32,  layerParamIdx_0 : u32,  vidx_0 : vec3<i32>,  value_4 : f32)
{
    var readaccessor_0 : pnanovdb_readaccessor_t_0;
    pnanovdb_readaccessor_init_0(&(readaccessor_0), pnanovdb_tree_get_root_0(channel_0, pnanovdb_grid_get_tree_0(channel_0, pnanovdb_grid_handle_t_x24init_0(pnanovdb_address_offset_0(pnanovdb_address_null_0(), layerParamIdx_0 * u32(736))))));
    var address_23 : pnanovdb_address_t_0 = pnanovdb_readaccessor_get_value_address_0(u32(1), channel_0, &(readaccessor_0), vidx_0);
    pnanovdb_write_float_0(channel_0, address_23, value_4);
    if(threadIdx1D_0 < u32(16))
    {
        pnanovdb_write_uint32_0(channel_0, pnanovdb_address_offset_0(readaccessor_0.leaf_0.address_9, u32(16) + u32(4) * threadIdx1D_0), u32(4294967295));
    }
    if(threadIdx1D_0 == u32(0))
    {
        pnanovdb_leaf_set_bbox_min_0(channel_0, readaccessor_0.leaf_0, vec3<i32>(((((vidx_0.x) >> (u32(3)))) << (u32(3))), ((((vidx_0.y) >> (u32(3)))) << (u32(3))), ((((vidx_0.z) >> (u32(3)))) << (u32(3)))));
        pnanovdb_leaf_set_bbox_dif_and_flags_0(channel_0, readaccessor_0.leaf_0, u32(526344));
    }
    return;
}

fn pnanovdb_grid_get_grid_type_0( buf_34 : u32,  p_8 : pnanovdb_grid_handle_t_0) -> u32
{
    return pnanovdb_read_uint32_0(buf_34, pnanovdb_address_offset_0(p_8.address_1, u32(636)));
}

fn writeChannelRgba_0( channel_1 : u32,  threadIdx1D_1 : u32,  layerParamIdx_1 : u32,  vidx_1 : vec3<i32>,  value_5 : vec4<f32>)
{
    var grid_1 : pnanovdb_grid_handle_t_0 = pnanovdb_grid_handle_t_x24init_0(pnanovdb_address_offset_0(pnanovdb_address_null_0(), layerParamIdx_1 * u32(736)));
    var grid_type_17 : u32 = pnanovdb_grid_get_grid_type_0(channel_1, grid_1);
    var readaccessor_1 : pnanovdb_readaccessor_t_0;
    pnanovdb_readaccessor_init_0(&(readaccessor_1), pnanovdb_tree_get_root_0(channel_1, pnanovdb_grid_get_tree_0(channel_1, grid_1)));
    var address_24 : pnanovdb_address_t_0 = pnanovdb_readaccessor_get_value_address_0(grid_type_17, channel_1, &(readaccessor_1), vidx_1);
    if(grid_type_17 == u32(17))
    {
        pnanovdb_write_float_0(channel_1, pnanovdb_address_offset_0(address_24, u32(0)), value_5.x);
        pnanovdb_write_float_0(channel_1, pnanovdb_address_offset_0(address_24, u32(4)), value_5.y);
        pnanovdb_write_float_0(channel_1, pnanovdb_address_offset_0(address_24, u32(8)), value_5.z);
        pnanovdb_write_float_0(channel_1, pnanovdb_address_offset_0(address_24, u32(12)), value_5.w);
    }
    else
    {
        if(grid_type_17 == u32(12))
        {
            pnanovdb_write_uint32_0(channel_1, pnanovdb_address_offset_0(address_24, u32(0)), (((((u32(255.0f * max(0.0f, min(1.0f, value_5.x))) | (((u32(255.0f * max(0.0f, min(1.0f, value_5.y))) << (u32(8))))))) | (((u32(255.0f * max(0.0f, min(1.0f, value_5.z))) << (u32(16))))))) | (((u32(255.0f * max(0.0f, min(1.0f, value_5.w))) << (u32(24)))))));
        }
    }
    if(threadIdx1D_1 < u32(16))
    {
        pnanovdb_write_uint32_0(channel_1, pnanovdb_address_offset_0(readaccessor_1.leaf_0.address_9, u32(16) + u32(4) * threadIdx1D_1), u32(4294967295));
    }
    if(threadIdx1D_1 == u32(0))
    {
        pnanovdb_leaf_set_bbox_min_0(channel_1, readaccessor_1.leaf_0, vec3<i32>(((((vidx_1.x) >> (u32(3)))) << (u32(3))), ((((vidx_1.y) >> (u32(3)))) << (u32(3))), ((((vidx_1.z) >> (u32(3)))) << (u32(3)))));
        pnanovdb_leaf_set_bbox_dif_and_flags_0(channel_1, readaccessor_1.leaf_0, u32(526344));
    }
    return;
}

fn writeChannelRgb_0( channel_2 : u32,  threadIdx1D_2 : u32,  layerParamIdx_2 : u32,  vidx_2 : vec3<i32>,  value_6 : vec3<f32>)
{
    var readaccessor_2 : pnanovdb_readaccessor_t_0;
    pnanovdb_readaccessor_init_0(&(readaccessor_2), pnanovdb_tree_get_root_0(channel_2, pnanovdb_grid_get_tree_0(channel_2, pnanovdb_grid_handle_t_x24init_0(pnanovdb_address_offset_0(pnanovdb_address_null_0(), layerParamIdx_2 * u32(736))))));
    var address_25 : pnanovdb_address_t_0 = pnanovdb_readaccessor_get_value_address_0(u32(6), channel_2, &(readaccessor_2), vidx_2);
    pnanovdb_write_float_0(channel_2, pnanovdb_address_offset_0(address_25, u32(0)), value_6.x);
    pnanovdb_write_float_0(channel_2, pnanovdb_address_offset_0(address_25, u32(4)), value_6.y);
    pnanovdb_write_float_0(channel_2, pnanovdb_address_offset_0(address_25, u32(8)), value_6.z);
    if(threadIdx1D_2 < u32(16))
    {
        pnanovdb_write_uint32_0(channel_2, pnanovdb_address_offset_0(readaccessor_2.leaf_0.address_9, u32(16) + u32(4) * threadIdx1D_2), u32(4294967295));
    }
    if(threadIdx1D_2 == u32(0))
    {
        pnanovdb_leaf_set_bbox_min_0(channel_2, readaccessor_2.leaf_0, vec3<i32>(((((vidx_2.x) >> (u32(3)))) << (u32(3))), ((((vidx_2.y) >> (u32(3)))) << (u32(3))), ((((vidx_2.z) >> (u32(3)))) << (u32(3)))));
        pnanovdb_leaf_set_bbox_dif_and_flags_0(channel_2, readaccessor_2.leaf_0, u32(526344));
    }
    return;
}

fn NvFlowGetLayerParamIdx_0( _S68 : NvFlowSparseLevelParams_0,  _S69 : u32) -> u32
{
    var layerParamIdx_3 : u32;
    if(_S69 < (_S68.numLocations_0))
    {
        layerParamIdx_3 = tableIn_0[_S69 + _S68.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_3 = u32(0);
    }
    return layerParamIdx_3;
}

fn NvFlowBlockIdxToLocation_0( _S70 : NvFlowSparseLevelParams_0,  _S71 : u32,  _S72 : ptr<function, vec4<i32>>) -> bool
{
    var _S73 : bool = _S71 < (_S70.numLocations_0);
    if(_S73)
    {
        var locationIdx_0 : u32 = ((_S71 << (u32(2)))) + _S70.locationOffset_0;
        (*_S72)[i32(0)] = i32(tableIn_0[locationIdx_0]);
        (*_S72)[i32(1)] = i32(tableIn_0[locationIdx_0 + u32(1)]);
        (*_S72)[i32(2)] = i32(tableIn_0[locationIdx_0 + u32(2)]);
        (*_S72)[i32(3)] = i32(tableIn_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S72)[i32(0)] = i32(1073741824);
        (*_S72)[i32(1)] = i32(1073741824);
        (*_S72)[i32(2)] = i32(1073741824);
        (*_S72)[i32(3)] = i32(1073741824);
    }
    return _S73;
}

fn NvFlowSingleVirtualToReal_0( _S74 : NvFlowSparseLevelParams_0,  _S75 : u32,  _S76 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S76, tableIn_0[NvFlowSingleToIdx_0(_S75) + _S74.blockLevelOffsetLocal_0]);
}

@compute
@workgroup_size(512, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx1D_3 : u32 = dispatchThreadID_0.x;
    var subBlockIdx1D_0 : u32 = dispatchThreadID_0.y;
    var blockIdx_1 : u32 = groupID_0.z + paramsIn_0.blockIdxOffset_0;
    var threadIdx_1 : vec3<i32> = vec3<i32>(i32(((((subBlockIdx1D_0 & ((paramsIn_0.densityFloat_0.subGridDimLessOne_0.x)))) << (u32(3)))) + ((threadIdx1D_3 & (u32(7))))), i32(((((((subBlockIdx1D_0 >> ((paramsIn_0.densityFloat_0.subGridDimBits_0.x)))) & ((paramsIn_0.densityFloat_0.subGridDimLessOne_0.y)))) << (u32(3)))) + ((((threadIdx1D_3 >> (u32(3)))) & (u32(7))))), i32(((((((subBlockIdx1D_0 >> ((paramsIn_0.densityFloat_0.subGridDimBits_0.x + paramsIn_0.densityFloat_0.subGridDimBits_0.y)))) & ((paramsIn_0.densityFloat_0.subGridDimLessOne_0.z)))) << (u32(3)))) + ((((threadIdx1D_3 >> (u32(6)))) & (u32(7))))));
    var _S77 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(paramsIn_0.tableDensity_0), blockIdx_1);
    var location_0 : vec4<i32>;
    var _S78 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_0(paramsIn_0.tableDensity_0), blockIdx_1, &(location_0));
    var vidx_3 : vec3<i32> = (((location_0.xyz) << (vec3<u32>(vec3<i32>(paramsIn_0.tableDensity_0.blockDimBits_0.xyz))))) + threadIdx_1;
    var _S79 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(NvFlowSingleVirtualToReal_0(unpackStorage_0(paramsIn_0.tableDensity_0), blockIdx_1, threadIdx_1).xyz), u32(0)));
    var _S80 : vec4<f32> = (textureLoad((densityIn_0), ((_S79)).xyz, ((_S79)).w));
    if((paramsIn_0.temperatureEnabled_0) != u32(0))
    {
        writeChannel_0(u32(0), threadIdx1D_3, _S77, vidx_3, _S80.x);
    }
    if((paramsIn_0.fuelEnabled_0) != u32(0))
    {
        writeChannel_0(u32(1), threadIdx1D_3, _S77, vidx_3, _S80.y);
    }
    if((paramsIn_0.burnEnabled_0) != u32(0))
    {
        writeChannel_0(u32(2), threadIdx1D_3, _S77, vidx_3, _S80.z);
    }
    if((paramsIn_0.smokeEnabled_0) != u32(0))
    {
        writeChannel_0(u32(3), threadIdx1D_3, _S77, vidx_3, _S80.w);
    }
    if((paramsIn_0.rgbaEnabled_0) != u32(0))
    {
        writeChannelRgba_0(u32(4), threadIdx1D_3, _S77, vidx_3, _S80);
    }
    if((paramsIn_0.rgbEnabled_0) != u32(0))
    {
        writeChannelRgb_0(u32(5), threadIdx1D_3, _S77, vidx_3, _S80.xyz);
    }
    return;
}

