// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct SparseRescaleGlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) tableParams_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableParamsOld_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : SparseRescaleGlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(3) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(4) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

struct SparseRescaleLayerParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) shouldClear_0 : u32,
    @align(16) blockSizeWorldOld_0 : vec3<f32>,
    @align(4) pad2_1 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<SparseRescaleLayerParams_std430_0>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_1.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_1.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_1.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_1.blockDimBits_0.y))))) & (i32(tableParams_1.blockDimLessOne_0.z))));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalVirtualToReal_0( _S6 : NvFlowSparseLevelParams_0,  _S7 : u32,  _S8 : vec3<i32>) -> vec4<i32>
{
    var neighbor_0 : vec3<i32> = (_S8 >> (vec3<u32>(vec3<i32>(_S6.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S8, gTable_0[NvFlowNeighborToIdx_0(_S7, neighbor_0.x, neighbor_0.y, neighbor_0.z) + _S6.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S9 : texture_3d<f32>,  _S10 : NvFlowSparseLevelParams_0,  _S11 : u32,  _S12 : vec3<i32>) -> vec4<f32>
{
    var _S13 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S10, _S11, _S12);
    var _S14 : vec4<f32>;
    if(bool(_S13.w))
    {
        var _S15 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S13.xyz), u32(0)));
        _S14 = (textureLoad((_S9), ((_S15)).xyz, ((_S15)).w));
    }
    else
    {
        _S14 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S14;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_1 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.tableParams_0), dispatchThreadID_0.x);
    var _S16 : u32 = groupID_0.y;
    var blockIdx_1 : u32 = _S16 + globalParamsIn_0.blockIdxOffset_0;
    var parity_0 : bool = (((((((threadIdx_1.x) ^ ((threadIdx_1.y)))) ^ ((threadIdx_1.z)))) & (i32(1)))) == i32(0);
    var readThreadIdx_0 : vec3<i32> = threadIdx_1;
    if(!parity_0)
    {
        readThreadIdx_0[i32(0)] = ((readThreadIdx_0[i32(0)]) ^ (i32(1)));
    }
    textureStore((valueOut_0), (vec3<u32>(threadIdx_1 + vec3<i32>((i32((_S16 & (u32(15)))) << (u32(i32(globalParamsIn_0.tableParams_0.blockDimBits_0.x)))), (((i32((_S16 >> (u32(4)))) & (i32(15)))) << (u32(i32(globalParamsIn_0.tableParams_0.blockDimBits_0.y)))), (((i32((_S16 >> (u32(8)))) & (i32(15)))) << (u32(i32(globalParamsIn_0.tableParams_0.blockDimBits_0.z))))))), (NvFlowLocalRead4f_0(valueIn_0, unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_1, readThreadIdx_0)));
    return;
}

