// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _Array_std140_NvFlowSparseLevelParams16_0
{
    @align(16) data_0 : array<NvFlowSparseLevelParams_std140_0, i32(16)>,
};

struct SparseShaderParams_std140_0
{
    @align(16) uploadBlockIdxOffset_0 : u32,
    @align(4) sparseBlockIdxOffset_0 : u32,
    @align(8) uploadSizeInBytes_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) tableParams_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) blockLevel_0 : _Array_std140_NvFlowSparseLevelParams16_0,
};

@binding(0) @group(0) var<uniform> gParams_0 : SparseShaderParams_std140_0;
@binding(1) @group(0) var<storage, read> gTableIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read_write> gTableOut_0 : array<u32>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn unpackAllocation_0( v_0 : u32) -> vec3<u32>
{
    return vec3<u32>(vec3<i32>(i32((v_0 & (u32(1023)))), i32((((v_0 >> (u32(10)))) & (u32(1023)))), i32((((v_0 >> (u32(20)))) & (u32(1023))))));
}

fn blockIdxToTableValue_0( blockIdx_0 : u32,  blockDimBits_1 : vec3<u32>,  neighborOffset_0 : vec3<i32>) -> u32
{
    var blockIdx3_0 : vec3<u32> = unpackAllocation_0(gTableIn_0[blockIdx_0 + gParams_0.tableParams_0.allocationOffset_0]);
    var _S3 : vec3<u32> = vec3<u32>(u32(1));
    var texelOffset_0 : vec3<u32> = ((((blockIdx3_0 << (blockDimBits_1))) + ((blockIdx3_0 << (_S3))) - vec3<u32>((neighborOffset_0 << (blockDimBits_1)))) >> (_S3));
    return (((((u32(2147483648) | ((((((texelOffset_0.z) & (u32(1023)))) << (u32(21))))))) | ((((((texelOffset_0.y) & (u32(1023)))) << (u32(11))))))) | ((((texelOffset_0.x) & (u32(2047))))));
}

fn blockIdxToTableValuePad_0( blockIdx_1 : u32,  blockDimBits_2 : vec3<u32>,  neighborOffset_1 : vec3<i32>) -> u32
{
    var blockIdx3_1 : vec3<u32> = unpackAllocation_0(gTableIn_0[blockIdx_1 + gParams_0.tableParams_0.allocationOffset_0]);
    var _S4 : vec3<u32> = vec3<u32>(u32(1));
    var texelOffset_1 : vec3<u32> = ((((blockIdx3_1 << (blockDimBits_2))) + ((blockIdx3_1 << (_S4)))) >> (_S4));
    return ((((((((texelOffset_1.z) & (u32(1023)))) << (u32(21)))) | ((((((texelOffset_1.y) & (u32(1023)))) << (u32(11))))))) | ((((texelOffset_1.x) & (u32(2047))))));
}

fn NvFlowLocationToBlockIdx_0( _S5 : NvFlowSparseLevelParams_0,  _S6 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S6.xyz) & ((_S5.tableDimLessOne_0)));
    var _S7 : u32 = ((((((((bucketIdx_0.z) << ((_S5.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S5.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S8 : u32 = gTableIn_0[_S7 + u32(1)];
    var _S9 : i32 = _S6.x;
    var _S10 : i32 = _S6.y;
    var _S11 : i32 = _S6.z;
    var _S12 : i32 = _S6.w;
    var blockIdx_2 : u32 = gTableIn_0[_S7];
    for(;;)
    {
        if(blockIdx_2 < _S8)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_2 << (u32(2)))) + _S5.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTableIn_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTableIn_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTableIn_0[compareLocationIdx_0 + u32(3)]);
        var _S13 : bool;
        if(i32(gTableIn_0[compareLocationIdx_0]) == _S9)
        {
            _S13 = compareLocation_y_0 == _S10;
        }
        else
        {
            _S13 = false;
        }
        var _S14 : bool;
        if(_S13)
        {
            _S14 = compareLocation_z_0 == _S11;
        }
        else
        {
            _S14 = false;
        }
        var _S15 : bool;
        if(_S14)
        {
            _S15 = compareLocation_w_0 == _S12;
        }
        else
        {
            _S15 = false;
        }
        if(_S15)
        {
            outBlockIdx_0 = blockIdx_2;
            break;
        }
        blockIdx_2 = blockIdx_2 + u32(1);
    }
    return outBlockIdx_0;
}

@compute
@workgroup_size(32, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var _S16 : u32 = dispatchThreadID_0.x;
    var laneIdx_0 : u32 = (_S16 & (u32(31)));
    var blockLevel_1 : u32 = (_S16 >> (u32(5)));
    var blockIdx_3 : u32 = groupID_0.y + gParams_0.sparseBlockIdxOffset_0;
    if(blockIdx_3 < (gParams_0.tableParams_0.numLocations_0))
    {
        var locationOffset_1 : u32 = gParams_0.tableParams_0.locationOffset_0;
        var location_0 : vec4<i32>;
        var _S17 : u32 = u32(4) * blockIdx_3;
        location_0[i32(0)] = i32(gTableIn_0[_S17 + gParams_0.tableParams_0.locationOffset_0]);
        location_0[i32(1)] = i32(gTableIn_0[_S17 + u32(1) + locationOffset_1]);
        location_0[i32(2)] = i32(gTableIn_0[_S17 + u32(2) + locationOffset_1]);
        location_0[i32(3)] = i32(gTableIn_0[_S17 + u32(3) + locationOffset_1]);
        var _S18 : bool = laneIdx_0 == u32(0);
        var tableValue_0 : u32;
        if(_S18)
        {
            var tableValue_1 : u32 = blockIdxToTableValue_0(blockIdx_3, gParams_0.blockLevel_0.data_0[blockLevel_1].blockDimBits_0, vec3<i32>(i32(0), i32(0), i32(0)));
            if(blockIdx_3 < (gParams_0.tableParams_0.numLocations_0))
            {
                tableValue_0 = tableValue_1;
            }
            else
            {
                tableValue_0 = u32(0);
            }
            gTableOut_0[blockIdx_3 + gParams_0.blockLevel_0.data_0[blockLevel_1].blockLevelOffsetGlobal_0] = tableValue_0;
        }
        var baseOffset_0 : u32 = ((blockIdx_3 << (u32(5)))) + gParams_0.blockLevel_0.data_0[blockLevel_1].blockLevelOffsetLocal_0;
        if(_S18)
        {
            tableValue_0 = u32(location_0.x);
        }
        else
        {
            tableValue_0 = u32(0);
        }
        if(laneIdx_0 == u32(1))
        {
            tableValue_0 = u32(location_0.y);
        }
        if(laneIdx_0 == u32(2))
        {
            tableValue_0 = u32(location_0.z);
        }
        if(laneIdx_0 == u32(3))
        {
            tableValue_0 = u32(location_0.w);
        }
        if(laneIdx_0 == u32(4))
        {
            tableValue_0 = u32(0);
        }
        if(laneIdx_0 >= u32(5))
        {
            var _S19 : u32 = laneIdx_0 - u32(5);
            var i_0 : i32 = i32(_S19 % u32(3)) - i32(1);
            var j_0 : i32 = i32(_S19 / u32(3) % u32(3)) - i32(1);
            var k_0 : i32 = i32(_S19 / u32(9)) - i32(1);
            var _S20 : u32 = NvFlowLocationToBlockIdx_0(unpackStorage_0(gParams_0.tableParams_0), location_0 + vec4<i32>(i_0, j_0, k_0, i32(0)));
            if(_S20 != u32(4294967295))
            {
                tableValue_0 = blockIdxToTableValue_0(_S20, gParams_0.blockLevel_0.data_0[blockLevel_1].blockDimBits_0, vec3<i32>(i_0, j_0, k_0));
            }
            else
            {
                tableValue_0 = blockIdxToTableValuePad_0(blockIdx_3, gParams_0.blockLevel_0.data_0[blockLevel_1].blockDimBits_0, vec3<i32>(i_0, j_0, k_0));
            }
        }
        gTableOut_0[baseOffset_0 + laneIdx_0] = tableValue_0;
    }
    return;
}

