// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseNanoVdbParams_std140_0
{
    @align(16) nanovdb_size_without_leaves_0 : vec2<u32>,
    @align(8) nanovdb_size_with_leaves_0 : vec2<u32>,
    @align(16) list_tile_offset_0 : vec2<u32>,
    @align(8) list_upper_offset_0 : vec2<u32>,
    @align(16) list_lower_offset_0 : vec2<u32>,
    @align(8) list_leaf_offset_0 : vec2<u32>,
    @align(16) cache_tile_offset_0 : vec2<u32>,
    @align(8) cache_upper_offset_0 : vec2<u32>,
    @align(16) cache_lower_offset_0 : vec2<u32>,
    @align(8) cache_leaf_offset_0 : vec2<u32>,
    @align(16) list_tile_count_0 : u32,
    @align(4) list_upper_count_0 : u32,
    @align(8) list_lower_count_0 : u32,
    @align(4) list_leaf_count_0 : u32,
    @align(16) cache_tile_count_0 : u32,
    @align(4) cache_upper_count_0 : u32,
    @align(8) cache_lower_count_0 : u32,
    @align(4) cache_leaf_count_0 : u32,
    @align(16) cache_size_0 : vec2<u32>,
    @align(8) grid_count_0 : u32,
    @align(4) grid_type_0 : u32,
    @align(16) subGridDimLessOne_0 : vec3<u32>,
    @align(4) pad3_0 : u32,
    @align(16) subGridDimBits_0 : vec3<u32>,
    @align(4) pad4_0 : u32,
};

struct SparseNanoVdbComputeStatsParams_std140_0
{
    @align(16) blockIdxOffset0_0 : u32,
    @align(4) blockIdxOffset1_0 : u32,
    @align(8) blockIdxOffset2_0 : u32,
    @align(4) blockIdxOffset3_0 : u32,
    @align(16) nanoVdb_0 : NvFlowSparseNanoVdbParams_std140_0,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : SparseNanoVdbComputeStatsParams_std140_0;
@binding(1) @group(0) var<storage, read> cacheIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read> nanovdbSrcIn_0 : array<u32>;

@binding(3) @group(0) var<storage, read_write> nanovdbInOut_0 : array<u32>;

struct pnanovdb_address_t_0
{
     byte_offset_0 : u32,
};

fn pnanovdb_address_offset_0( address_0 : pnanovdb_address_t_0,  byte_offset_1 : u32) -> pnanovdb_address_t_0
{
    var ret_0 : pnanovdb_address_t_0 = address_0;
    ret_0.byte_offset_0 = ret_0.byte_offset_0 + byte_offset_1;
    return ret_0;
}

fn pnanovdb_buf_read_uint32_0( buf_0 : u32,  byte_offset_2 : u32) -> u32
{
    return nanovdbSrcIn_0[(byte_offset_2 >> (u32(2)))];
}

fn pnanovdb_read_uint32_0( buf_1 : u32,  address_1 : pnanovdb_address_t_0) -> u32
{
    return pnanovdb_buf_read_uint32_0(buf_1, address_1.byte_offset_0);
}

struct pnanovdb_lower_handle_t_0
{
     address_2 : pnanovdb_address_t_0,
};

fn pnanovdb_lower_get_child_mask_0( buf_2 : u32,  p_0 : pnanovdb_lower_handle_t_0,  bit_index_0 : u32) -> bool
{
    return (((((pnanovdb_read_uint32_0(buf_2, pnanovdb_address_offset_0(p_0.address_2, u32(544) + u32(4) * ((bit_index_0 >> (u32(5))))))) >> (((bit_index_0 & (u32(31))))))) & (u32(1)))) != u32(0);
}

struct pnanovdb_leaf_handle_t_0
{
     address_3 : pnanovdb_address_t_0,
};

fn pnanovdb_leaf_handle_t_x24init_0( address_4 : pnanovdb_address_t_0) -> pnanovdb_leaf_handle_t_0
{
    var _S1 : pnanovdb_leaf_handle_t_0;
    _S1.address_3 = address_4;
    return _S1;
}

struct pnanovdb_grid_type_constants_t_0
{
     root_off_background_0 : u32,
     root_off_min_0 : u32,
     root_off_max_0 : u32,
     root_off_ave_0 : u32,
     root_off_stddev_0 : u32,
     root_size_0 : u32,
     value_stride_bits_0 : u32,
     table_stride_0 : u32,
     root_tile_off_value_0 : u32,
     root_tile_size_0 : u32,
     upper_off_min_0 : u32,
     upper_off_max_0 : u32,
     upper_off_ave_0 : u32,
     upper_off_stddev_0 : u32,
     upper_off_table_0 : u32,
     upper_size_0 : u32,
     lower_off_min_0 : u32,
     lower_off_max_0 : u32,
     lower_off_ave_0 : u32,
     lower_off_stddev_0 : u32,
     lower_off_table_0 : u32,
     lower_size_0 : u32,
     leaf_off_min_0 : u32,
     leaf_off_max_0 : u32,
     leaf_off_ave_0 : u32,
     leaf_off_stddev_0 : u32,
     leaf_off_table_0 : u32,
     leaf_size_0 : u32,
};

fn pnanovdb_grid_type_constants_t_x24init_0( root_off_background_1 : u32,  root_off_min_1 : u32,  root_off_max_1 : u32,  root_off_ave_1 : u32,  root_off_stddev_1 : u32,  root_size_1 : u32,  value_stride_bits_1 : u32,  table_stride_1 : u32,  root_tile_off_value_1 : u32,  root_tile_size_1 : u32,  upper_off_min_1 : u32,  upper_off_max_1 : u32,  upper_off_ave_1 : u32,  upper_off_stddev_1 : u32,  upper_off_table_1 : u32,  upper_size_1 : u32,  lower_off_min_1 : u32,  lower_off_max_1 : u32,  lower_off_ave_1 : u32,  lower_off_stddev_1 : u32,  lower_off_table_1 : u32,  lower_size_1 : u32,  leaf_off_min_1 : u32,  leaf_off_max_1 : u32,  leaf_off_ave_1 : u32,  leaf_off_stddev_1 : u32,  leaf_off_table_1 : u32,  leaf_size_1 : u32) -> pnanovdb_grid_type_constants_t_0
{
    var _S2 : pnanovdb_grid_type_constants_t_0;
    _S2.root_off_background_0 = root_off_background_1;
    _S2.root_off_min_0 = root_off_min_1;
    _S2.root_off_max_0 = root_off_max_1;
    _S2.root_off_ave_0 = root_off_ave_1;
    _S2.root_off_stddev_0 = root_off_stddev_1;
    _S2.root_size_0 = root_size_1;
    _S2.value_stride_bits_0 = value_stride_bits_1;
    _S2.table_stride_0 = table_stride_1;
    _S2.root_tile_off_value_0 = root_tile_off_value_1;
    _S2.root_tile_size_0 = root_tile_size_1;
    _S2.upper_off_min_0 = upper_off_min_1;
    _S2.upper_off_max_0 = upper_off_max_1;
    _S2.upper_off_ave_0 = upper_off_ave_1;
    _S2.upper_off_stddev_0 = upper_off_stddev_1;
    _S2.upper_off_table_0 = upper_off_table_1;
    _S2.upper_size_0 = upper_size_1;
    _S2.lower_off_min_0 = lower_off_min_1;
    _S2.lower_off_max_0 = lower_off_max_1;
    _S2.lower_off_ave_0 = lower_off_ave_1;
    _S2.lower_off_stddev_0 = lower_off_stddev_1;
    _S2.lower_off_table_0 = lower_off_table_1;
    _S2.lower_size_0 = lower_size_1;
    _S2.leaf_off_min_0 = leaf_off_min_1;
    _S2.leaf_off_max_0 = leaf_off_max_1;
    _S2.leaf_off_ave_0 = leaf_off_ave_1;
    _S2.leaf_off_stddev_0 = leaf_off_stddev_1;
    _S2.leaf_off_table_0 = leaf_off_table_1;
    _S2.leaf_size_0 = leaf_size_1;
    return _S2;
}

fn pnanovdb_lower_get_table_address_0( grid_type_1 : u32,  buf_3 : u32,  node_0 : pnanovdb_lower_handle_t_0,  n_0 : u32) -> pnanovdb_address_t_0
{
    var _S3 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S4 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S5 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S6 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S7 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_0 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S3, _S4, _S5, _S3, _S4, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S5, _S3, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S3, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S6, _S6, _S7, _S7, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_0.address_2, pnanovdb_grid_type_constants_0[grid_type_1].lower_off_table_0 + pnanovdb_grid_type_constants_0[grid_type_1].table_stride_0 * n_0);
}

fn pnanovdb_buf_read_uint64_0( buf_4 : u32,  byte_offset_3 : u32) -> vec2<u32>
{
    var ret_1 : vec2<u32>;
    ret_1[i32(0)] = pnanovdb_buf_read_uint32_0(buf_4, byte_offset_3);
    ret_1[i32(1)] = pnanovdb_buf_read_uint32_0(buf_4, byte_offset_3 + u32(4));
    return ret_1;
}

fn pnanovdb_read_uint64_0( buf_5 : u32,  address_5 : pnanovdb_address_t_0) -> vec2<u32>
{
    return pnanovdb_buf_read_uint64_0(buf_5, address_5.byte_offset_0);
}

fn pnanovdb_uint64_as_int64_0( v_0 : vec2<u32>) -> vec2<i32>
{
    return vec2<i32>(v_0);
}

fn pnanovdb_read_int64_0( buf_6 : u32,  address_6 : pnanovdb_address_t_0) -> vec2<i32>
{
    return pnanovdb_uint64_as_int64_0(pnanovdb_read_uint64_0(buf_6, address_6));
}

fn pnanovdb_lower_get_table_child_0( grid_type_2 : u32,  buf_7 : u32,  node_1 : pnanovdb_lower_handle_t_0,  n_1 : u32) -> vec2<i32>
{
    return pnanovdb_read_int64_0(buf_7, pnanovdb_lower_get_table_address_0(grid_type_2, buf_7, node_1, n_1));
}

fn pnanovdb_int64_as_uint64_0( v_1 : vec2<i32>) -> vec2<u32>
{
    return vec2<u32>(v_1);
}

fn pnanovdb_uint64_low_0( v_2 : vec2<u32>) -> u32
{
    return v_2.x;
}

fn pnanovdb_address_offset64_0( address_7 : pnanovdb_address_t_0,  byte_offset_4 : vec2<u32>) -> pnanovdb_address_t_0
{
    var ret_2 : pnanovdb_address_t_0 = address_7;
    ret_2.byte_offset_0 = ret_2.byte_offset_0 + pnanovdb_uint64_low_0(byte_offset_4);
    return ret_2;
}

fn pnanovdb_lower_get_child_0( grid_type_3 : u32,  buf_8 : u32,  lower_0 : pnanovdb_lower_handle_t_0,  n_2 : u32) -> pnanovdb_leaf_handle_t_0
{
    var leaf_0 : pnanovdb_leaf_handle_t_0 = pnanovdb_leaf_handle_t_x24init_0(lower_0.address_2);
    leaf_0.address_3 = pnanovdb_address_offset64_0(leaf_0.address_3, pnanovdb_int64_as_uint64_0(pnanovdb_lower_get_table_child_0(grid_type_3, buf_8, lower_0, n_2)));
    return leaf_0;
}

fn pnanovdb_buf_write_uint32_0( buf_9 : u32,  byte_offset_5 : u32,  value_0 : u32)
{
    nanovdbInOut_0[(byte_offset_5 >> (u32(2)))] = value_0;
    return;
}

fn pnanovdb_write_uint32_0( buf_10 : u32,  address_8 : pnanovdb_address_t_0,  value_1 : u32)
{
    pnanovdb_buf_write_uint32_0(buf_10, address_8.byte_offset_0, value_1);
    return;
}

fn pnanovdb_address_t_x24init_0( byte_offset_6 : u32) -> pnanovdb_address_t_0
{
    var _S8 : pnanovdb_address_t_0;
    _S8.byte_offset_0 = byte_offset_6;
    return _S8;
}

fn pnanovdb_address_null_0() -> pnanovdb_address_t_0
{
    return pnanovdb_address_t_x24init_0(u32(0));
}

fn pnanovdb_uint32_as_uint64_low_0( x_0 : u32) -> vec2<u32>
{
    return vec2<u32>(x_0, u32(0));
}

fn pnanovdb_uint64_high_0( v_3 : vec2<u32>) -> u32
{
    return v_3.y;
}

fn pnanovdb_uint32_as_uint64_0( x_1 : u32,  y_0 : u32) -> vec2<u32>
{
    return vec2<u32>(x_1, y_0);
}

fn pnanovdb_uint64_diff_0( a_0 : vec2<u32>,  b_0 : vec2<u32>) -> vec2<i32>
{
    var low_0 : u32 = pnanovdb_uint64_low_0(a_0);
    var high_0 : u32 = pnanovdb_uint64_high_0(a_0);
    var low_1 : u32 = low_0 - pnanovdb_uint64_low_0(b_0);
    var high_1 : u32;
    if(low_1 > low_0)
    {
        high_1 = high_0 - u32(1);
    }
    else
    {
        high_1 = high_0;
    }
    return pnanovdb_uint64_as_int64_0(pnanovdb_uint32_as_uint64_0(low_1, high_1 - pnanovdb_uint64_high_0(b_0)));
}

fn pnanovdb_address_diff_0( a_1 : pnanovdb_address_t_0,  b_1 : pnanovdb_address_t_0) -> vec2<i32>
{
    return pnanovdb_uint64_diff_0(pnanovdb_uint32_as_uint64_low_0(a_1.byte_offset_0), pnanovdb_uint32_as_uint64_low_0(b_1.byte_offset_0));
}

fn pnanovdb_buf_write_uint64_0( buf_11 : u32,  byte_offset_7 : u32,  value_2 : vec2<u32>)
{
    pnanovdb_buf_write_uint32_0(buf_11, byte_offset_7, value_2.x);
    pnanovdb_buf_write_uint32_0(buf_11, byte_offset_7 + u32(4), value_2.y);
    return;
}

fn pnanovdb_write_int64_0( buf_12 : u32,  address_9 : pnanovdb_address_t_0,  value_3 : vec2<i32>)
{
    pnanovdb_buf_write_uint64_0(buf_12, address_9.byte_offset_0, pnanovdb_int64_as_uint64_0(value_3));
    return;
}

fn pnanovdb_lower_set_table_child_0( grid_type_4 : u32,  buf_13 : u32,  node_2 : pnanovdb_lower_handle_t_0,  n_3 : u32,  child_0 : vec2<i32>)
{
    pnanovdb_write_int64_0(buf_13, pnanovdb_lower_get_table_address_0(grid_type_4, buf_13, node_2, n_3), child_0);
    return;
}

fn pnanovdb_lower_set_child_0( grid_type_5 : u32,  buf_14 : u32,  lower_1 : pnanovdb_lower_handle_t_0,  n_4 : u32,  leaf_1 : pnanovdb_leaf_handle_t_0)
{
    pnanovdb_lower_set_table_child_0(grid_type_5, buf_14, lower_1, n_4, pnanovdb_address_diff_0(leaf_1.address_3, lower_1.address_2));
    return;
}

fn pnanovdb_leaf_get_max_address_0( grid_type_6 : u32,  buf_15 : u32,  node_3 : pnanovdb_leaf_handle_t_0) -> pnanovdb_address_t_0
{
    var _S9 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S10 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S11 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S12 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S13 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_1 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S9, _S10, _S11, _S9, _S10, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S11, _S9, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S9, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S12, _S12, _S13, _S13, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_3.address_3, pnanovdb_grid_type_constants_1[grid_type_6].leaf_off_max_0);
}

fn pnanovdb_uint32_as_float_0( v_4 : u32) -> f32
{
    return (bitcast<f32>((v_4)));
}

fn pnanovdb_read_float_0( buf_16 : u32,  address_10 : pnanovdb_address_t_0) -> f32
{
    return pnanovdb_uint32_as_float_0(pnanovdb_read_uint32_0(buf_16, address_10));
}

fn pnanovdb_float_as_uint32_0( v_5 : f32) -> u32
{
    return (bitcast<u32>((v_5)));
}

fn pnanovdb_write_float_0( buf_17 : u32,  address_11 : pnanovdb_address_t_0,  value_4 : f32)
{
    pnanovdb_write_uint32_0(buf_17, address_11, pnanovdb_float_as_uint32_0(value_4));
    return;
}

fn pruneLeaves_0( threadIdx1D_0 : u32,  nodeIdx0_0 : u32,  grid_type_7 : u32)
{
    var lower_2 : pnanovdb_lower_handle_t_0;
    lower_2.address_2.byte_offset_0 = cacheIn_0[(((paramsIn_0.nanoVdb_0.list_lower_offset_0.x) >> (u32(2)))) + u32(2) * nodeIdx0_0];
    var null_leaf_0 : pnanovdb_leaf_handle_t_0 = pnanovdb_leaf_handle_t_x24init_0(pnanovdb_address_null_0());
    var _S14 : bool = grid_type_7 == u32(6);
    var _S15 : bool = grid_type_7 == u32(17);
    var _S16 : bool = grid_type_7 == u32(12);
    var lower_n_0 : u32 = threadIdx1D_0;
    for(;;)
    {
        if(lower_n_0 < u32(4096))
        {
        }
        else
        {
            break;
        }
        if(!pnanovdb_lower_get_child_mask_0(u32(0), lower_2, lower_n_0))
        {
            lower_n_0 = lower_n_0 + u32(256);
            continue;
        }
        var leaf_2 : pnanovdb_leaf_handle_t_0 = pnanovdb_lower_get_child_0(grid_type_7, u32(0), lower_2, lower_n_0);
        pnanovdb_write_uint32_0(u32(0), pnanovdb_address_offset_0(lower_2.address_2, u32(544) + u32(4) * ((lower_n_0 >> (u32(5))))), u32(0));
        pnanovdb_lower_set_child_0(grid_type_7, u32(0), lower_2, lower_n_0, null_leaf_0);
        var maxAddr_0 : pnanovdb_address_t_0 = pnanovdb_leaf_get_max_address_0(grid_type_7, u32(0), leaf_2);
        var dstAddr_0 : pnanovdb_address_t_0 = pnanovdb_lower_get_table_address_0(grid_type_7, u32(0), lower_2, lower_n_0);
        if(_S14)
        {
            var v_y_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(maxAddr_0, u32(4)));
            var v_z_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(maxAddr_0, u32(8)));
            pnanovdb_write_float_0(u32(0), dstAddr_0, pnanovdb_read_float_0(u32(0), maxAddr_0));
            pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(dstAddr_0, u32(4)), v_y_0);
            pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(dstAddr_0, u32(8)), v_z_0);
        }
        else
        {
            if(_S15)
            {
                var v_y_1 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(maxAddr_0, u32(4)));
                var v_z_1 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(maxAddr_0, u32(8)));
                var v_w_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(maxAddr_0, u32(12)));
                pnanovdb_write_float_0(u32(0), dstAddr_0, pnanovdb_read_float_0(u32(0), maxAddr_0));
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(dstAddr_0, u32(4)), v_y_1);
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(dstAddr_0, u32(8)), v_z_1);
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(dstAddr_0, u32(12)), v_w_0);
            }
            else
            {
                if(_S16)
                {
                    pnanovdb_write_uint32_0(u32(0), dstAddr_0, pnanovdb_read_uint32_0(u32(0), maxAddr_0));
                }
                else
                {
                    pnanovdb_write_float_0(u32(0), dstAddr_0, pnanovdb_read_float_0(u32(0), maxAddr_0));
                }
            }
        }
        lower_n_0 = lower_n_0 + u32(256);
    }
    return;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx1D_1 : u32 = dispatchThreadID_0.x;
    var nodeIdx0_1 : u32 = groupID_0.y + paramsIn_0.blockIdxOffset0_0;
    if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(1))
    {
        pruneLeaves_0(threadIdx1D_1, nodeIdx0_1, u32(1));
    }
    else
    {
        if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(6))
        {
            pruneLeaves_0(threadIdx1D_1, nodeIdx0_1, u32(6));
        }
        else
        {
            if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(17))
            {
                pruneLeaves_0(threadIdx1D_1, nodeIdx0_1, u32(17));
            }
            else
            {
                if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(12))
                {
                    pruneLeaves_0(threadIdx1D_1, nodeIdx0_1, u32(12));
                }
            }
        }
    }
    return;
}

