// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseNanoVdbParams_std140_0
{
    @align(16) nanovdb_size_without_leaves_0 : vec2<u32>,
    @align(8) nanovdb_size_with_leaves_0 : vec2<u32>,
    @align(16) list_tile_offset_0 : vec2<u32>,
    @align(8) list_upper_offset_0 : vec2<u32>,
    @align(16) list_lower_offset_0 : vec2<u32>,
    @align(8) list_leaf_offset_0 : vec2<u32>,
    @align(16) cache_tile_offset_0 : vec2<u32>,
    @align(8) cache_upper_offset_0 : vec2<u32>,
    @align(16) cache_lower_offset_0 : vec2<u32>,
    @align(8) cache_leaf_offset_0 : vec2<u32>,
    @align(16) list_tile_count_0 : u32,
    @align(4) list_upper_count_0 : u32,
    @align(8) list_lower_count_0 : u32,
    @align(4) list_leaf_count_0 : u32,
    @align(16) cache_tile_count_0 : u32,
    @align(4) cache_upper_count_0 : u32,
    @align(8) cache_lower_count_0 : u32,
    @align(4) cache_leaf_count_0 : u32,
    @align(16) cache_size_0 : vec2<u32>,
    @align(8) grid_count_0 : u32,
    @align(4) grid_type_0 : u32,
    @align(16) subGridDimLessOne_0 : vec3<u32>,
    @align(4) pad3_0 : u32,
    @align(16) subGridDimBits_0 : vec3<u32>,
    @align(4) pad4_0 : u32,
};

struct SparseNanoVdbComputeStatsParams_std140_0
{
    @align(16) blockIdxOffset0_0 : u32,
    @align(4) blockIdxOffset1_0 : u32,
    @align(8) blockIdxOffset2_0 : u32,
    @align(4) blockIdxOffset3_0 : u32,
    @align(16) nanoVdb_0 : NvFlowSparseNanoVdbParams_std140_0,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : SparseNanoVdbComputeStatsParams_std140_0;
@binding(1) @group(0) var<storage, read> cacheIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read_write> nanovdbInOut_0 : array<u32>;

struct pnanovdb_grid_type_constants_t_0
{
     root_off_background_0 : u32,
     root_off_min_0 : u32,
     root_off_max_0 : u32,
     root_off_ave_0 : u32,
     root_off_stddev_0 : u32,
     root_size_0 : u32,
     value_stride_bits_0 : u32,
     table_stride_0 : u32,
     root_tile_off_value_0 : u32,
     root_tile_size_0 : u32,
     upper_off_min_0 : u32,
     upper_off_max_0 : u32,
     upper_off_ave_0 : u32,
     upper_off_stddev_0 : u32,
     upper_off_table_0 : u32,
     upper_size_0 : u32,
     lower_off_min_0 : u32,
     lower_off_max_0 : u32,
     lower_off_ave_0 : u32,
     lower_off_stddev_0 : u32,
     lower_off_table_0 : u32,
     lower_size_0 : u32,
     leaf_off_min_0 : u32,
     leaf_off_max_0 : u32,
     leaf_off_ave_0 : u32,
     leaf_off_stddev_0 : u32,
     leaf_off_table_0 : u32,
     leaf_size_0 : u32,
};

fn pnanovdb_grid_type_constants_t_x24init_0( root_off_background_1 : u32,  root_off_min_1 : u32,  root_off_max_1 : u32,  root_off_ave_1 : u32,  root_off_stddev_1 : u32,  root_size_1 : u32,  value_stride_bits_1 : u32,  table_stride_1 : u32,  root_tile_off_value_1 : u32,  root_tile_size_1 : u32,  upper_off_min_1 : u32,  upper_off_max_1 : u32,  upper_off_ave_1 : u32,  upper_off_stddev_1 : u32,  upper_off_table_1 : u32,  upper_size_1 : u32,  lower_off_min_1 : u32,  lower_off_max_1 : u32,  lower_off_ave_1 : u32,  lower_off_stddev_1 : u32,  lower_off_table_1 : u32,  lower_size_1 : u32,  leaf_off_min_1 : u32,  leaf_off_max_1 : u32,  leaf_off_ave_1 : u32,  leaf_off_stddev_1 : u32,  leaf_off_table_1 : u32,  leaf_size_1 : u32) -> pnanovdb_grid_type_constants_t_0
{
    var _S1 : pnanovdb_grid_type_constants_t_0;
    _S1.root_off_background_0 = root_off_background_1;
    _S1.root_off_min_0 = root_off_min_1;
    _S1.root_off_max_0 = root_off_max_1;
    _S1.root_off_ave_0 = root_off_ave_1;
    _S1.root_off_stddev_0 = root_off_stddev_1;
    _S1.root_size_0 = root_size_1;
    _S1.value_stride_bits_0 = value_stride_bits_1;
    _S1.table_stride_0 = table_stride_1;
    _S1.root_tile_off_value_0 = root_tile_off_value_1;
    _S1.root_tile_size_0 = root_tile_size_1;
    _S1.upper_off_min_0 = upper_off_min_1;
    _S1.upper_off_max_0 = upper_off_max_1;
    _S1.upper_off_ave_0 = upper_off_ave_1;
    _S1.upper_off_stddev_0 = upper_off_stddev_1;
    _S1.upper_off_table_0 = upper_off_table_1;
    _S1.upper_size_0 = upper_size_1;
    _S1.lower_off_min_0 = lower_off_min_1;
    _S1.lower_off_max_0 = lower_off_max_1;
    _S1.lower_off_ave_0 = lower_off_ave_1;
    _S1.lower_off_stddev_0 = lower_off_stddev_1;
    _S1.lower_off_table_0 = lower_off_table_1;
    _S1.lower_size_0 = lower_size_1;
    _S1.leaf_off_min_0 = leaf_off_min_1;
    _S1.leaf_off_max_0 = leaf_off_max_1;
    _S1.leaf_off_ave_0 = leaf_off_ave_1;
    _S1.leaf_off_stddev_0 = leaf_off_stddev_1;
    _S1.leaf_off_table_0 = leaf_off_table_1;
    _S1.leaf_size_0 = leaf_size_1;
    return _S1;
}

struct pnanovdb_address_t_0
{
     byte_offset_0 : u32,
};

fn pnanovdb_address_offset_0( address_0 : pnanovdb_address_t_0,  byte_offset_1 : u32) -> pnanovdb_address_t_0
{
    var ret_0 : pnanovdb_address_t_0 = address_0;
    ret_0.byte_offset_0 = ret_0.byte_offset_0 + byte_offset_1;
    return ret_0;
}

struct pnanovdb_leaf_handle_t_0
{
     address_1 : pnanovdb_address_t_0,
};

fn pnanovdb_leaf_get_table_address_0( grid_type_1 : u32,  buf_0 : u32,  node_0 : pnanovdb_leaf_handle_t_0,  n_0 : u32) -> pnanovdb_address_t_0
{
    var _S2 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S3 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S4 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S5 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S6 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_0 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S2, _S3, _S4, _S2, _S3, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S4, _S2, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S2, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S5, _S5, _S6, _S6, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_0.address_1, pnanovdb_grid_type_constants_0[grid_type_1].leaf_off_table_0 + (((pnanovdb_grid_type_constants_0[grid_type_1].value_stride_bits_0 * n_0) >> (u32(3)))));
}

fn pnanovdb_buf_read_uint32_0( buf_1 : u32,  byte_offset_2 : u32) -> u32
{
    return nanovdbInOut_0[(byte_offset_2 >> (u32(2)))];
}

fn pnanovdb_read_uint32_0( buf_2 : u32,  address_2 : pnanovdb_address_t_0) -> u32
{
    return pnanovdb_buf_read_uint32_0(buf_2, address_2.byte_offset_0);
}

fn pnanovdb_uint32_as_float_0( v_0 : u32) -> f32
{
    return (bitcast<f32>((v_0)));
}

fn pnanovdb_read_float_0( buf_3 : u32,  address_3 : pnanovdb_address_t_0) -> f32
{
    return pnanovdb_uint32_as_float_0(pnanovdb_read_uint32_0(buf_3, address_3));
}

fn stat_add_0( stat_0 : ptr<function, vec4<f32>>,  count_0 : ptr<function, u32>,  value_0 : f32)
{
    if((*count_0) == u32(0))
    {
        var _S7 : vec2<f32> = vec2<f32>(value_0);
        (*stat_0).x = _S7.x;
        (*stat_0).y = _S7.y;
    }
    (*stat_0)[i32(0)] = min((*stat_0).x, value_0);
    (*stat_0)[i32(1)] = max((*stat_0).y, value_0);
    var _S8 : u32 = (*count_0) + u32(1);
    (*count_0) = _S8;
    var delta_0 : f32 = value_0 - (*stat_0).z;
    (*stat_0)[i32(2)] = (*stat_0).z + delta_0 / f32(_S8);
    (*stat_0)[i32(3)] = (*stat_0).w + delta_0 * (value_0 - (*stat_0).z);
    return;
}

var<workgroup> sdata0_0 : array<vec4<f32>, i32(64)>;

var<workgroup> sdata0u_0 : array<u32, i32(64)>;

fn stat_merge_0( stat_1 : ptr<function, vec4<f32>>,  count_1 : ptr<function, u32>,  other_0 : vec4<f32>,  otherCount_0 : u32)
{
    if(otherCount_0 > u32(0))
    {
        (*stat_1)[i32(0)] = min((*stat_1).x, other_0.x);
        (*stat_1)[i32(1)] = max((*stat_1).y, other_0.y);
        var delta_1 : f32 = other_0.z - (*stat_1).z;
        var _S9 : f32 = 1.0f / f32((*count_1) + otherCount_0) * delta_1;
        var _S10 : f32 = f32(otherCount_0);
        (*stat_1)[i32(2)] = (*stat_1).z + _S9 * _S10;
        (*stat_1)[i32(3)] = (*stat_1).w + other_0.w + _S9 * delta_1 * f32((*count_1)) * _S10;
        (*count_1) = (*count_1) + otherCount_0;
    }
    return;
}

var<workgroup> sdata1_0 : array<vec4<f32>, i32(8)>;

var<workgroup> sdata1u_0 : array<u32, i32(8)>;

fn stat_stddev_0( stat_2 : vec4<f32>,  count_2 : u32) -> f32
{
    var var_0 : f32;
    if(count_2 > u32(1))
    {
        var_0 = stat_2.w / f32(count_2);
    }
    else
    {
        var_0 = 0.0f;
    }
    return sqrt(var_0);
}

fn pnanovdb_leaf_get_min_address_0( grid_type_2 : u32,  buf_4 : u32,  node_1 : pnanovdb_leaf_handle_t_0) -> pnanovdb_address_t_0
{
    var _S11 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S12 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S13 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S14 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S15 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_1 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S11, _S12, _S13, _S11, _S12, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S13, _S11, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S11, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S14, _S14, _S15, _S15, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_1.address_1, pnanovdb_grid_type_constants_1[grid_type_2].leaf_off_min_0);
}

fn pnanovdb_float_as_uint32_0( v_1 : f32) -> u32
{
    return (bitcast<u32>((v_1)));
}

fn pnanovdb_buf_write_uint32_0( buf_5 : u32,  byte_offset_3 : u32,  value_1 : u32)
{
    nanovdbInOut_0[(byte_offset_3 >> (u32(2)))] = value_1;
    return;
}

fn pnanovdb_write_uint32_0( buf_6 : u32,  address_4 : pnanovdb_address_t_0,  value_2 : u32)
{
    pnanovdb_buf_write_uint32_0(buf_6, address_4.byte_offset_0, value_2);
    return;
}

fn pnanovdb_write_float_0( buf_7 : u32,  address_5 : pnanovdb_address_t_0,  value_3 : f32)
{
    pnanovdb_write_uint32_0(buf_7, address_5, pnanovdb_float_as_uint32_0(value_3));
    return;
}

fn pnanovdb_leaf_get_max_address_0( grid_type_3 : u32,  buf_8 : u32,  node_2 : pnanovdb_leaf_handle_t_0) -> pnanovdb_address_t_0
{
    var _S16 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S17 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S18 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S19 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S20 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_2 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S16, _S17, _S18, _S16, _S17, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S18, _S16, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S16, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S19, _S19, _S20, _S20, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_2.address_1, pnanovdb_grid_type_constants_2[grid_type_3].leaf_off_max_0);
}

fn pnanovdb_leaf_get_ave_address_0( grid_type_4 : u32,  buf_9 : u32,  node_3 : pnanovdb_leaf_handle_t_0) -> pnanovdb_address_t_0
{
    var _S21 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S22 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S23 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S24 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S25 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_3 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S21, _S22, _S23, _S21, _S22, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S23, _S21, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S21, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S24, _S24, _S25, _S25, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_3.address_1, pnanovdb_grid_type_constants_3[grid_type_4].leaf_off_ave_0);
}

fn pnanovdb_leaf_get_stddev_address_0( grid_type_5 : u32,  buf_10 : u32,  node_4 : pnanovdb_leaf_handle_t_0) -> pnanovdb_address_t_0
{
    var _S26 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S27 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S28 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S29 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S30 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_4 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S26, _S27, _S28, _S26, _S27, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S28, _S26, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S26, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S29, _S29, _S30, _S30, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_4.address_1, pnanovdb_grid_type_constants_4[grid_type_5].leaf_off_stddev_0);
}

fn stats0_0( threadIdx1D_0 : u32,  nodeIdx0_0 : u32,  channelIdx_0 : u32,  grid_type_6 : u32)
{
    var leaf_0 : pnanovdb_leaf_handle_t_0;
    leaf_0.address_1.byte_offset_0 = cacheIn_0[(((paramsIn_0.nanoVdb_0.list_leaf_offset_0.x) >> (u32(2)))) + u32(2) * nodeIdx0_0];
    var valueStat_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var valueCount_0 : u32 = u32(0);
    var _S31 : bool = grid_type_6 == u32(6);
    var _S32 : bool = threadIdx1D_0 < u32(8);
    var _S33 : bool = channelIdx_0 == u32(0);
    var _S34 : bool = grid_type_6 == u32(17);
    var _S35 : bool = channelIdx_0 == u32(2);
    var _S36 : bool = grid_type_6 == u32(12);
    var _S37 : bool = channelIdx_0 == u32(3);
    var _S38 : bool = channelIdx_0 == u32(4);
    var idx_0 : u32 = u32(0);
    for(;;)
    {
        if(idx_0 < u32(8))
        {
        }
        else
        {
            break;
        }
        var address_6 : pnanovdb_address_t_0 = pnanovdb_leaf_get_table_address_0(grid_type_6, u32(0), leaf_0, threadIdx1D_0 + u32(64) * idx_0);
        var value_4 : f32 = pnanovdb_read_float_0(u32(0), address_6);
        var value_5 : f32;
        var value_6 : f32;
        var value_7 : f32;
        if(_S31)
        {
            var value_y_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(address_6, u32(4)));
            var value_z_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(address_6, u32(8)));
            if(_S33)
            {
                value_5 = sqrt(value_4 * value_4 + value_y_0 * value_y_0 + value_z_0 * value_z_0);
            }
            else
            {
                value_5 = value_4;
            }
            if(_S35)
            {
                value_6 = value_y_0;
            }
            else
            {
                value_6 = value_5;
            }
            if(_S37)
            {
                value_7 = value_z_0;
            }
            else
            {
                value_7 = value_6;
            }
            value_5 = value_7;
        }
        else
        {
            if(_S34)
            {
                var value_y_1 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(address_6, u32(4)));
                var value_z_1 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(address_6, u32(8)));
                var value_w_0 : f32 = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_0(address_6, u32(12)));
                if(_S33)
                {
                    value_5 = sqrt(value_4 * value_4 + value_y_1 * value_y_1 + value_z_1 * value_z_1 + value_w_0 * value_w_0);
                }
                else
                {
                    value_5 = value_4;
                }
                if(_S35)
                {
                    value_6 = value_y_1;
                }
                else
                {
                    value_6 = value_5;
                }
                if(_S37)
                {
                    value_7 = value_z_1;
                }
                else
                {
                    value_7 = value_6;
                }
                var value_8 : f32;
                if(_S38)
                {
                    value_8 = value_w_0;
                }
                else
                {
                    value_8 = value_7;
                }
                value_5 = value_8;
            }
            else
            {
                if(_S36)
                {
                    var valueRaw_0 : u32 = pnanovdb_read_uint32_0(u32(0), address_6);
                    var value4_0 : vec4<f32> = vec4<f32>(f32((((valueRaw_0 >> (u32(0)))) & (u32(255)))) * 0.00392156885936856f, f32((((valueRaw_0 >> (u32(8)))) & (u32(255)))) * 0.00392156885936856f, f32((((valueRaw_0 >> (u32(16)))) & (u32(255)))) * 0.00392156885936856f, f32((((valueRaw_0 >> (u32(24)))) & (u32(255)))) * 0.00392156885936856f);
                    value_5 = sqrt(dot(value4_0, value4_0));
                }
                else
                {
                    value_5 = value_4;
                }
            }
        }
        stat_add_0(&(valueStat_0), &(valueCount_0), value_5);
        idx_0 = idx_0 + u32(1);
    }
    sdata0_0[threadIdx1D_0] = valueStat_0;
    sdata0u_0[threadIdx1D_0] = valueCount_0;
    workgroupBarrier();
    if(_S32)
    {
        var _S39 : u32 = threadIdx1D_0 + u32(8);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S39], sdata0u_0[_S39]);
        var _S40 : u32 = threadIdx1D_0 + u32(16);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S40], sdata0u_0[_S40]);
        var _S41 : u32 = threadIdx1D_0 + u32(24);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S41], sdata0u_0[_S41]);
        var _S42 : u32 = threadIdx1D_0 + u32(32);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S42], sdata0u_0[_S42]);
        var _S43 : u32 = threadIdx1D_0 + u32(40);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S43], sdata0u_0[_S43]);
        var _S44 : u32 = threadIdx1D_0 + u32(48);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S44], sdata0u_0[_S44]);
        var _S45 : u32 = threadIdx1D_0 + u32(56);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata0_0[_S45], sdata0u_0[_S45]);
        sdata1_0[threadIdx1D_0] = valueStat_0;
        sdata1u_0[threadIdx1D_0] = valueCount_0;
    }
    workgroupBarrier();
    if(threadIdx1D_0 == u32(0))
    {
        var _S46 : u32 = threadIdx1D_0 + u32(1);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S46], sdata1u_0[_S46]);
        var _S47 : u32 = threadIdx1D_0 + u32(2);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S47], sdata1u_0[_S47]);
        var _S48 : u32 = threadIdx1D_0 + u32(3);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S48], sdata1u_0[_S48]);
        var _S49 : u32 = threadIdx1D_0 + u32(4);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S49], sdata1u_0[_S49]);
        var _S50 : u32 = threadIdx1D_0 + u32(5);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S50], sdata1u_0[_S50]);
        var _S51 : u32 = threadIdx1D_0 + u32(6);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S51], sdata1u_0[_S51]);
        var _S52 : u32 = threadIdx1D_0 + u32(7);
        stat_merge_0(&(valueStat_0), &(valueCount_0), sdata1_0[_S52], sdata1u_0[_S52]);
        var valueStddev_0 : f32 = stat_stddev_0(valueStat_0, valueCount_0);
        var address_7 : pnanovdb_address_t_0 = pnanovdb_leaf_get_min_address_0(grid_type_6, u32(0), leaf_0);
        if(_S31)
        {
            if(channelIdx_0 == u32(1))
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(0)), valueStat_0.x);
            }
            if(_S35)
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(4)), valueStat_0.x);
            }
            if(_S37)
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(8)), valueStat_0.x);
            }
        }
        else
        {
            if(_S34)
            {
                if(channelIdx_0 == u32(1))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(0)), valueStat_0.x);
                }
                if(_S35)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(4)), valueStat_0.x);
                }
                if(_S37)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(8)), valueStat_0.x);
                }
                if(_S38)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_7, u32(12)), valueStat_0.x);
                }
            }
            else
            {
                if(_S36)
                {
                    pnanovdb_write_uint32_0(u32(0), address_7, u32(0));
                }
                else
                {
                    pnanovdb_write_float_0(u32(0), address_7, valueStat_0.x);
                }
            }
        }
        var address_8 : pnanovdb_address_t_0 = pnanovdb_leaf_get_max_address_0(grid_type_6, u32(0), leaf_0);
        if(_S31)
        {
            if(channelIdx_0 == u32(1))
            {
                pnanovdb_write_float_0(u32(0), address_8, valueStat_0.y);
            }
            if(_S35)
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_8, u32(4)), valueStat_0.y);
            }
            if(_S37)
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_8, u32(8)), valueStat_0.y);
            }
        }
        else
        {
            if(_S34)
            {
                if(channelIdx_0 == u32(1))
                {
                    pnanovdb_write_float_0(u32(0), address_8, valueStat_0.y);
                }
                if(_S35)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_8, u32(4)), valueStat_0.y);
                }
                if(_S37)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_8, u32(8)), valueStat_0.y);
                }
                if(_S38)
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_8, u32(12)), valueStat_0.y);
                }
            }
            else
            {
                if(_S36)
                {
                    var rawVal_0 : u32 = u32(max(0.0f, min(1.0f, valueStat_0.y) * 255.0f));
                    pnanovdb_write_uint32_0(u32(0), address_8, (((((rawVal_0 | (((rawVal_0 << (u32(8))))))) | (((rawVal_0 << (u32(16))))))) | (((rawVal_0 << (u32(24)))))));
                }
                else
                {
                    pnanovdb_write_float_0(u32(0), address_8, valueStat_0.y);
                }
            }
        }
        var address_9 : pnanovdb_address_t_0 = pnanovdb_leaf_get_ave_address_0(grid_type_6, u32(0), leaf_0);
        if(_S33)
        {
            pnanovdb_write_float_0(u32(0), address_9, valueStat_0.z);
        }
        var address_10 : pnanovdb_address_t_0 = pnanovdb_leaf_get_stddev_address_0(grid_type_6, u32(0), leaf_0);
        if(_S33)
        {
            pnanovdb_write_float_0(u32(0), address_10, valueStddev_0);
        }
    }
    return;
}

@compute
@workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx1D_1 : u32 = dispatchThreadID_0.x;
    var nodeIdx0_1 : u32 = groupID_0.y + paramsIn_0.blockIdxOffset0_0;
    var channelIdx_1 : u32 = groupID_0.z;
    if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(1))
    {
        stats0_0(threadIdx1D_1, nodeIdx0_1, channelIdx_1, u32(1));
    }
    else
    {
        if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(6))
        {
            stats0_0(threadIdx1D_1, nodeIdx0_1, channelIdx_1, u32(6));
        }
        else
        {
            if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(17))
            {
                stats0_0(threadIdx1D_1, nodeIdx0_1, channelIdx_1, u32(17));
            }
            else
            {
                if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(12))
                {
                    stats0_0(threadIdx1D_1, nodeIdx0_1, channelIdx_1, u32(12));
                }
            }
        }
    }
    return;
}

