// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseNanoVdbParams_std140_0
{
    @align(16) nanovdb_size_without_leaves_0 : vec2<u32>,
    @align(8) nanovdb_size_with_leaves_0 : vec2<u32>,
    @align(16) list_tile_offset_0 : vec2<u32>,
    @align(8) list_upper_offset_0 : vec2<u32>,
    @align(16) list_lower_offset_0 : vec2<u32>,
    @align(8) list_leaf_offset_0 : vec2<u32>,
    @align(16) cache_tile_offset_0 : vec2<u32>,
    @align(8) cache_upper_offset_0 : vec2<u32>,
    @align(16) cache_lower_offset_0 : vec2<u32>,
    @align(8) cache_leaf_offset_0 : vec2<u32>,
    @align(16) list_tile_count_0 : u32,
    @align(4) list_upper_count_0 : u32,
    @align(8) list_lower_count_0 : u32,
    @align(4) list_leaf_count_0 : u32,
    @align(16) cache_tile_count_0 : u32,
    @align(4) cache_upper_count_0 : u32,
    @align(8) cache_lower_count_0 : u32,
    @align(4) cache_leaf_count_0 : u32,
    @align(16) cache_size_0 : vec2<u32>,
    @align(8) grid_count_0 : u32,
    @align(4) grid_type_0 : u32,
    @align(16) subGridDimLessOne_0 : vec3<u32>,
    @align(4) pad3_0 : u32,
    @align(16) subGridDimBits_0 : vec3<u32>,
    @align(4) pad4_0 : u32,
};

struct SparseNanoVdbComputeStatsParams_std140_0
{
    @align(16) blockIdxOffset0_0 : u32,
    @align(4) blockIdxOffset1_0 : u32,
    @align(8) blockIdxOffset2_0 : u32,
    @align(4) blockIdxOffset3_0 : u32,
    @align(16) nanoVdb_0 : NvFlowSparseNanoVdbParams_std140_0,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : SparseNanoVdbComputeStatsParams_std140_0;
@binding(2) @group(0) var<storage, read_write> nanovdbInOut_0 : array<u32>;

@binding(1) @group(0) var<storage, read> cacheIn_0 : array<u32>;

struct pnanovdb_address_t_0
{
     byte_offset_0 : u32,
};

fn pnanovdb_address_t_x24init_0( byte_offset_1 : u32) -> pnanovdb_address_t_0
{
    var _S1 : pnanovdb_address_t_0;
    _S1.byte_offset_0 = byte_offset_1;
    return _S1;
}

fn pnanovdb_address_null_0() -> pnanovdb_address_t_0
{
    return pnanovdb_address_t_x24init_0(u32(0));
}

fn pnanovdb_address_offset_0( address_0 : pnanovdb_address_t_0,  byte_offset_2 : u32) -> pnanovdb_address_t_0
{
    var ret_0 : pnanovdb_address_t_0 = address_0;
    ret_0.byte_offset_0 = ret_0.byte_offset_0 + byte_offset_2;
    return ret_0;
}

struct pnanovdb_grid_handle_t_0
{
     address_1 : pnanovdb_address_t_0,
};

fn pnanovdb_grid_handle_t_x24init_0( address_2 : pnanovdb_address_t_0) -> pnanovdb_grid_handle_t_0
{
    var _S2 : pnanovdb_grid_handle_t_0;
    _S2.address_1 = address_2;
    return _S2;
}

struct pnanovdb_tree_handle_t_0
{
     address_3 : pnanovdb_address_t_0,
};

fn pnanovdb_tree_handle_t_x24init_0( address_4 : pnanovdb_address_t_0) -> pnanovdb_tree_handle_t_0
{
    var _S3 : pnanovdb_tree_handle_t_0;
    _S3.address_3 = address_4;
    return _S3;
}

fn pnanovdb_grid_get_tree_0( buf_0 : u32,  grid_0 : pnanovdb_grid_handle_t_0) -> pnanovdb_tree_handle_t_0
{
    var tree_0 : pnanovdb_tree_handle_t_0 = pnanovdb_tree_handle_t_x24init_0(grid_0.address_1);
    tree_0.address_3 = pnanovdb_address_offset_0(tree_0.address_3, u32(672));
    return tree_0;
}

struct pnanovdb_root_handle_t_0
{
     address_5 : pnanovdb_address_t_0,
};

fn pnanovdb_root_handle_t_x24init_0( address_6 : pnanovdb_address_t_0) -> pnanovdb_root_handle_t_0
{
    var _S4 : pnanovdb_root_handle_t_0;
    _S4.address_5 = address_6;
    return _S4;
}

fn pnanovdb_buf_read_uint32_0( buf_1 : u32,  byte_offset_3 : u32) -> u32
{
    return nanovdbInOut_0[(byte_offset_3 >> (u32(2)))];
}

fn pnanovdb_buf_read_uint64_0( buf_2 : u32,  byte_offset_4 : u32) -> vec2<u32>
{
    var ret_1 : vec2<u32>;
    ret_1[i32(0)] = pnanovdb_buf_read_uint32_0(buf_2, byte_offset_4);
    ret_1[i32(1)] = pnanovdb_buf_read_uint32_0(buf_2, byte_offset_4 + u32(4));
    return ret_1;
}

fn pnanovdb_read_uint64_0( buf_3 : u32,  address_7 : pnanovdb_address_t_0) -> vec2<u32>
{
    return pnanovdb_buf_read_uint64_0(buf_3, address_7.byte_offset_0);
}

fn pnanovdb_tree_get_node_offset_root_0( buf_4 : u32,  p_0 : pnanovdb_tree_handle_t_0) -> vec2<u32>
{
    return pnanovdb_read_uint64_0(buf_4, pnanovdb_address_offset_0(p_0.address_3, u32(24)));
}

fn pnanovdb_uint64_low_0( v_0 : vec2<u32>) -> u32
{
    return v_0.x;
}

fn pnanovdb_address_offset64_0( address_8 : pnanovdb_address_t_0,  byte_offset_5 : vec2<u32>) -> pnanovdb_address_t_0
{
    var ret_2 : pnanovdb_address_t_0 = address_8;
    ret_2.byte_offset_0 = ret_2.byte_offset_0 + pnanovdb_uint64_low_0(byte_offset_5);
    return ret_2;
}

fn pnanovdb_tree_get_root_0( buf_5 : u32,  tree_1 : pnanovdb_tree_handle_t_0) -> pnanovdb_root_handle_t_0
{
    var root_0 : pnanovdb_root_handle_t_0 = pnanovdb_root_handle_t_x24init_0(tree_1.address_3);
    root_0.address_5 = pnanovdb_address_offset64_0(root_0.address_5, pnanovdb_tree_get_node_offset_root_0(buf_5, tree_1));
    return root_0;
}

fn pnanovdb_read_uint32_0( buf_6 : u32,  address_9 : pnanovdb_address_t_0) -> u32
{
    return pnanovdb_buf_read_uint32_0(buf_6, address_9.byte_offset_0);
}

fn pnanovdb_root_get_tile_count_0( buf_7 : u32,  p_1 : pnanovdb_root_handle_t_0) -> u32
{
    return pnanovdb_read_uint32_0(buf_7, pnanovdb_address_offset_0(p_1.address_5, u32(24)));
}

struct pnanovdb_root_tile_handle_t_0
{
     address_10 : pnanovdb_address_t_0,
};

fn pnanovdb_root_tile_handle_t_x24init_0( address_11 : pnanovdb_address_t_0) -> pnanovdb_root_tile_handle_t_0
{
    var _S5 : pnanovdb_root_tile_handle_t_0;
    _S5.address_10 = address_11;
    return _S5;
}

struct pnanovdb_grid_type_constants_t_0
{
     root_off_background_0 : u32,
     root_off_min_0 : u32,
     root_off_max_0 : u32,
     root_off_ave_0 : u32,
     root_off_stddev_0 : u32,
     root_size_0 : u32,
     value_stride_bits_0 : u32,
     table_stride_0 : u32,
     root_tile_off_value_0 : u32,
     root_tile_size_0 : u32,
     upper_off_min_0 : u32,
     upper_off_max_0 : u32,
     upper_off_ave_0 : u32,
     upper_off_stddev_0 : u32,
     upper_off_table_0 : u32,
     upper_size_0 : u32,
     lower_off_min_0 : u32,
     lower_off_max_0 : u32,
     lower_off_ave_0 : u32,
     lower_off_stddev_0 : u32,
     lower_off_table_0 : u32,
     lower_size_0 : u32,
     leaf_off_min_0 : u32,
     leaf_off_max_0 : u32,
     leaf_off_ave_0 : u32,
     leaf_off_stddev_0 : u32,
     leaf_off_table_0 : u32,
     leaf_size_0 : u32,
};

fn pnanovdb_grid_type_constants_t_x24init_0( root_off_background_1 : u32,  root_off_min_1 : u32,  root_off_max_1 : u32,  root_off_ave_1 : u32,  root_off_stddev_1 : u32,  root_size_1 : u32,  value_stride_bits_1 : u32,  table_stride_1 : u32,  root_tile_off_value_1 : u32,  root_tile_size_1 : u32,  upper_off_min_1 : u32,  upper_off_max_1 : u32,  upper_off_ave_1 : u32,  upper_off_stddev_1 : u32,  upper_off_table_1 : u32,  upper_size_1 : u32,  lower_off_min_1 : u32,  lower_off_max_1 : u32,  lower_off_ave_1 : u32,  lower_off_stddev_1 : u32,  lower_off_table_1 : u32,  lower_size_1 : u32,  leaf_off_min_1 : u32,  leaf_off_max_1 : u32,  leaf_off_ave_1 : u32,  leaf_off_stddev_1 : u32,  leaf_off_table_1 : u32,  leaf_size_1 : u32) -> pnanovdb_grid_type_constants_t_0
{
    var _S6 : pnanovdb_grid_type_constants_t_0;
    _S6.root_off_background_0 = root_off_background_1;
    _S6.root_off_min_0 = root_off_min_1;
    _S6.root_off_max_0 = root_off_max_1;
    _S6.root_off_ave_0 = root_off_ave_1;
    _S6.root_off_stddev_0 = root_off_stddev_1;
    _S6.root_size_0 = root_size_1;
    _S6.value_stride_bits_0 = value_stride_bits_1;
    _S6.table_stride_0 = table_stride_1;
    _S6.root_tile_off_value_0 = root_tile_off_value_1;
    _S6.root_tile_size_0 = root_tile_size_1;
    _S6.upper_off_min_0 = upper_off_min_1;
    _S6.upper_off_max_0 = upper_off_max_1;
    _S6.upper_off_ave_0 = upper_off_ave_1;
    _S6.upper_off_stddev_0 = upper_off_stddev_1;
    _S6.upper_off_table_0 = upper_off_table_1;
    _S6.upper_size_0 = upper_size_1;
    _S6.lower_off_min_0 = lower_off_min_1;
    _S6.lower_off_max_0 = lower_off_max_1;
    _S6.lower_off_ave_0 = lower_off_ave_1;
    _S6.lower_off_stddev_0 = lower_off_stddev_1;
    _S6.lower_off_table_0 = lower_off_table_1;
    _S6.lower_size_0 = lower_size_1;
    _S6.leaf_off_min_0 = leaf_off_min_1;
    _S6.leaf_off_max_0 = leaf_off_max_1;
    _S6.leaf_off_ave_0 = leaf_off_ave_1;
    _S6.leaf_off_stddev_0 = leaf_off_stddev_1;
    _S6.leaf_off_table_0 = leaf_off_table_1;
    _S6.leaf_size_0 = leaf_size_1;
    return _S6;
}

fn pnanovdb_root_get_tile_zero_0( grid_type_1 : u32,  root_1 : pnanovdb_root_handle_t_0) -> pnanovdb_root_tile_handle_t_0
{
    var tile_0 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_tile_handle_t_x24init_0(root_1.address_5);
    var _S7 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S8 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S9 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S10 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S11 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_0 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S7, _S8, _S9, _S7, _S8, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S9, _S7, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S7, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S10, _S10, _S11, _S11, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    tile_0.address_10 = pnanovdb_address_offset_0(tile_0.address_10, pnanovdb_grid_type_constants_0[grid_type_1].root_size_0);
    return tile_0;
}

fn pnanovdb_uint64_as_int64_0( v_1 : vec2<u32>) -> vec2<i32>
{
    return vec2<i32>(v_1);
}

fn pnanovdb_read_int64_0( buf_8 : u32,  address_12 : pnanovdb_address_t_0) -> vec2<i32>
{
    return pnanovdb_uint64_as_int64_0(pnanovdb_read_uint64_0(buf_8, address_12));
}

fn pnanovdb_root_tile_get_child_0( buf_9 : u32,  p_2 : pnanovdb_root_tile_handle_t_0) -> vec2<i32>
{
    return pnanovdb_read_int64_0(buf_9, pnanovdb_address_offset_0(p_2.address_10, u32(8)));
}

fn pnanovdb_int64_is_zero_0( a_0 : vec2<i32>) -> bool
{
    var _S12 : bool;
    if((a_0.x) == i32(0))
    {
        _S12 = (a_0.y) == i32(0);
    }
    else
    {
        _S12 = false;
    }
    return _S12;
}

struct pnanovdb_upper_handle_t_0
{
     address_13 : pnanovdb_address_t_0,
};

fn pnanovdb_upper_handle_t_x24init_0( address_14 : pnanovdb_address_t_0) -> pnanovdb_upper_handle_t_0
{
    var _S13 : pnanovdb_upper_handle_t_0;
    _S13.address_13 = address_14;
    return _S13;
}

fn pnanovdb_int64_as_uint64_0( v_2 : vec2<i32>) -> vec2<u32>
{
    return vec2<u32>(v_2);
}

fn pnanovdb_root_get_child_0( grid_type_2 : u32,  buf_10 : u32,  root_2 : pnanovdb_root_handle_t_0,  tile_1 : pnanovdb_root_tile_handle_t_0) -> pnanovdb_upper_handle_t_0
{
    var upper_0 : pnanovdb_upper_handle_t_0 = pnanovdb_upper_handle_t_x24init_0(root_2.address_5);
    upper_0.address_13 = pnanovdb_address_offset64_0(upper_0.address_13, pnanovdb_int64_as_uint64_0(pnanovdb_root_tile_get_child_0(buf_10, tile_1)));
    return upper_0;
}

fn pnanovdb_upper_get_min_address_0( grid_type_3 : u32,  buf_11 : u32,  node_0 : pnanovdb_upper_handle_t_0) -> pnanovdb_address_t_0
{
    var _S14 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S15 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S16 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S17 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S18 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_1 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S14, _S15, _S16, _S14, _S15, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S16, _S14, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S14, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S17, _S17, _S18, _S18, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_0.address_13, pnanovdb_grid_type_constants_1[grid_type_3].upper_off_min_0);
}

fn pnanovdb_uint32_as_float_0( v_3 : u32) -> f32
{
    return (bitcast<f32>((v_3)));
}

fn pnanovdb_read_float_0( buf_12 : u32,  address_15 : pnanovdb_address_t_0) -> f32
{
    return pnanovdb_uint32_as_float_0(pnanovdb_read_uint32_0(buf_12, address_15));
}

fn pnanovdb_address_offset_product_0( address_16 : pnanovdb_address_t_0,  byte_offset_6 : u32,  multiplier_0 : u32) -> pnanovdb_address_t_0
{
    var ret_3 : pnanovdb_address_t_0 = address_16;
    ret_3.byte_offset_0 = ret_3.byte_offset_0 + byte_offset_6 * multiplier_0;
    return ret_3;
}

fn pnanovdb_upper_get_max_address_0( grid_type_4 : u32,  buf_13 : u32,  node_1 : pnanovdb_upper_handle_t_0) -> pnanovdb_address_t_0
{
    var _S19 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S20 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S21 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S22 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S23 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_2 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S19, _S20, _S21, _S19, _S20, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S21, _S19, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S19, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S22, _S22, _S23, _S23, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_1.address_13, pnanovdb_grid_type_constants_2[grid_type_4].upper_off_max_0);
}

fn pnanovdb_upper_get_ave_address_0( grid_type_5 : u32,  buf_14 : u32,  node_2 : pnanovdb_upper_handle_t_0) -> pnanovdb_address_t_0
{
    var _S24 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S25 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S26 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S27 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S28 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_3 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S24, _S25, _S26, _S24, _S25, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S26, _S24, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S24, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S27, _S27, _S28, _S28, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_2.address_13, pnanovdb_grid_type_constants_3[grid_type_5].upper_off_ave_0);
}

fn pnanovdb_upper_get_stddev_address_0( grid_type_6 : u32,  buf_15 : u32,  node_3 : pnanovdb_upper_handle_t_0) -> pnanovdb_address_t_0
{
    var _S29 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S30 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S31 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S32 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S33 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_4 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S29, _S30, _S31, _S29, _S30, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S31, _S29, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S29, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S32, _S32, _S33, _S33, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(node_3.address_13, pnanovdb_grid_type_constants_4[grid_type_6].upper_off_stddev_0);
}

fn stat_merge_0( stat_0 : ptr<function, vec4<f32>>,  count_0 : ptr<function, u32>,  other_0 : vec4<f32>,  otherCount_0 : u32)
{
    if(otherCount_0 > u32(0))
    {
        (*stat_0)[i32(0)] = min((*stat_0).x, other_0.x);
        (*stat_0)[i32(1)] = max((*stat_0).y, other_0.y);
        var delta_0 : f32 = other_0.z - (*stat_0).z;
        var _S34 : f32 = 1.0f / f32((*count_0) + otherCount_0) * delta_0;
        var _S35 : f32 = f32(otherCount_0);
        (*stat_0)[i32(2)] = (*stat_0).z + _S34 * _S35;
        (*stat_0)[i32(3)] = (*stat_0).w + other_0.w + _S34 * delta_0 * f32((*count_0)) * _S35;
        (*count_0) = (*count_0) + otherCount_0;
    }
    return;
}

fn stat_stddev_0( stat_1 : vec4<f32>,  count_1 : u32) -> f32
{
    var var_0 : f32;
    if(count_1 > u32(1))
    {
        var_0 = stat_1.w / f32(count_1);
    }
    else
    {
        var_0 = 0.0f;
    }
    return sqrt(var_0);
}

fn pnanovdb_root_get_min_address_0( grid_type_7 : u32,  buf_16 : u32,  root_3 : pnanovdb_root_handle_t_0) -> pnanovdb_address_t_0
{
    var _S36 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S37 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S38 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S39 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S40 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_5 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S36, _S37, _S38, _S36, _S37, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S38, _S36, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S36, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S39, _S39, _S40, _S40, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(root_3.address_5, pnanovdb_grid_type_constants_5[grid_type_7].root_off_min_0);
}

fn pnanovdb_float_as_uint32_0( v_4 : f32) -> u32
{
    return (bitcast<u32>((v_4)));
}

fn pnanovdb_buf_write_uint32_0( buf_17 : u32,  byte_offset_7 : u32,  value_0 : u32)
{
    nanovdbInOut_0[(byte_offset_7 >> (u32(2)))] = value_0;
    return;
}

fn pnanovdb_write_uint32_0( buf_18 : u32,  address_17 : pnanovdb_address_t_0,  value_1 : u32)
{
    pnanovdb_buf_write_uint32_0(buf_18, address_17.byte_offset_0, value_1);
    return;
}

fn pnanovdb_write_float_0( buf_19 : u32,  address_18 : pnanovdb_address_t_0,  value_2 : f32)
{
    pnanovdb_write_uint32_0(buf_19, address_18, pnanovdb_float_as_uint32_0(value_2));
    return;
}

fn pnanovdb_root_get_max_address_0( grid_type_8 : u32,  buf_20 : u32,  root_4 : pnanovdb_root_handle_t_0) -> pnanovdb_address_t_0
{
    var _S41 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S42 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S43 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S44 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S45 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_6 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S41, _S42, _S43, _S41, _S42, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S43, _S41, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S41, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S44, _S44, _S45, _S45, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(root_4.address_5, pnanovdb_grid_type_constants_6[grid_type_8].root_off_max_0);
}

fn pnanovdb_root_get_ave_address_0( grid_type_9 : u32,  buf_21 : u32,  root_5 : pnanovdb_root_handle_t_0) -> pnanovdb_address_t_0
{
    var _S46 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S47 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S48 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S49 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S50 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_7 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S46, _S47, _S48, _S46, _S47, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S48, _S46, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S46, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S49, _S49, _S50, _S50, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(root_5.address_5, pnanovdb_grid_type_constants_7[grid_type_9].root_off_ave_0);
}

fn pnanovdb_root_get_stddev_address_0( grid_type_10 : u32,  buf_22 : u32,  root_6 : pnanovdb_root_handle_t_0) -> pnanovdb_address_t_0
{
    var _S51 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
    var _S52 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
    var _S53 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
    var _S54 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
    var _S55 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
    var pnanovdb_grid_type_constants_8 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S51, _S52, _S53, _S51, _S52, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S53, _S51, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S51, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S54, _S54, _S55, _S55, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
    return pnanovdb_address_offset_0(root_6.address_5, pnanovdb_grid_type_constants_8[grid_type_10].root_off_stddev_0);
}

fn stats3_0( threadIdx1D_0 : u32,  gridIdx_0 : u32,  channelIdx_0 : u32,  grid_type_11 : u32)
{
    if(threadIdx1D_0 == u32(0))
    {
        var root_7 : pnanovdb_root_handle_t_0 = pnanovdb_tree_get_root_0(u32(0), pnanovdb_grid_get_tree_0(u32(0), pnanovdb_grid_handle_t_x24init_0(pnanovdb_address_offset_0(pnanovdb_address_null_0(), gridIdx_0 * u32(736)))));
        var valueStat_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
        var valueCount_0 : u32 = u32(0);
        var _S56 : u32 = pnanovdb_root_get_tile_count_0(u32(0), root_7);
        var tile_2 : pnanovdb_root_tile_handle_t_0 = pnanovdb_root_get_tile_zero_0(grid_type_11, root_7);
        var address_19 : pnanovdb_address_t_0 = pnanovdb_root_get_min_address_0(grid_type_11, u32(0), root_7);
        var _S57 : bool = grid_type_11 == u32(6);
        var _S58 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(32), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(84), u32(88), u32(92), u32(96), u32(2144));
        var _S59 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(64), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(104), u32(128), u32(4224));
        var _S60 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(30), u32(32), u32(36), u32(40), u32(64), u32(16), u32(8), u32(20), u32(32), u32(8224), u32(8226), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1058), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(82), u32(84), u32(88), u32(96), u32(1120));
        var _S61 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(96));
        var _S62 : pnanovdb_grid_type_constants_t_0 = pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(0), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(80), u32(160));
        var pnanovdb_grid_type_constants_9 : array<pnanovdb_grid_type_constants_t_0, i32(27)> = array<pnanovdb_grid_type_constants_t_0, i32(27)>( pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(28), u32(28), u32(28), u32(28), u32(32), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8224), u32(8224), u32(8224), u32(8224), u32(270368), u32(1056), u32(1056), u32(1056), u32(1056), u32(1056), u32(33824), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S58, _S59, _S60, _S58, _S59, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(40), u32(52), u32(64), u32(68), u32(96), u32(96), u32(16), u32(20), u32(32), u32(8224), u32(8236), u32(8248), u32(8252), u32(8256), u32(532544), u32(1056), u32(1068), u32(1080), u32(1084), u32(1088), u32(66624), u32(80), u32(92), u32(104), u32(108), u32(128), u32(6272)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(56), u32(80), u32(104), u32(112), u32(128), u32(192), u32(24), u32(24), u32(64), u32(8224), u32(8248), u32(8272), u32(8280), u32(8288), u32(794720), u32(1056), u32(1080), u32(1104), u32(1112), u32(1120), u32(99424), u32(80), u32(104), u32(128), u32(136), u32(160), u32(12448)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(96)), _S60, _S58, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(31), u32(32), u32(64), u32(1), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8226), u32(8227), u32(8256), u32(270400), u32(1056), u32(1057), u32(1058), u32(1059), u32(1088), u32(33856), u32(80), u32(80), u32(80), u32(80), u32(96), u32(160)), _S58, pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(352)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(608)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(32), u32(36), u32(40), u32(44), u32(64), u32(0), u32(8), u32(20), u32(32), u32(8224), u32(8228), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1060), u32(1064), u32(1068), u32(1088), u32(33856), u32(88), u32(90), u32(92), u32(94), u32(96), u32(96)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(44), u32(60), u32(76), u32(80), u32(96), u32(128), u32(16), u32(20), u32(64), u32(8224), u32(8240), u32(8256), u32(8260), u32(8288), u32(532576), u32(1056), u32(1072), u32(1088), u32(1092), u32(1120), u32(66656), u32(80), u32(96), u32(112), u32(116), u32(128), u32(8320)), pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(64), u32(96), u32(128), u32(136), u32(160), u32(256), u32(32), u32(24), u32(64), u32(8224), u32(8256), u32(8288), u32(8296), u32(8320), u32(1056896), u32(1056), u32(1088), u32(1120), u32(1128), u32(1152), u32(132224), u32(80), u32(112), u32(144), u32(152), u32(160), u32(16544)), _S61, _S61, _S62, _S62, pnanovdb_grid_type_constants_t_x24init_0(u32(32), u32(40), u32(48), u32(56), u32(64), u32(96), u32(16), u32(8), u32(24), u32(32), u32(8224), u32(8232), u32(8240), u32(8248), u32(8256), u32(270400), u32(1056), u32(1064), u32(1072), u32(1080), u32(1088), u32(33856), u32(80), u32(88), u32(96), u32(96), u32(96), u32(1120)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(31), u32(34), u32(40), u32(44), u32(64), u32(24), u32(8), u32(20), u32(32), u32(8224), u32(8227), u32(8232), u32(8236), u32(8256), u32(270400), u32(1056), u32(1059), u32(1064), u32(1068), u32(1088), u32(33856), u32(80), u32(83), u32(88), u32(92), u32(96), u32(1632)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(34), u32(40), u32(48), u32(52), u32(64), u32(48), u32(8), u32(20), u32(32), u32(8224), u32(8230), u32(8236), u32(8240), u32(8256), u32(270400), u32(1056), u32(1062), u32(1068), u32(1072), u32(1088), u32(33856), u32(80), u32(86), u32(92), u32(96), u32(128), u32(3200)), pnanovdb_grid_type_constants_t_x24init_0(u32(28), u32(29), u32(30), u32(32), u32(36), u32(64), u32(8), u32(8), u32(20), u32(32), u32(8224), u32(8225), u32(8228), u32(8232), u32(8256), u32(270400), u32(1056), u32(1057), u32(1060), u32(1064), u32(1088), u32(33856), u32(80), u32(81), u32(84), u32(88), u32(96), u32(608)) );
        var _S63 : bool = channelIdx_0 > u32(0);
        var _S64 : u32 = channelIdx_0 - u32(1);
        var i_0 : u32 = u32(0);
        for(;;)
        {
            if(i_0 < _S56)
            {
            }
            else
            {
                break;
            }
            if(!pnanovdb_int64_is_zero_0(pnanovdb_root_tile_get_child_0(u32(0), tile_2)))
            {
                var upper_1 : pnanovdb_upper_handle_t_0 = pnanovdb_root_get_child_0(grid_type_11, u32(0), root_7, tile_2);
                var address_20 : pnanovdb_address_t_0 = pnanovdb_upper_get_min_address_0(grid_type_11, u32(0), upper_1);
                var localStat_0 : vec4<f32>;
                localStat_0[i32(0)] = pnanovdb_read_float_0(u32(0), address_20);
                if(_S63)
                {
                    localStat_0[i32(0)] = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_product_0(address_20, _S64, u32(4)));
                }
                var address_21 : pnanovdb_address_t_0 = pnanovdb_upper_get_max_address_0(grid_type_11, u32(0), upper_1);
                localStat_0[i32(1)] = pnanovdb_read_float_0(u32(0), address_21);
                if(_S63)
                {
                    localStat_0[i32(1)] = pnanovdb_read_float_0(u32(0), pnanovdb_address_offset_product_0(address_21, _S64, u32(4)));
                }
                localStat_0[i32(2)] = pnanovdb_read_float_0(u32(0), pnanovdb_upper_get_ave_address_0(grid_type_11, u32(0), upper_1));
                localStat_0[i32(3)] = pnanovdb_read_float_0(u32(0), pnanovdb_upper_get_stddev_address_0(grid_type_11, u32(0), upper_1));
                stat_merge_0(&(valueStat_0), &(valueCount_0), localStat_0, u32(1));
            }
            tile_2.address_10 = pnanovdb_address_offset_0(tile_2.address_10, pnanovdb_grid_type_constants_9[grid_type_11].root_tile_size_0);
            i_0 = i_0 + u32(1);
        }
        var valueStddev_0 : f32 = stat_stddev_0(valueStat_0, valueCount_0);
        if(_S57)
        {
            if(channelIdx_0 == u32(1))
            {
                pnanovdb_write_float_0(u32(0), address_19, valueStat_0.x);
            }
            if(channelIdx_0 == u32(2))
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_19, u32(4)), valueStat_0.x);
            }
            if(channelIdx_0 == u32(3))
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_19, u32(8)), valueStat_0.x);
            }
        }
        else
        {
            if(grid_type_11 == u32(17))
            {
                if(channelIdx_0 == u32(1))
                {
                    pnanovdb_write_float_0(u32(0), address_19, valueStat_0.x);
                }
                if(channelIdx_0 == u32(2))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_19, u32(4)), valueStat_0.x);
                }
                if(channelIdx_0 == u32(3))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_19, u32(8)), valueStat_0.x);
                }
                if(channelIdx_0 == u32(4))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_19, u32(12)), valueStat_0.x);
                }
            }
            else
            {
                if(grid_type_11 == u32(12))
                {
                    var rawVal_0 : u32 = u32(max(0.0f, min(1.0f, valueStat_0.x) * 255.0f));
                    pnanovdb_write_uint32_0(u32(0), address_19, (((((rawVal_0 | (((rawVal_0 << (u32(8))))))) | (((rawVal_0 << (u32(16))))))) | (((rawVal_0 << (u32(24)))))));
                }
                else
                {
                    pnanovdb_write_float_0(u32(0), address_19, valueStat_0.x);
                }
            }
        }
        var address_22 : pnanovdb_address_t_0 = pnanovdb_root_get_max_address_0(grid_type_11, u32(0), root_7);
        if(_S57)
        {
            if(channelIdx_0 == u32(1))
            {
                pnanovdb_write_float_0(u32(0), address_22, valueStat_0.y);
            }
            if(channelIdx_0 == u32(2))
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_22, u32(4)), valueStat_0.y);
            }
            if(channelIdx_0 == u32(3))
            {
                pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_22, u32(8)), valueStat_0.y);
            }
        }
        else
        {
            if(grid_type_11 == u32(17))
            {
                if(channelIdx_0 == u32(1))
                {
                    pnanovdb_write_float_0(u32(0), address_22, valueStat_0.y);
                }
                if(channelIdx_0 == u32(2))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_22, u32(4)), valueStat_0.y);
                }
                if(channelIdx_0 == u32(3))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_22, u32(8)), valueStat_0.y);
                }
                if(channelIdx_0 == u32(4))
                {
                    pnanovdb_write_float_0(u32(0), pnanovdb_address_offset_0(address_22, u32(12)), valueStat_0.y);
                }
            }
            else
            {
                if(grid_type_11 == u32(12))
                {
                    var rawVal_1 : u32 = u32(max(0.0f, min(1.0f, valueStat_0.y) * 255.0f));
                    pnanovdb_write_uint32_0(u32(0), address_22, (((((rawVal_1 | (((rawVal_1 << (u32(8))))))) | (((rawVal_1 << (u32(16))))))) | (((rawVal_1 << (u32(24)))))));
                }
                else
                {
                    pnanovdb_write_float_0(u32(0), address_22, valueStat_0.y);
                }
            }
        }
        var address_23 : pnanovdb_address_t_0 = pnanovdb_root_get_ave_address_0(grid_type_11, u32(0), root_7);
        var _S65 : bool = channelIdx_0 == u32(0);
        if(_S65)
        {
            pnanovdb_write_float_0(u32(0), address_23, valueStat_0.z);
        }
        var address_24 : pnanovdb_address_t_0 = pnanovdb_root_get_stddev_address_0(grid_type_11, u32(0), root_7);
        if(_S65)
        {
            pnanovdb_write_float_0(u32(0), address_24, valueStddev_0);
        }
    }
    return;
}

@compute
@workgroup_size(32, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx1D_1 : u32 = dispatchThreadID_0.x;
    var gridIdx_1 : u32 = groupID_0.y + paramsIn_0.blockIdxOffset3_0;
    var channelIdx_1 : u32 = groupID_0.z;
    if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(1))
    {
        stats3_0(threadIdx1D_1, gridIdx_1, channelIdx_1, u32(1));
    }
    else
    {
        if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(6))
        {
            stats3_0(threadIdx1D_1, gridIdx_1, channelIdx_1, u32(6));
        }
        else
        {
            if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(17))
            {
                stats3_0(threadIdx1D_1, gridIdx_1, channelIdx_1, u32(17));
            }
            else
            {
                if((paramsIn_0.nanoVdb_0.grid_type_0) == u32(12))
                {
                    stats3_0(threadIdx1D_1, gridIdx_1, channelIdx_1, u32(12));
                }
            }
        }
    }
    return;
}

