// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct SparseRescaleGlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) tableParams_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableParamsOld_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : SparseRescaleGlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

struct SparseRescaleLayerParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) shouldClear_0 : u32,
    @align(16) blockSizeWorldOld_0 : vec3<f32>,
    @align(4) pad2_1 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<SparseRescaleLayerParams_std430_0>;

@binding(5) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(4) @group(0) var valueSampler_0 : sampler;

@binding(3) @group(0) var<storage, read> gTableOld_0 : array<u32>;

@binding(6) @group(0) var valueOut_0 : texture_storage_3d<r32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_1.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_1.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_1.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_1.blockDimBits_0.y))))) & (i32(tableParams_1.blockDimLessOne_0.z))));
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_2 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_2.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_2.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_2.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S10 < (_S9.numLocations_0))
    {
        layerParamIdx_0 = gTable_0[_S10 + _S9.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowBlockIdxToLocation_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : u32,  _S13 : ptr<function, vec4<i32>>) -> bool
{
    var _S14 : bool = _S12 < (_S11.numLocations_0);
    if(_S14)
    {
        var locationIdx_0 : u32 = ((_S12 << (u32(2)))) + _S11.locationOffset_0;
        (*_S13)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S13)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S13)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S13)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S13)[i32(0)] = i32(1073741824);
        (*_S13)[i32(1)] = i32(1073741824);
        (*_S13)[i32(2)] = i32(1073741824);
        (*_S13)[i32(3)] = i32(1073741824);
    }
    return _S14;
}

fn NvFlowRealToVirtual_0( _S15 : NvFlowSparseLevelParams_0,  _S16 : u32,  _S17 : vec3<i32>,  _S18 : ptr<function, vec4<i32>>) -> bool
{
    var location_0 : vec4<i32>;
    var _S19 : bool = NvFlowBlockIdxToLocation_0(_S15, _S16, &(location_0));
    (*_S18) = vec4<i32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(_S15.blockDimBits_0))))) + _S17, location_0.w);
    return _S19;
}

fn NvFlowLocationToBlockIdx_0( _S20 : NvFlowSparseLevelParams_0,  _S21 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S21.xyz) & ((_S20.tableDimLessOne_0)));
    var _S22 : u32 = ((((((((bucketIdx_0.z) << ((_S20.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S20.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S23 : u32 = gTableOld_0[_S22 + u32(1)];
    var _S24 : i32 = _S21.x;
    var _S25 : i32 = _S21.y;
    var _S26 : i32 = _S21.z;
    var _S27 : i32 = _S21.w;
    var blockIdx_1 : u32 = gTableOld_0[_S22];
    for(;;)
    {
        if(blockIdx_1 < _S23)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S20.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTableOld_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTableOld_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTableOld_0[compareLocationIdx_0 + u32(3)]);
        var _S28 : bool;
        if(i32(gTableOld_0[compareLocationIdx_0]) == _S24)
        {
            _S28 = compareLocation_y_0 == _S25;
        }
        else
        {
            _S28 = false;
        }
        var _S29 : bool;
        if(_S28)
        {
            _S29 = compareLocation_z_0 == _S26;
        }
        else
        {
            _S29 = false;
        }
        var _S30 : bool;
        if(_S29)
        {
            _S30 = compareLocation_w_0 == _S27;
        }
        else
        {
            _S30 = false;
        }
        if(_S30)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToReal_0( _S31 : NvFlowSparseLevelParams_0,  _S32 : vec4<i32>) -> vec4<i32>
{
    var _S33 : vec3<i32> = _S32.xyz;
    var _S34 : u32 = NvFlowLocationToBlockIdx_0(_S31, vec4<i32>((_S33 >> (vec3<u32>(vec3<i32>(_S31.blockDimBits_0)))), _S32.w));
    var tableValue_0 : u32;
    if(_S34 != u32(4294967295))
    {
        tableValue_0 = gTableOld_0[_S34 + _S31.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S33 & (vec3<i32>(_S31.blockDimLessOne_0))), tableValue_0);
}

fn NvFlowGlobalReadLinear1f_0( _S35 : texture_3d<f32>,  _S36 : sampler,  _S37 : NvFlowSparseLevelParams_0,  _S38 : vec3<f32>,  _S39 : i32) -> f32
{
    var vidx_0 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0(_S38), _S39);
    var _S40 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S37, vidx_0);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S40.xyz) + _S38 - vec3<f32>(vidx_0.xyz);
    var _S41 : f32;
    if(bool(_S40.w))
    {
        _S41 = (textureSampleLevel((_S35), (_S36), (readIdxf_0 * _S37.dimInv_0), (0.0f)).x);
    }
    else
    {
        _S41 = 0.0f;
    }
    return _S41;
}

fn NvFlowLocalWriteNeighbor1f_0( _S42 : NvFlowSparseLevelParams_0,  _S43 : i32,  _S44 : i32,  _S45 : i32,  _S46 : u32,  _S47 : vec3<i32>,  _S48 : f32)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S47, gTable_0[NvFlowNeighborToIdx_0(_S46, _S43, _S44, _S45) + _S42.blockLevelOffsetLocal_0], _S43, _S44, _S45);
    var _S49 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S50 : f32;
    if(bool(index_0.w))
    {
        _S50 = _S48;
    }
    else
    {
        _S50 = 0.0f;
    }
    textureStore((valueOut_0), (_S49), vec4<f32>((_S50), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S51 : NvFlowSparseLevelParams_0,  _S52 : u32,  _S53 : vec3<i32>,  _S54 : f32)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S51, _S53);
    NvFlowLocalWriteNeighbor1f_0(_S51, i32(0), i32(0), i32(0), _S52, _S53, _S54);
    var _S55 : i32 = neighbor_1.x;
    var _S56 : bool = _S55 != i32(0);
    if(_S56)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, _S55, i32(0), i32(0), _S52, _S53, _S54);
    }
    var _S57 : i32 = neighbor_1.y;
    var _S58 : bool = _S57 != i32(0);
    if(_S58)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, i32(0), _S57, i32(0), _S52, _S53, _S54);
    }
    var _S59 : i32 = neighbor_1.z;
    var _S60 : bool = _S59 != i32(0);
    if(_S60)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, i32(0), i32(0), _S59, _S52, _S53, _S54);
    }
    var _S61 : bool;
    if(_S56)
    {
        _S61 = _S58;
    }
    else
    {
        _S61 = false;
    }
    if(_S61)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, _S55, _S57, i32(0), _S52, _S53, _S54);
    }
    if(_S58)
    {
        _S61 = _S60;
    }
    else
    {
        _S61 = false;
    }
    if(_S61)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, i32(0), _S57, _S59, _S52, _S53, _S54);
    }
    if(_S56)
    {
        _S61 = _S60;
    }
    else
    {
        _S61 = false;
    }
    if(_S61)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, _S55, i32(0), _S59, _S52, _S53, _S54);
    }
    if(_S56)
    {
        _S61 = _S58;
    }
    else
    {
        _S61 = false;
    }
    if(_S61)
    {
        _S61 = _S60;
    }
    else
    {
        _S61 = false;
    }
    if(_S61)
    {
        NvFlowLocalWriteNeighbor1f_0(_S51, _S55, _S57, _S59, _S52, _S53, _S54);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.tableParams_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S62 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_2);
    var vidx_1 : vec4<i32>;
    var _S63 : bool = NvFlowRealToVirtual_0(unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_2, threadIdx_3, &(vidx_1));
    var oldVidxf_0 : vec3<f32> = (vec3<f32>(vidx_1.xyz) + vec3<f32>(0.5f, 0.5f, 0.5f)).xyz * layerParamsIn_0[_S62].blockSizeWorld_0 / layerParamsIn_0[_S62].blockSizeWorldOld_0;
    var copyValue_0 : f32;
    if(bool(layerParamsIn_0[_S62].shouldClear_0))
    {
        copyValue_0 = 0.0f;
    }
    else
    {
        copyValue_0 = NvFlowGlobalReadLinear1f_0(valueIn_0, valueSampler_0, unpackStorage_0(globalParamsIn_0.tableParamsOld_0), oldVidxf_0, vidx_1.w);
    }
    NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_2, threadIdx_3, copyValue_0);
    return;
}

