// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct SparseRescaleGlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) tableParams_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableParamsOld_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : SparseRescaleGlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

struct SparseRescaleLayerParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) shouldClear_0 : u32,
    @align(16) blockSizeWorldOld_0 : vec3<f32>,
    @align(4) pad2_1 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<SparseRescaleLayerParams_std430_0>;

@binding(3) @group(0) var valueOut_0 : texture_storage_3d<r32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_1.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_1.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_1.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_1.blockDimBits_0.y))))) & (i32(tableParams_1.blockDimLessOne_0.z))));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_2 : NvFlowSparseLevelParams_0,  threadIdx_0 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S5 : i32 = threadIdx_0.x;
    if(_S5 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S5 == i32(tableParams_2.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S6 : i32 = threadIdx_0.y;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S6 == i32(tableParams_2.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S7 : i32 = threadIdx_0.z;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S7 == i32(tableParams_2.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_1 : vec3<i32>,  v_0 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_0 : vec4<i32> = vec4<i32>(((threadIdx_1.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_1.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_1.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_0) >> (u32(31)));
    ridx_0[i32(0)] = ridx_0[i32(0)] + ((mask_0 & (x_1)));
    ridx_0[i32(1)] = ridx_0[i32(1)] + ((mask_0 & (y_1)));
    ridx_0[i32(2)] = ridx_0[i32(2)] + ((mask_0 & (z_1)));
    return ridx_0;
}

fn NvFlowGetLayerParamIdx_0( _S8 : NvFlowSparseLevelParams_0,  _S9 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S9 < (_S8.numLocations_0))
    {
        layerParamIdx_0 = gTable_0[_S9 + _S8.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowLocalWriteNeighbor1f_0( _S10 : NvFlowSparseLevelParams_0,  _S11 : i32,  _S12 : i32,  _S13 : i32,  _S14 : u32,  _S15 : vec3<i32>,  _S16 : f32)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S15, gTable_0[NvFlowNeighborToIdx_0(_S14, _S11, _S12, _S13) + _S10.blockLevelOffsetLocal_0], _S11, _S12, _S13);
    var _S17 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S18 : f32;
    if(bool(index_0.w))
    {
        _S18 = _S16;
    }
    else
    {
        _S18 = 0.0f;
    }
    textureStore((valueOut_0), (_S17), vec4<f32>((_S18), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S19 : NvFlowSparseLevelParams_0,  _S20 : u32,  _S21 : vec3<i32>,  _S22 : f32)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S19, _S21);
    NvFlowLocalWriteNeighbor1f_0(_S19, i32(0), i32(0), i32(0), _S20, _S21, _S22);
    var _S23 : i32 = neighbor_1.x;
    var _S24 : bool = _S23 != i32(0);
    if(_S24)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, _S23, i32(0), i32(0), _S20, _S21, _S22);
    }
    var _S25 : i32 = neighbor_1.y;
    var _S26 : bool = _S25 != i32(0);
    if(_S26)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, i32(0), _S25, i32(0), _S20, _S21, _S22);
    }
    var _S27 : i32 = neighbor_1.z;
    var _S28 : bool = _S27 != i32(0);
    if(_S28)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, i32(0), i32(0), _S27, _S20, _S21, _S22);
    }
    var _S29 : bool;
    if(_S24)
    {
        _S29 = _S26;
    }
    else
    {
        _S29 = false;
    }
    if(_S29)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, _S23, _S25, i32(0), _S20, _S21, _S22);
    }
    if(_S26)
    {
        _S29 = _S28;
    }
    else
    {
        _S29 = false;
    }
    if(_S29)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, i32(0), _S25, _S27, _S20, _S21, _S22);
    }
    if(_S24)
    {
        _S29 = _S28;
    }
    else
    {
        _S29 = false;
    }
    if(_S29)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, _S23, i32(0), _S27, _S20, _S21, _S22);
    }
    if(_S24)
    {
        _S29 = _S26;
    }
    else
    {
        _S29 = false;
    }
    if(_S29)
    {
        _S29 = _S28;
    }
    else
    {
        _S29 = false;
    }
    if(_S29)
    {
        NvFlowLocalWriteNeighbor1f_0(_S19, _S23, _S25, _S27, _S20, _S21, _S22);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_2 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.tableParams_0), dispatchThreadID_0.x);
    var blockIdx_1 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    if(bool(layerParamsIn_0[NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_1)].shouldClear_0))
    {
        NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.tableParams_0), blockIdx_1, threadIdx_2, 0.0f);
    }
    return;
}

