// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct SummaryCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) locationOffset_1 : u32,
    @align(8) layerCount_0 : u32,
    @align(4) anyNeighborAllocation_0 : u32,
    @align(16) anyEnabled_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> gParams_0 : SummaryCS_GlobalParams_std140_0;
@binding(5) @group(0) var<storage, read_write> summaryOut_0 : array<u32>;

struct SummaryCS_LayerParams_std430_0
{
    @align(16) smokeThreshold_0 : f32,
    @align(4) speedThresholdMinSmoke_0 : f32,
    @align(8) speedThreshold_0 : f32,
    @align(4) enableNeighborAllocation_0 : u32,
    @align(16) forceClear_0 : u32,
    @align(4) layerAndLevel_0 : u32,
    @align(8) enabled_0 : u32,
    @align(4) pad3_1 : u32,
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) pad4_0 : u32,
};

@binding(1) @group(0) var<storage, read> gLayerParams_0 : array<SummaryCS_LayerParams_std430_0>;

@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var densityCoarseIn_0 : texture_3d<f32>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S3 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S3, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S3 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

var<workgroup> sdata0_0 : array<vec4<f32>, i32(256)>;

var<workgroup> sdata1_0 : array<vec4<f32>, i32(256)>;

fn reduceMax4_0( threadIdx_1 : u32,  val_0 : vec4<f32>) -> vec4<f32>
{
    sdata0_0[threadIdx_1] = val_0;
    workgroupBarrier();
    var _S6 : vec4<f32>;
    if(threadIdx_1 < u32(64))
    {
        var _S7 : vec4<f32> = max(max(max(val_0, sdata0_0[threadIdx_1 + u32(64)]), sdata0_0[threadIdx_1 + u32(128)]), sdata0_0[threadIdx_1 + u32(192)]);
        sdata1_0[threadIdx_1] = _S7;
        _S6 = _S7;
    }
    else
    {
        _S6 = val_0;
    }
    workgroupBarrier();
    if(threadIdx_1 < u32(16))
    {
        var _S8 : vec4<f32> = max(max(max(_S6, sdata1_0[threadIdx_1 + u32(16)]), sdata1_0[threadIdx_1 + u32(32)]), sdata1_0[threadIdx_1 + u32(48)]);
        sdata0_0[threadIdx_1] = _S8;
        _S6 = _S8;
    }
    else
    {
    }
    workgroupBarrier();
    if(threadIdx_1 < u32(4))
    {
        var _S9 : vec4<f32> = max(max(max(_S6, sdata0_0[threadIdx_1 + u32(4)]), sdata0_0[threadIdx_1 + u32(8)]), sdata0_0[threadIdx_1 + u32(12)]);
        sdata1_0[threadIdx_1] = _S9;
        _S6 = _S9;
    }
    else
    {
    }
    workgroupBarrier();
    if(threadIdx_1 < u32(1))
    {
        sdata0_0[threadIdx_1] = max(max(max(_S6, sdata1_0[threadIdx_1 + u32(1)]), sdata1_0[threadIdx_1 + u32(2)]), sdata1_0[threadIdx_1 + u32(3)]);
    }
    workgroupBarrier();
    return sdata0_0[i32(0)];
}

fn NvFlowGetLayerParamIdx_0( _S10 : NvFlowSparseLevelParams_0,  _S11 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S11 < (_S10.numLocations_0))
    {
        layerParamIdx_0 = gTable_0[_S11 + _S10.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowSingleVirtualToReal_0( _S12 : NvFlowSparseLevelParams_0,  _S13 : u32,  _S14 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S14, gTable_0[NvFlowSingleToIdx_0(_S13) + _S12.blockLevelOffsetLocal_0]);
}

fn NvFlowBlockIdxToLocation_0( _S15 : NvFlowSparseLevelParams_0,  _S16 : u32,  _S17 : ptr<function, vec4<i32>>) -> bool
{
    var _S18 : bool = _S16 < (_S15.numLocations_0);
    if(_S18)
    {
        var locationIdx_0 : u32 = ((_S16 << (u32(2)))) + _S15.locationOffset_0;
        (*_S17)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S17)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S17)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S17)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S17)[i32(0)] = i32(1073741824);
        (*_S17)[i32(1)] = i32(1073741824);
        (*_S17)[i32(2)] = i32(1073741824);
        (*_S17)[i32(3)] = i32(1073741824);
    }
    return _S18;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var blockIdx_1 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var sthreadIdx_0 : u32 = dispatchThreadID_0.x;
    var writeVal_0 : u32;
    var mask_0 : u32;
    if(blockIdx_1 == u32(0))
    {
        if(sthreadIdx_0 < u32(4))
        {
            if(sthreadIdx_0 == u32(0))
            {
                writeVal_0 = gParams_0.layerCount_0;
            }
            else
            {
                writeVal_0 = u32(0);
            }
            if(sthreadIdx_0 == u32(1))
            {
                if((gParams_0.anyEnabled_0) != u32(0))
                {
                    writeVal_0 = gParams_0.table_0.numLocations_0;
                }
                else
                {
                    writeVal_0 = u32(0);
                }
            }
            else
            {
            }
            if(sthreadIdx_0 == u32(2))
            {
                writeVal_0 = gParams_0.table_0.maxLocations_0;
            }
            else
            {
            }
            if(sthreadIdx_0 == u32(3))
            {
                writeVal_0 = gParams_0.anyNeighborAllocation_0;
            }
            else
            {
            }
            summaryOut_0[sthreadIdx_0] = writeVal_0;
        }
        var _S19 : u32 = u32(4) * gParams_0.layerCount_0;
        writeVal_0 = sthreadIdx_0;
        for(;;)
        {
            var _S20 : bool = writeVal_0 < _S19;
            if(_S20)
            {
            }
            else
            {
                break;
            }
            if(_S20)
            {
                var layerParamIdx_1 : u32 = (writeVal_0 >> (u32(2)));
                var subIdx_0 : u32 = (writeVal_0 & (u32(3)));
                if(subIdx_0 == u32(0))
                {
                    mask_0 = (bitcast<u32>((gLayerParams_0[layerParamIdx_1].blockSizeWorld_0.x)));
                }
                else
                {
                    mask_0 = u32(0);
                }
                var writeVal_1 : u32;
                if(subIdx_0 == u32(1))
                {
                    writeVal_1 = (bitcast<u32>((gLayerParams_0[layerParamIdx_1].blockSizeWorld_0.y)));
                }
                else
                {
                    writeVal_1 = mask_0;
                }
                var writeVal_2 : u32;
                if(subIdx_0 == u32(2))
                {
                    writeVal_2 = (bitcast<u32>((gLayerParams_0[layerParamIdx_1].blockSizeWorld_0.z)));
                }
                else
                {
                    writeVal_2 = writeVal_1;
                }
                var writeVal_3 : u32;
                if(subIdx_0 == u32(3))
                {
                    writeVal_3 = gLayerParams_0[layerParamIdx_1].layerAndLevel_0;
                }
                else
                {
                    writeVal_3 = writeVal_2;
                }
                summaryOut_0[u32(4) + writeVal_0] = writeVal_3;
            }
            writeVal_0 = writeVal_0 + u32(256);
        }
    }
    var _S21 : bool;
    if((gParams_0.anyEnabled_0) != u32(0))
    {
        _S21 = blockIdx_1 < (gParams_0.table_0.numLocations_0);
    }
    else
    {
        _S21 = false;
    }
    if(_S21)
    {
        var _S22 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(gParams_0.table_0), blockIdx_1);
        if((gLayerParams_0[_S22].enabled_0) != u32(0))
        {
            var _S23 : vec3<i32> = NvFlowSingleVirtualToReal_0(unpackStorage_0(gParams_0.table_0), blockIdx_1, vec3<i32>(i32(0), i32(0), i32(0))).xyz;
            var maxSpeedSmoke_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
            var _S24 : u32 = (u32(1) << ((gParams_0.table_0.blockDimBits_0.x + gParams_0.table_0.blockDimBits_0.y + gParams_0.table_0.blockDimBits_0.z)));
            var _S25 : u32 = (((u32(1) << ((gParams_0.table_0.blockDimBits_0.x)))) >> (u32(1)));
            var _S26 : bool = sthreadIdx_0 < u32(1);
            writeVal_0 = sthreadIdx_0;
            for(;;)
            {
                if(writeVal_0 < _S24)
                {
                }
                else
                {
                    break;
                }
                var threadIdx_2 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(gParams_0.table_0), writeVal_0);
                var _S27 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S23 + threadIdx_2), u32(0)));
                var speed_0 : f32 = length((textureLoad((velocityIn_0), ((_S27)).xyz, ((_S27)).w)).xyz);
                var smoke_0 : f32 = (textureLoad((densityCoarseIn_0), ((_S27)).xyz, ((_S27)).w)).w;
                if(u32(threadIdx_2.x) < _S25)
                {
                    maxSpeedSmoke_0[i32(0)] = max(maxSpeedSmoke_0.x, speed_0);
                    maxSpeedSmoke_0[i32(1)] = max(maxSpeedSmoke_0.y, smoke_0);
                }
                else
                {
                    maxSpeedSmoke_0[i32(2)] = max(maxSpeedSmoke_0.z, speed_0);
                    maxSpeedSmoke_0[i32(3)] = max(maxSpeedSmoke_0.w, smoke_0);
                }
                writeVal_0 = writeVal_0 + u32(256);
            }
            var _S28 : vec4<f32> = reduceMax4_0(sthreadIdx_0, maxSpeedSmoke_0);
            maxSpeedSmoke_0 = _S28;
            if(_S26)
            {
                var maxSpeedNeg_0 : f32 = maxSpeedSmoke_0.x;
                var maxSmokeNeg_0 : f32 = maxSpeedSmoke_0.y;
                var maxSpeedPos_0 : f32 = maxSpeedSmoke_0.z;
                var maxSmokePos_0 : f32 = maxSpeedSmoke_0.w;
                if((gLayerParams_0[_S22].forceClear_0) == u32(0))
                {
                    if(maxSmokeNeg_0 > (gLayerParams_0[_S22].smokeThreshold_0))
                    {
                        _S21 = true;
                    }
                    else
                    {
                        if(maxSmokeNeg_0 > (gLayerParams_0[_S22].speedThresholdMinSmoke_0))
                        {
                            _S21 = maxSpeedNeg_0 > (gLayerParams_0[_S22].speedThreshold_0);
                        }
                        else
                        {
                            _S21 = false;
                        }
                    }
                    if(_S21)
                    {
                        mask_0 = u32(1);
                    }
                    else
                    {
                        mask_0 = u32(0);
                    }
                    if(maxSmokePos_0 > (gLayerParams_0[_S22].smokeThreshold_0))
                    {
                        _S21 = true;
                    }
                    else
                    {
                        if(maxSmokePos_0 > (gLayerParams_0[_S22].speedThresholdMinSmoke_0))
                        {
                            _S21 = maxSpeedPos_0 > (gLayerParams_0[_S22].speedThreshold_0);
                        }
                        else
                        {
                            _S21 = false;
                        }
                    }
                    if(_S21)
                    {
                        mask_0 = (mask_0 | (u32(2)));
                    }
                    else
                    {
                    }
                    if((gLayerParams_0[_S22].enableNeighborAllocation_0) != u32(0))
                    {
                        if(((mask_0 & (u32(3)))) != u32(0))
                        {
                            mask_0 = (mask_0 | (u32(240)));
                        }
                        else
                        {
                        }
                        if(((mask_0 & (u32(1)))) != u32(0))
                        {
                            mask_0 = (mask_0 | (u32(4)));
                        }
                        else
                        {
                        }
                        if(((mask_0 & (u32(2)))) != u32(0))
                        {
                            mask_0 = (mask_0 | (u32(8)));
                        }
                        else
                        {
                        }
                    }
                    else
                    {
                    }
                }
                else
                {
                    mask_0 = u32(0);
                }
                summaryOut_0[gParams_0.locationOffset_1 + u32(5) * blockIdx_1 + u32(4)] = mask_0;
            }
        }
        else
        {
            if(sthreadIdx_0 < u32(1))
            {
                summaryOut_0[gParams_0.locationOffset_1 + u32(5) * blockIdx_1 + u32(4)] = u32(0);
            }
        }
        if(sthreadIdx_0 < u32(4))
        {
            var location_0 : vec4<i32>;
            var _S29 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_0(gParams_0.table_0), blockIdx_1, &(location_0));
            if(sthreadIdx_0 == u32(0))
            {
                writeVal_0 = u32(location_0.x);
            }
            else
            {
                writeVal_0 = u32(0);
            }
            if(sthreadIdx_0 == u32(1))
            {
                writeVal_0 = u32(location_0.y);
            }
            else
            {
            }
            if(sthreadIdx_0 == u32(2))
            {
                writeVal_0 = u32(location_0.z);
            }
            else
            {
            }
            if(sthreadIdx_0 == u32(3))
            {
                writeVal_0 = u32(location_0.w);
            }
            else
            {
            }
            summaryOut_0[gParams_0.locationOffset_1 + u32(5) * blockIdx_1 + sthreadIdx_0] = writeVal_0;
        }
    }
    return;
}

