// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct VorticityCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : VorticityCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(4) @group(0) var curlIn_0 : texture_3d<f32>;

struct VorticityCS_LayerParams_std430_0
{
    @align(4) forceScale_0 : f32,
    @align(4) velocityLogScale_0 : f32,
    @align(4) velocityLogMask_0 : f32,
    @align(4) velocityLinearMask_0 : f32,
    @align(4) constantMask_0 : f32,
    @align(4) densityMask_0 : f32,
    @align(4) pad2_1 : f32,
    @align(4) pad3_1 : f32,
    @align(4) temperatureMask_0 : f32,
    @align(4) fuelMask_0 : f32,
    @align(4) burnMask_0 : f32,
    @align(4) smokeMask_0 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<VorticityCS_LayerParams_std430_0>;

@binding(5) @group(0) var lowpassIn_0 : texture_3d<f32>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(6) @group(0) var coarseDensityIn_0 : texture_3d<f32>;

@binding(7) @group(0) var velocityOut_0 : texture_storage_3d<rgba32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn crossProduct_0( a_0 : vec3<f32>,  b_0 : vec3<f32>) -> vec3<f32>
{
    var _S6 : f32 = a_0.y;
    var _S7 : f32 = b_0.z;
    var _S8 : f32 = a_0.z;
    var _S9 : f32 = b_0.y;
    var _S10 : f32 = b_0.x;
    var _S11 : f32 = a_0.x;
    return vec3<f32>(_S6 * _S7 - _S8 * _S9, _S8 * _S10 - _S11 * _S7, _S11 * _S9 - _S6 * _S10);
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S12 : i32 = threadIdx_1.x;
    if(_S12 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S12 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S13 : i32 = threadIdx_1.y;
    if(_S13 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S13 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S14 : i32 = threadIdx_1.z;
    if(_S14 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S14 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_1 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_1) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S15 : NvFlowSparseLevelParams_0,  _S16 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S16 < (_S15.numLocations_0))
    {
        layerParamIdx_0 = tableIn_0[_S16 + _S15.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowSingleVirtualToReal_0( _S17 : NvFlowSparseLevelParams_0,  _S18 : u32,  _S19 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S19, tableIn_0[NvFlowSingleToIdx_0(_S18) + _S17.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalWriteNeighbor4f_0( _S20 : NvFlowSparseLevelParams_0,  _S21 : i32,  _S22 : i32,  _S23 : i32,  _S24 : u32,  _S25 : vec3<i32>,  _S26 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S25, tableIn_0[NvFlowNeighborToIdx_0(_S24, _S21, _S22, _S23) + _S20.blockLevelOffsetLocal_0], _S21, _S22, _S23);
    var _S27 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S28 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S28 = _S26;
    }
    else
    {
        _S28 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((velocityOut_0), (_S27), (_S28));
    return;
}

fn NvFlowLocalWrite4f_0( _S29 : NvFlowSparseLevelParams_0,  _S30 : u32,  _S31 : vec3<i32>,  _S32 : vec4<f32>)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S29, _S31);
    NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), i32(0), i32(0), _S30, _S31, _S32);
    var _S33 : i32 = neighbor_1.x;
    var _S34 : bool = _S33 != i32(0);
    if(_S34)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, i32(0), i32(0), _S30, _S31, _S32);
    }
    var _S35 : i32 = neighbor_1.y;
    var _S36 : bool = _S35 != i32(0);
    if(_S36)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), _S35, i32(0), _S30, _S31, _S32);
    }
    var _S37 : i32 = neighbor_1.z;
    var _S38 : bool = _S37 != i32(0);
    if(_S38)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), i32(0), _S37, _S30, _S31, _S32);
    }
    var _S39 : bool;
    if(_S34)
    {
        _S39 = _S36;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, _S35, i32(0), _S30, _S31, _S32);
    }
    if(_S36)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), _S35, _S37, _S30, _S31, _S32);
    }
    if(_S34)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, i32(0), _S37, _S30, _S31, _S32);
    }
    if(_S34)
    {
        _S39 = _S36;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, _S35, _S37, _S30, _S31, _S32);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S40 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_2);
    var readIdx_0 : vec3<i32> = NvFlowSingleVirtualToReal_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_2, threadIdx_3).xyz;
    var n_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var _S41 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(-1), i32(0), i32(0))), u32(0)));
    var _S42 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(1), i32(0), i32(0))), u32(0)));
    n_0[i32(0)] = n_0[i32(0)] - (textureLoad((curlIn_0), ((_S41)).xyz, ((_S41)).w)).w + (textureLoad((curlIn_0), ((_S42)).xyz, ((_S42)).w)).w;
    var _S43 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(-1), i32(0))), u32(0)));
    var _S44 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(1), i32(0))), u32(0)));
    n_0[i32(1)] = n_0[i32(1)] - (textureLoad((curlIn_0), ((_S43)).xyz, ((_S43)).w)).w + (textureLoad((curlIn_0), ((_S44)).xyz, ((_S44)).w)).w;
    var _S45 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(0), i32(-1))), u32(0)));
    var _S46 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0 + vec3<i32>(i32(0), i32(0), i32(1))), u32(0)));
    n_0[i32(2)] = n_0[i32(2)] - (textureLoad((curlIn_0), ((_S45)).xyz, ((_S45)).w)).w + (textureLoad((curlIn_0), ((_S46)).xyz, ((_S46)).w)).w;
    n_0[i32(3)] = sqrt(n_0.x * n_0.x + n_0.y * n_0.y + n_0.z * n_0.z);
    if((n_0.w) > 0.0f)
    {
        n_0[i32(0)] = n_0[i32(0)] / n_0.w;
        n_0[i32(1)] = n_0[i32(1)] / n_0.w;
        n_0[i32(2)] = n_0[i32(2)] / n_0.w;
    }
    var _S47 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(readIdx_0), u32(0)));
    var impulse_0 : vec3<f32> = crossProduct_0(n_0.xyz, (textureLoad((curlIn_0), ((_S47)).xyz, ((_S47)).w)).xyz);
    var _S48 : f32 = layerParamsIn_0[_S40].forceScale_0;
    var _S49 : bool;
    if((layerParamsIn_0[_S40].velocityLogMask_0) != 0.0f)
    {
        _S49 = true;
    }
    else
    {
        _S49 = (layerParamsIn_0[_S40].velocityLinearMask_0) != 0.0f;
    }
    var speedLog_0 : f32;
    var speed_0 : f32;
    if(_S49)
    {
        var _S50 : vec4<f32> = ((textureLoad((lowpassIn_0), ((_S47)).xyz, ((_S47)).w)) + (textureLoad((lowpassIn_0), ((_S41)).xyz, ((_S41)).w)) + (textureLoad((lowpassIn_0), ((_S42)).xyz, ((_S42)).w)) + (textureLoad((lowpassIn_0), ((_S43)).xyz, ((_S43)).w)) + (textureLoad((lowpassIn_0), ((_S44)).xyz, ((_S44)).w)) + (textureLoad((lowpassIn_0), ((_S45)).xyz, ((_S45)).w)) + (textureLoad((lowpassIn_0), ((_S46)).xyz, ((_S46)).w))) * vec4<f32>(0.1428571492433548f);
        var velocityLowpass_0 : vec4<f32> = _S50;
        velocityLowpass_0[i32(3)] = length(_S50.xyz);
        var speed_1 : f32 = velocityLowpass_0.w;
        if(speed_1 > 0.0f)
        {
            speedLog_0 = log2(layerParamsIn_0[_S40].velocityLogScale_0 * speed_1 + 1.0f);
        }
        else
        {
            speedLog_0 = speed_1;
        }
        speed_0 = speed_1;
    }
    else
    {
        speedLog_0 = 0.0f;
        speed_0 = 0.0f;
    }
    var _S51 : vec4<f32> = (textureLoad((velocityIn_0), ((_S47)).xyz, ((_S47)).w));
    var velocity_0 : vec4<f32> = _S51;
    var _S52 : vec4<f32> = (textureLoad((coarseDensityIn_0), ((_S47)).xyz, ((_S47)).w));
    var _S53 : vec3<f32> = _S51.xyz + vec3<f32>((_S48 * max(0.0f, layerParamsIn_0[_S40].velocityLogMask_0 * speedLog_0 + layerParamsIn_0[_S40].velocityLinearMask_0 * speed_0 + layerParamsIn_0[_S40].densityMask_0 * _S51.w + layerParamsIn_0[_S40].constantMask_0 + layerParamsIn_0[_S40].temperatureMask_0 * _S52.x + layerParamsIn_0[_S40].fuelMask_0 * _S52.y + layerParamsIn_0[_S40].burnMask_0 * _S52.z + layerParamsIn_0[_S40].smokeMask_0 * _S52.w))) * impulse_0;
    velocity_0.x = _S53.x;
    velocity_0.y = _S53.y;
    velocity_0.z = _S53.z;
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_2, threadIdx_3, velocity_0);
    return;
}

