// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct CopyFP32toFP16CS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) threadCount_0 : u32,
    @align(8) dstOffset_0 : u32,
    @align(4) elementCount_0 : u32,
    @align(16) srcOffset_0 : u32,
    @align(4) pad1_0 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : CopyFP32toFP16CS_Params_std140_0;
@binding(2) @group(0) var<storage, read_write> dstOut_0 : array<u32>;

@binding(1) @group(0) var<storage, read> srcIn_0 : array<f32>;

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var tidx_0 : u32 = dispatchThreadID_0.x + (((paramsIn_0.blockIdxOffset_0) << (u32(7))));
    if(tidx_0 < (paramsIn_0.threadCount_0))
    {
        var _S1 : u32 = tidx_0 + (((paramsIn_0.dstOffset_0) >> (u32(1))));
        var idx0_0 : u32 = u32(2) * _S1;
        var idx1_0 : u32 = idx0_0 + u32(1);
        var inBounds0_0 : bool;
        if(idx0_0 >= (paramsIn_0.dstOffset_0))
        {
            inBounds0_0 = idx0_0 < (paramsIn_0.dstOffset_0 + paramsIn_0.elementCount_0);
        }
        else
        {
            inBounds0_0 = false;
        }
        var inBounds1_0 : bool;
        if(idx1_0 >= (paramsIn_0.dstOffset_0))
        {
            inBounds1_0 = idx1_0 < (paramsIn_0.dstOffset_0 + paramsIn_0.elementCount_0);
        }
        else
        {
            inBounds1_0 = false;
        }
        var _S2 : bool;
        if(!inBounds0_0)
        {
            _S2 = true;
        }
        else
        {
            _S2 = !inBounds1_0;
        }
        var val_0 : u32;
        if(_S2)
        {
            val_0 = dstOut_0[_S1];
        }
        else
        {
            val_0 = u32(0);
        }
        if(inBounds0_0)
        {
            val_0 = ((((pack2x16float(vec2f((srcIn_0[paramsIn_0.srcOffset_0 + idx0_0 - paramsIn_0.dstOffset_0]),0.0))) & (u32(65535)))) | (((val_0 & (u32(4294901760))))));
        }
        else
        {
        }
        if(inBounds1_0)
        {
            val_0 = ((((pack2x16float(vec2f((srcIn_0[paramsIn_0.srcOffset_0 + idx1_0 - paramsIn_0.dstOffset_0]),0.0))) << (u32(16)))) | (((val_0 & (u32(65535))))));
        }
        else
        {
        }
        dstOut_0[_S1] = val_0;
    }
    return;
}

