// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct DebugVolumeCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) velocityTable_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : DebugVolumeCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(3) @group(0) var densityShadowIn_0 : texture_3d<f32>;

@binding(4) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(5) @group(0) var samplerIn_0 : sampler;

struct DebugVolumeCS_LayerParams_std430_0
{
    @align(16) velocityScale_0 : vec3<f32>,
    @align(4) enableDivergenceAsSmoke_0 : u32,
    @align(16) enabled_0 : u32,
    @align(4) enableSpeedAsTemperature_0 : u32,
    @align(8) enableVelocityAsDensity_0 : u32,
    @align(4) outputScaleBySmoke_0 : u32,
    @align(16) outputTemperatureScale_0 : f32,
    @align(4) outputFuelScale_0 : f32,
    @align(8) outputBurnScale_0 : f32,
    @align(4) outputSmokeScale_0 : f32,
    @align(16) outputTemperatureOffset_0 : f32,
    @align(4) outputFuelOffset_0 : f32,
    @align(8) outputBurnOffset_0 : f32,
    @align(4) outputSmokeOffset_0 : f32,
    @align(16) slicePlane_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) slicePlaneThickness_0 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<DebugVolumeCS_LayerParams_std430_0>;

@binding(6) @group(0) var densityShadowOut_0 : texture_storage_3d<rgba32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowFloor_i_0( v_1 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_1));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S10 < (_S9.numLocations_0))
    {
        layerParamIdx_0 = tableIn_0[_S10 + _S9.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowLocalVirtualToReal_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : u32,  _S13 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S13 >> (vec3<u32>(vec3<i32>(_S11.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S13, tableIn_0[NvFlowNeighborToIdx_0(_S12, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S11.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S14 : texture_3d<f32>,  _S15 : NvFlowSparseLevelParams_0,  _S16 : u32,  _S17 : vec3<i32>) -> vec4<f32>
{
    var _S18 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S15, _S16, _S17);
    var _S19 : vec4<f32>;
    if(bool(_S18.w))
    {
        var _S20 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S18.xyz), u32(0)));
        _S19 = (textureLoad((_S14), ((_S20)).xyz, ((_S20)).w));
    }
    else
    {
        _S19 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S19;
}

fn NvFlowLocalReadLinear4f_0( _S21 : texture_3d<f32>,  _S22 : sampler,  _S23 : NvFlowSparseLevelParams_0,  _S24 : u32,  _S25 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S25);
    var _S26 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S23, _S24, threadIdx_3);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S26.xyz) + _S25 - vec3<f32>(threadIdx_3);
    var _S27 : vec4<f32>;
    if(bool(_S26.w))
    {
        _S27 = (textureSampleLevel((_S21), (_S22), (readIdxf_0 * _S23.dimInv_0), (0.0f)));
    }
    else
    {
        _S27 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S27;
}

fn NvFlowBlockIdxToLocation_0( _S28 : NvFlowSparseLevelParams_0,  _S29 : u32,  _S30 : ptr<function, vec4<i32>>) -> bool
{
    var _S31 : bool = _S29 < (_S28.numLocations_0);
    if(_S31)
    {
        var locationIdx_0 : u32 = ((_S29 << (u32(2)))) + _S28.locationOffset_0;
        (*_S30)[i32(0)] = i32(tableIn_0[locationIdx_0]);
        (*_S30)[i32(1)] = i32(tableIn_0[locationIdx_0 + u32(1)]);
        (*_S30)[i32(2)] = i32(tableIn_0[locationIdx_0 + u32(2)]);
        (*_S30)[i32(3)] = i32(tableIn_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S30)[i32(0)] = i32(1073741824);
        (*_S30)[i32(1)] = i32(1073741824);
        (*_S30)[i32(2)] = i32(1073741824);
        (*_S30)[i32(3)] = i32(1073741824);
    }
    return _S31;
}

fn NvFlowLocalWriteNeighbor4f_0( _S32 : NvFlowSparseLevelParams_0,  _S33 : i32,  _S34 : i32,  _S35 : i32,  _S36 : u32,  _S37 : vec3<i32>,  _S38 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S37, tableIn_0[NvFlowNeighborToIdx_0(_S36, _S33, _S34, _S35) + _S32.blockLevelOffsetLocal_0], _S33, _S34, _S35);
    var _S39 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S40 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S40 = _S38;
    }
    else
    {
        _S40 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((densityShadowOut_0), (_S39), (_S40));
    return;
}

fn NvFlowLocalWrite4f_0( _S41 : NvFlowSparseLevelParams_0,  _S42 : u32,  _S43 : vec3<i32>,  _S44 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S41, _S43);
    NvFlowLocalWriteNeighbor4f_0(_S41, i32(0), i32(0), i32(0), _S42, _S43, _S44);
    var _S45 : i32 = neighbor_2.x;
    var _S46 : bool = _S45 != i32(0);
    if(_S46)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, _S45, i32(0), i32(0), _S42, _S43, _S44);
    }
    var _S47 : i32 = neighbor_2.y;
    var _S48 : bool = _S47 != i32(0);
    if(_S48)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, i32(0), _S47, i32(0), _S42, _S43, _S44);
    }
    var _S49 : i32 = neighbor_2.z;
    var _S50 : bool = _S49 != i32(0);
    if(_S50)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, i32(0), i32(0), _S49, _S42, _S43, _S44);
    }
    var _S51 : bool;
    if(_S46)
    {
        _S51 = _S48;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, _S45, _S47, i32(0), _S42, _S43, _S44);
    }
    if(_S48)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, i32(0), _S47, _S49, _S42, _S43, _S44);
    }
    if(_S46)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, _S45, i32(0), _S49, _S42, _S43, _S44);
    }
    if(_S46)
    {
        _S51 = _S48;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor4f_0(_S41, _S45, _S47, _S49, _S42, _S43, _S44);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_4 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), dispatchThreadID_0.x);
    var blockIdx_1 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S52 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1);
    var density4_0 : vec4<f32> = NvFlowLocalRead4f_0(densityShadowIn_0, unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_4);
    var _S53 : vec3<f32> = vec3<f32>(0.5f);
    var _S54 : vec4<f32> = NvFlowLocalReadLinear4f_0(velocityIn_0, samplerIn_0, unpackStorage_0(globalParamsIn_0.velocityTable_0), blockIdx_1, _S53 * (vec3<f32>(threadIdx_4) + _S53));
    if((layerParamsIn_0[_S52].enabled_0) != u32(0))
    {
        if((layerParamsIn_0[_S52].enableSpeedAsTemperature_0) != u32(0))
        {
            density4_0[i32(0)] = length(_S54.xyz * layerParamsIn_0[_S52].velocityScale_0);
        }
        if((layerParamsIn_0[_S52].enableVelocityAsDensity_0) != u32(0))
        {
            var _S55 : vec3<f32> = abs(_S54.xyz * layerParamsIn_0[_S52].velocityScale_0);
            density4_0.x = _S55.x;
            density4_0.y = _S55.y;
            density4_0.z = _S55.z;
        }
        if((layerParamsIn_0[_S52].enableDivergenceAsSmoke_0) != u32(0))
        {
            density4_0[i32(3)] = _S54.w;
        }
        density4_0[i32(0)] = layerParamsIn_0[_S52].outputTemperatureScale_0 * density4_0.x + layerParamsIn_0[_S52].outputTemperatureOffset_0;
        density4_0[i32(1)] = layerParamsIn_0[_S52].outputFuelScale_0 * density4_0.y + layerParamsIn_0[_S52].outputFuelOffset_0;
        density4_0[i32(2)] = layerParamsIn_0[_S52].outputBurnScale_0 * density4_0.z + layerParamsIn_0[_S52].outputBurnOffset_0;
        density4_0[i32(3)] = layerParamsIn_0[_S52].outputSmokeScale_0 * density4_0.w + layerParamsIn_0[_S52].outputSmokeOffset_0;
        if((layerParamsIn_0[_S52].outputScaleBySmoke_0) != u32(0))
        {
            var _S56 : vec3<f32> = density4_0.xyz * vec3<f32>(density4_0.w);
            density4_0.x = _S56.x;
            density4_0.y = _S56.y;
            density4_0.z = _S56.z;
        }
        if((layerParamsIn_0[_S52].slicePlaneThickness_0) != 0.0f)
        {
            var location_0 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
            var _S57 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, &(location_0));
            if(_S57)
            {
                var isInside_0 : bool = (abs(dot(vec4<f32>((vec3<f32>((((location_0.xyz) << ((globalParamsIn_0.table_0.blockDimBits_0)))) + threadIdx_4) + vec3<f32>(0.5f, 0.5f, 0.5f)) * layerParamsIn_0[_S52].vidxToWorld_0, 1.0f), layerParamsIn_0[_S52].slicePlane_0))) > (abs(0.5f * layerParamsIn_0[_S52].slicePlaneThickness_0));
                var _S58 : bool;
                if((layerParamsIn_0[_S52].slicePlaneThickness_0) > 0.0f)
                {
                    _S58 = isInside_0;
                }
                else
                {
                    _S58 = false;
                }
                if(_S58)
                {
                    density4_0[i32(3)] = 0.0f;
                }
                if((layerParamsIn_0[_S52].slicePlaneThickness_0) < 0.0f)
                {
                    _S58 = !isInside_0;
                }
                else
                {
                    _S58 = false;
                }
                if(_S58)
                {
                    density4_0[i32(3)] = 0.0f;
                }
            }
        }
    }
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_4, density4_0);
    return;
}

