// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct EllipsoidRasterCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) totalParticleCount_0 : u32,
    @align(8) pad1_1 : u32,
    @align(4) pad2_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : EllipsoidRasterCS_GlobalParams_std140_0;
@binding(5) @group(0) var<storage, read> blockIdxIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(6) @group(0) var<storage, read> rangeIn_0 : array<vec2<u32>>;

struct EllipsoidRasterCS_LayerParams_std430_0
{
    @align(16) particleCount_0 : u32,
    @align(4) layerAndLevel_0 : i32,
    @align(8) density_0 : f32,
    @align(4) pad1_2 : f32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) rasterRadiusScale_0 : f32,
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) sdfMode_0 : u32,
    @align(16) cellSizeWorld_0 : vec3<f32>,
    @align(4) pad3_0 : f32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_anisotropyE1s_0 : vec2<u32>,
    @align(16) range_anisotropyE2s_0 : vec2<u32>,
    @align(8) range_anisotropyE3s_0 : vec2<u32>,
    @align(16) range_positionFloat3s_0 : vec2<u32>,
    @align(8) pad4_0 : f32,
    @align(4) pad5_0 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<EllipsoidRasterCS_LayerParams_std430_0>;

@binding(7) @group(0) var<storage, read> instanceIdIn_0 : array<u32>;

@binding(4) @group(0) var<storage, read> arrayValuesIn4_0 : array<vec4<f32>>;

@binding(3) @group(0) var<storage, read> arrayValuesIn1_0 : array<f32>;

@binding(8) @group(0) var valueOut_0 : texture_storage_3d<r32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn computeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32((threadIdx1D_0 >> (u32(8))));
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return ((vec3<i32>((_S3 & (i32(((tableParams_0.blockDimLessOne_0.x) >> (u32(3)))))), (((_S3 >> (u32(i32(_S4 - u32(3)))))) & (i32(((tableParams_0.blockDimLessOne_0.y) >> (u32(3)))))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y - u32(6)))))) & (i32(((tableParams_0.blockDimLessOne_0.z) >> (u32(2))))))) << (vec3<u32>(vec3<i32>(i32(3), i32(3), i32(2)))))) + vec3<i32>(i32((threadIdx1D_0 & (u32(7)))), i32((((threadIdx1D_0 >> (u32(3)))) & (u32(7)))), i32((((threadIdx1D_0 >> (u32(6)))) & (u32(3)))));
}

struct EllipsoidRasterCS_LayerParams_0
{
     particleCount_0 : u32,
     layerAndLevel_0 : i32,
     density_0 : f32,
     pad1_2 : f32,
     vidxToWorld_0 : vec3<f32>,
     rasterRadiusScale_0 : f32,
     blockSizeWorld_0 : vec3<f32>,
     sdfMode_0 : u32,
     cellSizeWorld_0 : vec3<f32>,
     pad3_0 : f32,
     range_positions_0 : vec2<u32>,
     range_anisotropyE1s_0 : vec2<u32>,
     range_anisotropyE2s_0 : vec2<u32>,
     range_anisotropyE3s_0 : vec2<u32>,
     range_positionFloat3s_0 : vec2<u32>,
     pad4_0 : f32,
     pad5_0 : f32,
};

fn unpackStorage_1( _S5 : EllipsoidRasterCS_LayerParams_std430_0) -> EllipsoidRasterCS_LayerParams_0
{
    var _S6 : EllipsoidRasterCS_LayerParams_0 = EllipsoidRasterCS_LayerParams_0( _S5.particleCount_0, _S5.layerAndLevel_0, _S5.density_0, _S5.pad1_2, _S5.vidxToWorld_0, _S5.rasterRadiusScale_0, _S5.blockSizeWorld_0, _S5.sdfMode_0, _S5.cellSizeWorld_0, _S5.pad3_0, _S5.range_positions_0, _S5.range_anisotropyE1s_0, _S5.range_anisotropyE2s_0, _S5.range_anisotropyE3s_0, _S5.range_positionFloat3s_0, _S5.pad4_0, _S5.pad5_0 );
    return _S6;
}

fn readPosition_0( layerParams_0 : EllipsoidRasterCS_LayerParams_0,  particleIdx_0 : u32) -> vec4<f32>
{
    var ret_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var _S7 : u32 = layerParams_0.range_positions_0.y;
    if(particleIdx_0 < _S7)
    {
        ret_0 = arrayValuesIn4_0[particleIdx_0 + layerParams_0.range_positions_0.x];
    }
    else
    {
        if(particleIdx_0 < (_S7 + layerParams_0.range_positionFloat3s_0.y))
        {
            var _S8 : u32 = u32(3) * (particleIdx_0 - _S7) + layerParams_0.range_positionFloat3s_0.x;
            ret_0[i32(0)] = arrayValuesIn1_0[_S8];
            ret_0[i32(1)] = arrayValuesIn1_0[_S8 + u32(1)];
            ret_0[i32(2)] = arrayValuesIn1_0[_S8 + u32(2)];
            ret_0[i32(3)] = 1.0f;
        }
    }
    return ret_0;
}

fn readAnisotropyE1_0( layerParams_1 : EllipsoidRasterCS_LayerParams_0,  particleIdx_1 : u32) -> vec4<f32>
{
    var _S9 : vec4<f32>;
    if(particleIdx_1 < (layerParams_1.range_anisotropyE1s_0.y))
    {
        _S9 = arrayValuesIn4_0[particleIdx_1 + layerParams_1.range_anisotropyE1s_0.x];
    }
    else
    {
        _S9 = vec4<f32>(1.0f, 0.0f, 0.0f, 1.0f);
    }
    return _S9;
}

fn readAnisotropyE2_0( layerParams_2 : EllipsoidRasterCS_LayerParams_0,  particleIdx_2 : u32) -> vec4<f32>
{
    var _S10 : vec4<f32>;
    if(particleIdx_2 < (layerParams_2.range_anisotropyE2s_0.y))
    {
        _S10 = arrayValuesIn4_0[particleIdx_2 + layerParams_2.range_anisotropyE2s_0.x];
    }
    else
    {
        _S10 = vec4<f32>(0.0f, 1.0f, 0.0f, 1.0f);
    }
    return _S10;
}

fn readAnisotropyE3_0( layerParams_3 : EllipsoidRasterCS_LayerParams_0,  particleIdx_3 : u32) -> vec4<f32>
{
    var _S11 : vec4<f32>;
    if(particleIdx_3 < (layerParams_3.range_anisotropyE3s_0.y))
    {
        _S11 = arrayValuesIn4_0[particleIdx_3 + layerParams_3.range_anisotropyE3s_0.x];
    }
    else
    {
        _S11 = vec4<f32>(0.0f, 0.0f, 1.0f, 1.0f);
    }
    return _S11;
}

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

var<workgroup> stotalCount_0 : u32;

fn blockScan_0( threadIdx_0 : u32,  val_0 : u32) -> u32
{
    sdata0_0[threadIdx_0] = val_0;
    workgroupBarrier();
    var localVal_0 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_0 = val_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_0 = val_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(2)];
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(3)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(4)];
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(8)];
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(12)];
    }
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(16)];
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(32)];
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(48)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(64)];
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(128)];
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(192)];
    }
    if(threadIdx_0 == u32(0))
    {
        stotalCount_0 = sdata1_0[i32(63)] + sdata1_0[i32(127)] + sdata1_0[i32(191)] + sdata1_0[i32(255)];
    }
    return localVal_0;
}

var<workgroup> sparticleIdx_0 : array<u32, i32(256)>;

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S12 : i32 = threadIdx_1.x;
    if(_S12 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S12 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S13 : i32 = threadIdx_1.y;
    if(_S13 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S13 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S14 : i32 = threadIdx_1.z;
    if(_S14 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S14 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_0 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_0 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_0) >> (u32(31)));
    ridx_0[i32(0)] = ridx_0[i32(0)] + ((mask_0 & (x_1)));
    ridx_0[i32(1)] = ridx_0[i32(1)] + ((mask_0 & (y_1)));
    ridx_0[i32(2)] = ridx_0[i32(2)] + ((mask_0 & (z_1)));
    return ridx_0;
}

fn NvFlowBlockIdxToLocation_0( _S15 : NvFlowSparseLevelParams_0,  _S16 : u32,  _S17 : ptr<function, vec4<i32>>) -> bool
{
    var _S18 : bool = _S16 < (_S15.numLocations_0);
    if(_S18)
    {
        var locationIdx_0 : u32 = ((_S16 << (u32(2)))) + _S15.locationOffset_0;
        (*_S17)[i32(0)] = i32(tableIn_0[locationIdx_0]);
        (*_S17)[i32(1)] = i32(tableIn_0[locationIdx_0 + u32(1)]);
        (*_S17)[i32(2)] = i32(tableIn_0[locationIdx_0 + u32(2)]);
        (*_S17)[i32(3)] = i32(tableIn_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S17)[i32(0)] = i32(1073741824);
        (*_S17)[i32(1)] = i32(1073741824);
        (*_S17)[i32(2)] = i32(1073741824);
        (*_S17)[i32(3)] = i32(1073741824);
    }
    return _S18;
}

fn NvFlowGetLayerParamIdx_0( _S19 : NvFlowSparseLevelParams_0,  _S20 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S20 < (_S19.numLocations_0))
    {
        layerParamIdx_0 = tableIn_0[_S20 + _S19.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowLocalWriteNeighbor1f_0( _S21 : NvFlowSparseLevelParams_0,  _S22 : i32,  _S23 : i32,  _S24 : i32,  _S25 : u32,  _S26 : vec3<i32>,  _S27 : f32)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S26, tableIn_0[NvFlowNeighborToIdx_0(_S25, _S22, _S23, _S24) + _S21.blockLevelOffsetLocal_0], _S22, _S23, _S24);
    var _S28 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S29 : f32;
    if(bool(index_0.w))
    {
        _S29 = _S27;
    }
    else
    {
        _S29 = 0.0f;
    }
    textureStore((valueOut_0), (_S28), vec4<f32>((_S29), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S30 : NvFlowSparseLevelParams_0,  _S31 : u32,  _S32 : vec3<i32>,  _S33 : f32)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S30, _S32);
    NvFlowLocalWriteNeighbor1f_0(_S30, i32(0), i32(0), i32(0), _S31, _S32, _S33);
    var _S34 : i32 = neighbor_1.x;
    var _S35 : bool = _S34 != i32(0);
    if(_S35)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, _S34, i32(0), i32(0), _S31, _S32, _S33);
    }
    var _S36 : i32 = neighbor_1.y;
    var _S37 : bool = _S36 != i32(0);
    if(_S37)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, i32(0), _S36, i32(0), _S31, _S32, _S33);
    }
    var _S38 : i32 = neighbor_1.z;
    var _S39 : bool = _S38 != i32(0);
    if(_S39)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, i32(0), i32(0), _S38, _S31, _S32, _S33);
    }
    var _S40 : bool;
    if(_S35)
    {
        _S40 = _S37;
    }
    else
    {
        _S40 = false;
    }
    if(_S40)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, _S34, _S36, i32(0), _S31, _S32, _S33);
    }
    if(_S37)
    {
        _S40 = _S39;
    }
    else
    {
        _S40 = false;
    }
    if(_S40)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, i32(0), _S36, _S38, _S31, _S32, _S33);
    }
    if(_S35)
    {
        _S40 = _S39;
    }
    else
    {
        _S40 = false;
    }
    if(_S40)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, _S34, i32(0), _S38, _S31, _S32, _S33);
    }
    if(_S35)
    {
        _S40 = _S37;
    }
    else
    {
        _S40 = false;
    }
    if(_S40)
    {
        _S40 = _S39;
    }
    else
    {
        _S40 = false;
    }
    if(_S40)
    {
        NvFlowLocalWriteNeighbor1f_0(_S30, _S34, _S36, _S38, _S31, _S32, _S33);
    }
    return;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var _S41 : u32 = dispatchThreadID_0.x;
    var threadIdx_3 : vec3<i32> = computeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), _S41);
    var listIdx_0 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var localThreadIdx_0 : u32 = (_S41 & (u32(255)));
    var blockIdx_1 : u32 = blockIdxIn_0[listIdx_0];
    var location_0 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
    var _S42 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, &(location_0));
    if(!_S42)
    {
        return;
    }
    var range_0 : vec2<u32> = rangeIn_0[listIdx_0];
    var _S43 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1);
    var _S44 : vec4<f32> = vec4<f32>((vec3<f32>((((location_0.xyz) << ((globalParamsIn_0.table_0.blockDimBits_0)))) + threadIdx_3) + vec3<f32>(0.5f, 0.5f, 0.5f)) * layerParamsIn_0[_S43].vidxToWorld_0, 1.0f);
    var _S45 : vec3<f32> = vec4<f32>(vec3<f32>((((location_0.xyz) << ((globalParamsIn_0.table_0.blockDimBits_0)))) + computeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), (_S41 & (u32(4294967040))))) * layerParamsIn_0[_S43].vidxToWorld_0, 1.0f).xyz;
    var _S46 : vec3<f32> = vec4<f32>((vec3<f32>((((location_0.xyz) << ((globalParamsIn_0.table_0.blockDimBits_0)))) + computeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), (_S41 | (u32(255))))) + vec3<f32>(1.0f, 1.0f, 1.0f)) * layerParamsIn_0[_S43].vidxToWorld_0, 1.0f).xyz;
    var _S47 : f32 = layerParamsIn_0[_S43].rasterRadiusScale_0;
    var _S48 : u32 = range_0.y;
    var _S49 : u32 = range_0.x;
    var _S50 : u32 = (_S48 - _S49 + u32(255)) / u32(256);
    var _S51 : u32 = _S49 + localThreadIdx_0;
    const _S52 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var _S53 : f32 = _S45.x;
    var _S54 : f32 = _S46.x;
    var _S55 : f32 = _S45.y;
    var _S56 : f32 = _S46.y;
    var _S57 : f32 = _S45.z;
    var _S58 : f32 = _S46.z;
    var batchIdx_0 : u32 = u32(0);
    var rangeIdx_0 : u32 = _S51;
    var sum_0 : f32 = 0.0f;
    for(;;)
    {
        if(batchIdx_0 < _S50)
        {
        }
        else
        {
            break;
        }
        var pred_0 : u32;
        var particleIdx_4 : u32;
        if(rangeIdx_0 < _S48)
        {
            var particleIdx_5 : u32 = instanceIdIn_0[rangeIdx_0];
            var position_0 : vec4<f32> = readPosition_0(unpackStorage_1(layerParamsIn_0[_S43]), particleIdx_5);
            var e1_0 : vec4<f32> = readAnisotropyE1_0(unpackStorage_1(layerParamsIn_0[_S43]), particleIdx_5);
            var e2_0 : vec4<f32> = readAnisotropyE2_0(unpackStorage_1(layerParamsIn_0[_S43]), particleIdx_5);
            var e3_0 : vec4<f32> = readAnisotropyE3_0(unpackStorage_1(layerParamsIn_0[_S43]), particleIdx_5);
            var _S59 : f32 = e1_0.w;
            var _S60 : f32 = e2_0.w;
            var _S61 : f32 = e3_0.w;
            var _S62 : vec4<f32> = vec4<f32>(e1_0.x * _S59, e2_0.x * _S60, e3_0.x * _S61, position_0.x);
            var _S63 : vec4<f32> = vec4<f32>(e1_0.y * _S59, e2_0.y * _S60, e3_0.y * _S61, position_0.y);
            var _S64 : vec4<f32> = vec4<f32>(e1_0.z * _S59, e2_0.z * _S60, e3_0.z * _S61, position_0.z);
            var minWorld_0 : vec4<f32> = _S52;
            var maxWorld_0 : vec4<f32> = _S52;
            var k_0 : i32 = i32(-1);
            for(;;)
            {
                if(k_0 <= i32(1))
                {
                }
                else
                {
                    break;
                }
                var _S65 : f32 = _S47 * f32(k_0);
                var j_0 : i32 = i32(-1);
                for(;;)
                {
                    if(j_0 <= i32(1))
                    {
                    }
                    else
                    {
                        break;
                    }
                    var _S66 : f32 = _S47 * f32(j_0);
                    var minWorld_1 : vec4<f32> = minWorld_0;
                    var maxWorld_1 : vec4<f32> = maxWorld_0;
                    var i_0 : i32 = i32(-1);
                    for(;;)
                    {
                        if(i_0 <= i32(1))
                        {
                        }
                        else
                        {
                            break;
                        }
                        var boxCoord_0 : vec4<f32> = vec4<f32>(_S47 * f32(i_0), _S66, _S65, 1.0f);
                        var worldCoord_0 : vec4<f32> = vec4<f32>(dot(_S62, boxCoord_0), dot(_S63, boxCoord_0), dot(_S64, boxCoord_0), 1.0f);
                        if((minWorld_1.w) == 0.0f)
                        {
                            minWorld_1 = worldCoord_0;
                            maxWorld_1 = worldCoord_0;
                        }
                        else
                        {
                            var _S67 : vec4<f32> = max(maxWorld_1, worldCoord_0);
                            minWorld_1 = min(minWorld_1, worldCoord_0);
                            maxWorld_1 = _S67;
                        }
                        i_0 = i_0 + i32(2);
                    }
                    var j_1 : i32 = j_0 + i32(2);
                    minWorld_0 = minWorld_1;
                    maxWorld_0 = maxWorld_1;
                    j_0 = j_1;
                }
                k_0 = k_0 + i32(2);
            }
            var _S68 : bool;
            if(_S53 > (maxWorld_0.x))
            {
                _S68 = true;
            }
            else
            {
                _S68 = (minWorld_0.x) > _S54;
            }
            var _S69 : bool;
            if(_S68)
            {
                _S69 = true;
            }
            else
            {
                _S69 = _S55 > (maxWorld_0.y);
            }
            var _S70 : bool;
            if(_S69)
            {
                _S70 = true;
            }
            else
            {
                _S70 = (minWorld_0.y) > _S56;
            }
            var _S71 : bool;
            if(_S70)
            {
                _S71 = true;
            }
            else
            {
                _S71 = _S57 > (maxWorld_0.z);
            }
            var _S72 : bool;
            if(_S71)
            {
                _S72 = true;
            }
            else
            {
                _S72 = (minWorld_0.z) > _S58;
            }
            if(!_S72)
            {
                pred_0 = u32(1);
            }
            else
            {
                pred_0 = u32(0);
            }
            particleIdx_4 = particleIdx_5;
        }
        else
        {
            pred_0 = u32(0);
            particleIdx_4 = u32(0);
        }
        var _S73 : u32 = blockScan_0(localThreadIdx_0, pred_0);
        var allocIdx_0 : u32 = _S73 - u32(1);
        if(bool(pred_0))
        {
            sparticleIdx_0[allocIdx_0] = particleIdx_4;
        }
        workgroupBarrier();
        var rangeIdx_1 : u32 = rangeIdx_0 + u32(256);
        var sharedIdx_0 : u32 = u32(0);
        var sum_1 : f32 = sum_0;
        for(;;)
        {
            if(sharedIdx_0 < stotalCount_0)
            {
            }
            else
            {
                break;
            }
            var position_1 : vec4<f32> = readPosition_0(unpackStorage_1(layerParamsIn_0[_S43]), sparticleIdx_0[sharedIdx_0]);
            var e1_1 : vec4<f32> = readAnisotropyE1_0(unpackStorage_1(layerParamsIn_0[_S43]), sparticleIdx_0[sharedIdx_0]);
            var e2_1 : vec4<f32> = readAnisotropyE2_0(unpackStorage_1(layerParamsIn_0[_S43]), sparticleIdx_0[sharedIdx_0]);
            var e3_1 : vec4<f32> = readAnisotropyE3_0(unpackStorage_1(layerParamsIn_0[_S43]), sparticleIdx_0[sharedIdx_0]);
            var _S74 : f32 = e1_1.w;
            var _S75 : f32 = e1_1.x / _S74;
            var _S76 : f32 = e1_1.y / _S74;
            var _S77 : f32 = e1_1.z / _S74;
            var xTransformInv_0 : vec4<f32> = vec4<f32>(_S75, _S76, _S77, 0.0f);
            var _S78 : f32 = e2_1.w;
            var _S79 : f32 = e2_1.x / _S78;
            var _S80 : f32 = e2_1.y / _S78;
            var _S81 : f32 = e2_1.z / _S78;
            var yTransformInv_0 : vec4<f32> = vec4<f32>(_S79, _S80, _S81, 0.0f);
            var _S82 : f32 = e3_1.w;
            var _S83 : f32 = e3_1.x / _S82;
            var _S84 : f32 = e3_1.y / _S82;
            var _S85 : f32 = e3_1.z / _S82;
            var zTransformInv_0 : vec4<f32> = vec4<f32>(_S83, _S84, _S85, 0.0f);
            var _S86 : vec3<f32> = position_1.xyz;
            xTransformInv_0[i32(3)] = - dot(vec3<f32>(_S75, _S76, _S77), _S86);
            yTransformInv_0[i32(3)] = - dot(vec3<f32>(_S79, _S80, _S81), _S86);
            zTransformInv_0[i32(3)] = - dot(vec3<f32>(_S83, _S84, _S85), _S86);
            var _S87 : vec3<f32> = vec3<f32>(dot(xTransformInv_0, _S44), dot(yTransformInv_0, _S44), dot(zTransformInv_0, _S44));
            var localPos_0 : vec3<f32> = _S87;
            var _S88 : vec3<f32> = _S87 * vec3<f32>((1.0f / _S47));
            localPos_0.x = _S88.x;
            localPos_0.y = _S88.y;
            localPos_0.z = _S88.z;
            var distance_0 : f32 = length(localPos_0.xyz);
            if((layerParamsIn_0[_S43].sdfMode_0) != u32(0))
            {
                sum_1 = max(sum_1, max(2.0f - distance_0, 0.0f));
            }
            else
            {
                var sum_2 : f32;
                if(distance_0 < 1.0f)
                {
                    sum_2 = sum_1 + layerParamsIn_0[_S43].density_0;
                }
                else
                {
                    sum_2 = sum_1;
                }
                sum_1 = sum_2;
            }
            sharedIdx_0 = sharedIdx_0 + u32(1);
        }
        workgroupBarrier();
        batchIdx_0 = batchIdx_0 + u32(1);
        rangeIdx_0 = rangeIdx_1;
        sum_0 = sum_1;
    }
    NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_3, sum_0);
    return;
}

