// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterMeshCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) faceBlockIdx1Offset_0 : u32,
    @align(8) faceBlockIdx2Offset_0 : u32,
    @align(4) faceBlockIdx3Offset_0 : u32,
    @align(16) face1Count_0 : u32,
    @align(4) face2Count_0 : u32,
    @align(8) face3Count_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) rasterThickness_0 : f32,
    @align(4) minDistance_0 : f32,
    @align(8) maxDistance_0 : f32,
    @align(4) orientationLeftHanded_0 : u32,
    @align(16) emptyMin_0 : vec4<f32>,
    @align(16) emptyMax_0 : vec4<f32>,
    @align(16) dispatchBoundsLocations_0 : u32,
    @align(4) layerAndLevel_0 : i32,
    @align(8) needsSrgbConversion_0 : u32,
    @align(4) pad1_1 : u32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldOld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_faceVertexIndices_0 : vec2<u32>,
    @align(16) range_faceVertexCounts_0 : vec2<u32>,
    @align(8) range_faceVertexStarts_0 : vec2<u32>,
    @align(16) range_velocities_0 : vec2<u32>,
    @align(8) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterMeshCS_Params_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(7) @group(0) var<storage, read> bounds3In_0 : array<vec4<u32>>;

@binding(6) @group(0) var<storage, read> bounds2In_0 : array<vec4<u32>>;

@binding(5) @group(0) var<storage, read> bounds1In_0 : array<vec4<u32>>;

@binding(4) @group(0) var<storage, read> sortValIn_0 : array<u32>;

@binding(3) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

struct EmitterMeshCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) weight_0 : f32,
    @align(8) pad2_0 : f32,
    @align(4) pad3_0 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterMeshCS_SubStepParams_std140_0;
@binding(9) @group(0) var closestOut_0 : texture_storage_3d<r32uint, write>;

@binding(8) @group(0) var<storage, read> bounds4In_0 : array<vec4<u32>>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn computeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32((threadIdx1D_0 >> (u32(8))));
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return (((vec3<i32>((_S4 & (i32(((tableParams_0.blockDimLessOne_0.x) >> (u32(3)))))), (((_S4 >> (u32(i32(_S5 - u32(3)))))) & (i32(((tableParams_0.blockDimLessOne_0.y) >> (u32(3)))))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y - u32(6)))))) & (i32(((tableParams_0.blockDimLessOne_0.z) >> (u32(2))))))) << (vec3<u32>(vec3<i32>(i32(3), i32(3), i32(2)))))) | (vec3<i32>(i32((threadIdx1D_0 & (u32(7)))), i32((((threadIdx1D_0 >> (u32(3)))) & (u32(7)))), i32((((threadIdx1D_0 >> (u32(6)))) & (u32(3)))))));
}

fn overlapTest_0( minA_0 : vec3<f32>,  maxA_0 : vec3<f32>,  minB_0 : vec3<f32>,  maxB_0 : vec3<f32>) -> bool
{
    var _S6 : bool;
    if((minA_0.x) > (maxB_0.x))
    {
        _S6 = true;
    }
    else
    {
        _S6 = (minB_0.x) > (maxA_0.x);
    }
    if(_S6)
    {
        _S6 = true;
    }
    else
    {
        _S6 = (minA_0.y) > (maxB_0.y);
    }
    if(_S6)
    {
        _S6 = true;
    }
    else
    {
        _S6 = (minB_0.y) > (maxA_0.y);
    }
    if(_S6)
    {
        _S6 = true;
    }
    else
    {
        _S6 = (minA_0.z) > (maxB_0.z);
    }
    if(_S6)
    {
        _S6 = true;
    }
    else
    {
        _S6 = (minB_0.z) > (maxA_0.z);
    }
    return !_S6;
}

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

fn blockScan_0( threadIdx_0 : u32,  val_0 : u32,  totalCount_0 : ptr<function, u32>) -> u32
{
    sdata0_0[threadIdx_0] = val_0;
    workgroupBarrier();
    var localVal_0 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_0 = val_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_0 = val_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(2)];
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(3)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(4)];
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(8)];
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(12)];
    }
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(16)];
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(32)];
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_0 = localVal_0 + sdata0_0[threadIdx_0 - u32(48)];
    }
    sdata1_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(64)];
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(128)];
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_0 = localVal_0 + sdata1_0[threadIdx_0 - u32(192)];
    }
    (*totalCount_0) = workgroupUniformLoad(&sdata1_0[i32(63)]) + workgroupUniformLoad(&sdata1_0[i32(127)]) + workgroupUniformLoad(&sdata1_0[i32(191)]) + workgroupUniformLoad(&sdata1_0[i32(255)]);
    return localVal_0;
}

var<workgroup> slist3_0 : array<u32, i32(256)>;

var<workgroup> slist2_0 : array<u32, i32(256)>;

var<workgroup> slist1_0 : array<u32, i32(256)>;

fn fetchWorldPos_0( faceVertexIdx_0 : u32) -> vec4<f32>
{
    var _S7 : u32 = u32(3) * faceVertexIdx_0;
    var posLocal_0 : vec4<f32> = vec4<f32>((bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7 + u32(1)]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7 + u32(2)]))), 1.0f);
    var posWorld_0 : vec4<f32> = (((unpackStorage_0(gParams_0.localToWorld_0)) * (posLocal_0)));
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var _S8 : vec4<f32> = posWorld_0 * vec4<f32>((1.0f - gSubStepParams_0.weight_0));
        posWorld_0 = _S8;
        posWorld_0 = _S8 + vec4<f32>(gSubStepParams_0.weight_0) * (((unpackStorage_0(gParams_0.localToWorldOld_0)) * (posLocal_0)));
    }
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var vel4_0 : vec4<f32> = vec4<f32>(gSubStepParams_0.defaultVelocity_0, 0.0f);
        if(faceVertexIdx_0 < (gParams_0.range_velocities_0.y))
        {
            vel4_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7])));
            vel4_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7 + u32(1)])));
            vel4_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7 + u32(2)])));
        }
        if((gParams_0.velocityIsWorldSpace_0) == u32(0))
        {
            vel4_0 = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vel4_0)));
        }
        var _S9 : vec3<f32> = vel4_0.xyz * vec3<f32>(gSubStepParams_0.velocityScale_0);
        vel4_0.x = _S9.x;
        vel4_0.y = _S9.y;
        vel4_0.z = _S9.z;
        var _S10 : vec3<f32> = posWorld_0.xyz - vec3<f32>(gSubStepParams_0.subStepAccumDeltaTime_0) * vel4_0.xyz;
        posWorld_0.x = _S10.x;
        posWorld_0.y = _S10.y;
        posWorld_0.z = _S10.z;
    }
    return posWorld_0;
}

fn rayTriangleNearest_0( o_0 : vec3<f32>,  d_0 : vec3<f32>,  p0_0 : vec3<f32>,  p1_0 : vec3<f32>,  p2_0 : vec3<f32>,  uvt_0 : ptr<function, vec3<f32>>) -> bool
{
    var e1_0 : vec3<f32> = p1_0 - p0_0;
    var e2_0 : vec3<f32> = p2_0 - p0_0;
    var q_0 : vec3<f32> = cross(d_0, e2_0);
    var a_0 : f32 = dot(e1_0, q_0);
    if(a_0 == 0.0f)
    {
        (*uvt_0) = vec3<f32>(0.0f, 0.0f, 0.0f);
        return false;
    }
    var f_0 : f32 = 1.0f / a_0;
    var s_0 : vec3<f32> = o_0 - p0_0;
    var u_0 : f32 = f_0 * dot(s_0, q_0);
    var r_0 : vec3<f32> = cross(s_0, e1_0);
    var v_0 : f32 = f_0 * dot(d_0, r_0);
    var t_0 : f32 = f_0 * dot(e2_0, r_0);
    var p_0 : vec3<f32> = o_0 + d_0 * vec3<f32>(t_0);
    var u_1 : f32;
    var v_1 : f32;
    if((1.0f - u_0 - v_0) < 0.0f)
    {
        var _S11 : vec3<f32> = p2_0 - p1_0;
        var edge_0 : f32 = clamp(dot(p_0 - p1_0, _S11) / dot(_S11, _S11), 0.0f, 1.0f);
        u_1 = 1.0f - edge_0;
        v_1 = edge_0;
    }
    else
    {
        if(u_0 < 0.0f)
        {
            var _S12 : vec3<f32> = p0_0 - p2_0;
            var _S13 : f32 = 1.0f - clamp(dot(p_0 - p2_0, _S12) / dot(_S12, _S12), 0.0f, 1.0f);
            u_1 = 0.0f;
            v_1 = _S13;
        }
        else
        {
            if(v_0 < 0.0f)
            {
                u_1 = clamp(dot(p_0 - p0_0, e1_0) / dot(e1_0, e1_0), 0.0f, 1.0f);
                v_1 = 0.0f;
            }
            else
            {
                u_1 = u_0;
                v_1 = v_0;
            }
        }
    }
    (*uvt_0) = vec3<f32>(u_1, v_1, t_0);
    return true;
}

fn signedDistTriangle_0( v1_0 : vec3<f32>,  v2_0 : vec3<f32>,  v3_0 : vec3<f32>,  p_1 : vec3<f32>) -> f32
{
    var uvt_1 : vec3<f32>;
    var valid_0 : bool = rayTriangleNearest_0(p_1, cross(v2_0 - v1_0, v3_0 - v1_0), v1_0, v2_0, v3_0, &(uvt_1));
    if(!valid_0)
    {
        return gParams_0.emptyMin_0.x;
    }
    var distSigned_0 : f32 = f32(sign(- uvt_1.z)) * length(p_1 - (vec3<f32>((1.0f - uvt_1.x - uvt_1.y)) * v1_0 + vec3<f32>(uvt_1.x) * v2_0 + vec3<f32>(uvt_1.y) * v3_0));
    var distSigned_1 : f32;
    if((gParams_0.orientationLeftHanded_0) != u32(0))
    {
        distSigned_1 = - distSigned_0;
    }
    else
    {
        distSigned_1 = distSigned_0;
    }
    return distSigned_1;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S14 : i32 = threadIdx_1.x;
    if(_S14 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S14 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S15 : i32 = threadIdx_1.y;
    if(_S15 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S15 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S16 : i32 = threadIdx_1.z;
    if(_S16 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S16 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_0 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_0[i32(0)] = ridx_0[i32(0)] + ((mask_0 & (x_1)));
    ridx_0[i32(1)] = ridx_0[i32(1)] + ((mask_0 & (y_1)));
    ridx_0[i32(2)] = ridx_0[i32(2)] + ((mask_0 & (z_1)));
    return ridx_0;
}

fn NvFlowLocationToBlockIdx_0( _S17 : NvFlowSparseLevelParams_0,  _S18 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S18.xyz) & ((_S17.tableDimLessOne_0)));
    var _S19 : u32 = ((((((((bucketIdx_0.z) << ((_S17.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S17.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S20 : u32 = gTable_0[_S19 + u32(1)];
    var _S21 : i32 = _S18.x;
    var _S22 : i32 = _S18.y;
    var _S23 : i32 = _S18.z;
    var _S24 : i32 = _S18.w;
    var blockIdx_1 : u32 = gTable_0[_S19];
    for(;;)
    {
        if(blockIdx_1 < _S20)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S17.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S25 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S21)
        {
            _S25 = compareLocation_y_0 == _S22;
        }
        else
        {
            _S25 = false;
        }
        var _S26 : bool;
        if(_S25)
        {
            _S26 = compareLocation_z_0 == _S23;
        }
        else
        {
            _S26 = false;
        }
        var _S27 : bool;
        if(_S26)
        {
            _S27 = compareLocation_w_0 == _S24;
        }
        else
        {
            _S27 = false;
        }
        if(_S27)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowBlockIdxToLocation_0( _S28 : NvFlowSparseLevelParams_0,  _S29 : u32,  _S30 : ptr<function, vec4<i32>>) -> bool
{
    var _S31 : bool = _S29 < (_S28.numLocations_0);
    if(_S31)
    {
        var locationIdx_0 : u32 = ((_S29 << (u32(2)))) + _S28.locationOffset_0;
        (*_S30)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S30)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S30)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S30)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S30)[i32(0)] = i32(1073741824);
        (*_S30)[i32(1)] = i32(1073741824);
        (*_S30)[i32(2)] = i32(1073741824);
        (*_S30)[i32(3)] = i32(1073741824);
    }
    return _S31;
}

fn NvFlowLocalWriteNeighbor1ui_0( _S32 : NvFlowSparseLevelParams_0,  _S33 : i32,  _S34 : i32,  _S35 : i32,  _S36 : u32,  _S37 : vec3<i32>,  _S38 : u32)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S37, gTable_0[NvFlowNeighborToIdx_0(_S36, _S33, _S34, _S35) + _S32.blockLevelOffsetLocal_0], _S33, _S34, _S35);
    var _S39 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S40 : u32;
    if(bool(index_0.w))
    {
        _S40 = _S38;
    }
    else
    {
        _S40 = u32(0);
    }
    textureStore((closestOut_0), (_S39), vec4<u32>((_S40), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1ui_0( _S41 : NvFlowSparseLevelParams_0,  _S42 : u32,  _S43 : vec3<i32>,  _S44 : u32)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S41, _S43);
    NvFlowLocalWriteNeighbor1ui_0(_S41, i32(0), i32(0), i32(0), _S42, _S43, _S44);
    var _S45 : i32 = neighbor_1.x;
    var _S46 : bool = _S45 != i32(0);
    if(_S46)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, _S45, i32(0), i32(0), _S42, _S43, _S44);
    }
    var _S47 : i32 = neighbor_1.y;
    var _S48 : bool = _S47 != i32(0);
    if(_S48)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, i32(0), _S47, i32(0), _S42, _S43, _S44);
    }
    var _S49 : i32 = neighbor_1.z;
    var _S50 : bool = _S49 != i32(0);
    if(_S50)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, i32(0), i32(0), _S49, _S42, _S43, _S44);
    }
    var _S51 : bool;
    if(_S46)
    {
        _S51 = _S48;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, _S45, _S47, i32(0), _S42, _S43, _S44);
    }
    if(_S48)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, i32(0), _S47, _S49, _S42, _S43, _S44);
    }
    if(_S46)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, _S45, i32(0), _S49, _S42, _S43, _S44);
    }
    if(_S46)
    {
        _S51 = _S48;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        _S51 = _S50;
    }
    else
    {
        _S51 = false;
    }
    if(_S51)
    {
        NvFlowLocalWriteNeighbor1ui_0(_S41, _S45, _S47, _S49, _S42, _S43, _S44);
    }
    return;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>, @builtin(local_invocation_id) groupThreadID_0 : vec3<u32>)
{
    var sthreadIdx_0 : u32 = groupThreadID_0.x;
    var threadIdx_3 : vec3<i32> = computeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var blockIdx_3 : u32;
    if((gParams_0.dispatchBoundsLocations_0) != u32(0))
    {
        var _S52 : u32 = blockIdx_2 % gParams_0.locationExtent_0.x;
        var _S53 : i32 = i32(_S52) + gParams_0.locationOffset_1.x;
        var _S54 : u32 = blockIdx_2 / gParams_0.locationExtent_0.x;
        var _S55 : u32 = _S54 % gParams_0.locationExtent_0.y;
        var _S56 : i32 = i32(_S55) + gParams_0.locationOffset_1.y;
        var _S57 : u32 = blockIdx_2 / (gParams_0.locationExtent_0.x * gParams_0.locationExtent_0.y);
        blockIdx_3 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(_S53, _S56, i32(_S57) + gParams_0.locationOffset_1.z, gParams_0.locationOffset_1.w));
    }
    else
    {
        blockIdx_3 = blockIdx_2;
    }
    var location_0 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
    var _S58 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_1(gParams_0.table_0), blockIdx_3, &(location_0));
    if(!_S58)
    {
        return;
    }
    var _S59 : f32 = gParams_0.emptyMin_0.x;
    var _S60 : vec3<f32> = (vec3<f32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(gParams_0.table_0.blockDimBits_0.xyz))))) + threadIdx_3) + vec3<f32>(0.5f, 0.5f, 0.5f)) * gParams_0.vidxToWorld_0;
    var _S61 : u32 = ((groupID_0.x) << (u32(8)));
    var groupWorldMin_0 : vec3<f32> = gParams_0.vidxToWorld_0 * vec3<f32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(gParams_0.table_0.blockDimBits_0.xyz))))) + computeThreadIdx_0(unpackStorage_1(gParams_0.table_0), _S61)) - vec3<f32>(gParams_0.rasterThickness_0);
    var groupWorldMax_0 : vec3<f32> = gParams_0.vidxToWorld_0 * vec3<f32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(gParams_0.table_0.blockDimBits_0.xyz))))) + computeThreadIdx_0(unpackStorage_1(gParams_0.table_0), _S61 + u32(255)) + vec3<i32>(i32(1), i32(1), i32(1))) + vec3<f32>(gParams_0.rasterThickness_0);
    var bounds3Min_0 : vec4<f32>;
    if(sthreadIdx_0 < (gParams_0.face3Count_0))
    {
        bounds3Min_0 = (bitcast<vec4<f32>>((bounds3In_0[u32(2) * sthreadIdx_0])));
    }
    else
    {
        bounds3Min_0 = gParams_0.emptyMin_0;
    }
    var bounds3Max_0 : vec4<f32>;
    if(sthreadIdx_0 < (gParams_0.face3Count_0))
    {
        bounds3Max_0 = (bitcast<vec4<f32>>((bounds3In_0[u32(2) * sthreadIdx_0 + u32(1)])));
    }
    else
    {
        bounds3Max_0 = gParams_0.emptyMax_0;
    }
    var overlap3_0 : u32;
    if(overlapTest_0(groupWorldMin_0, groupWorldMax_0, bounds3Min_0.xyz, bounds3Max_0.xyz))
    {
        overlap3_0 = u32(1);
    }
    else
    {
        overlap3_0 = u32(0);
    }
    var total3_0 : u32 = u32(0);
    var _S62 : u32 = blockScan_0(sthreadIdx_0, overlap3_0, &(total3_0));
    var scan3_0 : u32 = _S62 - overlap3_0;
    if(overlap3_0 != u32(0))
    {
        slist3_0[scan3_0] = sthreadIdx_0;
    }
    var overlap2_0 : u32;
    workgroupBarrier();
    var closestDistance_0 : f32 = _S59;
    var closestFaceIdx_0 : u32 = u32(4294967295);
    var slistIdx3_0 : u32 = u32(0);
    var testCount_0 : u32 = u32(0);
    for(;;)
    {
        if(slistIdx3_0 < total3_0)
        {
        }
        else
        {
            break;
        }
        var bounds2Idx_0 : u32 = (((slist3_0[slistIdx3_0]) << (u32(8)))) + sthreadIdx_0;
        var bounds2Min_0 : vec4<f32>;
        if(bounds2Idx_0 < (gParams_0.face2Count_0))
        {
            bounds2Min_0 = (bitcast<vec4<f32>>((bounds2In_0[u32(2) * bounds2Idx_0])));
        }
        else
        {
            bounds2Min_0 = gParams_0.emptyMin_0;
        }
        var bounds2Max_0 : vec4<f32>;
        if(bounds2Idx_0 < (gParams_0.face2Count_0))
        {
            bounds2Max_0 = (bitcast<vec4<f32>>((bounds2In_0[u32(2) * bounds2Idx_0 + u32(1)])));
        }
        else
        {
            bounds2Max_0 = gParams_0.emptyMax_0;
        }
        if(overlapTest_0(groupWorldMin_0, groupWorldMax_0, bounds2Min_0.xyz, bounds2Max_0.xyz))
        {
            overlap2_0 = u32(1);
        }
        else
        {
            overlap2_0 = u32(0);
        }
        var total2_0 : u32 = u32(0);
        var _S63 : u32 = blockScan_0(sthreadIdx_0, overlap2_0, &(total2_0));
        var scan2_0 : u32 = _S63 - overlap2_0;
        if(overlap2_0 != u32(0))
        {
            slist2_0[scan2_0] = bounds2Idx_0;
        }
        workgroupBarrier();
        var slistIdx2_0 : u32 = u32(0);
        for(;;)
        {
            if(slistIdx2_0 < total2_0)
            {
            }
            else
            {
                break;
            }
            var bounds1Idx_0 : u32 = (((slist2_0[slistIdx2_0]) << (u32(8)))) + sthreadIdx_0;
            var bounds1Min_0 : vec4<f32>;
            if(bounds1Idx_0 < (gParams_0.face1Count_0))
            {
                bounds1Min_0 = (bitcast<vec4<f32>>((bounds1In_0[u32(2) * bounds1Idx_0])));
            }
            else
            {
                bounds1Min_0 = gParams_0.emptyMin_0;
            }
            var bounds1Max_0 : vec4<f32>;
            if(bounds1Idx_0 < (gParams_0.face1Count_0))
            {
                bounds1Max_0 = (bitcast<vec4<f32>>((bounds1In_0[u32(2) * bounds1Idx_0 + u32(1)])));
            }
            else
            {
                bounds1Max_0 = gParams_0.emptyMax_0;
            }
            var overlap1_0 : u32;
            if(overlapTest_0(groupWorldMin_0, groupWorldMax_0, bounds1Min_0.xyz, bounds1Max_0.xyz))
            {
                overlap1_0 = u32(1);
            }
            else
            {
                overlap1_0 = u32(0);
            }
            var total1_0 : u32 = u32(0);
            var _S64 : u32 = blockScan_0(sthreadIdx_0, overlap1_0, &(total1_0));
            var scan1_0 : u32 = _S64 - overlap1_0;
            if(overlap1_0 != u32(0))
            {
                slist1_0[scan1_0] = bounds1Idx_0;
            }
            workgroupBarrier();
            var closestDistance_1 : f32 = closestDistance_0;
            var closestFaceIdx_1 : u32 = closestFaceIdx_0;
            var slistIdx1_0 : u32 = u32(0);
            var testCount_1 : u32 = testCount_0;
            for(;;)
            {
                if(slistIdx1_0 < total1_0)
                {
                }
                else
                {
                    break;
                }
                var sortedFaceIdx_0 : u32 = slist1_0[slistIdx1_0];
                var closestFaceIdx_2 : u32;
                var closestDistance_2 : f32;
                if((slist1_0[slistIdx1_0]) < (gParams_0.face1Count_0))
                {
                    var faceIdx_0 : u32 = sortValIn_0[sortedFaceIdx_0];
                    var _S65 : u32 = testCount_1 + u32(1);
                    var faceVertexCount_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexCounts_0.x + faceIdx_0];
                    var faceVertexStart_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexStarts_0.x + faceIdx_0];
                    if(faceVertexCount_0 >= u32(3))
                    {
                        var _S66 : u32 = faceVertexCount_0 - u32(2);
                        var _S67 : vec3<f32> = fetchWorldPos_0(arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0]).xyz;
                        closestDistance_2 = closestDistance_1;
                        closestFaceIdx_2 = closestFaceIdx_1;
                        var triangleIdx_0 : u32 = u32(0);
                        for(;;)
                        {
                            if(triangleIdx_0 < _S66)
                            {
                            }
                            else
                            {
                                break;
                            }
                            var dist_0 : f32 = signedDistTriangle_0(_S67, fetchWorldPos_0(arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0 + triangleIdx_0 + u32(1)]).xyz, fetchWorldPos_0(arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0 + triangleIdx_0 + u32(2)]).xyz, _S60);
                            if((abs(dist_0)) < (abs(closestDistance_2)))
                            {
                                closestDistance_2 = dist_0;
                                closestFaceIdx_2 = faceIdx_0;
                            }
                            triangleIdx_0 = triangleIdx_0 + u32(1);
                        }
                    }
                    else
                    {
                        closestDistance_2 = closestDistance_1;
                        closestFaceIdx_2 = closestFaceIdx_1;
                    }
                    testCount_1 = _S65;
                }
                else
                {
                    closestDistance_2 = closestDistance_1;
                    closestFaceIdx_2 = closestFaceIdx_1;
                }
                var _S68 : u32 = slistIdx1_0 + u32(1);
                closestDistance_1 = closestDistance_2;
                closestFaceIdx_1 = closestFaceIdx_2;
                slistIdx1_0 = _S68;
            }
            var _S69 : u32 = slistIdx2_0 + u32(1);
            closestDistance_0 = closestDistance_1;
            closestFaceIdx_0 = closestFaceIdx_1;
            slistIdx2_0 = _S69;
            testCount_0 = testCount_1;
        }
        slistIdx3_0 = slistIdx3_0 + u32(1);
    }
    var _S70 : bool;
    if(closestFaceIdx_0 != u32(4294967295))
    {
        _S70 = closestDistance_0 >= (gParams_0.minDistance_0);
    }
    else
    {
        _S70 = false;
    }
    if(_S70)
    {
        _S70 = closestDistance_0 <= (gParams_0.maxDistance_0);
    }
    else
    {
        _S70 = false;
    }
    if(_S70)
    {
        overlap2_0 = closestFaceIdx_0;
    }
    else
    {
        overlap2_0 = u32(4294967295);
    }
    NvFlowLocalWrite1ui_0(unpackStorage_1(gParams_0.table_0), blockIdx_3, threadIdx_3, overlap2_0);
    return;
}

