// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterNanoVdbCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(8) velocityIsWorldSpace_0 : u32,
    @align(4) sourceIsVelocity_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) targetValue_0 : vec4<f32>,
    @align(16) coupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) position_0 : vec3<f32>,
    @align(4) minDistance_0 : f32,
    @align(16) halfSizeInv_0 : vec3<f32>,
    @align(4) maxDistance_0 : f32,
    @align(16) halfSize_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) anyStreamingClearEnabled_0 : u32,
    @align(4) absoluteValue_0 : u32,
    @align(8) minSmoke_0 : f32,
    @align(4) maxSmoke_0 : f32,
    @align(16) computeSpeed_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) range_velocities_0 : vec4<u32>,
    @align(16) range_divergences_0 : vec4<u32>,
    @align(16) range_temperatures_0 : vec4<u32>,
    @align(16) range_fuels_0 : vec4<u32>,
    @align(16) range_burns_0 : vec4<u32>,
    @align(16) range_smokes_0 : vec4<u32>,
    @align(16) range_coupleRateVelocities_0 : vec4<u32>,
    @align(16) range_coupleRateDivergences_0 : vec4<u32>,
    @align(16) range_coupleRateTemperatures_0 : vec4<u32>,
    @align(16) range_coupleRateFuels_0 : vec4<u32>,
    @align(16) range_coupleRateBurns_0 : vec4<u32>,
    @align(16) range_coupleRateSmokes_0 : vec4<u32>,
    @align(16) range_distances_0 : vec4<u32>,
    @align(16) range_rgba8s_0 : vec4<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterNanoVdbCS_Params_std140_0;
@binding(1) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(2) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(3) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_0 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_0.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_0.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_0.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_1 : vec3<i32>,  v_0 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_0 : vec4<i32> = vec4<i32>(((threadIdx_1.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_1.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_1.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_0) >> (u32(31)));
    ridx_0[i32(0)] = ridx_0[i32(0)] + ((mask_0 & (x_1)));
    ridx_0[i32(1)] = ridx_0[i32(1)] + ((mask_0 & (y_1)));
    ridx_0[i32(2)] = ridx_0[i32(2)] + ((mask_0 & (z_1)));
    return ridx_0;
}

fn NvFlowLocationToBlockIdx_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S10.xyz) & ((_S9.tableDimLessOne_0)));
    var _S11 : u32 = ((((((((bucketIdx_0.z) << ((_S9.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S9.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S12 : u32 = gTable_0[_S11 + u32(1)];
    var _S13 : i32 = _S10.x;
    var _S14 : i32 = _S10.y;
    var _S15 : i32 = _S10.z;
    var _S16 : i32 = _S10.w;
    var blockIdx_1 : u32 = gTable_0[_S11];
    for(;;)
    {
        if(blockIdx_1 < _S12)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S9.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S17 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S13)
        {
            _S17 = compareLocation_y_0 == _S14;
        }
        else
        {
            _S17 = false;
        }
        var _S18 : bool;
        if(_S17)
        {
            _S18 = compareLocation_z_0 == _S15;
        }
        else
        {
            _S18 = false;
        }
        var _S19 : bool;
        if(_S18)
        {
            _S19 = compareLocation_w_0 == _S16;
        }
        else
        {
            _S19 = false;
        }
        if(_S19)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowLocalWriteNeighbor4f_0( _S20 : NvFlowSparseLevelParams_0,  _S21 : i32,  _S22 : i32,  _S23 : i32,  _S24 : u32,  _S25 : vec3<i32>,  _S26 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S25, gTable_0[NvFlowNeighborToIdx_0(_S24, _S21, _S22, _S23) + _S20.blockLevelOffsetLocal_0], _S21, _S22, _S23);
    var _S27 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S28 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S28 = _S26;
    }
    else
    {
        _S28 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S27), (_S28));
    return;
}

fn NvFlowLocalWrite4f_0( _S29 : NvFlowSparseLevelParams_0,  _S30 : u32,  _S31 : vec3<i32>,  _S32 : vec4<f32>)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S29, _S31);
    NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), i32(0), i32(0), _S30, _S31, _S32);
    var _S33 : i32 = neighbor_1.x;
    var _S34 : bool = _S33 != i32(0);
    if(_S34)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, i32(0), i32(0), _S30, _S31, _S32);
    }
    var _S35 : i32 = neighbor_1.y;
    var _S36 : bool = _S35 != i32(0);
    if(_S36)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), _S35, i32(0), _S30, _S31, _S32);
    }
    var _S37 : i32 = neighbor_1.z;
    var _S38 : bool = _S37 != i32(0);
    if(_S38)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), i32(0), _S37, _S30, _S31, _S32);
    }
    var _S39 : bool;
    if(_S34)
    {
        _S39 = _S36;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, _S35, i32(0), _S30, _S31, _S32);
    }
    if(_S36)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, i32(0), _S35, _S37, _S30, _S31, _S32);
    }
    if(_S34)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, i32(0), _S37, _S30, _S31, _S32);
    }
    if(_S34)
    {
        _S39 = _S36;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        _S39 = _S38;
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        NvFlowLocalWriteNeighbor4f_0(_S29, _S33, _S35, _S37, _S30, _S31, _S32);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_2 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var _S40 : u32 = groupID_0.y;
    var locationIdx_0 : u32 = _S40 + gParams_0.blockIdxOffset_0;
    var _S41 : u32 = locationIdx_0 % gParams_0.locationExtent_0.x;
    var _S42 : i32 = i32(_S41) + gParams_0.locationOffset_1.x;
    var _S43 : u32 = locationIdx_0 / gParams_0.locationExtent_0.x;
    var _S44 : u32 = _S43 % gParams_0.locationExtent_0.y;
    var _S45 : i32 = i32(_S44) + gParams_0.locationOffset_1.y;
    var _S46 : u32 = locationIdx_0 / (gParams_0.locationExtent_0.x * gParams_0.locationExtent_0.y);
    var _S47 : i32 = i32(_S46) + gParams_0.locationOffset_1.z;
    var _S48 : u32 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(_S42, _S45, _S47, gParams_0.locationOffset_1.w));
    if(_S48 >= (gParams_0.table_0.numLocations_0))
    {
        return;
    }
    var localPosTranslated_0 : vec3<f32> = (((unpackStorage_0(gParams_0.worldToLocal_0)) * (vec4<f32>(gParams_0.vidxToWorld_0 * (vec3<f32>(((vec3<i32>(_S42, _S45, _S47) << ((gParams_0.table_0.blockDimBits_0)))) + threadIdx_2) + vec3<f32>(0.5f, 0.5f, 0.5f)), 1.0f)))).xyz - gParams_0.position_0;
    var _S49 : bool;
    if((abs(localPosTranslated_0.x)) < (gParams_0.halfSize_0.x))
    {
        _S49 = (abs(localPosTranslated_0.y)) < (gParams_0.halfSize_0.y);
    }
    else
    {
        _S49 = false;
    }
    if(_S49)
    {
        _S49 = (abs(localPosTranslated_0.z)) < (gParams_0.halfSize_0.z);
    }
    else
    {
        _S49 = false;
    }
    if(_S49)
    {
        var _S50 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(threadIdx_2 + vec3<i32>((i32((_S40 & (u32(15)))) << (u32(i32(gParams_0.table_0.blockDimBits_0.x)))), (((i32((_S40 >> (u32(4)))) & (i32(15)))) << (u32(i32(gParams_0.table_0.blockDimBits_0.y)))), (((i32((_S40 >> (u32(8)))) & (i32(15)))) << (u32(i32(gParams_0.table_0.blockDimBits_0.z)))))), u32(0)));
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), _S48, threadIdx_2, (textureLoad((valueIn_0), ((_S50)).xyz, ((_S50)).w)));
    }
    return;
}

