// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterPointCS_Params_std140_0
{
    @align(16) pointBlockIdxOffset_0 : u32,
    @align(4) reduce2BlockIdxOffset_0 : u32,
    @align(8) reduce3BlockIdxOffset_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableCoarse_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) layerAndLevel_0 : i32,
    @align(4) defaultAllocateMask_0 : u32,
    @align(8) allocateMaskCount_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_velocities_0 : vec2<u32>,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) anyStreamingClearEnabled_0 : u32,
    @align(16) reduceCount1_0 : u32,
    @align(4) reduceCount2_0 : u32,
    @align(8) reduceCount3_0 : u32,
    @align(4) enableInterpolation_0 : u32,
    @align(16) voxelsPerPoint_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterPointCS_Params_std140_0;
@binding(3) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

struct EmitterPointCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) pad1_2 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterPointCS_SubStepParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(6) @group(0) var<storage, read_write> keyOut_0 : array<u32>;

@binding(7) @group(0) var<storage, read_write> valOut_0 : array<u32>;

@binding(8) @group(0) var<storage, read_write> keyLowOut_0 : array<u32>;

@binding(4) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(5) @group(0) var<storage, read_write> oldValueOut_0 : array<vec4<f32>>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S4 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S4, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S4 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocationToBlockIdx_0( _S5 : NvFlowSparseLevelParams_0,  _S6 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S6.xyz) & ((_S5.tableDimLessOne_0)));
    var _S7 : u32 = ((((((((bucketIdx_0.z) << ((_S5.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S5.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S8 : u32 = gTable_0[_S7 + u32(1)];
    var _S9 : i32 = _S6.x;
    var _S10 : i32 = _S6.y;
    var _S11 : i32 = _S6.z;
    var _S12 : i32 = _S6.w;
    var blockIdx_1 : u32 = gTable_0[_S7];
    for(;;)
    {
        if(blockIdx_1 < _S8)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S5.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S13 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S9)
        {
            _S13 = compareLocation_y_0 == _S10;
        }
        else
        {
            _S13 = false;
        }
        var _S14 : bool;
        if(_S13)
        {
            _S14 = compareLocation_z_0 == _S11;
        }
        else
        {
            _S14 = false;
        }
        var _S15 : bool;
        if(_S14)
        {
            _S15 = compareLocation_w_0 == _S12;
        }
        else
        {
            _S15 = false;
        }
        if(_S15)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowLocalVirtualToReal_0( _S16 : NvFlowSparseLevelParams_0,  _S17 : u32,  _S18 : vec3<i32>) -> vec4<i32>
{
    var neighbor_0 : vec3<i32> = (_S18 >> (vec3<u32>(vec3<i32>(_S16.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S18, gTable_0[NvFlowNeighborToIdx_0(_S17, neighbor_0.x, neighbor_0.y, neighbor_0.z) + _S16.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S19 : texture_3d<f32>,  _S20 : NvFlowSparseLevelParams_0,  _S21 : u32,  _S22 : vec3<i32>) -> vec4<f32>
{
    var _S23 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S20, _S21, _S22);
    var _S24 : vec4<f32>;
    if(bool(_S23.w))
    {
        var _S25 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S23.xyz), u32(0)));
        _S24 = (textureLoad((_S19), ((_S25)).xyz, ((_S25)).w));
    }
    else
    {
        _S24 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S24;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var fullIdx_0 : u32 = dispatchThreadID_0.x + (((gParams_0.pointBlockIdxOffset_0) << (u32(7))));
    var pointIdx_0 : u32 = fullIdx_0 / gParams_0.voxelsPerPoint_0;
    var subIdx_0 : u32 = fullIdx_0 % gParams_0.voxelsPerPoint_0;
    if(pointIdx_0 >= (gParams_0.range_positions_0.y))
    {
        return;
    }
    var positionLocal_0 : vec4<f32>;
    var _S26 : u32 = u32(3) * pointIdx_0;
    positionLocal_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S26])));
    positionLocal_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S26 + u32(1)])));
    positionLocal_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S26 + u32(2)])));
    positionLocal_0[i32(3)] = 1.0f;
    var position_0 : vec4<f32> = (((unpackStorage_0(gParams_0.localToWorld_0)) * (positionLocal_0)));
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var vel4_0 : vec4<f32> = vec4<f32>(gSubStepParams_0.defaultVelocity_0, 0.0f);
        if(pointIdx_0 < (gParams_0.range_velocities_0.y))
        {
            vel4_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S26])));
            vel4_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S26 + u32(1)])));
            vel4_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S26 + u32(2)])));
        }
        if((gParams_0.velocityIsWorldSpace_0) == u32(0))
        {
            vel4_0 = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vel4_0)));
        }
        var _S27 : vec3<f32> = vel4_0.xyz * vec3<f32>(gSubStepParams_0.velocityScale_0);
        vel4_0.x = _S27.x;
        vel4_0.y = _S27.y;
        vel4_0.z = _S27.z;
        var _S28 : vec3<f32> = position_0.xyz - vec3<f32>(gSubStepParams_0.subStepAccumDeltaTime_0) * vel4_0.xyz;
        position_0.x = _S28.x;
        position_0.y = _S28.y;
        position_0.z = _S28.z;
    }
    var vidxf_0 : vec3<f32> = position_0.xyz * gParams_0.worldToVidx_0;
    var vidxf_offset_0 : vec3<f32>;
    if((gParams_0.voxelsPerPoint_0) <= u32(1))
    {
        vidxf_offset_0 = vec3<f32>(0.0f, 0.0f, 0.0f);
    }
    else
    {
        if((gParams_0.voxelsPerPoint_0) <= u32(2))
        {
            vidxf_offset_0 = vec3<f32>(0.5f, 0.0f, 0.0f);
        }
        else
        {
            if((gParams_0.voxelsPerPoint_0) <= u32(4))
            {
                vidxf_offset_0 = vec3<f32>(0.5f, 0.5f, 0.0f);
            }
            else
            {
                vidxf_offset_0 = vec3<f32>(0.5f, 0.5f, 0.5f);
            }
        }
    }
    var vidx_0 : vec3<i32> = NvFlowFloor_i_0(vidxf_0 - vidxf_offset_0);
    vidx_0[i32(0)] = vidx_0[i32(0)] + i32((subIdx_0 & (u32(1))));
    vidx_0[i32(1)] = vidx_0[i32(1)] + ((i32((subIdx_0 & (u32(2)))) >> (u32(1))));
    vidx_0[i32(2)] = vidx_0[i32(2)] + ((i32((subIdx_0 & (u32(4)))) >> (u32(2))));
    var w3_0 : vec3<f32> = max(vec3<f32>(0.0f, 0.0f, 0.0f), vec3<f32>(1.0f, 1.0f, 1.0f) - abs(vidxf_0 - (vec3<f32>(vidx_0) + vec3<f32>(0.5f, 0.5f, 0.5f))));
    var _S29 : u32 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(((vidx_0.xyz) >> (vec3<u32>(vec3<i32>(gParams_0.table_0.blockDimBits_0)))), gParams_0.layerAndLevel_0));
    var threadIdx_1 : vec3<i32> = ((vidx_0.xyz) & (vec3<i32>(gParams_0.table_0.blockDimLessOne_0)));
    keyOut_0[fullIdx_0] = (((((u32(w3_0.x * w3_0.y * w3_0.z * 1023.0f) & (u32(1023)))) << (u32(22)))) | (((((u32(((threadIdx_1.z) << ((gParams_0.table_0.blockDimBits_0.x + gParams_0.table_0.blockDimBits_0.y)))) | (u32(((threadIdx_1.y) << ((gParams_0.table_0.blockDimBits_0.x))))))) | (u32(threadIdx_1.x))))));
    valOut_0[fullIdx_0] = fullIdx_0;
    keyLowOut_0[fullIdx_0] = _S29;
    const _S30 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var oldValue_0 : vec4<f32>;
    if(_S29 != u32(4294967295))
    {
        oldValue_0 = NvFlowLocalRead4f_0(valueIn_0, unpackStorage_1(gParams_0.table_0), _S29, threadIdx_1);
    }
    else
    {
        oldValue_0 = _S30;
    }
    oldValueOut_0[fullIdx_0] = oldValue_0;
    return;
}

