// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterPointCS_Params_std140_0
{
    @align(16) pointBlockIdxOffset_0 : u32,
    @align(4) reduce2BlockIdxOffset_0 : u32,
    @align(8) reduce3BlockIdxOffset_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableCoarse_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) layerAndLevel_0 : i32,
    @align(4) defaultAllocateMask_0 : u32,
    @align(8) allocateMaskCount_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_velocities_0 : vec2<u32>,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) anyStreamingClearEnabled_0 : u32,
    @align(16) reduceCount1_0 : u32,
    @align(4) reduceCount2_0 : u32,
    @align(8) reduceCount3_0 : u32,
    @align(4) enableInterpolation_0 : u32,
    @align(16) voxelsPerPoint_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterPointCS_Params_std140_0;
@binding(5) @group(0) var<storage, read> key2In_0 : array<vec2<u32>>;

@binding(2) @group(0) var<storage, read> reduceTarget2In_0 : array<vec4<f32>>;

@binding(3) @group(0) var<storage, read> reduceCouple2In_0 : array<vec4<f32>>;

@binding(4) @group(0) var<storage, read> reduceWeight2In_0 : array<f32>;

@binding(6) @group(0) var<storage, read_write> reduceTarget3Out_0 : array<vec4<f32>>;

@binding(7) @group(0) var<storage, read_write> reduceCouple3Out_0 : array<vec4<f32>>;

@binding(8) @group(0) var<storage, read_write> reduceWeight3Out_0 : array<f32>;

@binding(9) @group(0) var<storage, read_write> key3Out_0 : array<vec2<u32>>;

struct EmitterPointCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) pad1_2 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterPointCS_SubStepParams_std140_0;
var<workgroup> sTargetValueSum_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum_0 : array<f32, i32(128)>;

fn emitterPointReduce_0( sthreadIdx_0 : u32,  targetValueSum_0 : ptr<function, vec4<f32>>,  coupleRateSum_0 : ptr<function, vec4<f32>>,  weightSum_0 : ptr<function, f32>)
{
    sTargetValueSum_0[sthreadIdx_0] = (*targetValueSum_0);
    sCoupleRateSum_0[sthreadIdx_0] = (*coupleRateSum_0);
    sWeightSum_0[sthreadIdx_0] = (*weightSum_0);
    workgroupBarrier();
    if(sthreadIdx_0 < u32(32))
    {
        var _S1 : u32 = sthreadIdx_0 + u32(32);
        var _S2 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S1];
        sTargetValueSum_0[sthreadIdx_0] = _S2;
        var _S3 : u32 = sthreadIdx_0 + u32(64);
        var _S4 : vec4<f32> = _S2 + sTargetValueSum_0[_S3];
        sTargetValueSum_0[sthreadIdx_0] = _S4;
        var _S5 : u32 = sthreadIdx_0 + u32(96);
        sTargetValueSum_0[sthreadIdx_0] = _S4 + sTargetValueSum_0[_S5];
        var _S6 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S1];
        sCoupleRateSum_0[sthreadIdx_0] = _S6;
        var _S7 : vec4<f32> = _S6 + sCoupleRateSum_0[_S3];
        sCoupleRateSum_0[sthreadIdx_0] = _S7;
        sCoupleRateSum_0[sthreadIdx_0] = _S7 + sCoupleRateSum_0[_S5];
        var _S8 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S1];
        sWeightSum_0[sthreadIdx_0] = _S8;
        var _S9 : f32 = _S8 + sWeightSum_0[_S3];
        sWeightSum_0[sthreadIdx_0] = _S9;
        sWeightSum_0[sthreadIdx_0] = _S9 + sWeightSum_0[_S5];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(8))
    {
        var _S10 : u32 = sthreadIdx_0 + u32(8);
        var _S11 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S10];
        sTargetValueSum_0[sthreadIdx_0] = _S11;
        var _S12 : u32 = sthreadIdx_0 + u32(16);
        var _S13 : vec4<f32> = _S11 + sTargetValueSum_0[_S12];
        sTargetValueSum_0[sthreadIdx_0] = _S13;
        var _S14 : u32 = sthreadIdx_0 + u32(24);
        sTargetValueSum_0[sthreadIdx_0] = _S13 + sTargetValueSum_0[_S14];
        var _S15 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S10];
        sCoupleRateSum_0[sthreadIdx_0] = _S15;
        var _S16 : vec4<f32> = _S15 + sCoupleRateSum_0[_S12];
        sCoupleRateSum_0[sthreadIdx_0] = _S16;
        sCoupleRateSum_0[sthreadIdx_0] = _S16 + sCoupleRateSum_0[_S14];
        var _S17 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S10];
        sWeightSum_0[sthreadIdx_0] = _S17;
        var _S18 : f32 = _S17 + sWeightSum_0[_S12];
        sWeightSum_0[sthreadIdx_0] = _S18;
        sWeightSum_0[sthreadIdx_0] = _S18 + sWeightSum_0[_S14];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(2))
    {
        var _S19 : u32 = sthreadIdx_0 + u32(2);
        var _S20 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S19];
        sTargetValueSum_0[sthreadIdx_0] = _S20;
        var _S21 : u32 = sthreadIdx_0 + u32(4);
        var _S22 : vec4<f32> = _S20 + sTargetValueSum_0[_S21];
        sTargetValueSum_0[sthreadIdx_0] = _S22;
        var _S23 : u32 = sthreadIdx_0 + u32(6);
        sTargetValueSum_0[sthreadIdx_0] = _S22 + sTargetValueSum_0[_S23];
        var _S24 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S19];
        sCoupleRateSum_0[sthreadIdx_0] = _S24;
        var _S25 : vec4<f32> = _S24 + sCoupleRateSum_0[_S21];
        sCoupleRateSum_0[sthreadIdx_0] = _S25;
        sCoupleRateSum_0[sthreadIdx_0] = _S25 + sCoupleRateSum_0[_S23];
        var _S26 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S19];
        sWeightSum_0[sthreadIdx_0] = _S26;
        var _S27 : f32 = _S26 + sWeightSum_0[_S21];
        sWeightSum_0[sthreadIdx_0] = _S27;
        sWeightSum_0[sthreadIdx_0] = _S27 + sWeightSum_0[_S23];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(1))
    {
        var _S28 : u32 = sthreadIdx_0 + u32(1);
        sTargetValueSum_0[sthreadIdx_0] = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S28];
        sCoupleRateSum_0[sthreadIdx_0] = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S28];
        sWeightSum_0[sthreadIdx_0] = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S28];
    }
    workgroupBarrier();
    (*targetValueSum_0) = sTargetValueSum_0[i32(0)];
    (*coupleRateSum_0) = sCoupleRateSum_0[i32(0)];
    (*weightSum_0) = sWeightSum_0[i32(0)];
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var reduceIdx2_0 : u32 = dispatchThreadID_0.x + (((gParams_0.reduce3BlockIdxOffset_0) << (u32(7))));
    var sthreadIdx_1 : u32 = (reduceIdx2_0 & (u32(127)));
    var key2Cmp_0 : vec2<u32> = key2In_0[reduceIdx2_0 - sthreadIdx_1];
    var blockIdxCmp_0 : u32 = key2Cmp_0.x;
    var threadIdx1DCmp_0 : u32 = key2Cmp_0.y;
    const _S29 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var targetValueSum_1 : vec4<f32> = _S29;
    var coupleRateSum_1 : vec4<f32> = _S29;
    var weightSum_1 : f32 = 0.0f;
    if(reduceIdx2_0 < (gParams_0.reduceCount2_0))
    {
        var key2_0 : vec2<u32> = key2In_0[reduceIdx2_0];
        var threadIdx1D_0 : u32 = key2_0.y;
        var _S30 : bool;
        if(blockIdxCmp_0 == (key2_0.x))
        {
            _S30 = threadIdx1DCmp_0 == threadIdx1D_0;
        }
        else
        {
            _S30 = false;
        }
        if(_S30)
        {
            targetValueSum_1 = reduceTarget2In_0[reduceIdx2_0];
            coupleRateSum_1 = reduceCouple2In_0[reduceIdx2_0];
            weightSum_1 = reduceWeight2In_0[reduceIdx2_0];
        }
    }
    emitterPointReduce_0(sthreadIdx_1, &(targetValueSum_1), &(coupleRateSum_1), &(weightSum_1));
    if(sthreadIdx_1 < u32(1))
    {
        var reduceIdx3_0 : u32 = (reduceIdx2_0 >> (u32(7)));
        reduceTarget3Out_0[reduceIdx3_0] = targetValueSum_1;
        reduceCouple3Out_0[reduceIdx3_0] = coupleRateSum_1;
        reduceWeight3Out_0[reduceIdx3_0] = weightSum_1;
        key3Out_0[reduceIdx3_0] = vec2<u32>(blockIdxCmp_0, threadIdx1DCmp_0);
    }
    return;
}

