// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterPointCS_Params_std140_0
{
    @align(16) pointBlockIdxOffset_0 : u32,
    @align(4) reduce2BlockIdxOffset_0 : u32,
    @align(8) reduce3BlockIdxOffset_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableCoarse_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) layerAndLevel_0 : i32,
    @align(4) defaultAllocateMask_0 : u32,
    @align(8) allocateMaskCount_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_velocities_0 : vec2<u32>,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) anyStreamingClearEnabled_0 : u32,
    @align(16) reduceCount1_0 : u32,
    @align(4) reduceCount2_0 : u32,
    @align(8) reduceCount3_0 : u32,
    @align(4) enableInterpolation_0 : u32,
    @align(16) voxelsPerPoint_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterPointCS_Params_std140_0;
@binding(5) @group(0) var<storage, read> keyIn_0 : array<u32>;

@binding(6) @group(0) var<storage, read> valIn_0 : array<u32>;

@binding(4) @group(0) var<storage, read> keyLowIn_0 : array<u32>;

@binding(3) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

@binding(7) @group(0) var<storage, read_write> reduceTarget1Out_0 : array<vec4<f32>>;

@binding(8) @group(0) var<storage, read_write> reduceCouple1Out_0 : array<vec4<f32>>;

@binding(9) @group(0) var<storage, read_write> reduceWeight1Out_0 : array<f32>;

@binding(10) @group(0) var<storage, read_write> key1Out_0 : array<vec2<u32>>;

struct EmitterPointCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) pad1_2 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterPointCS_SubStepParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

fn srgb_to_linear1_0( v_0 : f32) -> f32
{
    var ret_0 : f32;
    if(v_0 <= 0.04044999927282333f)
    {
        ret_0 = v_0 * 0.07739938050508499f;
    }
    else
    {
        ret_0 = pow((v_0 + 0.05499999970197678f) * 0.94786733388900757f, 2.40000009536743164f);
    }
    return ret_0;
}

fn srgb_to_linear_0( c_0 : vec3<f32>) -> vec3<f32>
{
    return vec3<f32>(srgb_to_linear1_0(c_0.x), srgb_to_linear1_0(c_0.y), srgb_to_linear1_0(c_0.z));
}

var<workgroup> sTargetValueSum_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum_0 : array<f32, i32(128)>;

fn emitterPointReduce_0( sthreadIdx_0 : u32,  targetValueSum_0 : ptr<function, vec4<f32>>,  coupleRateSum_0 : ptr<function, vec4<f32>>,  weightSum_0 : ptr<function, f32>)
{
    sTargetValueSum_0[sthreadIdx_0] = (*targetValueSum_0);
    sCoupleRateSum_0[sthreadIdx_0] = (*coupleRateSum_0);
    sWeightSum_0[sthreadIdx_0] = (*weightSum_0);
    workgroupBarrier();
    if(sthreadIdx_0 < u32(32))
    {
        var _S2 : u32 = sthreadIdx_0 + u32(32);
        var _S3 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S2];
        sTargetValueSum_0[sthreadIdx_0] = _S3;
        var _S4 : u32 = sthreadIdx_0 + u32(64);
        var _S5 : vec4<f32> = _S3 + sTargetValueSum_0[_S4];
        sTargetValueSum_0[sthreadIdx_0] = _S5;
        var _S6 : u32 = sthreadIdx_0 + u32(96);
        sTargetValueSum_0[sthreadIdx_0] = _S5 + sTargetValueSum_0[_S6];
        var _S7 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S2];
        sCoupleRateSum_0[sthreadIdx_0] = _S7;
        var _S8 : vec4<f32> = _S7 + sCoupleRateSum_0[_S4];
        sCoupleRateSum_0[sthreadIdx_0] = _S8;
        sCoupleRateSum_0[sthreadIdx_0] = _S8 + sCoupleRateSum_0[_S6];
        var _S9 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S2];
        sWeightSum_0[sthreadIdx_0] = _S9;
        var _S10 : f32 = _S9 + sWeightSum_0[_S4];
        sWeightSum_0[sthreadIdx_0] = _S10;
        sWeightSum_0[sthreadIdx_0] = _S10 + sWeightSum_0[_S6];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(8))
    {
        var _S11 : u32 = sthreadIdx_0 + u32(8);
        var _S12 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S11];
        sTargetValueSum_0[sthreadIdx_0] = _S12;
        var _S13 : u32 = sthreadIdx_0 + u32(16);
        var _S14 : vec4<f32> = _S12 + sTargetValueSum_0[_S13];
        sTargetValueSum_0[sthreadIdx_0] = _S14;
        var _S15 : u32 = sthreadIdx_0 + u32(24);
        sTargetValueSum_0[sthreadIdx_0] = _S14 + sTargetValueSum_0[_S15];
        var _S16 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S11];
        sCoupleRateSum_0[sthreadIdx_0] = _S16;
        var _S17 : vec4<f32> = _S16 + sCoupleRateSum_0[_S13];
        sCoupleRateSum_0[sthreadIdx_0] = _S17;
        sCoupleRateSum_0[sthreadIdx_0] = _S17 + sCoupleRateSum_0[_S15];
        var _S18 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S11];
        sWeightSum_0[sthreadIdx_0] = _S18;
        var _S19 : f32 = _S18 + sWeightSum_0[_S13];
        sWeightSum_0[sthreadIdx_0] = _S19;
        sWeightSum_0[sthreadIdx_0] = _S19 + sWeightSum_0[_S15];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(2))
    {
        var _S20 : u32 = sthreadIdx_0 + u32(2);
        var _S21 : vec4<f32> = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S20];
        sTargetValueSum_0[sthreadIdx_0] = _S21;
        var _S22 : u32 = sthreadIdx_0 + u32(4);
        var _S23 : vec4<f32> = _S21 + sTargetValueSum_0[_S22];
        sTargetValueSum_0[sthreadIdx_0] = _S23;
        var _S24 : u32 = sthreadIdx_0 + u32(6);
        sTargetValueSum_0[sthreadIdx_0] = _S23 + sTargetValueSum_0[_S24];
        var _S25 : vec4<f32> = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S20];
        sCoupleRateSum_0[sthreadIdx_0] = _S25;
        var _S26 : vec4<f32> = _S25 + sCoupleRateSum_0[_S22];
        sCoupleRateSum_0[sthreadIdx_0] = _S26;
        sCoupleRateSum_0[sthreadIdx_0] = _S26 + sCoupleRateSum_0[_S24];
        var _S27 : f32 = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S20];
        sWeightSum_0[sthreadIdx_0] = _S27;
        var _S28 : f32 = _S27 + sWeightSum_0[_S22];
        sWeightSum_0[sthreadIdx_0] = _S28;
        sWeightSum_0[sthreadIdx_0] = _S28 + sWeightSum_0[_S24];
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(1))
    {
        var _S29 : u32 = sthreadIdx_0 + u32(1);
        sTargetValueSum_0[sthreadIdx_0] = sTargetValueSum_0[sthreadIdx_0] + sTargetValueSum_0[_S29];
        sCoupleRateSum_0[sthreadIdx_0] = sCoupleRateSum_0[sthreadIdx_0] + sCoupleRateSum_0[_S29];
        sWeightSum_0[sthreadIdx_0] = sWeightSum_0[sthreadIdx_0] + sWeightSum_0[_S29];
    }
    workgroupBarrier();
    (*targetValueSum_0) = sTargetValueSum_0[i32(0)];
    (*coupleRateSum_0) = sCoupleRateSum_0[i32(0)];
    (*weightSum_0) = sWeightSum_0[i32(0)];
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var sortedIdx_0 : u32 = dispatchThreadID_0.x + (((gParams_0.pointBlockIdxOffset_0) << (u32(7))));
    var sthreadIdx_1 : u32 = (sortedIdx_0 & (u32(127)));
    var sortedIdxCmp_0 : u32 = sortedIdx_0 - sthreadIdx_1;
    var blockIdxCmp_0 : u32 = keyIn_0[sortedIdxCmp_0];
    var threadIdx1DCmp_0 : u32 = (keyLowIn_0[valIn_0[sortedIdxCmp_0]] & (u32(4194303)));
    const _S30 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var targetValueSum_1 : vec4<f32> = _S30;
    var coupleRateSum_1 : vec4<f32> = _S30;
    var weightSum_1 : f32 = 0.0f;
    if(sortedIdx_0 < (gParams_0.voxelsPerPoint_0 * gParams_0.range_positions_0.y))
    {
        var fullIdx_0 : u32 = valIn_0[sortedIdx_0];
        var keyLow_0 : u32 = keyLowIn_0[fullIdx_0];
        var threadIdx1D_0 : u32 = (keyLow_0 & (u32(4194303)));
        var _S31 : bool;
        if(blockIdxCmp_0 == keyIn_0[sortedIdx_0])
        {
            _S31 = threadIdx1DCmp_0 == threadIdx1D_0;
        }
        else
        {
            _S31 = false;
        }
        if(_S31)
        {
            var pointIdx_0 : u32 = fullIdx_0 / gParams_0.voxelsPerPoint_0;
            var weight_0 : f32 = f32((((keyLow_0 >> (u32(22)))) & (u32(1023)))) * 0.00097751710563898f;
            var targetValue_0 : vec4<f32> = gParams_0.defaultTargetValue_0;
            var coupleRate_0 : vec4<f32> = gParams_0.defaultCoupleRate_0;
            if((gParams_0.isVelocity_0) != u32(0))
            {
                if(pointIdx_0 < (gParams_0.range_coupleRateVelocities_0.y))
                {
                    var velCoupleRate_0 : f32 = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateVelocities_0.x + pointIdx_0])));
                    coupleRate_0[i32(0)] = velCoupleRate_0;
                    coupleRate_0[i32(1)] = velCoupleRate_0;
                    coupleRate_0[i32(2)] = velCoupleRate_0;
                }
                if(pointIdx_0 < (gParams_0.range_coupleRateDivergences_0.y))
                {
                    coupleRate_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateDivergences_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_velocities_0.y))
                {
                    var _S32 : u32 = u32(3) * pointIdx_0;
                    targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S32])));
                    targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S32 + u32(1)])));
                    targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S32 + u32(2)])));
                }
                if(pointIdx_0 < (gParams_0.range_divergences_0.y))
                {
                    targetValue_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_divergences_0.x + pointIdx_0])));
                }
                if((gParams_0.velocityIsWorldSpace_0) == u32(0))
                {
                    var _S33 : vec3<f32> = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vec4<f32>(targetValue_0.xyz, 0.0f)))).xyz;
                    targetValue_0.x = _S33.x;
                    targetValue_0.y = _S33.y;
                    targetValue_0.z = _S33.z;
                }
            }
            else
            {
                if(pointIdx_0 < (gParams_0.range_coupleRateTemperatures_0.y))
                {
                    coupleRate_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateTemperatures_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_coupleRateFuels_0.y))
                {
                    coupleRate_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateFuels_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_coupleRateBurns_0.y))
                {
                    coupleRate_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateBurns_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_coupleRateSmokes_0.y))
                {
                    coupleRate_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateSmokes_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_temperatures_0.y))
                {
                    targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_temperatures_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_fuels_0.y))
                {
                    targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_fuels_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_burns_0.y))
                {
                    targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_burns_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_smokes_0.y))
                {
                    targetValue_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_smokes_0.x + pointIdx_0])));
                }
                if(pointIdx_0 < (gParams_0.range_colors_0.y))
                {
                    var _S34 : u32 = u32(3) * pointIdx_0;
                    targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S34])));
                    targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S34 + u32(1)])));
                    targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S34 + u32(2)])));
                }
                if((gParams_0.needsSrgbConversion_0) != u32(0))
                {
                    var _S35 : vec3<f32> = srgb_to_linear_0(targetValue_0.xyz);
                    targetValue_0.x = _S35.x;
                    targetValue_0.y = _S35.y;
                    targetValue_0.z = _S35.z;
                }
            }
            var _S36 : vec4<f32> = targetValue_0 * gParams_0.targetValueScale_0;
            targetValue_0 = _S36;
            var _S37 : vec4<f32> = vec4<f32>(weight_0);
            targetValueSum_1 = _S37 * _S36;
            coupleRateSum_1 = _S37 * (_S37 * coupleRate_0);
            weightSum_1 = weight_0;
        }
    }
    emitterPointReduce_0(sthreadIdx_1, &(targetValueSum_1), &(coupleRateSum_1), &(weightSum_1));
    if(sthreadIdx_1 < u32(1))
    {
        var reduceIdx1_0 : u32 = (sortedIdx_0 >> (u32(7)));
        reduceTarget1Out_0[reduceIdx1_0] = targetValueSum_1;
        reduceCouple1Out_0[reduceIdx1_0] = coupleRateSum_1;
        reduceWeight1Out_0[reduceIdx1_0] = weightSum_1;
        key1Out_0[reduceIdx1_0] = vec2<u32>(blockIdxCmp_0, threadIdx1DCmp_0);
    }
    return;
}

