// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct EmitterBoxCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) instanceCount_0 : u32,
    @align(4) deltaTime_0 : f32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterBoxCS_Params_std140_0;
@binding(4) @group(0) var<storage, read> gBlockIdx_0 : array<u32>;

@binding(7) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(5) @group(0) var<storage, read> gRange_0 : array<vec2<u32>>;

@binding(6) @group(0) var<storage, read> gInstanceId_0 : array<u32>;

struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterBoxCS_InstanceParams_std430_0
{
    @align(16) targetValue_0 : vec4<f32>,
    @align(16) coupleRate_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) layerAndLevel_0 : i32,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) localToWorldOld_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) halfSize_0 : vec3<f32>,
    @align(4) enabled_0 : u32,
    @align(16) position_0 : vec3<f32>,
    @align(4) clippingPlaneCountCount_0 : u32,
    @align(16) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(8) multisample_0 : u32,
    @align(4) clippingPlaneCount_0 : u32,
    @align(16) clippingPlanesOffset_0 : u32,
    @align(4) clippingPlaneCountsOffset_0 : u32,
    @align(8) pad1_2 : f32,
    @align(4) pad2_0 : f32,
};

@binding(1) @group(0) var<storage, read> gInstanceParams_0 : array<EmitterBoxCS_InstanceParams_std430_0>;

@binding(2) @group(0) var<storage, read> gPlanes_0 : array<vec4<f32>>;

@binding(3) @group(0) var<storage, read> gPlaneCounts_0 : array<u32>;

@binding(8) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(9) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd430_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn computeCoverage_0( instanceIdx_0 : u32,  worldPos_0 : vec3<f32>,  halfSize_1 : vec3<f32>) -> f32
{
    var localPos_0 : vec4<f32> = (((unpackStorage_0(gInstanceParams_0[instanceIdx_0].worldToLocal_0)) * (vec4<f32>(worldPos_0, 1.0f))));
    var localPosTranslated_0 : vec3<f32> = localPos_0.xyz - gInstanceParams_0[instanceIdx_0].position_0;
    var inBox_0 : bool;
    if((abs(localPosTranslated_0.x)) < (gInstanceParams_0[instanceIdx_0].halfSize_0.x))
    {
        inBox_0 = (abs(localPosTranslated_0.y)) < (gInstanceParams_0[instanceIdx_0].halfSize_0.y);
    }
    else
    {
        inBox_0 = false;
    }
    if(inBox_0)
    {
        inBox_0 = (abs(localPosTranslated_0.z)) < (gInstanceParams_0[instanceIdx_0].halfSize_0.z);
    }
    else
    {
        inBox_0 = false;
    }
    if(inBox_0)
    {
        var inConvex_0 : bool;
        if((gInstanceParams_0[instanceIdx_0].clippingPlaneCountCount_0) == u32(0))
        {
            inConvex_0 = (gInstanceParams_0[instanceIdx_0].clippingPlaneCount_0) == u32(0);
        }
        else
        {
            inConvex_0 = false;
        }
        var inConvexLocal_0 : bool;
        if((gInstanceParams_0[instanceIdx_0].clippingPlaneCountCount_0) == u32(0))
        {
            inConvexLocal_0 = (gInstanceParams_0[instanceIdx_0].clippingPlaneCount_0) != u32(0);
        }
        else
        {
            inConvexLocal_0 = false;
        }
        var planeBaseIdx_0 : u32;
        if(inConvexLocal_0)
        {
            var _S6 : u32 = gInstanceParams_0[instanceIdx_0].clippingPlaneCount_0;
            planeBaseIdx_0 = u32(0);
            for(;;)
            {
                if(planeBaseIdx_0 < _S6)
                {
                }
                else
                {
                    inConvexLocal_0 = true;
                    break;
                }
                if((dot(localPos_0, gPlanes_0[gInstanceParams_0[instanceIdx_0].clippingPlanesOffset_0 + planeBaseIdx_0])) > 0.0f)
                {
                    inConvexLocal_0 = false;
                    break;
                }
                planeBaseIdx_0 = planeBaseIdx_0 + u32(1);
            }
            if(inConvexLocal_0)
            {
                inConvex_0 = true;
            }
            else
            {
            }
            planeBaseIdx_0 = _S6;
        }
        else
        {
            planeBaseIdx_0 = u32(0);
        }
        var planeCountIdx_0 : u32 = u32(0);
        for(;;)
        {
            if(planeCountIdx_0 < (gInstanceParams_0[instanceIdx_0].clippingPlaneCountCount_0))
            {
            }
            else
            {
                break;
            }
            var planeCount_0 : u32 = gPlaneCounts_0[gInstanceParams_0[instanceIdx_0].clippingPlaneCountsOffset_0 + planeCountIdx_0];
            var planeLocalIdx_0 : u32 = u32(0);
            for(;;)
            {
                if(planeLocalIdx_0 < planeCount_0)
                {
                }
                else
                {
                    inConvexLocal_0 = true;
                    break;
                }
                if((dot(localPos_0, gPlanes_0[gInstanceParams_0[instanceIdx_0].clippingPlanesOffset_0 + planeBaseIdx_0 + planeLocalIdx_0])) > 0.0f)
                {
                    inConvexLocal_0 = false;
                    break;
                }
                planeLocalIdx_0 = planeLocalIdx_0 + u32(1);
            }
            if(inConvexLocal_0)
            {
                inConvex_0 = true;
                break;
            }
            var planeBaseIdx_1 : u32 = planeBaseIdx_0 + planeCount_0;
            planeCountIdx_0 = planeCountIdx_0 + u32(1);
            planeBaseIdx_0 = planeBaseIdx_1;
        }
        if(inBox_0)
        {
            inBox_0 = inConvex_0;
        }
        else
        {
            inBox_0 = false;
        }
    }
    else
    {
    }
    var _S7 : f32;
    if(inBox_0)
    {
        _S7 = 1.0f;
    }
    else
    {
        _S7 = 0.0f;
    }
    return _S7;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S8 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S8, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S8 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S9 : i32 = threadIdx_1.x;
    if(_S9 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S9 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S10 : i32 = threadIdx_1.y;
    if(_S10 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S10 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S11 : i32 = threadIdx_1.z;
    if(_S11 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S11 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_1 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_1) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowBlockIdxToLocation_0( _S12 : NvFlowSparseLevelParams_0,  _S13 : u32,  _S14 : ptr<function, vec4<i32>>) -> bool
{
    var _S15 : bool = _S13 < (_S12.numLocations_0);
    if(_S15)
    {
        var locationIdx_0 : u32 = ((_S13 << (u32(2)))) + _S12.locationOffset_0;
        (*_S14)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S14)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S14)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S14)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S14)[i32(0)] = i32(1073741824);
        (*_S14)[i32(1)] = i32(1073741824);
        (*_S14)[i32(2)] = i32(1073741824);
        (*_S14)[i32(3)] = i32(1073741824);
    }
    return _S15;
}

fn NvFlowLocalVirtualToReal_0( _S16 : NvFlowSparseLevelParams_0,  _S17 : u32,  _S18 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S18 >> (vec3<u32>(vec3<i32>(_S16.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S18, gTable_0[NvFlowNeighborToIdx_0(_S17, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S16.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S19 : texture_3d<f32>,  _S20 : NvFlowSparseLevelParams_0,  _S21 : u32,  _S22 : vec3<i32>) -> vec4<f32>
{
    var _S23 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S20, _S21, _S22);
    var _S24 : vec4<f32>;
    if(bool(_S23.w))
    {
        var _S25 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S23.xyz), u32(0)));
        _S24 = (textureLoad((_S19), ((_S25)).xyz, ((_S25)).w));
    }
    else
    {
        _S24 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S24;
}

fn NvFlowLocalWriteNeighbor4f_0( _S26 : NvFlowSparseLevelParams_0,  _S27 : i32,  _S28 : i32,  _S29 : i32,  _S30 : u32,  _S31 : vec3<i32>,  _S32 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S31, gTable_0[NvFlowNeighborToIdx_0(_S30, _S27, _S28, _S29) + _S26.blockLevelOffsetLocal_0], _S27, _S28, _S29);
    var _S33 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S34 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S34 = _S32;
    }
    else
    {
        _S34 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S33), (_S34));
    return;
}

fn NvFlowLocalWrite4f_0( _S35 : NvFlowSparseLevelParams_0,  _S36 : u32,  _S37 : vec3<i32>,  _S38 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S35, _S37);
    NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), i32(0), i32(0), _S36, _S37, _S38);
    var _S39 : i32 = neighbor_2.x;
    var _S40 : bool = _S39 != i32(0);
    if(_S40)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, i32(0), i32(0), _S36, _S37, _S38);
    }
    var _S41 : i32 = neighbor_2.y;
    var _S42 : bool = _S41 != i32(0);
    if(_S42)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), _S41, i32(0), _S36, _S37, _S38);
    }
    var _S43 : i32 = neighbor_2.z;
    var _S44 : bool = _S43 != i32(0);
    if(_S44)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), i32(0), _S43, _S36, _S37, _S38);
    }
    var _S45 : bool;
    if(_S40)
    {
        _S45 = _S42;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, _S41, i32(0), _S36, _S37, _S38);
    }
    if(_S42)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), _S41, _S43, _S36, _S37, _S38);
    }
    if(_S40)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, i32(0), _S43, _S36, _S37, _S38);
    }
    if(_S40)
    {
        _S45 = _S42;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, _S41, _S43, _S36, _S37, _S38);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var listIdx_0 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var blockIdx_1 : u32 = gBlockIdx_0[listIdx_0];
    var location_0 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
    var _S46 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_1(gParams_0.table_0), blockIdx_1, &(location_0));
    if(!_S46)
    {
        return;
    }
    var range_0 : vec2<u32> = gRange_0[listIdx_0];
    var _S47 : vec3<f32> = vec3<f32>((((location_0.xyz) << ((gParams_0.table_0.blockDimBits_0)))) + threadIdx_3) + vec3<f32>(0.5f, 0.5f, 0.5f);
    const _S48 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var _S49 : u32 = range_0.x;
    var _S50 : u32 = range_0.y;
    const _S51 : vec3<f32> = vec3<f32>(-0.25f, -0.25f, -0.25f);
    const _S52 : vec3<f32> = vec3<f32>(0.25f, -0.25f, -0.25f);
    const _S53 : vec3<f32> = vec3<f32>(-0.25f, 0.25f, -0.25f);
    const _S54 : vec3<f32> = vec3<f32>(0.25f, 0.25f, -0.25f);
    const _S55 : vec3<f32> = vec3<f32>(-0.25f, -0.25f, 0.25f);
    const _S56 : vec3<f32> = vec3<f32>(0.25f, -0.25f, 0.25f);
    const _S57 : vec3<f32> = vec3<f32>(-0.25f, 0.25f, 0.25f);
    const _S58 : vec3<f32> = vec3<f32>(0.25f, 0.25f, 0.25f);
    const _S59 : vec4<f32> = vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f);
    var valueFetched_0 : bool = false;
    var rangeIdx_0 : u32 = _S49;
    var value_0 : vec4<f32> = _S48;
    for(;;)
    {
        if(rangeIdx_0 < _S50)
        {
        }
        else
        {
            break;
        }
        var instanceIdx_1 : u32 = gInstanceId_0[rangeIdx_0];
        var _S60 : bool;
        if((gInstanceParams_0[instanceIdx_1].enabled_0) != u32(0))
        {
            _S60 = (gInstanceParams_0[instanceIdx_1].layerAndLevel_0) == (location_0.w);
        }
        else
        {
            _S60 = false;
        }
        var valueFetched_1 : bool;
        var value_1 : vec4<f32>;
        if(_S60)
        {
            var worldPos_1 : vec3<f32> = gInstanceParams_0[instanceIdx_1].vidxToWorld_0 * _S47;
            var coverage_0 : f32;
            if((gInstanceParams_0[instanceIdx_1].multisample_0) != u32(0))
            {
                coverage_0 = 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S51 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S52 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S53 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S54 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S55 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S56 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S57 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0) + 0.125f * computeCoverage_0(instanceIdx_1, worldPos_1 + _S58 * gInstanceParams_0[instanceIdx_1].vidxToWorld_0, gInstanceParams_0[instanceIdx_1].halfSize_0);
            }
            else
            {
                coverage_0 = computeCoverage_0(instanceIdx_1, worldPos_1, gInstanceParams_0[instanceIdx_1].halfSize_0);
            }
            if(coverage_0 > 0.0f)
            {
                if(!valueFetched_0)
                {
                    var _S61 : vec4<f32> = NvFlowLocalRead4f_0(valueIn_0, unpackStorage_1(gParams_0.table_0), blockIdx_1, threadIdx_3);
                    valueFetched_1 = true;
                    value_1 = _S61;
                }
                else
                {
                    valueFetched_1 = valueFetched_0;
                    value_1 = value_0;
                }
                var valueRate_0 : vec4<f32> = min(_S59, max(_S48, vec4<f32>(gParams_0.deltaTime_0) * gInstanceParams_0[instanceIdx_1].coupleRate_0 * vec4<f32>(coverage_0)));
                var targetValue_1 : vec4<f32> = gInstanceParams_0[instanceIdx_1].targetValue_0;
                if((gInstanceParams_0[instanceIdx_1].physicsVelocityScale_0) != 0.0f)
                {
                    var _S62 : vec3<f32> = targetValue_1.xyz + vec3<f32>(gInstanceParams_0[instanceIdx_1].physicsVelocityScale_0) * ((worldPos_1 - (((unpackStorage_0(gInstanceParams_0[instanceIdx_1].localToWorldOld_0)) * ((((unpackStorage_0(gInstanceParams_0[instanceIdx_1].worldToLocal_0)) * (vec4<f32>(worldPos_1, 1.0f))))))).xyz) * vec3<f32>(gInstanceParams_0[instanceIdx_1].physicsDeltaTimeInv_0));
                    targetValue_1.x = _S62.x;
                    targetValue_1.y = _S62.y;
                    targetValue_1.z = _S62.z;
                }
                value_1 = value_1 + valueRate_0 * (targetValue_1 - value_1);
            }
            else
            {
                valueFetched_1 = valueFetched_0;
                value_1 = value_0;
            }
        }
        else
        {
            valueFetched_1 = valueFetched_0;
            value_1 = value_0;
        }
        var _S63 : u32 = rangeIdx_0 + u32(1);
        valueFetched_0 = valueFetched_1;
        rangeIdx_0 = _S63;
        value_0 = value_1;
    }
    if(valueFetched_0)
    {
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), blockIdx_1, threadIdx_3, value_0);
    }
    return;
}

