// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterPointCS_Params_std140_0
{
    @align(16) pointBlockIdxOffset_0 : u32,
    @align(4) reduce2BlockIdxOffset_0 : u32,
    @align(8) reduce3BlockIdxOffset_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableCoarse_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) layerAndLevel_0 : i32,
    @align(4) defaultAllocateMask_0 : u32,
    @align(8) allocateMaskCount_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_velocities_0 : vec2<u32>,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) anyStreamingClearEnabled_0 : u32,
    @align(16) reduceCount1_0 : u32,
    @align(4) reduceCount2_0 : u32,
    @align(8) reduceCount3_0 : u32,
    @align(4) enableInterpolation_0 : u32,
    @align(16) voxelsPerPoint_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterPointCS_Params_std140_0;
@binding(6) @group(0) var<storage, read> keyIn_0 : array<u32>;

@binding(7) @group(0) var<storage, read> valIn_0 : array<u32>;

@binding(5) @group(0) var<storage, read> keyLowIn_0 : array<u32>;

@binding(3) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

@binding(11) @group(0) var<storage, read> key1In_0 : array<vec2<u32>>;

@binding(8) @group(0) var<storage, read> scanTarget1In_0 : array<vec4<f32>>;

@binding(9) @group(0) var<storage, read> scanCouple1In_0 : array<vec4<f32>>;

@binding(10) @group(0) var<storage, read> scanWeight1In_0 : array<f32>;

@binding(4) @group(0) var<storage, read> oldValueIn_0 : array<vec4<f32>>;

@binding(12) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(13) @group(0) var voxelWeightOut_0 : texture_storage_3d<r32float, write>;

struct EmitterPointCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) pad1_2 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterPointCS_SubStepParams_std140_0;
fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn srgb_to_linear1_0( v_0 : f32) -> f32
{
    var ret_0 : f32;
    if(v_0 <= 0.04044999927282333f)
    {
        ret_0 = v_0 * 0.07739938050508499f;
    }
    else
    {
        ret_0 = pow((v_0 + 0.05499999970197678f) * 0.94786733388900757f, 2.40000009536743164f);
    }
    return ret_0;
}

fn srgb_to_linear_0( c_0 : vec3<f32>) -> vec3<f32>
{
    return vec3<f32>(srgb_to_linear1_0(c_0.x), srgb_to_linear1_0(c_0.y), srgb_to_linear1_0(c_0.z));
}

var<workgroup> sBlockIdx_0 : array<u32, i32(128)>;

var<workgroup> sThreadIdx1D_0 : array<u32, i32(128)>;

var<workgroup> sTargetValueSum0_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum0_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum0_0 : array<f32, i32(128)>;

fn emitterPointScanAccum0_0( sthreadIdx_0 : u32,  targetValueSum_0 : ptr<function, vec4<f32>>,  coupleRateSum_0 : ptr<function, vec4<f32>>,  weightSum_0 : ptr<function, f32>,  offset_0 : u32)
{
    var _S4 : u32 = sthreadIdx_0 + offset_0;
    if(_S4 < u32(128))
    {
        var _S5 : bool;
        if((sBlockIdx_0[sthreadIdx_0]) == (sBlockIdx_0[_S4]))
        {
            _S5 = (sThreadIdx1D_0[sthreadIdx_0]) == (sThreadIdx1D_0[_S4]);
        }
        else
        {
            _S5 = false;
        }
        if(_S5)
        {
            (*targetValueSum_0) = (*targetValueSum_0) + sTargetValueSum0_0[_S4];
            (*coupleRateSum_0) = (*coupleRateSum_0) + sCoupleRateSum0_0[_S4];
            (*weightSum_0) = (*weightSum_0) + sWeightSum0_0[_S4];
        }
    }
    return;
}

var<workgroup> sTargetValueSum1_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum1_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum1_0 : array<f32, i32(128)>;

fn emitterPointScanAccum1_0( sthreadIdx_1 : u32,  targetValueSum_1 : ptr<function, vec4<f32>>,  coupleRateSum_1 : ptr<function, vec4<f32>>,  weightSum_1 : ptr<function, f32>,  offset_1 : u32)
{
    var _S6 : u32 = sthreadIdx_1 + offset_1;
    if(_S6 < u32(128))
    {
        var _S7 : bool;
        if((sBlockIdx_0[sthreadIdx_1]) == (sBlockIdx_0[_S6]))
        {
            _S7 = (sThreadIdx1D_0[sthreadIdx_1]) == (sThreadIdx1D_0[_S6]);
        }
        else
        {
            _S7 = false;
        }
        if(_S7)
        {
            (*targetValueSum_1) = (*targetValueSum_1) + sTargetValueSum1_0[_S6];
            (*coupleRateSum_1) = (*coupleRateSum_1) + sCoupleRateSum1_0[_S6];
            (*weightSum_1) = (*weightSum_1) + sWeightSum1_0[_S6];
        }
    }
    return;
}

var<workgroup> sTargetValueSumTotal_0 : vec4<f32>;

var<workgroup> sCoupleRateSumTotal_0 : vec4<f32>;

var<workgroup> sWeightSumTotal_0 : f32;

var<workgroup> sBlockIdxTotal_0 : u32;

var<workgroup> sThreadIdx1DTotal_0 : u32;

fn emitterPointScan_0( sthreadIdx_2 : u32,  targetValueSum_2 : ptr<function, vec4<f32>>,  coupleRateSum_2 : ptr<function, vec4<f32>>,  weightSum_2 : ptr<function, f32>,  blockIdx_0 : ptr<function, u32>,  threadIdx1D_0 : ptr<function, u32>)
{
    sBlockIdx_0[sthreadIdx_2] = (*blockIdx_0);
    sThreadIdx1D_0[sthreadIdx_2] = (*threadIdx1D_0);
    sTargetValueSum0_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum0_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum0_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(1));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(2));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(3));
    sTargetValueSum1_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum1_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum1_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(4));
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(8));
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(12));
    sTargetValueSum0_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum0_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum0_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(16));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(32));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(48));
    sTargetValueSum1_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum1_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum1_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(64));
    if(sthreadIdx_2 == u32(0))
    {
        sTargetValueSumTotal_0 = (*targetValueSum_2);
        sCoupleRateSumTotal_0 = (*coupleRateSum_2);
        sWeightSumTotal_0 = (*weightSum_2);
        sBlockIdxTotal_0 = (*blockIdx_0);
        sThreadIdx1DTotal_0 = (*threadIdx1D_0);
    }
    workgroupBarrier();
    return;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx_0 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S8 : i32 = threadIdx_0.x;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S8 == i32(tableParams_0.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S9 : i32 = threadIdx_0.y;
    if(_S9 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S9 == i32(tableParams_0.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S10 : i32 = threadIdx_0.z;
    if(_S10 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S10 == i32(tableParams_0.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_1 : vec3<i32>,  v_1 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_0 : vec4<i32> = vec4<i32>(((threadIdx_1.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_1.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_1.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_1) >> (u32(31)));
    ridx_0[i32(0)] = ridx_0[i32(0)] + ((mask_0 & (x_1)));
    ridx_0[i32(1)] = ridx_0[i32(1)] + ((mask_0 & (y_1)));
    ridx_0[i32(2)] = ridx_0[i32(2)] + ((mask_0 & (z_1)));
    return ridx_0;
}

fn NvFlowLocalWriteNeighbor4f_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : i32,  _S13 : i32,  _S14 : i32,  _S15 : u32,  _S16 : vec3<i32>,  _S17 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S16, gTable_0[NvFlowNeighborToIdx_0(_S15, _S12, _S13, _S14) + _S11.blockLevelOffsetLocal_0], _S12, _S13, _S14);
    var _S18 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S19 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S19 = _S17;
    }
    else
    {
        _S19 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S18), (_S19));
    return;
}

fn NvFlowLocalWrite4f_0( _S20 : NvFlowSparseLevelParams_0,  _S21 : u32,  _S22 : vec3<i32>,  _S23 : vec4<f32>)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S20, _S22);
    NvFlowLocalWriteNeighbor4f_0(_S20, i32(0), i32(0), i32(0), _S21, _S22, _S23);
    var _S24 : i32 = neighbor_1.x;
    var _S25 : bool = _S24 != i32(0);
    if(_S25)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, _S24, i32(0), i32(0), _S21, _S22, _S23);
    }
    var _S26 : i32 = neighbor_1.y;
    var _S27 : bool = _S26 != i32(0);
    if(_S27)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, i32(0), _S26, i32(0), _S21, _S22, _S23);
    }
    var _S28 : i32 = neighbor_1.z;
    var _S29 : bool = _S28 != i32(0);
    if(_S29)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, i32(0), i32(0), _S28, _S21, _S22, _S23);
    }
    var _S30 : bool;
    if(_S25)
    {
        _S30 = _S27;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, _S24, _S26, i32(0), _S21, _S22, _S23);
    }
    if(_S27)
    {
        _S30 = _S29;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, i32(0), _S26, _S28, _S21, _S22, _S23);
    }
    if(_S25)
    {
        _S30 = _S29;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, _S24, i32(0), _S28, _S21, _S22, _S23);
    }
    if(_S25)
    {
        _S30 = _S27;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        _S30 = _S29;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        NvFlowLocalWriteNeighbor4f_0(_S20, _S24, _S26, _S28, _S21, _S22, _S23);
    }
    return;
}

fn NvFlowLocalWriteNeighbor1f_0( _S31 : NvFlowSparseLevelParams_0,  _S32 : i32,  _S33 : i32,  _S34 : i32,  _S35 : u32,  _S36 : vec3<i32>,  _S37 : f32)
{
    var index_1 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S36, gTable_0[NvFlowNeighborToIdx_0(_S35, _S32, _S33, _S34) + _S31.blockLevelOffsetLocal_0], _S32, _S33, _S34);
    var _S38 : vec3<u32> = vec3<u32>(index_1.xyz);
    var _S39 : f32;
    if(bool(index_1.w))
    {
        _S39 = _S37;
    }
    else
    {
        _S39 = 0.0f;
    }
    textureStore((voxelWeightOut_0), (_S38), vec4<f32>((_S39), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S40 : NvFlowSparseLevelParams_0,  _S41 : u32,  _S42 : vec3<i32>,  _S43 : f32)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S40, _S42);
    NvFlowLocalWriteNeighbor1f_0(_S40, i32(0), i32(0), i32(0), _S41, _S42, _S43);
    var _S44 : i32 = neighbor_2.x;
    var _S45 : bool = _S44 != i32(0);
    if(_S45)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, _S44, i32(0), i32(0), _S41, _S42, _S43);
    }
    var _S46 : i32 = neighbor_2.y;
    var _S47 : bool = _S46 != i32(0);
    if(_S47)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, i32(0), _S46, i32(0), _S41, _S42, _S43);
    }
    var _S48 : i32 = neighbor_2.z;
    var _S49 : bool = _S48 != i32(0);
    if(_S49)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, i32(0), i32(0), _S48, _S41, _S42, _S43);
    }
    var _S50 : bool;
    if(_S45)
    {
        _S50 = _S47;
    }
    else
    {
        _S50 = false;
    }
    if(_S50)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, _S44, _S46, i32(0), _S41, _S42, _S43);
    }
    if(_S47)
    {
        _S50 = _S49;
    }
    else
    {
        _S50 = false;
    }
    if(_S50)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, i32(0), _S46, _S48, _S41, _S42, _S43);
    }
    if(_S45)
    {
        _S50 = _S49;
    }
    else
    {
        _S50 = false;
    }
    if(_S50)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, _S44, i32(0), _S48, _S41, _S42, _S43);
    }
    if(_S45)
    {
        _S50 = _S47;
    }
    else
    {
        _S50 = false;
    }
    if(_S50)
    {
        _S50 = _S49;
    }
    else
    {
        _S50 = false;
    }
    if(_S50)
    {
        NvFlowLocalWriteNeighbor1f_0(_S40, _S44, _S46, _S48, _S41, _S42, _S43);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var sortedIdx_0 : u32 = dispatchThreadID_0.x + (((gParams_0.pointBlockIdxOffset_0) << (u32(7))));
    var sthreadIdx_3 : u32 = (sortedIdx_0 & (u32(127)));
    var blockIdx_2 : u32 = u32(4294967295);
    var threadIdx1D_1 : u32 = u32(4294967295);
    const _S51 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var targetValueSum_3 : vec4<f32> = _S51;
    var coupleRateSum_3 : vec4<f32> = _S51;
    var weightSum_3 : f32 = 0.0f;
    var fullIdx_0 : u32;
    if(sortedIdx_0 < (gParams_0.voxelsPerPoint_0 * gParams_0.range_positions_0.y))
    {
        blockIdx_2 = keyIn_0[sortedIdx_0];
        var fullIdx_1 : u32 = valIn_0[sortedIdx_0];
        var keyLow_0 : u32 = keyLowIn_0[fullIdx_1];
        threadIdx1D_1 = (keyLow_0 & (u32(4194303)));
        var pointIdx_0 : u32 = fullIdx_1 / gParams_0.voxelsPerPoint_0;
        var weight_0 : f32 = f32((((keyLow_0 >> (u32(22)))) & (u32(1023)))) * 0.00097751710563898f;
        var targetValue_0 : vec4<f32> = gParams_0.defaultTargetValue_0;
        var coupleRate_0 : vec4<f32> = gParams_0.defaultCoupleRate_0;
        if((gParams_0.isVelocity_0) != u32(0))
        {
            if(pointIdx_0 < (gParams_0.range_coupleRateVelocities_0.y))
            {
                var velCoupleRate_0 : f32 = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateVelocities_0.x + pointIdx_0])));
                coupleRate_0[i32(0)] = velCoupleRate_0;
                coupleRate_0[i32(1)] = velCoupleRate_0;
                coupleRate_0[i32(2)] = velCoupleRate_0;
            }
            if(pointIdx_0 < (gParams_0.range_coupleRateDivergences_0.y))
            {
                coupleRate_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateDivergences_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_velocities_0.y))
            {
                var _S52 : u32 = u32(3) * pointIdx_0;
                targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S52])));
                targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S52 + u32(1)])));
                targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S52 + u32(2)])));
            }
            if(pointIdx_0 < (gParams_0.range_divergences_0.y))
            {
                targetValue_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_divergences_0.x + pointIdx_0])));
            }
            if((gParams_0.velocityIsWorldSpace_0) == u32(0))
            {
                var _S53 : vec3<f32> = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vec4<f32>(targetValue_0.xyz, 0.0f)))).xyz;
                targetValue_0.x = _S53.x;
                targetValue_0.y = _S53.y;
                targetValue_0.z = _S53.z;
            }
        }
        else
        {
            if(pointIdx_0 < (gParams_0.range_coupleRateTemperatures_0.y))
            {
                coupleRate_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateTemperatures_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_coupleRateFuels_0.y))
            {
                coupleRate_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateFuels_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_coupleRateBurns_0.y))
            {
                coupleRate_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateBurns_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_coupleRateSmokes_0.y))
            {
                coupleRate_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateSmokes_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_temperatures_0.y))
            {
                targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_temperatures_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_fuels_0.y))
            {
                targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_fuels_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_burns_0.y))
            {
                targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_burns_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_smokes_0.y))
            {
                targetValue_0[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_smokes_0.x + pointIdx_0])));
            }
            if(pointIdx_0 < (gParams_0.range_colors_0.y))
            {
                var _S54 : u32 = u32(3) * pointIdx_0;
                targetValue_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S54])));
                targetValue_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S54 + u32(1)])));
                targetValue_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S54 + u32(2)])));
            }
            if((gParams_0.needsSrgbConversion_0) != u32(0))
            {
                var _S55 : vec3<f32> = srgb_to_linear_0(targetValue_0.xyz);
                targetValue_0.x = _S55.x;
                targetValue_0.y = _S55.y;
                targetValue_0.z = _S55.z;
            }
        }
        targetValue_0 = targetValue_0 * gParams_0.targetValueScale_0;
        var coupleRateWeight_0 : f32;
        if((gParams_0.enableInterpolation_0) == u32(0))
        {
            coupleRateWeight_0 = weight_0;
        }
        else
        {
            coupleRateWeight_0 = 1.0f;
        }
        var _S56 : vec4<f32> = vec4<f32>(weight_0);
        targetValueSum_3 = _S56 * targetValue_0;
        coupleRateSum_3 = vec4<f32>(coupleRateWeight_0) * (_S56 * coupleRate_0);
        weightSum_3 = weight_0;
        fullIdx_0 = fullIdx_1;
    }
    else
    {
        fullIdx_0 = u32(4294967295);
    }
    emitterPointScan_0(sthreadIdx_3, &(targetValueSum_3), &(coupleRateSum_3), &(weightSum_3), &(blockIdx_2), &(threadIdx1D_1));
    var reduceIdx1_0 : u32 = ((sortedIdx_0 >> (u32(7)))) + u32(1);
    var _S57 : bool;
    if(reduceIdx1_0 < (gParams_0.reduceCount1_0))
    {
        var key1_0 : vec2<u32> = key1In_0[reduceIdx1_0];
        var threadIdx1D1_0 : u32 = key1_0.y;
        if((key1_0.x) == blockIdx_2)
        {
            _S57 = threadIdx1D1_0 == threadIdx1D_1;
        }
        else
        {
            _S57 = false;
        }
        if(_S57)
        {
            targetValueSum_3 = targetValueSum_3 + scanTarget1In_0[reduceIdx1_0];
            coupleRateSum_3 = coupleRateSum_3 + scanCouple1In_0[reduceIdx1_0];
            weightSum_3 = weightSum_3 + scanWeight1In_0[reduceIdx1_0];
        }
    }
    if(blockIdx_2 == u32(4294967295))
    {
        return;
    }
    if(fullIdx_0 >= (gParams_0.voxelsPerPoint_0 * gParams_0.range_positions_0.y))
    {
        _S57 = true;
    }
    else
    {
        _S57 = sortedIdx_0 >= (gParams_0.voxelsPerPoint_0 * gParams_0.range_positions_0.y);
    }
    if(_S57)
    {
        return;
    }
    if(sortedIdx_0 > u32(0))
    {
        var _S58 : u32 = sortedIdx_0 - u32(1);
        var cmpThreadIdx1D_0 : u32 = (keyLowIn_0[valIn_0[_S58]] & (u32(4194303)));
        if(blockIdx_2 == keyIn_0[_S58])
        {
            _S57 = threadIdx1D_1 == cmpThreadIdx1D_0;
        }
        else
        {
            _S57 = false;
        }
        if(_S57)
        {
            return;
        }
    }
    var threadIdx_2 : vec3<i32> = vec3<i32>(i32((threadIdx1D_1 & ((gParams_0.table_0.blockDimLessOne_0.x)))), i32((((threadIdx1D_1 >> ((gParams_0.table_0.blockDimBits_0.x)))) & ((gParams_0.table_0.blockDimLessOne_0.y)))), i32((((threadIdx1D_1 >> ((gParams_0.table_0.blockDimBits_0.x + gParams_0.table_0.blockDimBits_0.y)))) & ((gParams_0.table_0.blockDimLessOne_0.z)))));
    if(weightSum_3 > 0.0f)
    {
        var _S59 : vec4<f32> = vec4<f32>((1.0f / weightSum_3));
        var _S60 : vec4<f32> = targetValueSum_3 * _S59;
        targetValueSum_3 = _S60;
        var _S61 : vec4<f32> = coupleRateSum_3 * _S59;
        coupleRateSum_3 = _S61;
        var valueRate_0 : vec4<f32> = min(vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f), max(_S51, vec4<f32>(gParams_0.deltaTime_0) * _S61));
        var value_0 : vec4<f32> = oldValueIn_0[fullIdx_0];
        var value_1 : vec4<f32> = value_0 + valueRate_0 * (_S60 - value_0);
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), blockIdx_2, threadIdx_2, value_1 + valueRate_0 * (_S60 - value_1));
        NvFlowLocalWrite1f_0(unpackStorage_1(gParams_0.table_0), blockIdx_2, threadIdx_2, 1.0f);
    }
    return;
}

