// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterPointCS_Params_std140_0
{
    @align(16) pointBlockIdxOffset_0 : u32,
    @align(4) reduce2BlockIdxOffset_0 : u32,
    @align(8) reduce3BlockIdxOffset_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) tableCoarse_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) layerAndLevel_0 : i32,
    @align(4) defaultAllocateMask_0 : u32,
    @align(8) allocateMaskCount_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_velocities_0 : vec2<u32>,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
    @align(16) velocityToDensityBlockScale_0 : vec3<f32>,
    @align(4) anyStreamingClearEnabled_0 : u32,
    @align(16) reduceCount1_0 : u32,
    @align(4) reduceCount2_0 : u32,
    @align(8) reduceCount3_0 : u32,
    @align(4) enableInterpolation_0 : u32,
    @align(16) voxelsPerPoint_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterPointCS_Params_std140_0;
@binding(5) @group(0) var<storage, read> key2In_0 : array<vec2<u32>>;

@binding(2) @group(0) var<storage, read> reduceTarget2In_0 : array<vec4<f32>>;

@binding(3) @group(0) var<storage, read> reduceCouple2In_0 : array<vec4<f32>>;

@binding(4) @group(0) var<storage, read> reduceWeight2In_0 : array<f32>;

@binding(9) @group(0) var<storage, read> key3In_0 : array<vec2<u32>>;

@binding(6) @group(0) var<storage, read> scanTarget3In_0 : array<vec4<f32>>;

@binding(7) @group(0) var<storage, read> scanCouple3In_0 : array<vec4<f32>>;

@binding(8) @group(0) var<storage, read> scanWeight3In_0 : array<f32>;

@binding(10) @group(0) var<storage, read_write> scanTarget2Out_0 : array<vec4<f32>>;

@binding(11) @group(0) var<storage, read_write> scanCouple2Out_0 : array<vec4<f32>>;

@binding(12) @group(0) var<storage, read_write> scanWeight2Out_0 : array<f32>;

struct EmitterPointCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) pad1_2 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterPointCS_SubStepParams_std140_0;
var<workgroup> sBlockIdx_0 : array<u32, i32(128)>;

var<workgroup> sThreadIdx1D_0 : array<u32, i32(128)>;

var<workgroup> sTargetValueSum0_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum0_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum0_0 : array<f32, i32(128)>;

fn emitterPointScanAccum0_0( sthreadIdx_0 : u32,  targetValueSum_0 : ptr<function, vec4<f32>>,  coupleRateSum_0 : ptr<function, vec4<f32>>,  weightSum_0 : ptr<function, f32>,  offset_0 : u32)
{
    var _S1 : u32 = sthreadIdx_0 + offset_0;
    if(_S1 < u32(128))
    {
        var _S2 : bool;
        if((sBlockIdx_0[sthreadIdx_0]) == (sBlockIdx_0[_S1]))
        {
            _S2 = (sThreadIdx1D_0[sthreadIdx_0]) == (sThreadIdx1D_0[_S1]);
        }
        else
        {
            _S2 = false;
        }
        if(_S2)
        {
            (*targetValueSum_0) = (*targetValueSum_0) + sTargetValueSum0_0[_S1];
            (*coupleRateSum_0) = (*coupleRateSum_0) + sCoupleRateSum0_0[_S1];
            (*weightSum_0) = (*weightSum_0) + sWeightSum0_0[_S1];
        }
    }
    return;
}

var<workgroup> sTargetValueSum1_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sCoupleRateSum1_0 : array<vec4<f32>, i32(128)>;

var<workgroup> sWeightSum1_0 : array<f32, i32(128)>;

fn emitterPointScanAccum1_0( sthreadIdx_1 : u32,  targetValueSum_1 : ptr<function, vec4<f32>>,  coupleRateSum_1 : ptr<function, vec4<f32>>,  weightSum_1 : ptr<function, f32>,  offset_1 : u32)
{
    var _S3 : u32 = sthreadIdx_1 + offset_1;
    if(_S3 < u32(128))
    {
        var _S4 : bool;
        if((sBlockIdx_0[sthreadIdx_1]) == (sBlockIdx_0[_S3]))
        {
            _S4 = (sThreadIdx1D_0[sthreadIdx_1]) == (sThreadIdx1D_0[_S3]);
        }
        else
        {
            _S4 = false;
        }
        if(_S4)
        {
            (*targetValueSum_1) = (*targetValueSum_1) + sTargetValueSum1_0[_S3];
            (*coupleRateSum_1) = (*coupleRateSum_1) + sCoupleRateSum1_0[_S3];
            (*weightSum_1) = (*weightSum_1) + sWeightSum1_0[_S3];
        }
    }
    return;
}

var<workgroup> sTargetValueSumTotal_0 : vec4<f32>;

var<workgroup> sCoupleRateSumTotal_0 : vec4<f32>;

var<workgroup> sWeightSumTotal_0 : f32;

var<workgroup> sBlockIdxTotal_0 : u32;

var<workgroup> sThreadIdx1DTotal_0 : u32;

fn emitterPointScan_0( sthreadIdx_2 : u32,  targetValueSum_2 : ptr<function, vec4<f32>>,  coupleRateSum_2 : ptr<function, vec4<f32>>,  weightSum_2 : ptr<function, f32>,  blockIdx_0 : ptr<function, u32>,  threadIdx1D_0 : ptr<function, u32>)
{
    sBlockIdx_0[sthreadIdx_2] = (*blockIdx_0);
    sThreadIdx1D_0[sthreadIdx_2] = (*threadIdx1D_0);
    sTargetValueSum0_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum0_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum0_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(1));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(2));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(3));
    sTargetValueSum1_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum1_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum1_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(4));
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(8));
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(12));
    sTargetValueSum0_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum0_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum0_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(16));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(32));
    emitterPointScanAccum0_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(48));
    sTargetValueSum1_0[sthreadIdx_2] = (*targetValueSum_2);
    sCoupleRateSum1_0[sthreadIdx_2] = (*coupleRateSum_2);
    sWeightSum1_0[sthreadIdx_2] = (*weightSum_2);
    workgroupBarrier();
    emitterPointScanAccum1_0(sthreadIdx_2, &((*targetValueSum_2)), &((*coupleRateSum_2)), &((*weightSum_2)), u32(64));
    if(sthreadIdx_2 == u32(0))
    {
        sTargetValueSumTotal_0 = (*targetValueSum_2);
        sCoupleRateSumTotal_0 = (*coupleRateSum_2);
        sWeightSumTotal_0 = (*weightSum_2);
        sBlockIdxTotal_0 = (*blockIdx_0);
        sThreadIdx1DTotal_0 = (*threadIdx1D_0);
    }
    workgroupBarrier();
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var reduceIdx2_0 : u32 = dispatchThreadID_0.x + (((gParams_0.reduce3BlockIdxOffset_0) << (u32(7))));
    var sthreadIdx_3 : u32 = (reduceIdx2_0 & (u32(127)));
    const _S5 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var targetValueSum_3 : vec4<f32> = _S5;
    var coupleRateSum_3 : vec4<f32> = _S5;
    var weightSum_3 : f32 = 0.0f;
    var blockIdx_1 : u32 = u32(4294967295);
    var threadIdx1D_1 : u32 = u32(4294967295);
    if(reduceIdx2_0 < (gParams_0.reduceCount2_0))
    {
        var key2_0 : vec2<u32> = key2In_0[reduceIdx2_0];
        blockIdx_1 = key2_0.x;
        threadIdx1D_1 = key2_0.y;
        targetValueSum_3 = reduceTarget2In_0[reduceIdx2_0];
        coupleRateSum_3 = reduceCouple2In_0[reduceIdx2_0];
        weightSum_3 = reduceWeight2In_0[reduceIdx2_0];
    }
    emitterPointScan_0(sthreadIdx_3, &(targetValueSum_3), &(coupleRateSum_3), &(weightSum_3), &(blockIdx_1), &(threadIdx1D_1));
    var reduceIdx3_0 : u32 = ((reduceIdx2_0 >> (u32(7)))) + u32(1);
    if(reduceIdx3_0 < (gParams_0.reduceCount3_0))
    {
        var key3_0 : vec2<u32> = key3In_0[reduceIdx3_0];
        var threadIdx1D3_0 : u32 = key3_0.y;
        var _S6 : bool;
        if((key3_0.x) == blockIdx_1)
        {
            _S6 = threadIdx1D3_0 == threadIdx1D_1;
        }
        else
        {
            _S6 = false;
        }
        if(_S6)
        {
            targetValueSum_3 = targetValueSum_3 + scanTarget3In_0[reduceIdx3_0];
            coupleRateSum_3 = coupleRateSum_3 + scanCouple3In_0[reduceIdx3_0];
            weightSum_3 = weightSum_3 + scanWeight3In_0[reduceIdx3_0];
        }
    }
    if(reduceIdx2_0 < (gParams_0.reduceCount2_0))
    {
        scanTarget2Out_0[reduceIdx2_0] = targetValueSum_3;
        scanCouple2Out_0[reduceIdx2_0] = coupleRateSum_3;
        scanWeight2Out_0[reduceIdx2_0] = weightSum_3;
    }
    return;
}

