// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterMeshCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) faceBlockIdx1Offset_0 : u32,
    @align(8) faceBlockIdx2Offset_0 : u32,
    @align(4) faceBlockIdx3Offset_0 : u32,
    @align(16) face1Count_0 : u32,
    @align(4) face2Count_0 : u32,
    @align(8) face3Count_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) rasterThickness_0 : f32,
    @align(4) minDistance_0 : f32,
    @align(8) maxDistance_0 : f32,
    @align(4) orientationLeftHanded_0 : u32,
    @align(16) emptyMin_0 : vec4<f32>,
    @align(16) emptyMax_0 : vec4<f32>,
    @align(16) dispatchBoundsLocations_0 : u32,
    @align(4) layerAndLevel_0 : i32,
    @align(8) needsSrgbConversion_0 : u32,
    @align(4) pad1_1 : u32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldOld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_faceVertexIndices_0 : vec2<u32>,
    @align(16) range_faceVertexCounts_0 : vec2<u32>,
    @align(8) range_faceVertexStarts_0 : vec2<u32>,
    @align(16) range_velocities_0 : vec2<u32>,
    @align(8) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterMeshCS_Params_std140_0;
@binding(2) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

struct EmitterMeshCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) weight_0 : f32,
    @align(8) pad2_0 : f32,
    @align(4) pad3_0 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterMeshCS_SubStepParams_std140_0;
@binding(3) @group(0) var<storage, read> bounds4In_0 : array<vec4<u32>>;

@binding(4) @group(0) var<storage, read_write> sortKeyOut_0 : array<u32>;

@binding(5) @group(0) var<storage, read_write> sortValOut_0 : array<u32>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

fn fetchWorldPos_0( faceVertexIdx_0 : u32) -> vec4<f32>
{
    var _S2 : u32 = u32(3) * faceVertexIdx_0;
    var posLocal_0 : vec4<f32> = vec4<f32>((bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S2]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S2 + u32(1)]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S2 + u32(2)]))), 1.0f);
    var posWorld_0 : vec4<f32> = (((unpackStorage_0(gParams_0.localToWorld_0)) * (posLocal_0)));
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var _S3 : vec4<f32> = posWorld_0 * vec4<f32>((1.0f - gSubStepParams_0.weight_0));
        posWorld_0 = _S3;
        posWorld_0 = _S3 + vec4<f32>(gSubStepParams_0.weight_0) * (((unpackStorage_0(gParams_0.localToWorldOld_0)) * (posLocal_0)));
    }
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var vel4_0 : vec4<f32> = vec4<f32>(gSubStepParams_0.defaultVelocity_0, 0.0f);
        if(faceVertexIdx_0 < (gParams_0.range_velocities_0.y))
        {
            vel4_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S2])));
            vel4_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S2 + u32(1)])));
            vel4_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S2 + u32(2)])));
        }
        if((gParams_0.velocityIsWorldSpace_0) == u32(0))
        {
            vel4_0 = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vel4_0)));
        }
        var _S4 : vec3<f32> = vel4_0.xyz * vec3<f32>(gSubStepParams_0.velocityScale_0);
        vel4_0.x = _S4.x;
        vel4_0.y = _S4.y;
        vel4_0.z = _S4.z;
        var _S5 : vec3<f32> = posWorld_0.xyz - vec3<f32>(gSubStepParams_0.subStepAccumDeltaTime_0) * vel4_0.xyz;
        posWorld_0.x = _S5.x;
        posWorld_0.y = _S5.y;
        posWorld_0.z = _S5.z;
    }
    return posWorld_0;
}

fn mortonShift_0( x_0 : u32) -> u32
{
    var _S6 : u32 = (((x_0 | (((x_0 << (u32(16))))))) & (u32(50331903)));
    var _S7 : u32 = (((_S6 | (((_S6 << (u32(8))))))) & (u32(50393103)));
    var _S8 : u32 = (((_S7 | (((_S7 << (u32(4))))))) & (u32(51130563)));
    return (((_S8 | (((_S8 << (u32(2))))))) & (u32(153391689)));
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>, @builtin(local_invocation_id) groupThreadID_0 : vec3<u32>)
{
    var gthreadIdx_0 : u32 = dispatchThreadID_0.x + (((gParams_0.faceBlockIdx1Offset_0) << (u32(8))));
    var _S9 : vec4<f32> = gParams_0.emptyMin_0;
    var _S10 : vec4<f32> = gParams_0.emptyMax_0;
    var bbox_min_0 : vec4<f32>;
    var bbox_max_0 : vec4<f32>;
    if(gthreadIdx_0 < (gParams_0.face1Count_0))
    {
        var faceVertexCount_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexCounts_0.x + gthreadIdx_0];
        var faceVertexStart_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexStarts_0.x + gthreadIdx_0];
        if(faceVertexCount_0 > u32(0))
        {
            var posWorld_1 : vec4<f32> = fetchWorldPos_0(arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0]);
            bbox_min_0 = posWorld_1;
            bbox_max_0 = posWorld_1;
        }
        else
        {
            bbox_min_0 = _S9;
            bbox_max_0 = _S10;
        }
        var faceVertexIdxIdx_0 : u32 = u32(1);
        for(;;)
        {
            if(faceVertexIdxIdx_0 < faceVertexCount_0)
            {
            }
            else
            {
                break;
            }
            var posWorld_2 : vec4<f32> = fetchWorldPos_0(arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0 + faceVertexIdxIdx_0]);
            var _S11 : vec4<f32> = min(bbox_min_0, posWorld_2);
            var _S12 : vec4<f32> = max(bbox_max_0, posWorld_2);
            var _S13 : u32 = faceVertexIdxIdx_0 + u32(1);
            bbox_min_0 = _S11;
            bbox_max_0 = _S12;
            faceVertexIdxIdx_0 = _S13;
        }
    }
    else
    {
        bbox_min_0 = _S9;
        bbox_max_0 = _S10;
    }
    var _S14 : vec3<f32> = (bitcast<vec4<f32>>((bounds4In_0[u32(0)]))).xyz;
    var _S15 : vec3<u32> = vec3<u32>(round(vec3<f32>(1023.0f) * (((vec3<f32>(0.5f) * (bbox_min_0.xyz + bbox_max_0.xyz)).xyz - _S14) / ((bitcast<vec4<f32>>((bounds4In_0[u32(1)]))).xyz - _S14))));
    var _S16 : u32 = mortonShift_0(_S15.y);
    var sortKey_0 : u32 = ((((mortonShift_0(_S15.x)) | (((_S16 << (u32(1))))))) | (((_S16 << (u32(2))))));
    if(gthreadIdx_0 < (gParams_0.face1Count_0))
    {
        sortKeyOut_0[gthreadIdx_0] = sortKey_0;
        sortValOut_0[gthreadIdx_0] = gthreadIdx_0;
    }
    return;
}

