// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterTextureCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) isVelocity_0 : u32,
    @align(8) textureFirstElement_0 : u32,
    @align(4) needsSrgbConversion_0 : u32,
    @align(16) textureWidth_0 : u32,
    @align(4) textureHeight_0 : u32,
    @align(8) textureDepth_0 : u32,
    @align(4) deltaTime_0 : f32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) targetValue_0 : vec4<f32>,
    @align(16) coupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) halfSizeInv_0 : vec3<f32>,
    @align(4) pad2_0 : f32,
    @align(16) halfSize_0 : vec3<f32>,
    @align(4) pad3_0 : f32,
    @align(16) position_0 : vec3<f32>,
    @align(4) textureIsColumnMajor_0 : u32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) minDistance_0 : f32,
    @align(4) maxDistance_0 : f32,
    @align(8) range_distances_0 : vec2<u32>,
    @align(16) range_velocities_0 : vec2<u32>,
    @align(8) range_divergences_0 : vec2<u32>,
    @align(16) range_temperatures_0 : vec2<u32>,
    @align(8) range_fuels_0 : vec2<u32>,
    @align(16) range_burns_0 : vec2<u32>,
    @align(8) range_smokes_0 : vec2<u32>,
    @align(16) range_coupleRateVelocities_0 : vec2<u32>,
    @align(8) range_coupleRateDivergences_0 : vec2<u32>,
    @align(16) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(8) range_coupleRateFuels_0 : vec2<u32>,
    @align(16) range_coupleRateBurns_0 : vec2<u32>,
    @align(8) range_coupleRateSmokes_0 : vec2<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterTextureCS_Params_std140_0;
@binding(1) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(2) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

@binding(3) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(4) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn computeTex1D_0( texIdx_0 : vec3<i32>) -> u32
{
    var texIdx1D_0 : u32;
    if((gParams_0.textureIsColumnMajor_0) == u32(0))
    {
        texIdx1D_0 = u32((texIdx_0.z * i32(gParams_0.textureHeight_0) + texIdx_0.y) * i32(gParams_0.textureWidth_0) + texIdx_0.x) + gParams_0.textureFirstElement_0;
    }
    else
    {
        texIdx1D_0 = u32((texIdx_0.x * i32(gParams_0.textureHeight_0) + texIdx_0.y) * i32(gParams_0.textureDepth_0) + texIdx_0.z) + gParams_0.textureFirstElement_0;
    }
    return texIdx1D_0;
}

fn readArrayValue_0( idx_0 : u32) -> f32
{
    return (unpack2x16float(((arrayValuesIn_0[(idx_0 >> (u32(1)))] >> (((((idx_0 & (u32(1)))) << (u32(4)))))))).x);
}

fn srgb_to_linear1_0( v_0 : f32) -> f32
{
    var ret_0 : f32;
    if(v_0 <= 0.04044999927282333f)
    {
        ret_0 = v_0 * 0.07739938050508499f;
    }
    else
    {
        ret_0 = pow((v_0 + 0.05499999970197678f) * 0.94786733388900757f, 2.40000009536743164f);
    }
    return ret_0;
}

fn srgb_to_linear_0( c_0 : vec3<f32>) -> vec3<f32>
{
    return vec3<f32>(srgb_to_linear1_0(c_0.x), srgb_to_linear1_0(c_0.y), srgb_to_linear1_0(c_0.z));
}

fn lookupSdf_0( texIdx_1 : vec3<i32>) -> f32
{
    var _S6 : vec3<i32> = texIdx_1;
    _S6[i32(0)] = max(i32(0), min(texIdx_1.x, i32(gParams_0.textureWidth_0) - i32(1)));
    _S6[i32(1)] = max(i32(0), min(_S6.y, i32(gParams_0.textureHeight_0) - i32(1)));
    _S6[i32(2)] = max(i32(0), min(_S6.z, i32(gParams_0.textureDepth_0) - i32(1)));
    return readArrayValue_0(min(computeTex1D_0(_S6), gParams_0.range_distances_0.y - u32(1)) + gParams_0.range_distances_0.x);
}

fn sampleSdf_0( uvw_0 : vec3<f32>) -> f32
{
    var _S7 : vec3<f32> = uvw_0 * vec3<f32>(f32(gParams_0.textureWidth_0), f32(gParams_0.textureHeight_0), f32(gParams_0.textureDepth_0)) - vec3<f32>(0.5f);
    var _S8 : vec3<i32> = vec3<i32>(floor(_S7));
    var w1_0 : vec3<f32> = _S7 - vec3<f32>(_S8);
    var w0_0 : vec3<f32> = vec3<f32>(1.0f, 1.0f, 1.0f) - w1_0;
    var _S9 : f32 = w0_0.x;
    var _S10 : f32 = w0_0.y;
    var _S11 : f32 = _S9 * _S10;
    var _S12 : f32 = w0_0.z;
    var _S13 : f32 = w1_0.x;
    var _S14 : f32 = _S13 * _S10;
    var _S15 : f32 = w1_0.y;
    var _S16 : f32 = _S9 * _S15;
    var _S17 : f32 = _S13 * _S15;
    var _S18 : f32 = w1_0.z;
    return _S11 * _S12 * lookupSdf_0(_S8) + _S14 * _S12 * lookupSdf_0(_S8 + vec3<i32>(i32(1), i32(0), i32(0))) + _S16 * _S12 * lookupSdf_0(_S8 + vec3<i32>(i32(0), i32(1), i32(0))) + _S17 * _S12 * lookupSdf_0(_S8 + vec3<i32>(i32(1), i32(1), i32(0))) + _S11 * _S18 * lookupSdf_0(_S8 + vec3<i32>(i32(0), i32(0), i32(1))) + _S14 * _S18 * lookupSdf_0(_S8 + vec3<i32>(i32(1), i32(0), i32(1))) + _S16 * _S18 * lookupSdf_0(_S8 + vec3<i32>(i32(0), i32(1), i32(1))) + _S17 * _S18 * lookupSdf_0(_S8 + vec3<i32>(i32(1), i32(1), i32(1)));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S19 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S19, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S19 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S20 : i32 = threadIdx_1.x;
    if(_S20 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S20 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S21 : i32 = threadIdx_1.y;
    if(_S21 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S21 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S22 : i32 = threadIdx_1.z;
    if(_S22 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S22 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowLocationToBlockIdx_0( _S23 : NvFlowSparseLevelParams_0,  _S24 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S24.xyz) & ((_S23.tableDimLessOne_0)));
    var _S25 : u32 = ((((((((bucketIdx_0.z) << ((_S23.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S23.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S26 : u32 = gTable_0[_S25 + u32(1)];
    var _S27 : i32 = _S24.x;
    var _S28 : i32 = _S24.y;
    var _S29 : i32 = _S24.z;
    var _S30 : i32 = _S24.w;
    var blockIdx_1 : u32 = gTable_0[_S25];
    for(;;)
    {
        if(blockIdx_1 < _S26)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S23.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S31 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S27)
        {
            _S31 = compareLocation_y_0 == _S28;
        }
        else
        {
            _S31 = false;
        }
        var _S32 : bool;
        if(_S31)
        {
            _S32 = compareLocation_z_0 == _S29;
        }
        else
        {
            _S32 = false;
        }
        var _S33 : bool;
        if(_S32)
        {
            _S33 = compareLocation_w_0 == _S30;
        }
        else
        {
            _S33 = false;
        }
        if(_S33)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowLocalVirtualToReal_0( _S34 : NvFlowSparseLevelParams_0,  _S35 : u32,  _S36 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S36 >> (vec3<u32>(vec3<i32>(_S34.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S36, gTable_0[NvFlowNeighborToIdx_0(_S35, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S34.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S37 : texture_3d<f32>,  _S38 : NvFlowSparseLevelParams_0,  _S39 : u32,  _S40 : vec3<i32>) -> vec4<f32>
{
    var _S41 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S38, _S39, _S40);
    var _S42 : vec4<f32>;
    if(bool(_S41.w))
    {
        var _S43 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S41.xyz), u32(0)));
        _S42 = (textureLoad((_S37), ((_S43)).xyz, ((_S43)).w));
    }
    else
    {
        _S42 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S42;
}

fn NvFlowLocalWriteNeighbor4f_0( _S44 : NvFlowSparseLevelParams_0,  _S45 : i32,  _S46 : i32,  _S47 : i32,  _S48 : u32,  _S49 : vec3<i32>,  _S50 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S49, gTable_0[NvFlowNeighborToIdx_0(_S48, _S45, _S46, _S47) + _S44.blockLevelOffsetLocal_0], _S45, _S46, _S47);
    var _S51 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S52 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S52 = _S50;
    }
    else
    {
        _S52 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S51), (_S52));
    return;
}

fn NvFlowLocalWrite4f_0( _S53 : NvFlowSparseLevelParams_0,  _S54 : u32,  _S55 : vec3<i32>,  _S56 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S53, _S55);
    NvFlowLocalWriteNeighbor4f_0(_S53, i32(0), i32(0), i32(0), _S54, _S55, _S56);
    var _S57 : i32 = neighbor_2.x;
    var _S58 : bool = _S57 != i32(0);
    if(_S58)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, _S57, i32(0), i32(0), _S54, _S55, _S56);
    }
    var _S59 : i32 = neighbor_2.y;
    var _S60 : bool = _S59 != i32(0);
    if(_S60)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, i32(0), _S59, i32(0), _S54, _S55, _S56);
    }
    var _S61 : i32 = neighbor_2.z;
    var _S62 : bool = _S61 != i32(0);
    if(_S62)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, i32(0), i32(0), _S61, _S54, _S55, _S56);
    }
    var _S63 : bool;
    if(_S58)
    {
        _S63 = _S60;
    }
    else
    {
        _S63 = false;
    }
    if(_S63)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, _S57, _S59, i32(0), _S54, _S55, _S56);
    }
    if(_S60)
    {
        _S63 = _S62;
    }
    else
    {
        _S63 = false;
    }
    if(_S63)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, i32(0), _S59, _S61, _S54, _S55, _S56);
    }
    if(_S58)
    {
        _S63 = _S62;
    }
    else
    {
        _S63 = false;
    }
    if(_S63)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, _S57, i32(0), _S61, _S54, _S55, _S56);
    }
    if(_S58)
    {
        _S63 = _S60;
    }
    else
    {
        _S63 = false;
    }
    if(_S63)
    {
        _S63 = _S62;
    }
    else
    {
        _S63 = false;
    }
    if(_S63)
    {
        NvFlowLocalWriteNeighbor4f_0(_S53, _S57, _S59, _S61, _S54, _S55, _S56);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var locationIdx_0 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var _S64 : u32 = locationIdx_0 % gParams_0.locationExtent_0.x;
    var _S65 : i32 = i32(_S64) + gParams_0.locationOffset_1.x;
    var _S66 : u32 = locationIdx_0 / gParams_0.locationExtent_0.x;
    var _S67 : u32 = _S66 % gParams_0.locationExtent_0.y;
    var _S68 : i32 = i32(_S67) + gParams_0.locationOffset_1.y;
    var _S69 : u32 = locationIdx_0 / (gParams_0.locationExtent_0.x * gParams_0.locationExtent_0.y);
    var _S70 : i32 = i32(_S69) + gParams_0.locationOffset_1.z;
    var _S71 : u32 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(_S65, _S68, _S70, gParams_0.locationOffset_1.w));
    if(_S71 >= (gParams_0.table_0.numLocations_0))
    {
        return;
    }
    var _S72 : vec4<f32> = (((unpackStorage_0(gParams_0.worldToLocal_0)) * (vec4<f32>(gParams_0.vidxToWorld_0 * (vec3<f32>(((vec3<i32>(_S65, _S68, _S70) << ((gParams_0.table_0.blockDimBits_0)))) + threadIdx_3) + vec3<f32>(0.5f, 0.5f, 0.5f)), 1.0f))));
    var localPosTranslated_0 : vec4<f32> = _S72;
    var _S73 : vec3<f32> = _S72.xyz - gParams_0.position_0;
    localPosTranslated_0.x = _S73.x;
    localPosTranslated_0.y = _S73.y;
    localPosTranslated_0.z = _S73.z;
    var _S74 : bool;
    if((abs(localPosTranslated_0.x)) < (gParams_0.halfSize_0.x))
    {
        _S74 = (abs(localPosTranslated_0.y)) < (gParams_0.halfSize_0.y);
    }
    else
    {
        _S74 = false;
    }
    if(_S74)
    {
        _S74 = (abs(localPosTranslated_0.z)) < (gParams_0.halfSize_0.z);
    }
    else
    {
        _S74 = false;
    }
    if(_S74)
    {
        var _S75 : vec3<f32> = vec3<f32>(0.5f);
        var uvw_1 : vec3<f32> = _S75 * localPosTranslated_0.xyz * gParams_0.halfSizeInv_0 + _S75;
        var _S76 : i32 = i32(floor(uvw_1.x * f32(gParams_0.textureWidth_0)));
        var _S77 : i32 = i32(floor(uvw_1.y * f32(gParams_0.textureHeight_0)));
        var _S78 : i32 = i32(floor(uvw_1.z * f32(gParams_0.textureDepth_0)));
        var texIdx_2 : vec3<i32> = vec3<i32>(_S76, _S77, _S78);
        var coupleRate_1 : vec4<f32> = gParams_0.coupleRate_0;
        var targetValue_1 : vec4<f32> = gParams_0.targetValue_0;
        if((gParams_0.textureWidth_0) > u32(0))
        {
            _S74 = (gParams_0.textureHeight_0) > u32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = (gParams_0.textureDepth_0) > u32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S76 >= i32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S76 < i32(gParams_0.textureWidth_0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S77 >= i32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S77 < i32(gParams_0.textureHeight_0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S78 >= i32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = _S78 < i32(gParams_0.textureDepth_0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            var texIdx1D_1 : u32 = computeTex1D_0(texIdx_2);
            if((gParams_0.isVelocity_0) != u32(0))
            {
                if(texIdx1D_1 < (gParams_0.range_coupleRateVelocities_0.y))
                {
                    var velCoupleRate_0 : f32 = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateVelocities_0.x);
                    coupleRate_1[i32(0)] = velCoupleRate_0;
                    coupleRate_1[i32(1)] = velCoupleRate_0;
                    coupleRate_1[i32(2)] = velCoupleRate_0;
                }
                if(texIdx1D_1 < (gParams_0.range_coupleRateDivergences_0.y))
                {
                    coupleRate_1[i32(3)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateDivergences_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_velocities_0.y))
                {
                    var _S79 : u32 = u32(3) * texIdx1D_1;
                    targetValue_1[i32(0)] = readArrayValue_0(_S79 + gParams_0.range_velocities_0.x);
                    targetValue_1[i32(1)] = readArrayValue_0(_S79 + u32(1) + gParams_0.range_velocities_0.x);
                    targetValue_1[i32(2)] = readArrayValue_0(_S79 + u32(2) + gParams_0.range_velocities_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_divergences_0.y))
                {
                    targetValue_1[i32(3)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_divergences_0.x);
                }
            }
            else
            {
                if(texIdx1D_1 < (gParams_0.range_coupleRateTemperatures_0.y))
                {
                    coupleRate_1[i32(0)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateTemperatures_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_coupleRateFuels_0.y))
                {
                    coupleRate_1[i32(1)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateFuels_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_coupleRateBurns_0.y))
                {
                    coupleRate_1[i32(2)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateBurns_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_coupleRateSmokes_0.y))
                {
                    coupleRate_1[i32(3)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_coupleRateSmokes_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_temperatures_0.y))
                {
                    targetValue_1[i32(0)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_temperatures_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_fuels_0.y))
                {
                    targetValue_1[i32(1)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_fuels_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_burns_0.y))
                {
                    targetValue_1[i32(2)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_burns_0.x);
                }
                if(texIdx1D_1 < (gParams_0.range_smokes_0.y))
                {
                    targetValue_1[i32(3)] = readArrayValue_0(texIdx1D_1 + gParams_0.range_smokes_0.x);
                }
            }
        }
        if((gParams_0.isVelocity_0) != u32(0))
        {
            if((gParams_0.velocityIsWorldSpace_0) == u32(0))
            {
                var _S80 : vec3<f32> = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vec4<f32>(targetValue_1.xyz, 0.0f)))).xyz;
                targetValue_1.x = _S80.x;
                targetValue_1.y = _S80.y;
                targetValue_1.z = _S80.z;
            }
        }
        else
        {
            if((gParams_0.needsSrgbConversion_0) != u32(0))
            {
                var _S81 : vec3<f32> = srgb_to_linear_0(targetValue_1.xyz);
                targetValue_1.x = _S81.x;
                targetValue_1.y = _S81.y;
                targetValue_1.z = _S81.z;
            }
        }
        targetValue_1 = targetValue_1 * gParams_0.targetValueScale_0;
        if((gParams_0.range_distances_0.y) > u32(0))
        {
            _S74 = (gParams_0.textureWidth_0) > u32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = (gParams_0.textureHeight_0) > u32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            _S74 = (gParams_0.textureDepth_0) > u32(0);
        }
        else
        {
            _S74 = false;
        }
        if(_S74)
        {
            var dist_0 : f32 = sampleSdf_0(uvw_1);
            if(dist_0 < (gParams_0.minDistance_0))
            {
                _S74 = true;
            }
            else
            {
                _S74 = dist_0 > (gParams_0.maxDistance_0);
            }
            if(_S74)
            {
                coupleRate_1 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
            }
        }
        var _S82 : vec4<f32> = NvFlowLocalRead4f_0(valueIn_0, unpackStorage_1(gParams_0.table_0), _S71, threadIdx_3);
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), _S71, threadIdx_3, _S82 + min(vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f), max(vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f), vec4<f32>(gParams_0.deltaTime_0) * coupleRate_1)) * (targetValue_1 - _S82));
    }
    return;
}

