// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterMeshCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) faceBlockIdx1Offset_0 : u32,
    @align(8) faceBlockIdx2Offset_0 : u32,
    @align(4) faceBlockIdx3Offset_0 : u32,
    @align(16) face1Count_0 : u32,
    @align(4) face2Count_0 : u32,
    @align(8) face3Count_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) rasterThickness_0 : f32,
    @align(4) minDistance_0 : f32,
    @align(8) maxDistance_0 : f32,
    @align(4) orientationLeftHanded_0 : u32,
    @align(16) emptyMin_0 : vec4<f32>,
    @align(16) emptyMax_0 : vec4<f32>,
    @align(16) dispatchBoundsLocations_0 : u32,
    @align(4) layerAndLevel_0 : i32,
    @align(8) needsSrgbConversion_0 : u32,
    @align(4) pad1_1 : u32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldOld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_faceVertexIndices_0 : vec2<u32>,
    @align(16) range_faceVertexCounts_0 : vec2<u32>,
    @align(8) range_faceVertexStarts_0 : vec2<u32>,
    @align(16) range_velocities_0 : vec2<u32>,
    @align(8) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterMeshCS_Params_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(5) @group(0) var closestIn_0 : texture_3d<u32>;

@binding(4) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(3) @group(0) var<storage, read> arrayValuesIn_0 : array<u32>;

struct EmitterMeshCS_SubStepParams_std140_0
{
    @align(16) subStepIdx_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(8) subStepDeltaTime_0 : f32,
    @align(4) subStepAccumDeltaTime_0 : f32,
    @align(16) defaultVelocity_0 : vec3<f32>,
    @align(4) totalDeltaTime_0 : f32,
    @align(16) velocityScale_0 : f32,
    @align(4) weight_0 : f32,
    @align(8) pad2_0 : f32,
    @align(4) pad3_0 : f32,
};

@binding(1) @group(0) var<uniform> gSubStepParams_0 : EmitterMeshCS_SubStepParams_std140_0;
@binding(6) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S6 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S6, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S6 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn fetchWorldPos_0( faceVertexIdx_0 : u32) -> vec4<f32>
{
    var _S7 : u32 = u32(3) * faceVertexIdx_0;
    var posLocal_0 : vec4<f32> = vec4<f32>((bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7 + u32(1)]))), (bitcast<f32>((arrayValuesIn_0[gParams_0.range_positions_0.x + _S7 + u32(2)]))), 1.0f);
    var posWorld_0 : vec4<f32> = (((unpackStorage_0(gParams_0.localToWorld_0)) * (posLocal_0)));
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var _S8 : vec4<f32> = posWorld_0 * vec4<f32>((1.0f - gSubStepParams_0.weight_0));
        posWorld_0 = _S8;
        posWorld_0 = _S8 + vec4<f32>(gSubStepParams_0.weight_0) * (((unpackStorage_0(gParams_0.localToWorldOld_0)) * (posLocal_0)));
    }
    if((gSubStepParams_0.subStepIdx_0) >= u32(1))
    {
        var vel4_0 : vec4<f32> = vec4<f32>(gSubStepParams_0.defaultVelocity_0, 0.0f);
        if(faceVertexIdx_0 < (gParams_0.range_velocities_0.y))
        {
            vel4_0[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7])));
            vel4_0[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7 + u32(1)])));
            vel4_0[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S7 + u32(2)])));
        }
        if((gParams_0.velocityIsWorldSpace_0) == u32(0))
        {
            vel4_0 = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vel4_0)));
        }
        var _S9 : vec3<f32> = vel4_0.xyz * vec3<f32>(gSubStepParams_0.velocityScale_0);
        vel4_0.x = _S9.x;
        vel4_0.y = _S9.y;
        vel4_0.z = _S9.z;
        var _S10 : vec3<f32> = posWorld_0.xyz - vec3<f32>(gSubStepParams_0.subStepAccumDeltaTime_0) * vel4_0.xyz;
        posWorld_0.x = _S10.x;
        posWorld_0.y = _S10.y;
        posWorld_0.z = _S10.z;
    }
    return posWorld_0;
}

fn rayTriangleNearest_0( o_0 : vec3<f32>,  d_0 : vec3<f32>,  p0_0 : vec3<f32>,  p1_0 : vec3<f32>,  p2_0 : vec3<f32>,  uvt_0 : ptr<function, vec3<f32>>) -> bool
{
    var e1_0 : vec3<f32> = p1_0 - p0_0;
    var e2_0 : vec3<f32> = p2_0 - p0_0;
    var q_0 : vec3<f32> = cross(d_0, e2_0);
    var a_0 : f32 = dot(e1_0, q_0);
    if(a_0 == 0.0f)
    {
        (*uvt_0) = vec3<f32>(0.0f, 0.0f, 0.0f);
        return false;
    }
    var f_0 : f32 = 1.0f / a_0;
    var s_0 : vec3<f32> = o_0 - p0_0;
    var u_0 : f32 = f_0 * dot(s_0, q_0);
    var r_0 : vec3<f32> = cross(s_0, e1_0);
    var v_1 : f32 = f_0 * dot(d_0, r_0);
    var t_0 : f32 = f_0 * dot(e2_0, r_0);
    var p_0 : vec3<f32> = o_0 + d_0 * vec3<f32>(t_0);
    var u_1 : f32;
    var v_2 : f32;
    if((1.0f - u_0 - v_1) < 0.0f)
    {
        var _S11 : vec3<f32> = p2_0 - p1_0;
        var edge_0 : f32 = clamp(dot(p_0 - p1_0, _S11) / dot(_S11, _S11), 0.0f, 1.0f);
        u_1 = 1.0f - edge_0;
        v_2 = edge_0;
    }
    else
    {
        if(u_0 < 0.0f)
        {
            var _S12 : vec3<f32> = p0_0 - p2_0;
            var _S13 : f32 = 1.0f - clamp(dot(p_0 - p2_0, _S12) / dot(_S12, _S12), 0.0f, 1.0f);
            u_1 = 0.0f;
            v_2 = _S13;
        }
        else
        {
            if(v_1 < 0.0f)
            {
                u_1 = clamp(dot(p_0 - p0_0, e1_0) / dot(e1_0, e1_0), 0.0f, 1.0f);
                v_2 = 0.0f;
            }
            else
            {
                u_1 = u_0;
                v_2 = v_1;
            }
        }
    }
    (*uvt_0) = vec3<f32>(u_1, v_2, t_0);
    return true;
}

fn srgb_to_linear1_0( v_3 : f32) -> f32
{
    var ret_0 : f32;
    if(v_3 <= 0.04044999927282333f)
    {
        ret_0 = v_3 * 0.07739938050508499f;
    }
    else
    {
        ret_0 = pow((v_3 + 0.05499999970197678f) * 0.94786733388900757f, 2.40000009536743164f);
    }
    return ret_0;
}

fn srgb_to_linear_0( c_0 : vec3<f32>) -> vec3<f32>
{
    return vec3<f32>(srgb_to_linear1_0(c_0.x), srgb_to_linear1_0(c_0.y), srgb_to_linear1_0(c_0.z));
}

fn fetchAttributeValue_0( faceVertexIdx_1 : u32,  attributeIdx_0 : u32,  coupleRate_0 : ptr<function, vec4<f32>>,  targetValue_0 : ptr<function, vec4<f32>>)
{
    if((gParams_0.isVelocity_0) != u32(0))
    {
        if(attributeIdx_0 < (gParams_0.range_coupleRateVelocities_0.y))
        {
            var velCoupleRate_0 : f32 = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateVelocities_0.x + attributeIdx_0])));
            (*coupleRate_0)[i32(0)] = velCoupleRate_0;
            (*coupleRate_0)[i32(1)] = velCoupleRate_0;
            (*coupleRate_0)[i32(2)] = velCoupleRate_0;
        }
        if(attributeIdx_0 < (gParams_0.range_coupleRateDivergences_0.y))
        {
            (*coupleRate_0)[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateDivergences_0.x + attributeIdx_0])));
        }
        if(faceVertexIdx_1 < (gParams_0.range_velocities_0.y))
        {
            var _S14 : u32 = u32(3) * faceVertexIdx_1;
            (*targetValue_0)[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S14])));
            (*targetValue_0)[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S14 + u32(1)])));
            (*targetValue_0)[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_velocities_0.x + _S14 + u32(2)])));
        }
        if(attributeIdx_0 < (gParams_0.range_divergences_0.y))
        {
            (*targetValue_0)[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_divergences_0.x + attributeIdx_0])));
        }
        if((gParams_0.velocityIsWorldSpace_0) == u32(0))
        {
            var _S15 : vec3<f32> = (((unpackStorage_0(gParams_0.localToWorldVelocity_0)) * (vec4<f32>((*targetValue_0).xyz, 0.0f)))).xyz;
            (*targetValue_0).x = _S15.x;
            (*targetValue_0).y = _S15.y;
            (*targetValue_0).z = _S15.z;
        }
    }
    else
    {
        if(attributeIdx_0 < (gParams_0.range_coupleRateTemperatures_0.y))
        {
            (*coupleRate_0)[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateTemperatures_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_coupleRateFuels_0.y))
        {
            (*coupleRate_0)[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateFuels_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_coupleRateBurns_0.y))
        {
            (*coupleRate_0)[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateBurns_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_coupleRateSmokes_0.y))
        {
            (*coupleRate_0)[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_coupleRateSmokes_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_temperatures_0.y))
        {
            (*targetValue_0)[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_temperatures_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_fuels_0.y))
        {
            (*targetValue_0)[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_fuels_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_burns_0.y))
        {
            (*targetValue_0)[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_burns_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_smokes_0.y))
        {
            (*targetValue_0)[i32(3)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_smokes_0.x + attributeIdx_0])));
        }
        if(attributeIdx_0 < (gParams_0.range_colors_0.y))
        {
            var _S16 : u32 = u32(3) * attributeIdx_0;
            (*targetValue_0)[i32(0)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S16])));
            (*targetValue_0)[i32(1)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S16 + u32(1)])));
            (*targetValue_0)[i32(2)] = (bitcast<f32>((arrayValuesIn_0[gParams_0.range_colors_0.x + _S16 + u32(2)])));
        }
        if((gParams_0.needsSrgbConversion_0) != u32(0))
        {
            var _S17 : vec3<f32> = srgb_to_linear_0((*targetValue_0).xyz);
            (*targetValue_0).x = _S17.x;
            (*targetValue_0).y = _S17.y;
            (*targetValue_0).z = _S17.z;
        }
    }
    return;
}

fn fetchFaceValues_0( faceIdx_0 : u32,  vidx_0 : vec3<i32>,  coupleRate_1 : ptr<function, vec4<f32>>,  targetValue_1 : ptr<function, vec4<f32>>)
{
    var _S18 : vec3<f32> = (vec3<f32>(vidx_0) + vec3<f32>(0.5f, 0.5f, 0.5f)) * gParams_0.vidxToWorld_0;
    const _S19 : vec3<u32> = vec3<u32>(u32(4294967295), u32(4294967295), u32(4294967295));
    const _S20 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var faceVertexCount_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexCounts_0.x + faceIdx_0];
    var faceVertexStart_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexStarts_0.x + faceIdx_0];
    var minAttributeIdx_0 : vec3<u32>;
    var minFaceVertexIdx_0 : vec3<u32>;
    var minUvt_0 : vec3<f32>;
    if(faceVertexCount_0 >= u32(3))
    {
        var faceVertexIdx0_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0];
        var _S21 : u32 = faceVertexCount_0 - u32(2);
        var _S22 : vec3<f32> = fetchWorldPos_0(faceVertexIdx0_0).xyz;
        var minDist_0 : f32 = 0.0f;
        minAttributeIdx_0 = _S19;
        minFaceVertexIdx_0 = _S19;
        minUvt_0 = _S20;
        var triangleIdx_0 : u32 = u32(0);
        for(;;)
        {
            if(triangleIdx_0 < _S21)
            {
            }
            else
            {
                break;
            }
            var faceVertexIdx1_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0 + triangleIdx_0 + u32(1)];
            var faceVertexIdx2_0 : u32 = arrayValuesIn_0[gParams_0.range_faceVertexIndices_0.x + faceVertexStart_0 + triangleIdx_0 + u32(2)];
            var _S23 : vec3<f32> = fetchWorldPos_0(faceVertexIdx1_0).xyz;
            var _S24 : vec3<f32> = fetchWorldPos_0(faceVertexIdx2_0).xyz;
            var uvt_1 : vec3<f32>;
            var valid_0 : bool = rayTriangleNearest_0(_S18, cross(_S23 - _S22, _S24 - _S22), _S22, _S23, _S24, &(uvt_1));
            if(valid_0)
            {
                var dist_0 : f32 = length(_S18 - (vec3<f32>((1.0f - uvt_1.x - uvt_1.y)) * _S22 + vec3<f32>(uvt_1.x) * _S23 + vec3<f32>(uvt_1.y) * _S24));
                var _S25 : bool;
                if(dist_0 < minDist_0)
                {
                    _S25 = true;
                }
                else
                {
                    _S25 = (minAttributeIdx_0.x) == u32(4294967295);
                }
                var minDist_1 : f32;
                var minAttributeIdx_1 : vec3<u32>;
                var minFaceVertexIdx_1 : vec3<u32>;
                var minUvt_1 : vec3<f32>;
                if(_S25)
                {
                    var _S26 : u32 = faceVertexStart_0 + triangleIdx_0;
                    var _S27 : vec3<u32> = vec3<u32>(faceVertexStart_0, _S26 + u32(1), _S26 + u32(2));
                    var _S28 : vec3<u32> = vec3<u32>(faceVertexIdx0_0, faceVertexIdx1_0, faceVertexIdx2_0);
                    minDist_1 = dist_0;
                    minAttributeIdx_1 = _S27;
                    minFaceVertexIdx_1 = _S28;
                    minUvt_1 = uvt_1;
                }
                else
                {
                    minDist_1 = minDist_0;
                    minAttributeIdx_1 = minAttributeIdx_0;
                    minFaceVertexIdx_1 = minFaceVertexIdx_0;
                    minUvt_1 = minUvt_0;
                }
                minDist_0 = minDist_1;
                minAttributeIdx_0 = minAttributeIdx_1;
                minFaceVertexIdx_0 = minFaceVertexIdx_1;
                minUvt_0 = minUvt_1;
            }
            triangleIdx_0 = triangleIdx_0 + u32(1);
        }
    }
    else
    {
        minAttributeIdx_0 = _S19;
        minFaceVertexIdx_0 = _S19;
        minUvt_0 = _S20;
    }
    var _S29 : u32 = minAttributeIdx_0.x;
    if(_S29 != u32(4294967295))
    {
        var targetValue0_0 : vec4<f32> = gParams_0.defaultTargetValue_0;
        var coupleRate0_0 : vec4<f32> = gParams_0.defaultCoupleRate_0;
        fetchAttributeValue_0(minFaceVertexIdx_0.x, _S29, &(coupleRate0_0), &(targetValue0_0));
        var targetValue1_0 : vec4<f32> = gParams_0.defaultTargetValue_0;
        var coupleRate1_0 : vec4<f32> = gParams_0.defaultCoupleRate_0;
        fetchAttributeValue_0(minFaceVertexIdx_0.y, minAttributeIdx_0.y, &(coupleRate1_0), &(targetValue1_0));
        var targetValue2_0 : vec4<f32> = gParams_0.defaultTargetValue_0;
        var coupleRate2_0 : vec4<f32> = gParams_0.defaultCoupleRate_0;
        fetchAttributeValue_0(minFaceVertexIdx_0.z, minAttributeIdx_0.z, &(coupleRate2_0), &(targetValue2_0));
        var _S30 : f32 = minUvt_0.x;
        var _S31 : f32 = minUvt_0.y;
        var _S32 : vec4<f32> = vec4<f32>((1.0f - _S30 - _S31));
        var _S33 : vec4<f32> = vec4<f32>(_S30);
        var _S34 : vec4<f32> = vec4<f32>(_S31);
        (*coupleRate_1) = _S32 * coupleRate0_0 + _S33 * coupleRate1_0 + _S34 * coupleRate2_0;
        (*targetValue_1) = _S32 * targetValue0_0 + _S33 * targetValue1_0 + _S34 * targetValue2_0;
    }
    return;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S35 : i32 = threadIdx_1.x;
    if(_S35 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S35 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S36 : i32 = threadIdx_1.y;
    if(_S36 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S36 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S37 : i32 = threadIdx_1.z;
    if(_S37 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S37 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_4 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_4 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_4 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_4 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_4 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_4) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowLocationToBlockIdx_0( _S38 : NvFlowSparseLevelParams_0,  _S39 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S39.xyz) & ((_S38.tableDimLessOne_0)));
    var _S40 : u32 = ((((((((bucketIdx_0.z) << ((_S38.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S38.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S41 : u32 = gTable_0[_S40 + u32(1)];
    var _S42 : i32 = _S39.x;
    var _S43 : i32 = _S39.y;
    var _S44 : i32 = _S39.z;
    var _S45 : i32 = _S39.w;
    var blockIdx_2 : u32 = gTable_0[_S40];
    for(;;)
    {
        if(blockIdx_2 < _S41)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_2 << (u32(2)))) + _S38.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S46 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S42)
        {
            _S46 = compareLocation_y_0 == _S43;
        }
        else
        {
            _S46 = false;
        }
        var _S47 : bool;
        if(_S46)
        {
            _S47 = compareLocation_z_0 == _S44;
        }
        else
        {
            _S47 = false;
        }
        var _S48 : bool;
        if(_S47)
        {
            _S48 = compareLocation_w_0 == _S45;
        }
        else
        {
            _S48 = false;
        }
        if(_S48)
        {
            outBlockIdx_0 = blockIdx_2;
            break;
        }
        blockIdx_2 = blockIdx_2 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowBlockIdxToLocation_0( _S49 : NvFlowSparseLevelParams_0,  _S50 : u32,  _S51 : ptr<function, vec4<i32>>) -> bool
{
    var _S52 : bool = _S50 < (_S49.numLocations_0);
    if(_S52)
    {
        var locationIdx_0 : u32 = ((_S50 << (u32(2)))) + _S49.locationOffset_0;
        (*_S51)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S51)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S51)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S51)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S51)[i32(0)] = i32(1073741824);
        (*_S51)[i32(1)] = i32(1073741824);
        (*_S51)[i32(2)] = i32(1073741824);
        (*_S51)[i32(3)] = i32(1073741824);
    }
    return _S52;
}

fn NvFlowSingleVirtualToReal_0( _S53 : NvFlowSparseLevelParams_0,  _S54 : u32,  _S55 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S55, gTable_0[NvFlowSingleToIdx_0(_S54) + _S53.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalWriteNeighbor4f_0( _S56 : NvFlowSparseLevelParams_0,  _S57 : i32,  _S58 : i32,  _S59 : i32,  _S60 : u32,  _S61 : vec3<i32>,  _S62 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S61, gTable_0[NvFlowNeighborToIdx_0(_S60, _S57, _S58, _S59) + _S56.blockLevelOffsetLocal_0], _S57, _S58, _S59);
    var _S63 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S64 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S64 = _S62;
    }
    else
    {
        _S64 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S63), (_S64));
    return;
}

fn NvFlowLocalWrite4f_0( _S65 : NvFlowSparseLevelParams_0,  _S66 : u32,  _S67 : vec3<i32>,  _S68 : vec4<f32>)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S65, _S67);
    NvFlowLocalWriteNeighbor4f_0(_S65, i32(0), i32(0), i32(0), _S66, _S67, _S68);
    var _S69 : i32 = neighbor_1.x;
    var _S70 : bool = _S69 != i32(0);
    if(_S70)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, _S69, i32(0), i32(0), _S66, _S67, _S68);
    }
    var _S71 : i32 = neighbor_1.y;
    var _S72 : bool = _S71 != i32(0);
    if(_S72)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, i32(0), _S71, i32(0), _S66, _S67, _S68);
    }
    var _S73 : i32 = neighbor_1.z;
    var _S74 : bool = _S73 != i32(0);
    if(_S74)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, i32(0), i32(0), _S73, _S66, _S67, _S68);
    }
    var _S75 : bool;
    if(_S70)
    {
        _S75 = _S72;
    }
    else
    {
        _S75 = false;
    }
    if(_S75)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, _S69, _S71, i32(0), _S66, _S67, _S68);
    }
    if(_S72)
    {
        _S75 = _S74;
    }
    else
    {
        _S75 = false;
    }
    if(_S75)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, i32(0), _S71, _S73, _S66, _S67, _S68);
    }
    if(_S70)
    {
        _S75 = _S74;
    }
    else
    {
        _S75 = false;
    }
    if(_S75)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, _S69, i32(0), _S73, _S66, _S67, _S68);
    }
    if(_S70)
    {
        _S75 = _S72;
    }
    else
    {
        _S75 = false;
    }
    if(_S75)
    {
        _S75 = _S74;
    }
    else
    {
        _S75 = false;
    }
    if(_S75)
    {
        NvFlowLocalWriteNeighbor4f_0(_S65, _S69, _S71, _S73, _S66, _S67, _S68);
    }
    return;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>, @builtin(local_invocation_id) groupThreadID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var blockIdx_3 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var blockIdx_4 : u32;
    if((gParams_0.dispatchBoundsLocations_0) != u32(0))
    {
        var _S76 : u32 = blockIdx_3 % gParams_0.locationExtent_0.x;
        var _S77 : i32 = i32(_S76) + gParams_0.locationOffset_1.x;
        var _S78 : u32 = blockIdx_3 / gParams_0.locationExtent_0.x;
        var _S79 : u32 = _S78 % gParams_0.locationExtent_0.y;
        var _S80 : i32 = i32(_S79) + gParams_0.locationOffset_1.y;
        var _S81 : u32 = blockIdx_3 / (gParams_0.locationExtent_0.x * gParams_0.locationExtent_0.y);
        blockIdx_4 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(_S77, _S80, i32(_S81) + gParams_0.locationOffset_1.z, gParams_0.locationOffset_1.w));
    }
    else
    {
        blockIdx_4 = blockIdx_3;
    }
    var location_0 : vec4<i32> = vec4<i32>(i32(0), i32(0), i32(0), i32(0));
    var _S82 : bool = NvFlowBlockIdxToLocation_0(unpackStorage_1(gParams_0.table_0), blockIdx_4, &(location_0));
    if(!_S82)
    {
        return;
    }
    if((location_0.w) != (gParams_0.layerAndLevel_0))
    {
        return;
    }
    var _S83 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(NvFlowSingleVirtualToReal_0(unpackStorage_1(gParams_0.table_0), blockIdx_4, threadIdx_3).xyz), u32(0)));
    var _S84 : u32 = (textureLoad((closestIn_0), ((_S83)).xyz, ((_S83)).w).x);
    if(_S84 != u32(4294967295))
    {
        var _S85 : vec4<f32> = (textureLoad((valueIn_0), ((_S83)).xyz, ((_S83)).w));
        var coupleRate_2 : vec4<f32> = gParams_0.defaultCoupleRate_0;
        var targetValue_2 : vec4<f32> = gParams_0.defaultTargetValue_0;
        var vidx_1 : vec3<i32> = (((location_0.xyz) << (vec3<u32>(vec3<i32>(gParams_0.table_0.blockDimBits_0))))) + threadIdx_3;
        fetchFaceValues_0(_S84, vidx_1, &(coupleRate_2), &(targetValue_2));
        targetValue_2 = targetValue_2 * gParams_0.targetValueScale_0;
        if((gParams_0.physicsVelocityScale_0) != 0.0f)
        {
            var worldPos_0 : vec3<f32> = gParams_0.vidxToWorld_0 * (vec3<f32>(vidx_1) + vec3<f32>(0.5f, 0.5f, 0.5f));
            var _S86 : vec3<f32> = targetValue_2.xyz + vec3<f32>(gParams_0.physicsVelocityScale_0) * ((worldPos_0 - (((unpackStorage_0(gParams_0.localToWorldOld_0)) * ((((unpackStorage_0(gParams_0.worldToLocal_0)) * (vec4<f32>(worldPos_0, 1.0f))))))).xyz) * vec3<f32>(gParams_0.physicsDeltaTimeInv_0));
            targetValue_2.x = _S86.x;
            targetValue_2.y = _S86.y;
            targetValue_2.z = _S86.z;
        }
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), blockIdx_4, threadIdx_3, _S85 + min(vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f), max(vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f), vec4<f32>(gParams_0.deltaTime_0) * coupleRate_2)) * (targetValue_2 - _S85));
    }
    return;
}

