// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct EmitterMeshCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) faceBlockIdx1Offset_0 : u32,
    @align(8) faceBlockIdx2Offset_0 : u32,
    @align(4) faceBlockIdx3Offset_0 : u32,
    @align(16) face1Count_0 : u32,
    @align(4) face2Count_0 : u32,
    @align(8) face3Count_0 : u32,
    @align(4) velocityIsWorldSpace_0 : u32,
    @align(16) rasterThickness_0 : f32,
    @align(4) minDistance_0 : f32,
    @align(8) maxDistance_0 : f32,
    @align(4) orientationLeftHanded_0 : u32,
    @align(16) emptyMin_0 : vec4<f32>,
    @align(16) emptyMax_0 : vec4<f32>,
    @align(16) dispatchBoundsLocations_0 : u32,
    @align(4) layerAndLevel_0 : i32,
    @align(8) needsSrgbConversion_0 : u32,
    @align(4) pad1_1 : u32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) localToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldVelocity_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) worldToLocal_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) localToWorldOld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) defaultTargetValue_0 : vec4<f32>,
    @align(16) defaultCoupleRate_0 : vec4<f32>,
    @align(16) targetValueScale_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) worldToVidx_0 : vec3<f32>,
    @align(4) isVelocity_0 : u32,
    @align(16) range_positions_0 : vec2<u32>,
    @align(8) range_faceVertexIndices_0 : vec2<u32>,
    @align(16) range_faceVertexCounts_0 : vec2<u32>,
    @align(8) range_faceVertexStarts_0 : vec2<u32>,
    @align(16) range_velocities_0 : vec2<u32>,
    @align(8) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(16) range_divergences_0 : vec2<u32>,
    @align(8) range_temperatures_0 : vec2<u32>,
    @align(16) range_fuels_0 : vec2<u32>,
    @align(8) range_burns_0 : vec2<u32>,
    @align(16) range_smokes_0 : vec2<u32>,
    @align(8) range_coupleRateVelocities_0 : vec2<u32>,
    @align(16) range_coupleRateDivergences_0 : vec2<u32>,
    @align(8) range_coupleRateTemperatures_0 : vec2<u32>,
    @align(16) range_coupleRateFuels_0 : vec2<u32>,
    @align(8) range_coupleRateBurns_0 : vec2<u32>,
    @align(16) range_coupleRateSmokes_0 : vec2<u32>,
    @align(8) range_colors_0 : vec2<u32>,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterMeshCS_Params_std140_0;
@binding(1) @group(0) var<storage, read> bounds2In_0 : array<vec4<u32>>;

@binding(2) @group(0) var<storage, read_write> bounds3Out_0 : array<vec4<u32>>;

var<workgroup> sboundsMin_0 : array<vec4<f32>, i32(256)>;

var<workgroup> sboundsMax_0 : array<vec4<f32>, i32(256)>;

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>, @builtin(local_invocation_id) groupThreadID_0 : vec3<u32>)
{
    var gthreadIdx_0 : u32 = dispatchThreadID_0.x + (((gParams_0.faceBlockIdx2Offset_0) << (u32(8))));
    var sthreadIdx_0 : u32 = groupThreadID_0.x;
    var _S1 : vec4<f32> = gParams_0.emptyMin_0;
    var _S2 : vec4<f32> = gParams_0.emptyMax_0;
    var bbox_min_0 : vec4<f32>;
    var bbox_max_0 : vec4<f32>;
    if(gthreadIdx_0 < (gParams_0.face2Count_0))
    {
        var _S3 : u32 = u32(2) * gthreadIdx_0;
        var _S4 : vec4<f32> = (bitcast<vec4<f32>>((bounds2In_0[_S3 + u32(1)])));
        bbox_min_0 = (bitcast<vec4<f32>>((bounds2In_0[_S3])));
        bbox_max_0 = _S4;
    }
    else
    {
        bbox_min_0 = _S1;
        bbox_max_0 = _S2;
    }
    sboundsMin_0[sthreadIdx_0] = bbox_min_0;
    sboundsMax_0[sthreadIdx_0] = bbox_max_0;
    workgroupBarrier();
    if(sthreadIdx_0 < u32(64))
    {
        var _S5 : u32 = sthreadIdx_0 + u32(64);
        var _S6 : u32 = sthreadIdx_0 + u32(128);
        var _S7 : u32 = sthreadIdx_0 + u32(192);
        var bbox_min_1 : vec4<f32> = min(min(min(bbox_min_0, sboundsMin_0[_S5]), sboundsMin_0[_S6]), sboundsMin_0[_S7]);
        var bbox_max_1 : vec4<f32> = max(max(max(bbox_max_0, sboundsMax_0[_S5]), sboundsMax_0[_S6]), sboundsMax_0[_S7]);
        sboundsMin_0[sthreadIdx_0] = bbox_min_1;
        sboundsMax_0[sthreadIdx_0] = bbox_max_1;
        bbox_min_0 = bbox_min_1;
        bbox_max_0 = bbox_max_1;
    }
    else
    {
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(16))
    {
        var _S8 : u32 = sthreadIdx_0 + u32(16);
        var _S9 : u32 = sthreadIdx_0 + u32(32);
        var _S10 : u32 = sthreadIdx_0 + u32(48);
        var bbox_min_2 : vec4<f32> = min(min(min(bbox_min_0, sboundsMin_0[_S8]), sboundsMin_0[_S9]), sboundsMin_0[_S10]);
        var bbox_max_2 : vec4<f32> = max(max(max(bbox_max_0, sboundsMax_0[_S8]), sboundsMax_0[_S9]), sboundsMax_0[_S10]);
        sboundsMin_0[sthreadIdx_0] = bbox_min_2;
        sboundsMax_0[sthreadIdx_0] = bbox_max_2;
        bbox_min_0 = bbox_min_2;
        bbox_max_0 = bbox_max_2;
    }
    else
    {
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(4))
    {
        var _S11 : u32 = sthreadIdx_0 + u32(4);
        var _S12 : u32 = sthreadIdx_0 + u32(8);
        var _S13 : u32 = sthreadIdx_0 + u32(12);
        var bbox_min_3 : vec4<f32> = min(min(min(bbox_min_0, sboundsMin_0[_S11]), sboundsMin_0[_S12]), sboundsMin_0[_S13]);
        var bbox_max_3 : vec4<f32> = max(max(max(bbox_max_0, sboundsMax_0[_S11]), sboundsMax_0[_S12]), sboundsMax_0[_S13]);
        sboundsMin_0[sthreadIdx_0] = bbox_min_3;
        sboundsMax_0[sthreadIdx_0] = bbox_max_3;
        bbox_min_0 = bbox_min_3;
        bbox_max_0 = bbox_max_3;
    }
    else
    {
    }
    workgroupBarrier();
    if(sthreadIdx_0 < u32(1))
    {
        var _S14 : u32 = sthreadIdx_0 + u32(1);
        var _S15 : u32 = sthreadIdx_0 + u32(2);
        var _S16 : u32 = sthreadIdx_0 + u32(3);
        var write_max_0 : vec4<u32> = (bitcast<vec4<u32>>((max(max(max(bbox_max_0, sboundsMax_0[_S14]), sboundsMax_0[_S15]), sboundsMax_0[_S16]))));
        var _S17 : u32 = u32(2) * ((gthreadIdx_0 >> (u32(8))));
        bounds3Out_0[_S17] = (bitcast<vec4<u32>>((min(min(min(bbox_min_0, sboundsMin_0[_S14]), sboundsMin_0[_S15]), sboundsMin_0[_S16]))));
        bounds3Out_0[_S17 + u32(1)] = write_max_0;
    }
    return;
}

