// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct _Array_std140_matrixx3Cfloatx2C4x2C4x3E32_0
{
    @align(16) data_1 : array<_MatrixStorage_float4x4_ColMajorstd140_0, i32(32)>,
};

struct EmitterSphereCS_Params_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) targetValue_0 : vec4<f32>,
    @align(16) coupleRate_0 : vec4<f32>,
    @align(16) vidxToWorld_0 : vec3<f32>,
    @align(4) pad4_0 : f32,
    @align(16) worldToLocals_0 : _Array_std140_matrixx3Cfloatx2C4x2C4x3E32_0,
    @align(16) localToWorldOlds_0 : _Array_std140_matrixx3Cfloatx2C4x2C4x3E32_0,
    @align(16) physicsVelocityScale_0 : f32,
    @align(4) physicsDeltaTimeInv_0 : f32,
    @align(8) multisample_0 : u32,
    @align(4) numSubSteps_0 : u32,
    @align(16) numSubStepsInv_0 : f32,
    @align(4) radius_0 : f32,
    @align(8) radius2_0 : f32,
    @align(4) deltaTime_0 : f32,
    @align(16) position_0 : vec3<f32>,
    @align(4) pad5_0 : f32,
    @align(16) locationOffset_1 : vec4<i32>,
    @align(16) locationExtent_0 : vec4<u32>,
    @align(16) velocityTable_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) numTraceSamples_0 : u32,
    @align(16) valueToVelocityBlockScale_0 : vec3<f32>,
    @align(4) traceDeltaTime_0 : f32,
};

@binding(0) @group(0) var<uniform> gParams_0 : EmitterSphereCS_Params_std140_0;
@binding(1) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var samplerIn_0 : sampler;

@binding(2) @group(0) var valueIn_0 : texture_3d<f32>;

@binding(5) @group(0) var valueOut_0 : texture_storage_3d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S4 : i32 = i32(threadIdx1D_0);
    var _S5 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S4 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S4 >> (u32(i32(_S5))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S4 >> (u32(i32(_S5 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S6 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S6, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S6 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowBlockIdxToLocation_0( _S7 : NvFlowSparseLevelParams_0,  _S8 : u32,  _S9 : ptr<function, vec4<i32>>) -> bool
{
    var _S10 : bool = _S8 < (_S7.numLocations_0);
    if(_S10)
    {
        var locationIdx_0 : u32 = ((_S8 << (u32(2)))) + _S7.locationOffset_0;
        (*_S9)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S9)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S9)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S9)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S9)[i32(0)] = i32(1073741824);
        (*_S9)[i32(1)] = i32(1073741824);
        (*_S9)[i32(2)] = i32(1073741824);
        (*_S9)[i32(3)] = i32(1073741824);
    }
    return _S10;
}

fn NvFlowLocationToBlockIdx_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S12.xyz) & ((_S11.tableDimLessOne_0)));
    var _S13 : u32 = ((((((((bucketIdx_0.z) << ((_S11.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S11.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S14 : u32 = gTable_0[_S13 + u32(1)];
    var _S15 : i32 = _S12.x;
    var _S16 : i32 = _S12.y;
    var _S17 : i32 = _S12.z;
    var _S18 : i32 = _S12.w;
    var blockIdx_0 : u32 = gTable_0[_S13];
    for(;;)
    {
        if(blockIdx_0 < _S14)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_0 << (u32(2)))) + _S11.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S19 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S15)
        {
            _S19 = compareLocation_y_0 == _S16;
        }
        else
        {
            _S19 = false;
        }
        var _S20 : bool;
        if(_S19)
        {
            _S20 = compareLocation_z_0 == _S17;
        }
        else
        {
            _S20 = false;
        }
        var _S21 : bool;
        if(_S20)
        {
            _S21 = compareLocation_w_0 == _S18;
        }
        else
        {
            _S21 = false;
        }
        if(_S21)
        {
            outBlockIdx_0 = blockIdx_0;
            break;
        }
        blockIdx_0 = blockIdx_0 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToReal_0( _S22 : NvFlowSparseLevelParams_0,  _S23 : vec4<i32>) -> vec4<i32>
{
    var _S24 : vec3<i32> = _S23.xyz;
    var _S25 : u32 = NvFlowLocationToBlockIdx_0(_S22, vec4<i32>((_S24 >> (vec3<u32>(vec3<i32>(_S22.blockDimBits_0)))), _S23.w));
    var tableValue_0 : u32;
    if(_S25 != u32(4294967295))
    {
        tableValue_0 = gTable_0[_S25 + _S22.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S24 & (vec3<i32>(_S22.blockDimLessOne_0))), tableValue_0);
}

fn NvFlowLocalReadLinearSafe4f_0( _S26 : texture_3d<f32>,  _S27 : sampler,  _S28 : NvFlowSparseLevelParams_0,  _S29 : u32,  _S30 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_1 : vec3<i32> = NvFlowFloor_i_0(_S30);
    var location_0 : vec4<i32>;
    var _S31 : bool = NvFlowBlockIdxToLocation_0(_S28, _S29, &(location_0));
    var _S32 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S28, vec4<i32>((((location_0.xyz) << (vec3<u32>(vec3<i32>(_S28.blockDimBits_0))))) + threadIdx_1, location_0.w));
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S32.xyz) + _S30 - vec3<f32>(threadIdx_1);
    var _S33 : vec4<f32>;
    if(bool(_S32.w))
    {
        _S33 = (textureSampleLevel((_S26), (_S27), (readIdxf_0 * _S28.dimInv_0), (0.0f)));
    }
    else
    {
        _S33 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S33;
}

fn computeCoverage_0( subStepIdx_0 : u32,  blockIdx_1 : u32,  threadIdx_2 : vec3<i32>,  worldPos_0 : vec3<f32>) -> f32
{
    var coverage_0 : f32;
    if((gParams_0.numTraceSamples_0) != u32(0))
    {
        var _S34 : vec3<f32> = vec3<f32>(threadIdx_2) + vec3<f32>(0.5f, 0.5f, 0.5f);
        var _S35 : f32 = 1.0f / f32(gParams_0.numTraceSamples_0);
        coverage_0 = 0.0f;
        var velSampleIdx_0 : u32 = u32(0);
        var threadIdxf_0 : vec3<f32> = _S34;
        var _S36 : vec3<f32> = worldPos_0;
        for(;;)
        {
            var _S37 : bool;
            if(velSampleIdx_0 < (gParams_0.numTraceSamples_0))
            {
                _S37 = velSampleIdx_0 < u32(256);
            }
            else
            {
                _S37 = false;
            }
            if(_S37)
            {
            }
            else
            {
                break;
            }
            var displacement_0 : vec3<f32> = vec3<f32>((_S35 * gParams_0.traceDeltaTime_0)) * gParams_0.cellSizeInv_0 * NvFlowLocalReadLinearSafe4f_0(velocityIn_0, samplerIn_0, unpackStorage_1(gParams_0.velocityTable_0), blockIdx_1, gParams_0.valueToVelocityBlockScale_0 * threadIdxf_0).xyz;
            var _S38 : vec4<f32> = (((unpackStorage_0(gParams_0.worldToLocals_0.data_1[subStepIdx_0])) * (vec4<f32>(_S36, 1.0f))));
            var localPos_0 : vec4<f32> = _S38;
            var _S39 : vec3<f32> = _S38.xyz - gParams_0.position_0;
            localPos_0.x = _S39.x;
            localPos_0.y = _S39.y;
            localPos_0.z = _S39.z;
            var _S40 : f32;
            if((dot(localPos_0.xyz, localPos_0.xyz)) < (gParams_0.radius2_0))
            {
                _S40 = 1.0f;
            }
            else
            {
                _S40 = 0.0f;
            }
            var _S41 : f32 = max(coverage_0, _S40);
            var _S42 : vec3<f32> = _S36 - gParams_0.vidxToWorld_0 * displacement_0;
            var threadIdxf_1 : vec3<f32> = threadIdxf_0 - displacement_0;
            var _S43 : u32 = velSampleIdx_0 + u32(1);
            coverage_0 = _S41;
            velSampleIdx_0 = _S43;
            threadIdxf_0 = threadIdxf_1;
            _S36 = _S42;
        }
    }
    else
    {
        var _S44 : vec4<f32> = (((unpackStorage_0(gParams_0.worldToLocals_0.data_1[subStepIdx_0])) * (vec4<f32>(worldPos_0, 1.0f))));
        var localPos_1 : vec4<f32> = _S44;
        var _S45 : vec3<f32> = _S44.xyz - gParams_0.position_0;
        localPos_1.x = _S45.x;
        localPos_1.y = _S45.y;
        localPos_1.z = _S45.z;
        if((dot(localPos_1.xyz, localPos_1.xyz)) < (gParams_0.radius2_0))
        {
            coverage_0 = 1.0f;
        }
        else
        {
            coverage_0 = 0.0f;
        }
    }
    return coverage_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_2 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_2 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_3 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S46 : i32 = threadIdx_3.x;
    if(_S46 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S46 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S47 : i32 = threadIdx_3.y;
    if(_S47 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S47 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S48 : i32 = threadIdx_3.z;
    if(_S48 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S48 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_4 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_4.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_4.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_4.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowLocalVirtualToReal_0( _S49 : NvFlowSparseLevelParams_0,  _S50 : u32,  _S51 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S51 >> (vec3<u32>(vec3<i32>(_S49.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S51, gTable_0[NvFlowNeighborToIdx_0(_S50, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S49.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S52 : texture_3d<f32>,  _S53 : NvFlowSparseLevelParams_0,  _S54 : u32,  _S55 : vec3<i32>) -> vec4<f32>
{
    var _S56 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S53, _S54, _S55);
    var _S57 : vec4<f32>;
    if(bool(_S56.w))
    {
        var _S58 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S56.xyz), u32(0)));
        _S57 = (textureLoad((_S52), ((_S58)).xyz, ((_S58)).w));
    }
    else
    {
        _S57 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S57;
}

fn NvFlowLocalWriteNeighbor4f_0( _S59 : NvFlowSparseLevelParams_0,  _S60 : i32,  _S61 : i32,  _S62 : i32,  _S63 : u32,  _S64 : vec3<i32>,  _S65 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S64, gTable_0[NvFlowNeighborToIdx_0(_S63, _S60, _S61, _S62) + _S59.blockLevelOffsetLocal_0], _S60, _S61, _S62);
    var _S66 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S67 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S67 = _S65;
    }
    else
    {
        _S67 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((valueOut_0), (_S66), (_S67));
    return;
}

fn NvFlowLocalWrite4f_0( _S68 : NvFlowSparseLevelParams_0,  _S69 : u32,  _S70 : vec3<i32>,  _S71 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S68, _S70);
    NvFlowLocalWriteNeighbor4f_0(_S68, i32(0), i32(0), i32(0), _S69, _S70, _S71);
    var _S72 : i32 = neighbor_2.x;
    var _S73 : bool = _S72 != i32(0);
    if(_S73)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, _S72, i32(0), i32(0), _S69, _S70, _S71);
    }
    var _S74 : i32 = neighbor_2.y;
    var _S75 : bool = _S74 != i32(0);
    if(_S75)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, i32(0), _S74, i32(0), _S69, _S70, _S71);
    }
    var _S76 : i32 = neighbor_2.z;
    var _S77 : bool = _S76 != i32(0);
    if(_S77)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, i32(0), i32(0), _S76, _S69, _S70, _S71);
    }
    var _S78 : bool;
    if(_S73)
    {
        _S78 = _S75;
    }
    else
    {
        _S78 = false;
    }
    if(_S78)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, _S72, _S74, i32(0), _S69, _S70, _S71);
    }
    if(_S75)
    {
        _S78 = _S77;
    }
    else
    {
        _S78 = false;
    }
    if(_S78)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, i32(0), _S74, _S76, _S69, _S70, _S71);
    }
    if(_S73)
    {
        _S78 = _S77;
    }
    else
    {
        _S78 = false;
    }
    if(_S78)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, _S72, i32(0), _S76, _S69, _S70, _S71);
    }
    if(_S73)
    {
        _S78 = _S75;
    }
    else
    {
        _S78 = false;
    }
    if(_S78)
    {
        _S78 = _S77;
    }
    else
    {
        _S78 = false;
    }
    if(_S78)
    {
        NvFlowLocalWriteNeighbor4f_0(_S68, _S72, _S74, _S76, _S69, _S70, _S71);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_5 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_1(gParams_0.table_0), dispatchThreadID_0.x);
    var locationIdx_1 : u32 = groupID_0.y + gParams_0.blockIdxOffset_0;
    var _S79 : u32 = locationIdx_1 % gParams_0.locationExtent_0.x;
    var _S80 : i32 = i32(_S79) + gParams_0.locationOffset_1.x;
    var _S81 : u32 = locationIdx_1 / gParams_0.locationExtent_0.x;
    var _S82 : u32 = _S81 % gParams_0.locationExtent_0.y;
    var _S83 : i32 = i32(_S82) + gParams_0.locationOffset_1.y;
    var _S84 : u32 = locationIdx_1 / (gParams_0.locationExtent_0.x * gParams_0.locationExtent_0.y);
    var _S85 : i32 = i32(_S84) + gParams_0.locationOffset_1.z;
    var _S86 : u32 = NvFlowLocationToBlockIdx_0(unpackStorage_1(gParams_0.table_0), vec4<i32>(_S80, _S83, _S85, gParams_0.locationOffset_1.w));
    if(_S86 >= (gParams_0.table_0.numLocations_0))
    {
        return;
    }
    var _S87 : vec3<f32> = gParams_0.vidxToWorld_0 * (vec3<f32>(((vec3<i32>(_S80, _S83, _S85) << ((gParams_0.table_0.blockDimBits_0)))) + threadIdx_5) + vec3<f32>(0.5f, 0.5f, 0.5f));
    const _S88 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    const _S89 : vec3<f32> = vec3<f32>(-0.25f, -0.25f, -0.25f);
    const _S90 : vec3<f32> = vec3<f32>(0.25f, -0.25f, -0.25f);
    const _S91 : vec3<f32> = vec3<f32>(-0.25f, 0.25f, -0.25f);
    const _S92 : vec3<f32> = vec3<f32>(0.25f, 0.25f, -0.25f);
    const _S93 : vec3<f32> = vec3<f32>(-0.25f, -0.25f, 0.25f);
    const _S94 : vec3<f32> = vec3<f32>(0.25f, -0.25f, 0.25f);
    const _S95 : vec3<f32> = vec3<f32>(-0.25f, 0.25f, 0.25f);
    const _S96 : vec3<f32> = vec3<f32>(0.25f, 0.25f, 0.25f);
    const _S97 : vec4<f32> = vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f);
    var _S98 : vec4<f32> = vec4<f32>(_S87, 1.0f);
    var valueIsValid_0 : bool = false;
    var subStepIdx_1 : u32 = u32(0);
    var value_0 : vec4<f32> = _S88;
    for(;;)
    {
        if(subStepIdx_1 < (gParams_0.numSubSteps_0))
        {
        }
        else
        {
            break;
        }
        var coverage_1 : f32;
        if((gParams_0.multisample_0) != u32(0))
        {
            coverage_1 = 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S89 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S90 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S91 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S92 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S93 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S94 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S95 * gParams_0.vidxToWorld_0) + 0.125f * computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87 + _S96 * gParams_0.vidxToWorld_0);
        }
        else
        {
            coverage_1 = computeCoverage_0(subStepIdx_1, _S86, threadIdx_5, _S87);
        }
        if(coverage_1 > 0.0f)
        {
            var valueIsValid_1 : bool;
            var value_1 : vec4<f32>;
            if(!valueIsValid_0)
            {
                var _S99 : vec4<f32> = NvFlowLocalRead4f_0(valueIn_0, unpackStorage_1(gParams_0.table_0), _S86, threadIdx_5);
                valueIsValid_1 = true;
                value_1 = _S99;
            }
            else
            {
                valueIsValid_1 = valueIsValid_0;
                value_1 = value_0;
            }
            var valueRate_0 : vec4<f32> = min(_S97, max(_S88, vec4<f32>((gParams_0.numSubStepsInv_0 * gParams_0.deltaTime_0)) * gParams_0.coupleRate_0 * vec4<f32>(coverage_1)));
            var targetValue_1 : vec4<f32> = gParams_0.targetValue_0;
            if((gParams_0.physicsVelocityScale_0) != 0.0f)
            {
                var _S100 : vec3<f32> = targetValue_1.xyz + vec3<f32>(gParams_0.physicsVelocityScale_0) * ((_S87 - (((unpackStorage_0(gParams_0.localToWorldOlds_0.data_1[subStepIdx_1])) * ((((unpackStorage_0(gParams_0.worldToLocals_0.data_1[subStepIdx_1])) * (_S98)))))).xyz) * vec3<f32>(gParams_0.physicsDeltaTimeInv_0) * vec3<f32>(f32(gParams_0.numSubSteps_0)));
                targetValue_1.x = _S100.x;
                targetValue_1.y = _S100.y;
                targetValue_1.z = _S100.z;
            }
            var value_2 : vec4<f32> = value_1 + valueRate_0 * (targetValue_1 - value_1);
            valueIsValid_0 = valueIsValid_1;
            value_0 = value_2;
        }
        subStepIdx_1 = subStepIdx_1 + u32(1);
    }
    if(valueIsValid_0)
    {
        NvFlowLocalWrite4f_0(unpackStorage_1(gParams_0.table_0), _S86, threadIdx_5, value_0);
    }
    return;
}

