// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// Generated by pinned Slang; see manifest.json.
struct RadixSortCSParams_std140_0
{
    @align(16) gridDim_0 : u32,
    @align(4) passStart_0 : u32,
    @align(8) passMask_0 : u32,
    @align(4) passNumBits_0 : u32,
    @align(16) numCounters_0 : u32,
    @align(4) numKeyBits_0 : u32,
    @align(8) numKeys_0 : u32,
    @align(4) pad1_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : RadixSortCSParams_std140_0;
@binding(1) @group(0) var<storage, read> countersIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read_write> countersOut_0 : array<u32>;

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

fn blockScan_0( threadIdx_0 : u32,  val_0 : vec4<u32>,  totalCount_0 : ptr<function, u32>) -> vec4<u32>
{
    var _S1 : u32 = val_0.y;
    var _S2 : u32 = val_0.z;
    var _S3 : u32 = val_0.w;
    var localVal_0 : u32 = val_0.x + _S1 + _S2 + _S3;
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    var localVal_1 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_1 = localVal_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_1 = localVal_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(2)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(3)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(4)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(8)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(12)];
    }
    else
    {
    }
    sdata0_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(16)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(32)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(48)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(64)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(128)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(192)];
    }
    else
    {
    }
    var retVal_0 : vec4<u32>;
    retVal_0[i32(3)] = localVal_1;
    retVal_0[i32(2)] = retVal_0.w - _S3;
    retVal_0[i32(1)] = retVal_0.z - _S2;
    retVal_0[i32(0)] = retVal_0.y - _S1;
    (*totalCount_0) = sdata1_0[i32(63)] + sdata1_0[i32(127)] + sdata1_0[i32(191)] + sdata1_0[i32(255)];
    return retVal_0;
}

fn read4_0( _S4 : u32) -> vec4<u32>
{
    var _S5 : u32 = u32(4) * _S4;
    return vec4<u32>(countersIn_0[_S5], countersIn_0[_S5 + u32(1)], countersIn_0[_S5 + u32(2)], countersIn_0[_S5 + u32(3)]);
}

fn write4_0( _S6 : u32,  _S7 : vec4<u32>)
{
    var _S8 : u32 = u32(4) * _S6;
    countersOut_0[_S8] = _S7.x;
    countersOut_0[_S8 + u32(1)] = _S7.y;
    countersOut_0[_S8 + u32(2)] = _S7.z;
    countersOut_0[_S8 + u32(3)] = _S7.w;
    return;
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_1 : u32 = dispatchThreadID_0.x;
    var passID_0 : u32;
    var idx_0 : u32;
    var globalOffset_0 : u32;
    var countLocal_0 : vec4<u32>;
    if((groupID_0.y) == u32(0))
    {
        var _S9 : u32 = (paramsIn_0.numCounters_0 / u32(4) + u32(256) - u32(1)) / u32(256);
        const _S10 : vec4<u32> = vec4<u32>(u32(0), u32(0), u32(0), u32(0));
        passID_0 = u32(0);
        idx_0 = threadIdx_1;
        globalOffset_0 = u32(0);
        for(;;)
        {
            if(passID_0 < _S9)
            {
            }
            else
            {
                break;
            }
            var blockOffset_0 : u32 = u32(0);
            if(idx_0 < (paramsIn_0.numCounters_0 / u32(4)))
            {
                countLocal_0 = read4_0(idx_0);
            }
            else
            {
                countLocal_0 = _S10;
            }
            var _S11 : vec4<u32> = blockScan_0(threadIdx_1, countLocal_0, &(blockOffset_0));
            var countGlobal_0 : vec4<u32> = _S11;
            countGlobal_0[i32(0)] = countGlobal_0[i32(0)] - countLocal_0.x;
            countGlobal_0[i32(1)] = countGlobal_0[i32(1)] - countLocal_0.y;
            countGlobal_0[i32(2)] = countGlobal_0[i32(2)] - countLocal_0.z;
            countGlobal_0[i32(3)] = countGlobal_0[i32(3)] - countLocal_0.w;
            countGlobal_0[i32(0)] = countGlobal_0[i32(0)] + globalOffset_0;
            countGlobal_0[i32(1)] = countGlobal_0[i32(1)] + globalOffset_0;
            countGlobal_0[i32(2)] = countGlobal_0[i32(2)] + globalOffset_0;
            countGlobal_0[i32(3)] = countGlobal_0[i32(3)] + globalOffset_0;
            if(idx_0 < (paramsIn_0.numCounters_0 / u32(4)))
            {
                write4_0(idx_0, countGlobal_0);
            }
            var globalOffset_1 : u32 = globalOffset_0 + blockOffset_0;
            var idx_1 : u32 = idx_0 + u32(256);
            passID_0 = passID_0 + u32(1);
            idx_0 = idx_1;
            globalOffset_0 = globalOffset_1;
        }
    }
    else
    {
        var _S12 : u32 = (paramsIn_0.numCounters_0 / u32(4) + u32(256) - u32(1)) / u32(256);
        var _S13 : u32 = (threadIdx_1 & (u32(3)));
        var _S14 : bool = _S13 >= u32(1);
        const _S15 : vec4<u32> = vec4<u32>(u32(0), u32(0), u32(0), u32(0));
        var _S16 : bool = _S13 >= u32(2);
        var _S17 : bool = _S13 >= u32(3);
        passID_0 = u32(0);
        idx_0 = threadIdx_1;
        for(;;)
        {
            if(passID_0 < _S12)
            {
            }
            else
            {
                break;
            }
            var countLocal_1 : vec4<u32>;
            if(idx_0 < (paramsIn_0.numCounters_0 / u32(4)))
            {
                countLocal_0 = read4_0(idx_0 + paramsIn_0.numCounters_0 / u32(4));
            }
            else
            {
                countLocal_0 = _S15;
            }
            countLocal_1 = countLocal_0;
            sdata0_0[threadIdx_1] = countLocal_0.x + countLocal_0.y + countLocal_0.z + countLocal_0.w;
            workgroupBarrier();
            if(_S14)
            {
                globalOffset_0 = sdata0_0[u32(4) * (threadIdx_1 / u32(4))];
            }
            else
            {
                globalOffset_0 = u32(0);
            }
            var scanTotal_0 : u32;
            if(_S16)
            {
                scanTotal_0 = globalOffset_0 + sdata0_0[u32(4) * (threadIdx_1 / u32(4)) + u32(1)];
            }
            else
            {
                scanTotal_0 = globalOffset_0;
            }
            var scanTotal_1 : u32;
            if(_S17)
            {
                scanTotal_1 = scanTotal_0 + sdata0_0[u32(4) * (threadIdx_1 / u32(4)) + u32(2)];
            }
            else
            {
                scanTotal_1 = scanTotal_0;
            }
            countLocal_1[i32(3)] = countLocal_1.z + countLocal_1.y + countLocal_1.x + scanTotal_1;
            countLocal_1[i32(2)] = countLocal_1.y + countLocal_1.x + scanTotal_1;
            countLocal_1[i32(1)] = countLocal_1.x + scanTotal_1;
            countLocal_1[i32(0)] = scanTotal_1;
            if(idx_0 < (paramsIn_0.numCounters_0 / u32(4)))
            {
                write4_0(idx_0 + paramsIn_0.numCounters_0 / u32(4), countLocal_1);
            }
            var idx_2 : u32 = idx_0 + u32(256);
            passID_0 = passID_0 + u32(1);
            idx_0 = idx_2;
        }
    }
    return;
}

