// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct RadixSortCSParams_std140_0
{
    @align(16) gridDim_0 : u32,
    @align(4) passStart_0 : u32,
    @align(8) passMask_0 : u32,
    @align(4) passNumBits_0 : u32,
    @align(16) numCounters_0 : u32,
    @align(4) numKeyBits_0 : u32,
    @align(8) numKeys_0 : u32,
    @align(4) pad1_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : RadixSortCSParams_std140_0;
@binding(1) @group(0) var<storage, read_write> keyDst_0 : array<u32>;

@compute
@workgroup_size(1024, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var padIdx_0 : u32 = ((((((paramsIn_0.numKeys_0 + u32(1023)) >> (u32(10)))) - u32(1)) << (u32(10)))) + dispatchThreadID_0.x;
    if(padIdx_0 >= (paramsIn_0.numKeys_0))
    {
        keyDst_0[padIdx_0] = u32(4294967295);
    }
    return;
}

