// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// Generated by pinned Slang; see manifest.json.
@binding(1) @group(0) var<storage, read> keyIn_0 : array<u32>;

struct RadixSortCSParams_std140_0
{
    @align(16) gridDim_0 : u32,
    @align(4) passStart_0 : u32,
    @align(8) passMask_0 : u32,
    @align(4) passNumBits_0 : u32,
    @align(16) numCounters_0 : u32,
    @align(4) numKeyBits_0 : u32,
    @align(8) numKeys_0 : u32,
    @align(4) pad1_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : RadixSortCSParams_std140_0;
@binding(2) @group(0) var<storage, read_write> countersOut_0 : array<u32>;

fn count_0( counter_0 : ptr<function, vec4<u32>>,  bucket_0 : u32)
{
    if(bucket_0 == u32(0))
    {
        (*counter_0)[i32(0)] = (*counter_0)[i32(0)] + u32(1);
    }
    if(bucket_0 == u32(1))
    {
        (*counter_0)[i32(0)] = (*counter_0)[i32(0)] + u32(65536);
    }
    if(bucket_0 == u32(2))
    {
        (*counter_0)[i32(1)] = (*counter_0)[i32(1)] + u32(1);
    }
    if(bucket_0 == u32(3))
    {
        (*counter_0)[i32(1)] = (*counter_0)[i32(1)] + u32(65536);
    }
    if(bucket_0 == u32(4))
    {
        (*counter_0)[i32(2)] = (*counter_0)[i32(2)] + u32(1);
    }
    if(bucket_0 == u32(5))
    {
        (*counter_0)[i32(2)] = (*counter_0)[i32(2)] + u32(65536);
    }
    if(bucket_0 == u32(6))
    {
        (*counter_0)[i32(3)] = (*counter_0)[i32(3)] + u32(1);
    }
    if(bucket_0 == u32(7))
    {
        (*counter_0)[i32(3)] = (*counter_0)[i32(3)] + u32(65536);
    }
    if(bucket_0 == u32(8))
    {
        (*counter_0)[i32(0)] = (*counter_0)[i32(0)] + u32(256);
    }
    if(bucket_0 == u32(9))
    {
        (*counter_0)[i32(0)] = (*counter_0)[i32(0)] + u32(16777216);
    }
    if(bucket_0 == u32(10))
    {
        (*counter_0)[i32(1)] = (*counter_0)[i32(1)] + u32(256);
    }
    if(bucket_0 == u32(11))
    {
        (*counter_0)[i32(1)] = (*counter_0)[i32(1)] + u32(16777216);
    }
    if(bucket_0 == u32(12))
    {
        (*counter_0)[i32(2)] = (*counter_0)[i32(2)] + u32(256);
    }
    if(bucket_0 == u32(13))
    {
        (*counter_0)[i32(2)] = (*counter_0)[i32(2)] + u32(16777216);
    }
    if(bucket_0 == u32(14))
    {
        (*counter_0)[i32(3)] = (*counter_0)[i32(3)] + u32(256);
    }
    if(bucket_0 == u32(15))
    {
        (*counter_0)[i32(3)] = (*counter_0)[i32(3)] + u32(16777216);
    }
    return;
}

var<workgroup> scount0_0 : array<vec4<u32>, i32(256)>;

var<workgroup> scount1_0 : array<vec4<u32>, i32(64)>;

fn expand8to16L_0( counter_1 : vec4<u32>) -> vec4<u32>
{
    var counterL_0 : vec4<u32>;
    counterL_0[i32(0)] = ((counter_1.x) & (u32(16711935)));
    counterL_0[i32(1)] = ((counter_1.y) & (u32(16711935)));
    counterL_0[i32(2)] = ((counter_1.z) & (u32(16711935)));
    counterL_0[i32(3)] = ((counter_1.w) & (u32(16711935)));
    return counterL_0;
}

fn expand8to16H_0( counter_2 : vec4<u32>) -> vec4<u32>
{
    var counterH_0 : vec4<u32>;
    counterH_0[i32(0)] = ((((counter_2.x) & (u32(4278255360)))) >> (u32(8)));
    counterH_0[i32(1)] = ((((counter_2.y) & (u32(4278255360)))) >> (u32(8)));
    counterH_0[i32(2)] = ((((counter_2.z) & (u32(4278255360)))) >> (u32(8)));
    counterH_0[i32(3)] = ((((counter_2.w) & (u32(4278255360)))) >> (u32(8)));
    return counterH_0;
}

fn read4_0( _S1 : u32) -> vec4<u32>
{
    var _S2 : u32 = u32(4) * _S1;
    return vec4<u32>(keyIn_0[_S2], keyIn_0[_S2 + u32(1)], keyIn_0[_S2 + u32(2)], keyIn_0[_S2 + u32(3)]);
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var threadIdx_0 : u32 = dispatchThreadID_0.x;
    var blockIdx_0 : u32 = dispatchThreadID_0.y;
    var globalOffset_0 : u32 = blockIdx_0 * u32(256);
    var localCount_0 : vec4<u32> = vec4<u32>(u32(0), u32(0), u32(0), u32(0));
    var _S3 : vec4<u32> = read4_0(threadIdx_0 + globalOffset_0);
    var keyLocal_0 : vec4<u32> = _S3;
    keyLocal_0[i32(0)] = ((((_S3.x) >> ((paramsIn_0.passStart_0)))) & ((paramsIn_0.passMask_0)));
    keyLocal_0[i32(1)] = ((((keyLocal_0.y) >> ((paramsIn_0.passStart_0)))) & ((paramsIn_0.passMask_0)));
    keyLocal_0[i32(2)] = ((((keyLocal_0.z) >> ((paramsIn_0.passStart_0)))) & ((paramsIn_0.passMask_0)));
    keyLocal_0[i32(3)] = ((((keyLocal_0.w) >> ((paramsIn_0.passStart_0)))) & ((paramsIn_0.passMask_0)));
    count_0(&(localCount_0), keyLocal_0.x);
    count_0(&(localCount_0), keyLocal_0.y);
    count_0(&(localCount_0), keyLocal_0.z);
    count_0(&(localCount_0), keyLocal_0.w);
    scount0_0[threadIdx_0] = localCount_0;
    workgroupBarrier();
    if(threadIdx_0 < u32(64))
    {
        var _S4 : vec4<u32> = scount0_0[threadIdx_0];
        localCount_0 = scount0_0[threadIdx_0];
        var _S5 : vec4<u32> = _S4 + scount0_0[threadIdx_0 + u32(64)];
        localCount_0 = _S5;
        var _S6 : vec4<u32> = _S5 + scount0_0[threadIdx_0 + u32(128)];
        localCount_0 = _S6;
        var _S7 : vec4<u32> = _S6 + scount0_0[threadIdx_0 + u32(192)];
        localCount_0 = _S7;
        scount1_0[threadIdx_0] = _S7;
    }
    workgroupBarrier();
    if(threadIdx_0 < u32(16))
    {
        var _S8 : vec4<u32> = expand8to16L_0(scount1_0[threadIdx_0]);
        localCount_0 = _S8;
        var localCountH_0 : vec4<u32> = expand8to16H_0(scount1_0[threadIdx_0]);
        var _S9 : u32 = threadIdx_0 + u32(16);
        var _S10 : vec4<u32> = _S8 + expand8to16L_0(scount1_0[_S9]);
        localCount_0 = _S10;
        var localCountH_1 : vec4<u32> = localCountH_0 + expand8to16H_0(scount1_0[_S9]);
        var _S11 : vec4<u32> = _S10 + expand8to16L_0(scount1_0[threadIdx_0 + u32(32)]);
        localCount_0 = _S11;
        var localCountH_2 : vec4<u32> = localCountH_1 + expand8to16H_0(scount1_0[threadIdx_0 + u32(32)]);
        var _S12 : vec4<u32> = _S11 + expand8to16L_0(scount1_0[threadIdx_0 + u32(48)]);
        localCount_0 = _S12;
        var localCountH_3 : vec4<u32> = localCountH_2 + expand8to16H_0(scount1_0[threadIdx_0 + u32(48)]);
        scount0_0[threadIdx_0] = _S12;
        scount0_0[_S9] = localCountH_3;
    }
    workgroupBarrier();
    var setID_0 : u32 = threadIdx_0 / u32(128);
    var setLaneID_0 : u32 = (threadIdx_0 & (u32(127)));
    if(setLaneID_0 < u32(4))
    {
        var _S13 : u32 = setID_0 * u32(256);
        var offset_0 : u32 = _S13 / u32(16);
        var _S14 : vec4<u32> = scount0_0[setLaneID_0 + offset_0];
        localCount_0 = scount0_0[setLaneID_0 + offset_0];
        var _S15 : vec4<u32> = _S14 + scount0_0[setLaneID_0 + u32(4) + offset_0];
        localCount_0 = _S15;
        var _S16 : vec4<u32> = _S15 + scount0_0[setLaneID_0 + u32(8) + offset_0];
        localCount_0 = _S16;
        var _S17 : vec4<u32> = _S16 + scount0_0[setLaneID_0 + u32(12) + offset_0];
        localCount_0 = _S17;
        scount1_0[setLaneID_0 + _S13 / u32(64)] = _S17;
    }
    workgroupBarrier();
    if(setLaneID_0 == u32(0))
    {
        var offset_1 : u32 = setID_0 * u32(256) / u32(64);
        var _S18 : vec4<u32> = scount1_0[offset_1];
        localCount_0 = scount1_0[offset_1];
        var _S19 : vec4<u32> = _S18 + scount1_0[u32(1) + offset_1];
        localCount_0 = _S19;
        var _S20 : vec4<u32> = _S19 + scount1_0[u32(2) + offset_1];
        localCount_0 = _S20;
        var _S21 : vec4<u32> = _S20 + scount1_0[u32(3) + offset_1];
        localCount_0 = _S21;
        var bucketOffset_0 : u32 = u32(8) * setID_0;
        countersOut_0[bucketOffset_0 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((_S21.x) & (u32(65535)))) >> (u32(0)));
        var _S22 : u32 = bucketOffset_0 + u32(1);
        countersOut_0[_S22 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.x) & (u32(4294901760)))) >> (u32(16)));
        var _S23 : u32 = bucketOffset_0 + u32(2);
        countersOut_0[_S23 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.y) & (u32(65535)))) >> (u32(0)));
        var _S24 : u32 = bucketOffset_0 + u32(3);
        countersOut_0[_S24 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.y) & (u32(4294901760)))) >> (u32(16)));
        var _S25 : u32 = bucketOffset_0 + u32(4);
        countersOut_0[_S25 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.z) & (u32(65535)))) >> (u32(0)));
        var _S26 : u32 = bucketOffset_0 + u32(5);
        countersOut_0[_S26 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.z) & (u32(4294901760)))) >> (u32(16)));
        var _S27 : u32 = bucketOffset_0 + u32(6);
        countersOut_0[_S27 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.w) & (u32(65535)))) >> (u32(0)));
        var _S28 : u32 = bucketOffset_0 + u32(7);
        countersOut_0[_S28 * paramsIn_0.gridDim_0 + blockIdx_0] = ((((localCount_0.w) & (u32(4294901760)))) >> (u32(16)));
        countersOut_0[bucketOffset_0 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.x) & (u32(65535)))) >> (u32(0)));
        countersOut_0[_S22 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.x) & (u32(4294901760)))) >> (u32(16)));
        countersOut_0[_S23 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.y) & (u32(65535)))) >> (u32(0)));
        countersOut_0[_S24 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.y) & (u32(4294901760)))) >> (u32(16)));
        countersOut_0[_S25 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.z) & (u32(65535)))) >> (u32(0)));
        countersOut_0[_S26 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.z) & (u32(4294901760)))) >> (u32(16)));
        countersOut_0[_S27 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.w) & (u32(65535)))) >> (u32(0)));
        countersOut_0[_S28 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)] = ((((localCount_0.w) & (u32(4294901760)))) >> (u32(16)));
    }
    return;
}

