// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// Generated by pinned Slang; see manifest.json.
struct RadixSortCSParams_std140_0
{
    @align(16) gridDim_0 : u32,
    @align(4) passStart_0 : u32,
    @align(8) passMask_0 : u32,
    @align(4) passNumBits_0 : u32,
    @align(16) numCounters_0 : u32,
    @align(4) numKeyBits_0 : u32,
    @align(8) numKeys_0 : u32,
    @align(4) pad1_0 : u32,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : RadixSortCSParams_std140_0;
@binding(3) @group(0) var<storage, read> countersIn_0 : array<u32>;

@binding(1) @group(0) var<storage, read> keyIn_0 : array<u32>;

@binding(2) @group(0) var<storage, read> valIn_0 : array<u32>;

@binding(4) @group(0) var<storage, read_write> keyOut_0 : array<u32>;

@binding(5) @group(0) var<storage, read_write> valOut_0 : array<u32>;

var<workgroup> globalCounters_0 : array<u32, i32(16)>;

var<workgroup> localCounters_0 : array<u32, i32(16)>;

var<workgroup> sdata0_0 : array<u32, i32(256)>;

var<workgroup> sdata1_0 : array<u32, i32(256)>;

fn blockScan_0( threadIdx_0 : u32,  val_0 : vec4<u32>,  totalCount_0 : ptr<function, u32>) -> vec4<u32>
{
    var _S1 : u32 = val_0.y;
    var _S2 : u32 = val_0.z;
    var _S3 : u32 = val_0.w;
    var localVal_0 : u32 = val_0.x + _S1 + _S2 + _S3;
    sdata0_0[threadIdx_0] = localVal_0;
    workgroupBarrier();
    var localVal_1 : u32;
    if(threadIdx_0 >= u32(1))
    {
        localVal_1 = localVal_0 + sdata0_0[threadIdx_0 - u32(1)];
    }
    else
    {
        localVal_1 = localVal_0;
    }
    if(threadIdx_0 >= u32(2))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(2)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(3))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(3)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(4))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(4)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(8))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(8)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(12))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(12)];
    }
    else
    {
    }
    sdata0_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(16))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(16)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(32))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(32)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(48))
    {
        localVal_1 = localVal_1 + sdata0_0[threadIdx_0 - u32(48)];
    }
    else
    {
    }
    sdata1_0[threadIdx_0] = localVal_1;
    workgroupBarrier();
    if(threadIdx_0 >= u32(64))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(64)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(128))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(128)];
    }
    else
    {
    }
    if(threadIdx_0 >= u32(192))
    {
        localVal_1 = localVal_1 + sdata1_0[threadIdx_0 - u32(192)];
    }
    else
    {
    }
    var retVal_0 : vec4<u32>;
    retVal_0[i32(3)] = localVal_1;
    retVal_0[i32(2)] = retVal_0.w - _S3;
    retVal_0[i32(1)] = retVal_0.z - _S2;
    retVal_0[i32(0)] = retVal_0.y - _S1;
    (*totalCount_0) = sdata1_0[i32(63)] + sdata1_0[i32(127)] + sdata1_0[i32(191)] + sdata1_0[i32(255)];
    return retVal_0;
}

fn split4_0( threadIdx_1 : u32,  pred_0 : vec4<u32>) -> vec4<u32>
{
    var totalCount_1 : u32;
    var scanVal_0 : vec4<u32> = blockScan_0(threadIdx_1, pred_0, &(totalCount_1));
    var rank_0 : vec4<u32>;
    var _S4 : u32;
    if(bool(pred_0.x))
    {
        _S4 = scanVal_0.x - u32(1);
    }
    else
    {
        _S4 = u32(4) * threadIdx_1 - scanVal_0.x + totalCount_1;
    }
    rank_0[i32(0)] = _S4;
    if(bool(pred_0.y))
    {
        _S4 = scanVal_0.y - u32(1);
    }
    else
    {
        _S4 = u32(4) * threadIdx_1 + u32(1) - scanVal_0.y + totalCount_1;
    }
    rank_0[i32(1)] = _S4;
    if(bool(pred_0.z))
    {
        _S4 = scanVal_0.z - u32(1);
    }
    else
    {
        _S4 = u32(4) * threadIdx_1 + u32(2) - scanVal_0.z + totalCount_1;
    }
    rank_0[i32(2)] = _S4;
    if(bool(pred_0.w))
    {
        _S4 = scanVal_0.w - u32(1);
    }
    else
    {
        _S4 = u32(4) * threadIdx_1 + u32(3) - scanVal_0.w + totalCount_1;
    }
    rank_0[i32(3)] = _S4;
    return rank_0;
}

var<workgroup> skey_0 : array<u32, i32(1024)>;

var<workgroup> sval_0 : array<u32, i32(1024)>;

fn read4_0( _S5 : u32) -> vec4<u32>
{
    var _S6 : u32 = u32(4) * _S5;
    return vec4<u32>(keyIn_0[_S6], keyIn_0[_S6 + u32(1)], keyIn_0[_S6 + u32(2)], keyIn_0[_S6 + u32(3)]);
}

fn read4_1( _S7 : u32) -> vec4<u32>
{
    var _S8 : u32 = u32(4) * _S7;
    return vec4<u32>(valIn_0[_S8], valIn_0[_S8 + u32(1)], valIn_0[_S8 + u32(2)], valIn_0[_S8 + u32(3)]);
}

@compute
@workgroup_size(256, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var threadIdx_2 : u32 = dispatchThreadID_0.x;
    var blockIdx_0 : u32 = dispatchThreadID_0.y;
    var idx_0 : u32 = u32(256) * blockIdx_0 + threadIdx_2;
    if(threadIdx_2 < u32(16))
    {
        globalCounters_0[threadIdx_2] = countersIn_0[threadIdx_2 * paramsIn_0.gridDim_0 + blockIdx_0];
        localCounters_0[threadIdx_2] = countersIn_0[threadIdx_2 + u32(16) * (paramsIn_0.gridDim_0 + blockIdx_0)];
    }
    var keyLocal_0 : vec4<u32> = read4_0(idx_0);
    var valLocal_0 : vec4<u32> = read4_1(idx_0);
    var _S9 : u32 = u32(4) * threadIdx_2;
    var _S10 : u32 = _S9 + u32(1);
    var _S11 : u32 = _S9 + u32(2);
    var _S12 : u32 = _S9 + u32(3);
    var passID_0 : u32 = paramsIn_0.passStart_0;
    for(;;)
    {
        if(passID_0 < (paramsIn_0.passStart_0 + paramsIn_0.passNumBits_0))
        {
        }
        else
        {
            break;
        }
        var allocVal_0 : vec4<u32>;
        allocVal_0[i32(0)] = ((((((keyLocal_0.x) >> (passID_0))) & (u32(1)))) ^ (u32(1)));
        allocVal_0[i32(1)] = ((((((keyLocal_0.y) >> (passID_0))) & (u32(1)))) ^ (u32(1)));
        allocVal_0[i32(2)] = ((((((keyLocal_0.z) >> (passID_0))) & (u32(1)))) ^ (u32(1)));
        allocVal_0[i32(3)] = ((((((keyLocal_0.w) >> (passID_0))) & (u32(1)))) ^ (u32(1)));
        var allocIdx_0 : vec4<u32> = split4_0(threadIdx_2, allocVal_0);
        var _S13 : u32 = allocIdx_0.x;
        skey_0[_S13] = keyLocal_0.x;
        var _S14 : u32 = allocIdx_0.y;
        skey_0[_S14] = keyLocal_0.y;
        var _S15 : u32 = allocIdx_0.z;
        skey_0[_S15] = keyLocal_0.z;
        var _S16 : u32 = allocIdx_0.w;
        skey_0[_S16] = keyLocal_0.w;
        sval_0[_S13] = valLocal_0.x;
        sval_0[_S14] = valLocal_0.y;
        sval_0[_S15] = valLocal_0.z;
        sval_0[_S16] = valLocal_0.w;
        workgroupBarrier();
        keyLocal_0[i32(0)] = skey_0[_S9];
        keyLocal_0[i32(1)] = skey_0[_S10];
        keyLocal_0[i32(2)] = skey_0[_S11];
        keyLocal_0[i32(3)] = skey_0[_S12];
        valLocal_0[i32(0)] = sval_0[_S9];
        valLocal_0[i32(1)] = sval_0[_S10];
        valLocal_0[i32(2)] = sval_0[_S11];
        valLocal_0[i32(3)] = sval_0[_S12];
        passID_0 = passID_0 + u32(1);
    }
    workgroupBarrier();
    var sharedIdx_0 : u32 = threadIdx_2;
    for(;;)
    {
        if(sharedIdx_0 < u32(1024))
        {
        }
        else
        {
            break;
        }
        var bucketIdx_0 : u32 = ((((skey_0[sharedIdx_0]) >> ((paramsIn_0.passStart_0)))) & ((paramsIn_0.passMask_0)));
        var dstIdx_0 : u32 = sharedIdx_0 - localCounters_0[bucketIdx_0] + globalCounters_0[bucketIdx_0];
        keyOut_0[dstIdx_0] = skey_0[sharedIdx_0];
        valOut_0[dstIdx_0] = sval_0[sharedIdx_0];
        sharedIdx_0 = sharedIdx_0 + u32(256);
    }
    return;
}

