// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct NvFlowRayMarchShaderParams_std140_0
{
    @align(16) levelParamsVelocity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) levelParamsDensity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) view_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) projectionJitteredInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) viewInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) rayDir00_0 : vec4<f32>,
    @align(16) rayDir10_0 : vec4<f32>,
    @align(16) rayDir01_0 : vec4<f32>,
    @align(16) rayDir11_0 : vec4<f32>,
    @align(16) rayOrigin00_0 : vec4<f32>,
    @align(16) rayOrigin10_0 : vec4<f32>,
    @align(16) rayOrigin01_0 : vec4<f32>,
    @align(16) rayOrigin11_0 : vec4<f32>,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) depthWidth_0 : f32,
    @align(4) depthHeight_0 : f32,
    @align(8) depthWidthInv_0 : f32,
    @align(4) depthHeightInv_0 : f32,
    @align(16) numLayers_1 : u32,
    @align(4) maxWorldDistance_0 : f32,
    @align(8) isReverseZ_0 : u32,
    @align(4) compositeColorScale_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : NvFlowRayMarchShaderParams_std140_0;
@binding(5) @group(0) var depthIn_0 : texture_2d<f32>;

struct NvFlowRayMarchIsosurfaceLayerShaderParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) minBlockSizeWorld_0 : f32,
    @align(16) blockSizeWorldInv_0 : vec3<f32>,
    @align(4) maxBlockSizeWorld_0 : f32,
    @align(16) cellSize_0 : vec3<f32>,
    @align(4) stepSize_0 : f32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) stepSizeInv_0 : f32,
    @align(16) locationMin_0 : vec4<i32>,
    @align(16) locationMax_0 : vec4<i32>,
    @align(16) worldMin_0 : vec3<f32>,
    @align(4) enableBlockWireframe_0 : u32,
    @align(16) worldMax_0 : vec3<f32>,
    @align(4) visualizeNormals_0 : u32,
    @align(16) layerAndLevel_0 : i32,
    @align(4) densityThreshold_0 : f32,
    @align(8) refractionMode_0 : u32,
    @align(4) pad2_0 : u32,
    @align(16) fluidColor_0 : vec3<f32>,
    @align(4) fluidIoR_0 : f32,
    @align(16) fluidSpecularReflectance_0 : vec3<f32>,
    @align(4) fluidAbsorptionCoefficient_0 : f32,
    @align(16) fluidDiffuseReflectance_0 : vec3<f32>,
    @align(4) pad3_0 : f32,
    @align(16) fluidRadiance_0 : vec3<f32>,
    @align(4) pad4_0 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<NvFlowRayMarchIsosurfaceLayerShaderParams_std430_0>;

@binding(3) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var densitySampler_0 : sampler;

@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(6) @group(0) var colorIn_0 : texture_2d<f32>;

@binding(7) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn depthToWorld_0( depthIdx_0 : vec2<i32>,  sceneDepth_0 : f32) -> vec4<f32>
{
    var inUV_0 : vec2<f32> = (vec2<f32>(depthIdx_0) + vec2<f32>(0.5f)) * vec2<f32>(globalParamsIn_0.depthWidthInv_0, globalParamsIn_0.depthHeightInv_0);
    var _S4 : vec4<f32> = (((unpackStorage_0(globalParamsIn_0.projectionJitteredInv_0)) * (vec4<f32>(2.0f * inUV_0.x - 1.0f, -2.0f * inUV_0.y + 1.0f, sceneDepth_0, 1.0f))));
    var sceneWorld_0 : vec4<f32> = _S4;
    var _S5 : vec4<f32> = (((unpackStorage_0(globalParamsIn_0.viewInv_0)) * (_S4)));
    sceneWorld_0 = _S5;
    if((_S5.w) != 0.0f)
    {
        var _S6 : vec3<f32> = sceneWorld_0.xyz * vec3<f32>((1.0f / sceneWorld_0.w));
        sceneWorld_0.x = _S6.x;
        sceneWorld_0.y = _S6.y;
        sceneWorld_0.z = _S6.z;
    }
    return sceneWorld_0;
}

fn computeDepthNormalSample_0( depthIdxA_0 : vec2<i32>,  depthIdxB_0 : vec2<i32>) -> vec4<f32>
{
    var _S7 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdxA_0), u32(0)));
    var _S8 : f32 = (textureLoad((depthIn_0), ((_S7)).xy, ((_S7)).z).x);
    var _S9 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdxB_0), u32(0)));
    var _S10 : f32 = (textureLoad((depthIn_0), ((_S9)).xy, ((_S9)).z).x);
    var depthCmp_0 : bool = _S10 > _S8;
    var depthCmp_1 : bool;
    if((globalParamsIn_0.isReverseZ_0) == u32(0))
    {
        depthCmp_1 = !depthCmp_0;
    }
    else
    {
        depthCmp_1 = depthCmp_0;
    }
    var depthIdx_1 : vec2<i32>;
    var depth_0 : f32;
    if(depthCmp_1)
    {
        depthIdx_1 = depthIdxB_0;
        depth_0 = _S10;
    }
    else
    {
        depthIdx_1 = depthIdxA_0;
        depth_0 = _S8;
    }
    return depthToWorld_0(depthIdx_1, depth_0);
}

fn crossProduct_0( a_0 : vec3<f32>,  b_0 : vec3<f32>) -> vec3<f32>
{
    var _S11 : f32 = a_0.y;
    var _S12 : f32 = b_0.z;
    var _S13 : f32 = a_0.z;
    var _S14 : f32 = b_0.y;
    var _S15 : f32 = b_0.x;
    var _S16 : f32 = a_0.x;
    return vec3<f32>(_S11 * _S12 - _S13 * _S14, _S13 * _S15 - _S16 * _S12, _S16 * _S14 - _S11 * _S15);
}

fn computeDepthPositionAndNormal_0( depthPosition_0 : ptr<function, vec4<f32>>,  depthNormal_0 : ptr<function, vec3<f32>>,  rayDir_0 : vec3<f32>,  tidx_0 : vec2<i32>)
{
    var _S17 : bool;
    if((globalParamsIn_0.width_0) != (globalParamsIn_0.depthWidth_0))
    {
        _S17 = true;
    }
    else
    {
        _S17 = (globalParamsIn_0.height_0) != (globalParamsIn_0.depthHeight_0);
    }
    var depthIdx_2 : vec2<i32>;
    if(_S17)
    {
        depthIdx_2 = vec2<i32>(floor(vec2<f32>(globalParamsIn_0.depthWidth_0, globalParamsIn_0.depthHeight_0) * ((vec2<f32>(tidx_0) + vec2<f32>(0.5f, 0.5f)) * vec2<f32>(globalParamsIn_0.widthInv_0, globalParamsIn_0.heightInv_0))));
    }
    else
    {
        depthIdx_2 = tidx_0;
    }
    var _S18 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdx_2), u32(0)));
    (*depthPosition_0) = depthToWorld_0(depthIdx_2, (textureLoad((depthIn_0), ((_S18)).xy, ((_S18)).z).x));
    var _S19 : i32 = depthIdx_2.x;
    var _S20 : i32 = depthIdx_2.y;
    var depthPosition_dx_0 : vec4<f32> = computeDepthNormalSample_0(vec2<i32>(_S19 - i32(1), _S20), vec2<i32>(_S19 + i32(1), _S20));
    var depthPosition_dy_0 : vec4<f32> = computeDepthNormalSample_0(vec2<i32>(_S19, _S20 - i32(1)), vec2<i32>(_S19, _S20 + i32(1)));
    (*depthNormal_0) = - rayDir_0;
    if(((*depthPosition_0).w) != 0.0f)
    {
        _S17 = (depthPosition_dx_0.w) != 0.0f;
    }
    else
    {
        _S17 = false;
    }
    if(_S17)
    {
        _S17 = (depthPosition_dy_0.w) != 0.0f;
    }
    else
    {
        _S17 = false;
    }
    if(_S17)
    {
        var _S21 : vec3<f32> = normalize(crossProduct_0(depthPosition_dx_0.xyz - (*depthPosition_0).xyz, depthPosition_dy_0.xyz - (*depthPosition_0).xyz));
        (*depthNormal_0) = _S21;
        if((dot(_S21, rayDir_0)) > 0.0f)
        {
            (*depthNormal_0) = - (*depthNormal_0);
        }
    }
    return;
}

struct NvFlowRayMarchIsosurfaceLayerShaderParams_0
{
     blockSizeWorld_0 : vec3<f32>,
     minBlockSizeWorld_0 : f32,
     blockSizeWorldInv_0 : vec3<f32>,
     maxBlockSizeWorld_0 : f32,
     cellSize_0 : vec3<f32>,
     stepSize_0 : f32,
     cellSizeInv_0 : vec3<f32>,
     stepSizeInv_0 : f32,
     locationMin_0 : vec4<i32>,
     locationMax_0 : vec4<i32>,
     worldMin_0 : vec3<f32>,
     enableBlockWireframe_0 : u32,
     worldMax_0 : vec3<f32>,
     visualizeNormals_0 : u32,
     layerAndLevel_0 : i32,
     densityThreshold_0 : f32,
     refractionMode_0 : u32,
     pad2_0 : u32,
     fluidColor_0 : vec3<f32>,
     fluidIoR_0 : f32,
     fluidSpecularReflectance_0 : vec3<f32>,
     fluidAbsorptionCoefficient_0 : f32,
     fluidDiffuseReflectance_0 : vec3<f32>,
     pad3_0 : f32,
     fluidRadiance_0 : vec3<f32>,
     pad4_0 : f32,
};

fn unpackStorage_2( _S22 : NvFlowRayMarchIsosurfaceLayerShaderParams_std430_0) -> NvFlowRayMarchIsosurfaceLayerShaderParams_0
{
    var _S23 : NvFlowRayMarchIsosurfaceLayerShaderParams_0 = NvFlowRayMarchIsosurfaceLayerShaderParams_0( _S22.blockSizeWorld_0, _S22.minBlockSizeWorld_0, _S22.blockSizeWorldInv_0, _S22.maxBlockSizeWorld_0, _S22.cellSize_0, _S22.stepSize_0, _S22.cellSizeInv_0, _S22.stepSizeInv_0, _S22.locationMin_0, _S22.locationMax_0, _S22.worldMin_0, _S22.enableBlockWireframe_0, _S22.worldMax_0, _S22.visualizeNormals_0, _S22.layerAndLevel_0, _S22.densityThreshold_0, _S22.refractionMode_0, _S22.pad2_0, _S22.fluidColor_0, _S22.fluidIoR_0, _S22.fluidSpecularReflectance_0, _S22.fluidAbsorptionCoefficient_0, _S22.fluidDiffuseReflectance_0, _S22.pad3_0, _S22.fluidRadiance_0, _S22.pad4_0 );
    return _S23;
}

fn NvFlowIntersectBox_0( rayDir_1 : vec3<f32>,  rayDirInv_0 : vec3<f32>,  boxMin_0 : vec3<f32>,  boxMax_0 : vec3<f32>,  tnear_0 : ptr<function, f32>,  tfar_0 : ptr<function, f32>) -> bool
{
    var tbot_0 : vec3<f32> = boxMin_0 * rayDirInv_0;
    var ttop_0 : vec3<f32> = boxMax_0 * rayDirInv_0;
    var tmin_0 : vec3<f32> = min(ttop_0, tbot_0);
    var tmax_0 : vec3<f32> = max(ttop_0, tbot_0);
    var _S24 : f32 = tmin_0.x;
    (*tnear_0) = max(max(_S24, tmin_0.y), max(_S24, tmin_0.z));
    var _S25 : f32 = tmax_0.x;
    var _S26 : f32 = min(min(_S25, tmax_0.y), min(_S25, tmax_0.z));
    (*tfar_0) = _S26;
    return _S26 > (*tnear_0);
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowRayMarchComputeFinalLocation_0( rayDir_2 : vec3<f32>,  location_0 : vec4<i32>,  locationMin_1 : vec4<i32>,  locationMax_1 : vec4<i32>) -> vec3<i32>
{
    var _S27 : i32;
    if((rayDir_2.x) > 0.0f)
    {
        _S27 = max(location_0.x, locationMax_1.x);
    }
    else
    {
        _S27 = min(location_0.x, locationMin_1.x - i32(1));
    }
    var _S28 : i32;
    if((rayDir_2.y) > 0.0f)
    {
        _S28 = max(location_0.y, locationMax_1.y);
    }
    else
    {
        _S28 = min(location_0.y, locationMin_1.y - i32(1));
    }
    var _S29 : i32;
    if((rayDir_2.z) > 0.0f)
    {
        _S29 = max(location_0.z, locationMax_1.z);
    }
    else
    {
        _S29 = min(location_0.z, locationMin_1.z - i32(1));
    }
    return vec3<i32>(_S27, _S28, _S29);
}

fn NvFlowRayMarchWireframeIsosurface_0( paramsTable_0 : NvFlowSparseLevelParams_0,  params_0 : NvFlowRayMarchIsosurfaceLayerShaderParams_0,  rayOrigin_0 : vec3<f32>,  rayMinT_0 : f32,  rayDir_3 : vec3<f32>,  hitT_0 : f32,  location_1 : vec4<i32>,  debugHitT_0 : ptr<function, f32>)
{
    var _S30 : bool;
    if((*debugHitT_0) == rayMinT_0)
    {
        _S30 = hitT_0 > rayMinT_0;
    }
    else
    {
        _S30 = false;
    }
    if(_S30)
    {
        var blockFrac_0 : vec3<f32> = params_0.blockSizeWorld_0 * ((rayOrigin_0 + vec3<f32>(hitT_0) * rayDir_3) * params_0.blockSizeWorldInv_0 - vec3<f32>(location_1.xyz));
        var _S31 : f32 = params_0.cellSize_0.x;
        var _S32 : f32 = blockFrac_0.x;
        var _S33 : f32 = params_0.cellSize_0.y;
        var _S34 : f32 = blockFrac_0.y;
        var faceY_0 : f32 = max(_S33 - _S34, _S34 - f32(paramsTable_0.blockDimLessOne_0.y) * _S33);
        var _S35 : f32 = params_0.cellSize_0.z;
        var _S36 : f32 = blockFrac_0.z;
        var faceZ_0 : f32 = max(_S35 - _S36, _S36 - f32(paramsTable_0.blockDimLessOne_0.z) * _S35);
        var _S37 : bool = (max(_S31 - _S32, _S32 - f32(paramsTable_0.blockDimLessOne_0.x) * _S31)) > 0.0f;
        if(_S37)
        {
            _S30 = faceY_0 > 0.0f;
        }
        else
        {
            _S30 = false;
        }
        if(_S30)
        {
            _S30 = true;
        }
        else
        {
            if(faceY_0 > 0.0f)
            {
                _S30 = faceZ_0 > 0.0f;
            }
            else
            {
                _S30 = false;
            }
        }
        if(_S30)
        {
            _S30 = true;
        }
        else
        {
            if(faceZ_0 > 0.0f)
            {
                _S30 = _S37;
            }
            else
            {
                _S30 = false;
            }
        }
        if(_S30)
        {
            (*debugHitT_0) = hitT_0;
        }
    }
    return;
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S38 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S38, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S38 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowRayMarchAdvanceRay_0( blockSizeWorld_1 : vec3<f32>,  rayDir_4 : vec3<f32>,  rayDirInv_1 : vec3<f32>,  rayOrigin_1 : vec3<f32>,  location_2 : ptr<function, vec4<i32>>,  hitT_1 : ptr<function, f32>)
{
    var _S39 : i32 = (*location_2).x;
    var _S40 : f32 = rayDir_4.x;
    var _S41 : bool = _S40 > 0.0f;
    var _S42 : i32;
    if(_S41)
    {
        _S42 = i32(1);
    }
    else
    {
        _S42 = i32(0);
    }
    var hitTx_0 : f32 = (f32(_S39 + _S42) * blockSizeWorld_1.x - rayOrigin_1.x) * rayDirInv_1.x;
    var _S43 : i32 = (*location_2).y;
    var _S44 : f32 = rayDir_4.y;
    var _S45 : bool = _S44 > 0.0f;
    if(_S45)
    {
        _S42 = i32(1);
    }
    else
    {
        _S42 = i32(0);
    }
    var hitTy_0 : f32 = (f32(_S43 + _S42) * blockSizeWorld_1.y - rayOrigin_1.y) * rayDirInv_1.y;
    var _S46 : i32 = (*location_2).z;
    var _S47 : f32 = rayDir_4.z;
    var _S48 : bool = _S47 > 0.0f;
    if(_S48)
    {
        _S42 = i32(1);
    }
    else
    {
        _S42 = i32(0);
    }
    var hitTz_0 : f32 = (f32(_S46 + _S42) * blockSizeWorld_1.z - rayOrigin_1.z) * rayDirInv_1.z;
    var _S49 : bool;
    if(_S40 != 0.0f)
    {
        if(hitTx_0 <= hitTy_0)
        {
            _S49 = true;
        }
        else
        {
            _S49 = _S44 == 0.0f;
        }
    }
    else
    {
        _S49 = false;
    }
    if(_S49)
    {
        if(hitTx_0 <= hitTz_0)
        {
            _S49 = true;
        }
        else
        {
            _S49 = _S47 == 0.0f;
        }
    }
    else
    {
        _S49 = false;
    }
    if(_S49)
    {
        (*hitT_1) = hitTx_0;
        if(_S41)
        {
            _S42 = i32(1);
        }
        else
        {
            _S42 = i32(-1);
        }
        (*location_2)[i32(0)] = (*location_2)[i32(0)] + _S42;
    }
    else
    {
        if(_S44 != 0.0f)
        {
            if(hitTy_0 <= hitTx_0)
            {
                _S49 = true;
            }
            else
            {
                _S49 = _S40 == 0.0f;
            }
        }
        else
        {
            _S49 = false;
        }
        if(_S49)
        {
            if(hitTy_0 <= hitTz_0)
            {
                _S49 = true;
            }
            else
            {
                _S49 = _S47 == 0.0f;
            }
        }
        else
        {
            _S49 = false;
        }
        if(_S49)
        {
            (*hitT_1) = hitTy_0;
            if(_S45)
            {
                _S42 = i32(1);
            }
            else
            {
                _S42 = i32(-1);
            }
            (*location_2)[i32(1)] = (*location_2)[i32(1)] + _S42;
        }
        else
        {
            (*hitT_1) = hitTz_0;
            if(_S48)
            {
                _S42 = i32(1);
            }
            else
            {
                _S42 = i32(-1);
            }
            (*location_2)[i32(2)] = (*location_2)[i32(2)] + _S42;
        }
    }
    return;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn rayDirectionDebugVis_0( rayDir_5 : vec3<f32>) -> vec3<f32>
{
    var _S50 : f32 = rayDir_5.x;
    var _S51 : f32 = abs(_S50);
    var _S52 : f32 = rayDir_5.y;
    var _S53 : f32 = abs(_S52);
    var _S54 : bool;
    if(_S51 > _S53)
    {
        _S54 = _S51 > (abs(rayDir_5.z));
    }
    else
    {
        _S54 = false;
    }
    var color_0 : vec3<f32>;
    var u_0 : f32;
    var v_2 : f32;
    if(_S54)
    {
        var _S55 : f32 = _S52 / _S50;
        var _S56 : f32 = rayDir_5.z / _S50;
        if(_S50 > 0.0f)
        {
            color_0 = vec3<f32>(1.0f, 0.0f, 0.0f);
        }
        else
        {
            color_0 = vec3<f32>(1.0f, 1.0f, 0.0f);
        }
        u_0 = _S55;
        v_2 = _S56;
    }
    else
    {
        if(_S53 > _S51)
        {
            _S54 = _S53 > (abs(rayDir_5.z));
        }
        else
        {
            _S54 = false;
        }
        if(_S54)
        {
            var _S57 : f32 = _S50 / _S52;
            var _S58 : f32 = rayDir_5.z / _S52;
            if(_S52 > 0.0f)
            {
                color_0 = vec3<f32>(0.0f, 1.0f, 0.0f);
            }
            else
            {
                color_0 = vec3<f32>(0.0f, 1.0f, 1.0f);
            }
            u_0 = _S57;
            v_2 = _S58;
        }
        else
        {
            var _S59 : f32 = rayDir_5.z;
            var _S60 : f32 = _S50 / _S59;
            var _S61 : f32 = _S52 / _S59;
            if(_S59 > 0.0f)
            {
                color_0 = vec3<f32>(0.0f, 0.0f, 1.0f);
            }
            else
            {
                color_0 = vec3<f32>(1.0f, 0.0f, 1.0f);
            }
            u_0 = _S60;
            v_2 = _S61;
        }
    }
    if(((((i32(floor(4.0f * u_0)) & (i32(1)))) ^ (((i32(floor(4.0f * v_2)) & (i32(1))))))) == i32(0))
    {
        color_0 = vec3<f32>(0.0f, 0.0f, 0.0f);
    }
    return color_0;
}

fn NvFlowLocationToBlockIdx_0( _S62 : NvFlowSparseLevelParams_0,  _S63 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S63.xyz) & ((_S62.tableDimLessOne_0)));
    var _S64 : u32 = ((((((((bucketIdx_0.z) << ((_S62.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S62.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S65 : u32 = tableIn_0[_S64 + u32(1)];
    var _S66 : i32 = _S63.x;
    var _S67 : i32 = _S63.y;
    var _S68 : i32 = _S63.z;
    var _S69 : i32 = _S63.w;
    var blockIdx_1 : u32 = tableIn_0[_S64];
    for(;;)
    {
        if(blockIdx_1 < _S65)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S62.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(3)]);
        var _S70 : bool;
        if(i32(tableIn_0[compareLocationIdx_0]) == _S66)
        {
            _S70 = compareLocation_y_0 == _S67;
        }
        else
        {
            _S70 = false;
        }
        var _S71 : bool;
        if(_S70)
        {
            _S71 = compareLocation_z_0 == _S68;
        }
        else
        {
            _S71 = false;
        }
        var _S72 : bool;
        if(_S71)
        {
            _S72 = compareLocation_w_0 == _S69;
        }
        else
        {
            _S72 = false;
        }
        if(_S72)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToRealOffset_0( _S73 : NvFlowSparseLevelParams_0,  _S74 : vec4<i32>,  _S75 : u32) -> vec3<i32>
{
    var tableValue_0 : u32;
    if(_S75 != u32(4294967295))
    {
        tableValue_0 = tableIn_0[_S75 + _S73.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0(vec3<i32>(i32(0), i32(0), i32(0)), tableValue_0).xyz - (((_S74.xyz) << ((_S73.blockDimBits_0))));
}

fn NvFlowRayMarchBlockIsosurface_0( _S76 : texture_3d<f32>,  _S77 : sampler,  _S78 : NvFlowSparseLevelParams_0,  _S79 : NvFlowRayMarchIsosurfaceLayerShaderParams_0,  _S80 : u32,  _S81 : u32,  _S82 : vec3<f32>,  _S83 : f32,  _S84 : vec3<f32>,  _S85 : f32,  _S86 : vec3<f32>,  _S87 : u32,  _S88 : vec4<i32>,  _S89 : ptr<function, u32>,  _S90 : ptr<function, f32>,  _S91 : ptr<function, f32>,  _S92 : ptr<function, f32>) -> bool
{
    var _S93 : vec3<i32> = _S88.xyz;
    var _S94 : vec3<f32> = vec3<f32>(0.00009999999747379f) * _S79.cellSize_0;
    var boxMinT_0 : f32;
    var boxMaxT_0 : f32;
    var _S95 : bool = NvFlowIntersectBox_0(_S84, _S86, vec3<f32>(_S93) * _S79.blockSizeWorld_0 - _S82 - _S94, vec3<f32>(_S93 + vec3<i32>(i32(1), i32(1), i32(1))) * _S79.blockSizeWorld_0 - _S82 + _S94, &(boxMinT_0), &(boxMaxT_0));
    var _S96 : f32 = max(_S83, boxMinT_0);
    boxMinT_0 = _S96;
    var isHit_0 : bool;
    if(_S96 > boxMaxT_0)
    {
        isHit_0 = false;
    }
    else
    {
        isHit_0 = _S95;
    }
    var _S97 : bool = boxMaxT_0 > _S85;
    if(_S97)
    {
        boxMaxT_0 = _S85;
    }
    const _S98 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var stepIdx_0 : i32;
    var hitRidxf_0 : vec3<f32>;
    if(isHit_0)
    {
        var _S99 : bool = (_S79.enableBlockWireframe_0) != u32(0);
        if(_S99)
        {
            NvFlowRayMarchWireframeIsosurface_0(_S78, _S79, _S82, _S83, _S84, boxMinT_0, _S88, &((*_S92)));
        }
        var tmin_1 : f32 = round(_S79.stepSizeInv_0 * boxMinT_0);
        var _S100 : i32 = i32(round(_S79.stepSizeInv_0 * boxMaxT_0) - tmin_1);
        var currentT_0 : f32 = _S79.stepSize_0 * tmin_1;
        var _S101 : vec3<f32> = vec3<f32>(_S79.stepSize_0) * _S84 * _S79.cellSizeInv_0;
        var _S102 : vec3<f32> = (_S82 + vec3<f32>(currentT_0) * _S84) * _S79.cellSizeInv_0 + vec3<f32>(NvFlowGlobalVirtualToRealOffset_0(_S78, _S88, _S87));
        stepIdx_0 = i32(0);
        var currentT_1 : f32 = currentT_0;
        var ridxf_0 : vec3<f32> = _S102;
        for(;;)
        {
            if(stepIdx_0 < _S100)
            {
            }
            else
            {
                break;
            }
            if(currentT_1 > _S83)
            {
                break;
            }
            var ridxf_1 : vec3<f32> = ridxf_0 + _S101;
            var currentT_2 : f32 = currentT_1 + _S79.stepSize_0;
            stepIdx_0 = stepIdx_0 + i32(1);
            currentT_1 = currentT_2;
            ridxf_0 = ridxf_1;
        }
        for(;;)
        {
            if(stepIdx_0 < _S100)
            {
            }
            else
            {
                hitRidxf_0 = _S98;
                break;
            }
            var value_0 : f32 = (textureSampleLevel((_S76), (_S77), (ridxf_0 * _S78.dimInv_0), (0.0f)).x);
            var threshTest_0 : u32 = (((u32((*_S91) >= (_S79.densityThreshold_0)) << (u32(1)))) | (u32(value_0 >= (_S79.densityThreshold_0))));
            if(((threshTest_0 & (_S80))) == _S81)
            {
                (*_S89) = threshTest_0;
                (*_S90) = currentT_1;
                hitRidxf_0 = ridxf_0;
                break;
            }
            (*_S91) = value_0;
            var ridxf_2 : vec3<f32> = ridxf_0 + _S101;
            var currentT_3 : f32 = currentT_1 + _S79.stepSize_0;
            stepIdx_0 = stepIdx_0 + i32(1);
            ridxf_0 = ridxf_2;
            currentT_1 = currentT_3;
        }
        if(_S99)
        {
            NvFlowRayMarchWireframeIsosurface_0(_S78, _S79, _S82, _S83, _S84, boxMaxT_0, _S88, &((*_S92)));
        }
    }
    else
    {
        hitRidxf_0 = _S98;
    }
    if(bool((*_S89)))
    {
        var _S103 : vec3<f32> = vec3<f32>(0.00390625f) * (vec3<f32>(_S79.stepSize_0) * _S84) * _S79.cellSizeInv_0;
        stepIdx_0 = i32(0);
        for(;;)
        {
            if(stepIdx_0 < i32(8))
            {
            }
            else
            {
                break;
            }
            var stepScale_0 : f32 = f32((i32(1) << (u32(i32(7) - stepIdx_0))));
            var ridxfBisect_0 : vec3<f32> = hitRidxf_0 - vec3<f32>(stepScale_0) * _S103;
            var tStepLocal_0 : f32 = 0.00390625f * stepScale_0 * _S79.stepSize_0;
            if(((((((u32((*_S91) >= (_S79.densityThreshold_0)) << (u32(1)))) | (u32((textureSampleLevel((_S76), (_S77), (ridxfBisect_0 * _S78.dimInv_0), (0.0f)).x) >= (_S79.densityThreshold_0))))) & (_S80))) == _S81)
            {
                (*_S90) = (*_S90) - tStepLocal_0;
                hitRidxf_0 = ridxfBisect_0;
            }
            stepIdx_0 = stepIdx_0 + i32(1);
        }
    }
    return _S97;
}

fn NvFlowRayMarchBlocksIsosurface_0( _S104 : texture_3d<f32>,  _S105 : sampler,  _S106 : NvFlowSparseLevelParams_0,  _S107 : NvFlowRayMarchIsosurfaceLayerShaderParams_0,  _S108 : u32,  _S109 : u32,  _S110 : f32,  _S111 : vec3<f32>,  _S112 : f32,  _S113 : vec3<f32>,  _S114 : f32,  _S115 : vec3<f32>,  _S116 : ptr<function, u32>,  _S117 : ptr<function, f32>,  _S118 : ptr<function, f32>)
{
    var boxMinT_1 : f32;
    var boxMaxT_1 : f32;
    var _S119 : bool = NvFlowIntersectBox_0(_S113, _S115, _S107.worldMin_0 - _S111, _S107.worldMax_0 - _S111, &(boxMinT_1), &(boxMaxT_1));
    var _S120 : f32 = max(_S112, boxMinT_1);
    boxMinT_1 = _S120;
    var isHit_1 : bool;
    if(_S120 > boxMaxT_1)
    {
        isHit_1 = false;
    }
    else
    {
        isHit_1 = _S119;
    }
    if(isHit_1)
    {
        var _S121 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0((_S113 * vec3<f32>(boxMinT_1) + _S111) * _S107.blockSizeWorldInv_0), _S107.layerAndLevel_0);
        var location_3 : vec4<i32> = _S121;
        var _S122 : vec3<i32> = NvFlowRayMarchComputeFinalLocation_0(_S113, _S121, _S107.locationMin_0, _S107.locationMax_0);
        var blockHitT_0 : f32 = boxMinT_1;
        var lastVal_0 : f32 = _S110;
        (*_S116) = u32(0);
        var _S123 : i32 = _S122.x;
        var _S124 : i32 = _S122.y;
        var _S125 : i32 = _S122.z;
        var hitMax_0 : bool = false;
        for(;;)
        {
            if((location_3.x) != _S123)
            {
                isHit_1 = (location_3.y) != _S124;
            }
            else
            {
                isHit_1 = false;
            }
            var _S126 : bool;
            if(isHit_1)
            {
                _S126 = (location_3.z) != _S125;
            }
            else
            {
                _S126 = false;
            }
            var _S127 : bool;
            if(_S126)
            {
                _S127 = !hitMax_0;
            }
            else
            {
                _S127 = false;
            }
            var _S128 : bool;
            if(_S127)
            {
                _S128 = (*_S116) == u32(0);
            }
            else
            {
                _S128 = false;
            }
            if(_S128)
            {
            }
            else
            {
                break;
            }
            var _S129 : u32 = NvFlowLocationToBlockIdx_0(_S106, location_3);
            if(_S129 != u32(4294967295))
            {
                var _S130 : bool = NvFlowRayMarchBlockIsosurface_0(_S104, _S105, _S106, _S107, _S108, _S109, _S111, _S112, _S113, _S114, _S115, _S129, location_3, &((*_S116)), &((*_S117)), &(lastVal_0), &((*_S118)));
                hitMax_0 = _S130;
            }
            NvFlowRayMarchAdvanceRay_0(_S107.blockSizeWorld_0, _S113, _S115, _S111, &(location_3), &(blockHitT_0));
        }
    }
    return;
}

fn NvFlowLocalVirtualToReal_0( _S131 : NvFlowSparseLevelParams_0,  _S132 : u32,  _S133 : vec3<i32>) -> vec4<i32>
{
    var neighbor_0 : vec3<i32> = (_S133 >> (vec3<u32>(vec3<i32>(_S131.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S133, tableIn_0[NvFlowNeighborToIdx_0(_S132, neighbor_0.x, neighbor_0.y, neighbor_0.z) + _S131.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalReadLinear1f_0( _S134 : texture_3d<f32>,  _S135 : sampler,  _S136 : NvFlowSparseLevelParams_0,  _S137 : u32,  _S138 : vec3<f32>) -> f32
{
    var threadIdx_1 : vec3<i32> = NvFlowFloor_i_0(_S138);
    var _S139 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S136, _S137, threadIdx_1);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S139.xyz) + _S138 - vec3<f32>(threadIdx_1);
    var _S140 : f32;
    if(bool(_S139.w))
    {
        _S140 = (textureSampleLevel((_S134), (_S135), (readIdxf_0 * _S136.dimInv_0), (0.0f)).x);
    }
    else
    {
        _S140 = 0.0f;
    }
    return _S140;
}

fn NvFlowRayMarchBlocksIsosurfaceComputeNormal_0( _S141 : texture_3d<f32>,  _S142 : sampler,  _S143 : NvFlowSparseLevelParams_0,  _S144 : NvFlowRayMarchIsosurfaceLayerShaderParams_0,  _S145 : vec3<f32>) -> vec3<f32>
{
    var vidx_0 : vec3<i32> = NvFlowFloor_i_0(_S145);
    var _S146 : u32 = NvFlowLocationToBlockIdx_0(_S143, vec4<i32>((vidx_0 >> (vec3<u32>(vec3<i32>(_S143.blockDimBits_0)))), _S144.layerAndLevel_0));
    const _S147 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var hitNormal_0 : vec3<f32>;
    if(_S146 != u32(4294967295))
    {
        var threadIdxf_0 : vec3<f32> = vec3<f32>((vidx_0 & (vec3<i32>(_S143.blockDimLessOne_0)))) + (_S145 - vec3<f32>(vidx_0));
        var _S148 : f32 = NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(1.0f, 0.0f, 0.0f)) - NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(-1.0f, 0.0f, 0.0f));
        var _S149 : f32 = NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(0.0f, 1.0f, 0.0f)) - NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(0.0f, -1.0f, 0.0f));
        var _S150 : f32 = NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(0.0f, 0.0f, 1.0f)) - NvFlowLocalReadLinear1f_0(_S141, _S142, _S143, _S146, threadIdxf_0 + vec3<f32>(0.0f, 0.0f, -1.0f));
        var hitNormal_1 : vec3<f32> = vec3<f32>(_S148, _S149, _S150);
        var _S151 : bool;
        if(_S148 != 0.0f)
        {
            _S151 = true;
        }
        else
        {
            _S151 = _S149 != 0.0f;
        }
        if(_S151)
        {
            _S151 = true;
        }
        else
        {
            _S151 = _S150 != 0.0f;
        }
        if(_S151)
        {
            hitNormal_0 = normalize(hitNormal_1);
        }
        else
        {
            hitNormal_0 = hitNormal_1;
        }
    }
    else
    {
        hitNormal_0 = _S147;
    }
    return hitNormal_0;
}

@compute
@workgroup_size(8, 4, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var _S152 : vec2<i32> = vec2<i32>(dispatchThreadID_0.xy);
    var _S153 : bool;
    if(f32(_S152.x) >= (globalParamsIn_0.width_0))
    {
        _S153 = true;
    }
    else
    {
        _S153 = f32(_S152.y) >= (globalParamsIn_0.height_0);
    }
    if(_S153)
    {
        return;
    }
    var inUV_1 : vec2<f32> = (vec2<f32>(_S152) + vec2<f32>(0.5f)) * vec2<f32>(globalParamsIn_0.widthInv_0, globalParamsIn_0.heightInv_0);
    var _S154 : f32 = inUV_1.x;
    var _S155 : f32 = 1.0f - _S154;
    var _S156 : f32 = inUV_1.y;
    var _S157 : f32 = 1.0f - _S156;
    var _S158 : vec3<f32> = vec3<f32>((_S155 * _S157));
    var _S159 : vec3<f32> = vec3<f32>((_S154 * _S157));
    var _S160 : vec3<f32> = vec3<f32>((_S155 * _S156));
    var _S161 : vec3<f32> = vec3<f32>((_S154 * _S156));
    var rayDir_6 : vec3<f32> = normalize(_S158 * globalParamsIn_0.rayDir00_0.xyz + _S159 * globalParamsIn_0.rayDir10_0.xyz + _S160 * globalParamsIn_0.rayDir01_0.xyz + _S161 * globalParamsIn_0.rayDir11_0.xyz);
    var rayOrigin_2 : vec3<f32> = _S158 * globalParamsIn_0.rayOrigin00_0.xyz + _S159 * globalParamsIn_0.rayOrigin10_0.xyz + _S160 * globalParamsIn_0.rayOrigin01_0.xyz + _S161 * globalParamsIn_0.rayOrigin11_0.xyz;
    var _S162 : vec3<f32> = vec3<f32>(1.0f, 1.0f, 1.0f) / rayDir_6;
    var depthPosition_1 : vec4<f32>;
    var depthNormal_1 : vec3<f32>;
    computeDepthPositionAndNormal_0(&(depthPosition_1), &(depthNormal_1), rayDir_6, _S152);
    var _S163 : f32 = globalParamsIn_0.maxWorldDistance_0;
    var sceneT_0 : f32;
    if((depthPosition_1.w) != 0.0f)
    {
        var plane_denom_0 : f32 = dot(depthNormal_1, rayDir_6);
        if((abs(plane_denom_0)) > 0.00999999977648258f)
        {
            sceneT_0 = dot(depthNormal_1, depthPosition_1.xyz - rayOrigin_2) / plane_denom_0;
        }
        else
        {
            sceneT_0 = dot(rayDir_6, depthPosition_1.xyz - rayOrigin_2);
        }
    }
    else
    {
        sceneT_0 = _S163;
    }
    var _S164 : f32 = min(globalParamsIn_0.maxWorldDistance_0, sceneT_0);
    var sum_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 1.0f);
    var _S165 : vec2<u32> = vec2<u32>(_S152);
    var _S166 : vec3<i32> = vec3<i32>(vec3<u32>(_S165, u32(0)));
    var _S167 : vec4<f32> = (textureLoad((colorIn_0), ((_S166)).xy, ((_S166)).z));
    const _S168 : vec4<f32> = vec4<f32>(0.0f, 0.80000001192092896f, 0.0f, 0.0f);
    const _S169 : vec4<f32> = vec4<f32>(0.30000001192092896f, 0.30000001192092896f, 0.30000001192092896f, 0.0f);
    const _S170 : vec4<f32> = vec4<f32>(0.80000001192092896f, 0.80000001192092896f, 0.80000001192092896f, 0.0f);
    var rayOrigin_3 : vec3<f32> = rayOrigin_2;
    var rayDir_7 : vec3<f32> = rayDir_6;
    var rayDirInv_2 : vec3<f32> = _S162;
    var layerParamIdx_0 : u32 = u32(0);
    var _S171 : vec3<f32> = _S167.xyz;
    var _S172 : vec3<f32> = vec3<f32>(1.0f);
    for(;;)
    {
        if(layerParamIdx_0 < (globalParamsIn_0.numLayers_1))
        {
        }
        else
        {
            break;
        }
        if((layerParamsIn_0[layerParamIdx_0].refractionMode_0) != u32(0))
        {
            var rayOrigin_4 : vec3<f32> = rayOrigin_3;
            var rayDir_8 : vec3<f32> = rayDir_7;
            var rayDirInv_3 : vec3<f32> = rayDirInv_2;
            var bounceIdx_0 : i32 = i32(0);
            for(;;)
            {
                if(bounceIdx_0 < i32(3))
                {
                }
                else
                {
                    break;
                }
                var debugHitT_1 : f32 = 0.0f;
                var hitT_2 : f32 = 0.0f;
                var hitEdge_0 : u32 = u32(2);
                NvFlowRayMarchBlocksIsosurface_0(densityIn_0, densitySampler_0, unpackStorage_1(globalParamsIn_0.levelParamsDensity_0), unpackStorage_2(layerParamsIn_0[layerParamIdx_0]), u32(3), u32(1), 0.0f, rayOrigin_4, 0.0f, rayDir_8, _S164, rayDirInv_3, &(hitEdge_0), &(hitT_2), &(debugHitT_1));
                if(!bool(hitEdge_0))
                {
                    break;
                }
                var _S173 : vec3<f32> = NvFlowRayMarchBlocksIsosurfaceComputeNormal_0(densityIn_0, densitySampler_0, unpackStorage_1(globalParamsIn_0.levelParamsDensity_0), unpackStorage_2(layerParamsIn_0[layerParamIdx_0]), (rayDir_8 * vec3<f32>(hitT_2) + rayOrigin_4) * layerParamsIn_0[layerParamIdx_0].cellSizeInv_0);
                var _S174 : vec3<f32> = vec3<f32>(hitT_2) * rayDir_8 + rayOrigin_4;
                var ior_0 : f32;
                var inverseIor_0 : f32;
                var hitNormal_2 : vec3<f32>;
                if(bool((hitEdge_0 & (u32(1)))))
                {
                    var _S175 : f32 = layerParamsIn_0[layerParamIdx_0].fluidIoR_0;
                    var _S176 : f32 = 1.0f / layerParamsIn_0[layerParamIdx_0].fluidIoR_0;
                    hitNormal_2 = - _S173;
                    ior_0 = _S175;
                    inverseIor_0 = _S176;
                }
                else
                {
                    var _S177 : f32 = 1.0f / layerParamsIn_0[layerParamIdx_0].fluidIoR_0;
                    var _S178 : f32 = layerParamsIn_0[layerParamIdx_0].fluidIoR_0;
                    hitNormal_2 = _S173;
                    ior_0 = _S177;
                    inverseIor_0 = _S178;
                }
                var cos_i_0 : f32 = max(0.0f, - dot(rayDir_8, hitNormal_2));
                var rayDir_9 : vec3<f32> = normalize(vec3<f32>(inverseIor_0) * rayDir_8 + vec3<f32>((inverseIor_0 * cos_i_0 - sqrt(max((- cos_i_0 * cos_i_0 + 1.0f) * (-1.0f / (ior_0 * ior_0)) + 1.0f, 0.0f)))) * hitNormal_2);
                var _S179 : vec3<f32> = _S172 / rayDir_9;
                var _S180 : i32 = bounceIdx_0 + i32(1);
                rayOrigin_4 = _S174;
                rayDir_8 = rayDir_9;
                rayDirInv_3 = _S179;
                bounceIdx_0 = _S180;
            }
            var _S181 : vec3<f32> = rayDirectionDebugVis_0(rayDir_8);
            sum_0.x = _S181.x;
            sum_0.y = _S181.y;
            sum_0.z = _S181.z;
            sum_0[i32(3)] = 0.5f;
            rayOrigin_3 = rayOrigin_4;
            rayDir_7 = rayDir_8;
            rayDirInv_2 = rayDirInv_3;
        }
        else
        {
            var debugHitT_2 : f32 = 0.0f;
            var hitT_3 : f32 = 0.0f;
            var hitEdge_1 : u32 = u32(0);
            NvFlowRayMarchBlocksIsosurface_0(densityIn_0, densitySampler_0, unpackStorage_1(globalParamsIn_0.levelParamsDensity_0), unpackStorage_2(layerParamsIn_0[layerParamIdx_0]), u32(3), u32(1), 0.0f, rayOrigin_3, 0.0f, rayDir_7, _S164, rayDirInv_2, &(hitEdge_1), &(hitT_3), &(debugHitT_2));
            if(bool(hitEdge_1))
            {
                var vidxf_0 : vec3<f32> = (rayDir_7 * vec3<f32>(hitT_3) + rayOrigin_3) * layerParamsIn_0[layerParamIdx_0].cellSizeInv_0;
                var vidx_1 : vec3<i32> = NvFlowFloor_i_0(vidxf_0);
                if((((vidx_1.x) & (i32(3)))) == i32(0))
                {
                    _S153 = true;
                }
                else
                {
                    _S153 = (((vidx_1.y) & (i32(3)))) == i32(0);
                }
                if(_S153)
                {
                    sum_0 = _S168;
                }
                else
                {
                    sum_0 = _S169;
                }
                if(bool(layerParamsIn_0[layerParamIdx_0].visualizeNormals_0))
                {
                    sum_0 = vec4<f32>(abs(NvFlowRayMarchBlocksIsosurfaceComputeNormal_0(densityIn_0, densitySampler_0, unpackStorage_1(globalParamsIn_0.levelParamsDensity_0), unpackStorage_2(layerParamsIn_0[layerParamIdx_0]), vidxf_0)), 0.0f);
                }
            }
            if((layerParamsIn_0[layerParamIdx_0].enableBlockWireframe_0) != u32(0))
            {
                if(debugHitT_2 > 0.0f)
                {
                    if(hitEdge_1 == u32(0))
                    {
                        _S153 = true;
                    }
                    else
                    {
                        _S153 = debugHitT_2 < hitT_3;
                    }
                }
                else
                {
                    _S153 = false;
                }
                if(_S153)
                {
                    sum_0 = _S170;
                }
            }
        }
        layerParamIdx_0 = layerParamIdx_0 + u32(1);
    }
    var color_1 : vec4<f32> = _S167;
    var _S182 : vec3<f32> = sum_0.xyz * vec3<f32>(globalParamsIn_0.compositeColorScale_0);
    sum_0.x = _S182.x;
    sum_0.y = _S182.y;
    sum_0.z = _S182.z;
    var _S183 : vec3<f32> = sum_0.xyz + vec3<f32>(sum_0.w) * _S171;
    color_1.x = _S183.x;
    color_1.y = _S183.y;
    color_1.z = _S183.z;
    textureStore((colorOut_0), (_S165), (color_1));
    return;
}

