// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct RayMarchCopyTextureCS_Params_std140_0
{
    @align(16) pixelMini_0 : vec2<i32>,
    @align(8) pixelMaxi_0 : vec2<i32>,
};

@binding(0) @group(0) var<uniform> paramsIn_0 : RayMarchCopyTextureCS_Params_std140_0;
@binding(1) @group(0) var colorIn_0 : texture_2d<f32>;

@binding(2) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var tidx_0 : vec2<i32> = vec2<i32>(dispatchThreadID_0.xy) + paramsIn_0.pixelMini_0;
    var _S1 : bool;
    if((tidx_0.x) >= (paramsIn_0.pixelMaxi_0.x))
    {
        _S1 = true;
    }
    else
    {
        _S1 = (tidx_0.y) >= (paramsIn_0.pixelMaxi_0.y);
    }
    if(_S1)
    {
        return;
    }
    var _S2 : vec2<u32> = vec2<u32>(tidx_0);
    var _S3 : vec3<i32> = vec3<i32>(vec3<u32>(_S2, u32(0)));
    textureStore((colorOut_0), (_S2), ((textureLoad((colorIn_0), ((_S3)).xy, ((_S3)).z))));
    return;
}

