// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct NvFlowRayMarchShaderParams_std140_0
{
    @align(16) levelParamsVelocity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) levelParamsDensity_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) view_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) projectionJitteredInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) viewInv_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) rayDir00_0 : vec4<f32>,
    @align(16) rayDir10_0 : vec4<f32>,
    @align(16) rayDir01_0 : vec4<f32>,
    @align(16) rayDir11_0 : vec4<f32>,
    @align(16) rayOrigin00_0 : vec4<f32>,
    @align(16) rayOrigin10_0 : vec4<f32>,
    @align(16) rayOrigin01_0 : vec4<f32>,
    @align(16) rayOrigin11_0 : vec4<f32>,
    @align(16) width_0 : f32,
    @align(4) height_0 : f32,
    @align(8) widthInv_0 : f32,
    @align(4) heightInv_0 : f32,
    @align(16) depthWidth_0 : f32,
    @align(4) depthHeight_0 : f32,
    @align(8) depthWidthInv_0 : f32,
    @align(4) depthHeightInv_0 : f32,
    @align(16) numLayers_1 : u32,
    @align(4) maxWorldDistance_0 : f32,
    @align(8) isReverseZ_0 : u32,
    @align(4) compositeColorScale_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : NvFlowRayMarchShaderParams_std140_0;
@binding(9) @group(0) var depthIn_0 : texture_2d<f32>;

@binding(3) @group(0) var velocityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var velocitySampler_0 : sampler;

@binding(5) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(6) @group(0) var densitySampler_0 : sampler;

@binding(7) @group(0) var colormapIn_0 : texture_2d<f32>;

@binding(8) @group(0) var colormapSampler_0 : sampler;

@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

struct NvFlowRayMarchCloudLayerShaderParams_std430_0
{
    @align(16) densityMultiplier_0 : f32,
    @align(4) enableCloudMode_0 : u32,
    @align(8) pad1_1 : f32,
    @align(4) pad2_0 : f32,
    @align(16) ambientColor_0 : vec3<f32>,
    @align(4) ambientMultiplier_0 : f32,
    @align(16) volumeBaseColor_0 : vec3<f32>,
    @align(4) volumeColorMultiplier_0 : f32,
    @align(16) sunDirection_0 : vec3<f32>,
    @align(4) shadowStepMultiplier_0 : f32,
    @align(16) attenuationMultiplier_0 : vec3<f32>,
    @align(4) numShadowSteps_0 : i32,
};

struct NvFlowRayMarchLayerShaderParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) minBlockSizeWorld_0 : f32,
    @align(16) blockSizeWorldInv_0 : vec3<f32>,
    @align(4) maxBlockSizeWorld_0 : f32,
    @align(16) cellSize_0 : vec3<f32>,
    @align(4) stepSize_0 : f32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) stepSizeInv_0 : f32,
    @align(16) locationMin_0 : vec4<i32>,
    @align(16) locationMax_0 : vec4<i32>,
    @align(16) worldMin_0 : vec3<f32>,
    @align(4) enableBlockWireframe_0 : u32,
    @align(16) worldMax_0 : vec3<f32>,
    @align(4) enableRawMode_0 : u32,
    @align(16) velocityCellSizeInv_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) layerAndLevel_0 : i32,
    @align(4) layerAndLevelColormapV_0 : f32,
    @align(8) alphaScale_0 : f32,
    @align(4) colorScale_0 : f32,
    @align(16) shadowFactor_0 : f32,
    @align(4) rawModeIsosurface_0 : u32,
    @align(8) rawModeNormalize_0 : u32,
    @align(4) pad3_0 : f32,
    @align(16) colormapXOffset_0 : f32,
    @align(4) colormapXScale_0 : f32,
    @align(8) pad4_0 : f32,
    @align(4) pad5_0 : f32,
    @align(16) cloud_0 : NvFlowRayMarchCloudLayerShaderParams_std430_0,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<NvFlowRayMarchLayerShaderParams_std430_0>;

@binding(10) @group(0) var colorIn_0 : texture_2d<f32>;

@binding(11) @group(0) var colorOut_0 : texture_storage_2d<rgba32float, write>;

fn unpackStorage_0( _S1 : _MatrixStorage_float4x4_ColMajorstd140_0) -> mat4x4<f32>
{
    return mat4x4<f32>(_S1.data_0[i32(0)][i32(0)], _S1.data_0[i32(1)][i32(0)], _S1.data_0[i32(2)][i32(0)], _S1.data_0[i32(3)][i32(0)], _S1.data_0[i32(0)][i32(1)], _S1.data_0[i32(1)][i32(1)], _S1.data_0[i32(2)][i32(1)], _S1.data_0[i32(3)][i32(1)], _S1.data_0[i32(0)][i32(2)], _S1.data_0[i32(1)][i32(2)], _S1.data_0[i32(2)][i32(2)], _S1.data_0[i32(3)][i32(2)], _S1.data_0[i32(0)][i32(3)], _S1.data_0[i32(1)][i32(3)], _S1.data_0[i32(2)][i32(3)], _S1.data_0[i32(3)][i32(3)]);
}

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_1( _S2 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S3 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S2.blockDimLessOne_0, _S2.threadsPerBlock_0, _S2.blockDimBits_0, _S2.numLocations_0, _S2.tableDimLessOne_0, _S2.tableDim3_0, _S2.tableDimBits_x_0, _S2.tableDimBits_xy_0, _S2.tableDimBits_z_0, _S2.locationOffset_0, _S2.allocationOffset_0, _S2.newListOffset_0, _S2.blockLevelOffsetGlobal_0, _S2.blockLevelOffsetLocal_0, _S2.layerParamIdxOffset_0, _S2.numLayers_0, _S2.pad0_0, _S2.pad1_0, _S2.dim_0, _S2.maxLocations_0, _S2.dimInv_0, _S2.numNewLocations_0, _S2.globalLocationMin_0, _S2.globalLocationMax_0 );
    return _S3;
}

fn depthToWorld_0( depthIdx_0 : vec2<i32>,  sceneDepth_0 : f32) -> vec4<f32>
{
    var inUV_0 : vec2<f32> = (vec2<f32>(depthIdx_0) + vec2<f32>(0.5f)) * vec2<f32>(globalParamsIn_0.depthWidthInv_0, globalParamsIn_0.depthHeightInv_0);
    var _S4 : vec4<f32> = (((unpackStorage_0(globalParamsIn_0.projectionJitteredInv_0)) * (vec4<f32>(2.0f * inUV_0.x - 1.0f, -2.0f * inUV_0.y + 1.0f, sceneDepth_0, 1.0f))));
    var sceneWorld_0 : vec4<f32> = _S4;
    var _S5 : vec4<f32> = (((unpackStorage_0(globalParamsIn_0.viewInv_0)) * (_S4)));
    sceneWorld_0 = _S5;
    if((_S5.w) != 0.0f)
    {
        var _S6 : vec3<f32> = sceneWorld_0.xyz * vec3<f32>((1.0f / sceneWorld_0.w));
        sceneWorld_0.x = _S6.x;
        sceneWorld_0.y = _S6.y;
        sceneWorld_0.z = _S6.z;
    }
    return sceneWorld_0;
}

fn computeDepthNormalSample_0( depthIdxA_0 : vec2<i32>,  depthIdxB_0 : vec2<i32>) -> vec4<f32>
{
    var _S7 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdxA_0), u32(0)));
    var _S8 : f32 = (textureLoad((depthIn_0), ((_S7)).xy, ((_S7)).z).x);
    var _S9 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdxB_0), u32(0)));
    var _S10 : f32 = (textureLoad((depthIn_0), ((_S9)).xy, ((_S9)).z).x);
    var depthCmp_0 : bool = _S10 > _S8;
    var depthCmp_1 : bool;
    if((globalParamsIn_0.isReverseZ_0) == u32(0))
    {
        depthCmp_1 = !depthCmp_0;
    }
    else
    {
        depthCmp_1 = depthCmp_0;
    }
    var depthIdx_1 : vec2<i32>;
    var depth_0 : f32;
    if(depthCmp_1)
    {
        depthIdx_1 = depthIdxB_0;
        depth_0 = _S10;
    }
    else
    {
        depthIdx_1 = depthIdxA_0;
        depth_0 = _S8;
    }
    return depthToWorld_0(depthIdx_1, depth_0);
}

fn crossProduct_0( a_0 : vec3<f32>,  b_0 : vec3<f32>) -> vec3<f32>
{
    var _S11 : f32 = a_0.y;
    var _S12 : f32 = b_0.z;
    var _S13 : f32 = a_0.z;
    var _S14 : f32 = b_0.y;
    var _S15 : f32 = b_0.x;
    var _S16 : f32 = a_0.x;
    return vec3<f32>(_S11 * _S12 - _S13 * _S14, _S13 * _S15 - _S16 * _S12, _S16 * _S14 - _S11 * _S15);
}

fn computeDepthPositionAndNormal_0( depthPosition_0 : ptr<function, vec4<f32>>,  depthNormal_0 : ptr<function, vec3<f32>>,  rayDir_0 : vec3<f32>,  tidx_0 : vec2<i32>)
{
    var _S17 : bool;
    if((globalParamsIn_0.width_0) != (globalParamsIn_0.depthWidth_0))
    {
        _S17 = true;
    }
    else
    {
        _S17 = (globalParamsIn_0.height_0) != (globalParamsIn_0.depthHeight_0);
    }
    var depthIdx_2 : vec2<i32>;
    if(_S17)
    {
        depthIdx_2 = vec2<i32>(floor(vec2<f32>(globalParamsIn_0.depthWidth_0, globalParamsIn_0.depthHeight_0) * ((vec2<f32>(tidx_0) + vec2<f32>(0.5f, 0.5f)) * vec2<f32>(globalParamsIn_0.widthInv_0, globalParamsIn_0.heightInv_0))));
    }
    else
    {
        depthIdx_2 = tidx_0;
    }
    var _S18 : vec3<i32> = vec3<i32>(vec3<u32>(vec2<u32>(depthIdx_2), u32(0)));
    (*depthPosition_0) = depthToWorld_0(depthIdx_2, (textureLoad((depthIn_0), ((_S18)).xy, ((_S18)).z).x));
    var _S19 : i32 = depthIdx_2.x;
    var _S20 : i32 = depthIdx_2.y;
    var depthPosition_dx_0 : vec4<f32> = computeDepthNormalSample_0(vec2<i32>(_S19 - i32(1), _S20), vec2<i32>(_S19 + i32(1), _S20));
    var depthPosition_dy_0 : vec4<f32> = computeDepthNormalSample_0(vec2<i32>(_S19, _S20 - i32(1)), vec2<i32>(_S19, _S20 + i32(1)));
    (*depthNormal_0) = - rayDir_0;
    if(((*depthPosition_0).w) != 0.0f)
    {
        _S17 = (depthPosition_dx_0.w) != 0.0f;
    }
    else
    {
        _S17 = false;
    }
    if(_S17)
    {
        _S17 = (depthPosition_dy_0.w) != 0.0f;
    }
    else
    {
        _S17 = false;
    }
    if(_S17)
    {
        var _S21 : vec3<f32> = normalize(crossProduct_0(depthPosition_dx_0.xyz - (*depthPosition_0).xyz, depthPosition_dy_0.xyz - (*depthPosition_0).xyz));
        (*depthNormal_0) = _S21;
        if((dot(_S21, rayDir_0)) > 0.0f)
        {
            (*depthNormal_0) = - (*depthNormal_0);
        }
    }
    return;
}

struct NvFlowRayMarchCloudLayerShaderParams_0
{
     densityMultiplier_0 : f32,
     enableCloudMode_0 : u32,
     pad1_1 : f32,
     pad2_0 : f32,
     ambientColor_0 : vec3<f32>,
     ambientMultiplier_0 : f32,
     volumeBaseColor_0 : vec3<f32>,
     volumeColorMultiplier_0 : f32,
     sunDirection_0 : vec3<f32>,
     shadowStepMultiplier_0 : f32,
     attenuationMultiplier_0 : vec3<f32>,
     numShadowSteps_0 : i32,
};

fn unpackStorage_2( _S22 : NvFlowRayMarchCloudLayerShaderParams_std430_0) -> NvFlowRayMarchCloudLayerShaderParams_0
{
    var _S23 : NvFlowRayMarchCloudLayerShaderParams_0 = NvFlowRayMarchCloudLayerShaderParams_0( _S22.densityMultiplier_0, _S22.enableCloudMode_0, _S22.pad1_1, _S22.pad2_0, _S22.ambientColor_0, _S22.ambientMultiplier_0, _S22.volumeBaseColor_0, _S22.volumeColorMultiplier_0, _S22.sunDirection_0, _S22.shadowStepMultiplier_0, _S22.attenuationMultiplier_0, _S22.numShadowSteps_0 );
    return _S23;
}

struct NvFlowRayMarchLayerShaderParams_0
{
     blockSizeWorld_0 : vec3<f32>,
     minBlockSizeWorld_0 : f32,
     blockSizeWorldInv_0 : vec3<f32>,
     maxBlockSizeWorld_0 : f32,
     cellSize_0 : vec3<f32>,
     stepSize_0 : f32,
     cellSizeInv_0 : vec3<f32>,
     stepSizeInv_0 : f32,
     locationMin_0 : vec4<i32>,
     locationMax_0 : vec4<i32>,
     worldMin_0 : vec3<f32>,
     enableBlockWireframe_0 : u32,
     worldMax_0 : vec3<f32>,
     enableRawMode_0 : u32,
     velocityCellSizeInv_0 : vec3<f32>,
     deltaTime_0 : f32,
     layerAndLevel_0 : i32,
     layerAndLevelColormapV_0 : f32,
     alphaScale_0 : f32,
     colorScale_0 : f32,
     shadowFactor_0 : f32,
     rawModeIsosurface_0 : u32,
     rawModeNormalize_0 : u32,
     pad3_0 : f32,
     colormapXOffset_0 : f32,
     colormapXScale_0 : f32,
     pad4_0 : f32,
     pad5_0 : f32,
     cloud_0 : NvFlowRayMarchCloudLayerShaderParams_0,
};

fn unpackStorage_3( _S24 : NvFlowRayMarchLayerShaderParams_std430_0) -> NvFlowRayMarchLayerShaderParams_0
{
    var _S25 : NvFlowRayMarchLayerShaderParams_0 = NvFlowRayMarchLayerShaderParams_0( _S24.blockSizeWorld_0, _S24.minBlockSizeWorld_0, _S24.blockSizeWorldInv_0, _S24.maxBlockSizeWorld_0, _S24.cellSize_0, _S24.stepSize_0, _S24.cellSizeInv_0, _S24.stepSizeInv_0, _S24.locationMin_0, _S24.locationMax_0, _S24.worldMin_0, _S24.enableBlockWireframe_0, _S24.worldMax_0, _S24.enableRawMode_0, _S24.velocityCellSizeInv_0, _S24.deltaTime_0, _S24.layerAndLevel_0, _S24.layerAndLevelColormapV_0, _S24.alphaScale_0, _S24.colorScale_0, _S24.shadowFactor_0, _S24.rawModeIsosurface_0, _S24.rawModeNormalize_0, _S24.pad3_0, _S24.colormapXOffset_0, _S24.colormapXScale_0, _S24.pad4_0, _S24.pad5_0, unpackStorage_2(_S24.cloud_0) );
    return _S25;
}

fn NvFlowIntersectBox_0( rayDir_1 : vec3<f32>,  rayDirInv_0 : vec3<f32>,  boxMin_0 : vec3<f32>,  boxMax_0 : vec3<f32>,  tnear_0 : ptr<function, f32>,  tfar_0 : ptr<function, f32>) -> bool
{
    var tbot_0 : vec3<f32> = boxMin_0 * rayDirInv_0;
    var ttop_0 : vec3<f32> = boxMax_0 * rayDirInv_0;
    var tmin_0 : vec3<f32> = min(ttop_0, tbot_0);
    var tmax_0 : vec3<f32> = max(ttop_0, tbot_0);
    var _S26 : f32 = tmin_0.x;
    (*tnear_0) = max(max(_S26, tmin_0.y), max(_S26, tmin_0.z));
    var _S27 : f32 = tmax_0.x;
    var _S28 : f32 = min(min(_S27, tmax_0.y), min(_S27, tmax_0.z));
    (*tfar_0) = _S28;
    return _S28 > (*tnear_0);
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowRayMarchComputeFinalLocation_0( rayDir_2 : vec3<f32>,  location_0 : vec4<i32>,  locationMin_1 : vec4<i32>,  locationMax_1 : vec4<i32>) -> vec3<i32>
{
    var _S29 : i32;
    if((rayDir_2.x) > 0.0f)
    {
        _S29 = max(location_0.x, locationMax_1.x);
    }
    else
    {
        _S29 = min(location_0.x, locationMin_1.x - i32(1));
    }
    var _S30 : i32;
    if((rayDir_2.y) > 0.0f)
    {
        _S30 = max(location_0.y, locationMax_1.y);
    }
    else
    {
        _S30 = min(location_0.y, locationMin_1.y - i32(1));
    }
    var _S31 : i32;
    if((rayDir_2.z) > 0.0f)
    {
        _S31 = max(location_0.z, locationMax_1.z);
    }
    else
    {
        _S31 = min(location_0.z, locationMin_1.z - i32(1));
    }
    return vec3<i32>(_S29, _S30, _S31);
}

fn NvFlowRayMarchHash_0( inputValue_0 : u32) -> u32
{
    var state_0 : u32 = inputValue_0 * u32(747796405) + u32(2891336453);
    var word_0 : u32 = ((((state_0 >> ((((state_0 >> (u32(28)))) + u32(4))))) ^ (state_0))) * u32(277803737);
    return (((word_0 >> (u32(22)))) ^ (word_0));
}

fn NvFlowRayMarchRandNorm_0( inputValue_1 : u32) -> f32
{
    return f32(((NvFlowRayMarchHash_0(inputValue_1)) & (u32(65535)))) * 0.00001525902189314f;
}

fn NvFlowRayMarchNoiseFromDir_0( rayDir_3 : vec3<f32>) -> f32
{
    var _S32 : f32 = abs(rayDir_3.x);
    var _S33 : f32 = abs(rayDir_3.y);
    var _S34 : bool;
    if(_S32 > _S33)
    {
        _S34 = _S32 > (abs(rayDir_3.z));
    }
    else
    {
        _S34 = false;
    }
    var uv_0 : vec2<f32>;
    if(_S34)
    {
        uv_0 = rayDir_3.yz;
    }
    else
    {
        if(_S33 > _S32)
        {
            _S34 = _S33 > (abs(rayDir_3.z));
        }
        else
        {
            _S34 = false;
        }
        if(_S34)
        {
            uv_0 = rayDir_3.xz;
        }
        else
        {
            uv_0 = rayDir_3.xy;
        }
    }
    var maxAxis_0 : f32 = max(_S32, max(_S33, abs(rayDir_3.z)));
    if(maxAxis_0 > 0.0f)
    {
        uv_0 = uv_0 * vec2<f32>((1.0f / maxAxis_0));
    }
    var _S35 : vec2<f32> = vec2<f32>(0.5f);
    var uv_1 : vec2<f32> = _S35 * uv_0 + _S35;
    return NvFlowRayMarchRandNorm_0((u32(65535.0f * uv_1.x) ^ (((u32(65535.0f * uv_1.y) << (u32(16)))))));
}

fn NvFlowRayMarchWireframe_0( paramsTable_0 : NvFlowSparseLevelParams_0,  params_0 : NvFlowRayMarchLayerShaderParams_0,  rayOrigin_0 : vec3<f32>,  rayMinT_0 : f32,  rayDir_4 : vec3<f32>,  hitT_0 : f32,  location_1 : vec4<i32>,  brightness_0 : f32,  sum_0 : ptr<function, vec4<f32>>,  nominalT_0 : ptr<function, f32>)
{
    if(hitT_0 > rayMinT_0)
    {
        var blockFrac_0 : vec3<f32> = params_0.blockSizeWorld_0 * ((rayOrigin_0 + vec3<f32>(hitT_0) * rayDir_4) * params_0.blockSizeWorldInv_0 - vec3<f32>(location_1.xyz));
        var _S36 : f32 = params_0.cellSize_0.x;
        var _S37 : f32 = blockFrac_0.x;
        var faceX_0 : f32 = max(2.0f * _S36 - _S37, _S37 - f32(paramsTable_0.blockDimLessOne_0.x - u32(1)) * _S36);
        var _S38 : f32 = params_0.cellSize_0.y;
        var _S39 : f32 = blockFrac_0.y;
        var faceY_0 : f32 = max(2.0f * _S38 - _S39, _S39 - f32(paramsTable_0.blockDimLessOne_0.y - u32(1)) * _S38);
        var _S40 : f32 = params_0.cellSize_0.z;
        var _S41 : f32 = blockFrac_0.z;
        var faceZ_0 : f32 = max(2.0f * _S40 - _S41, _S41 - f32(paramsTable_0.blockDimLessOne_0.z - u32(1)) * _S40);
        var _S42 : bool = faceX_0 > 0.0f;
        var _S43 : bool;
        if(_S42)
        {
            _S43 = faceY_0 > 0.0f;
        }
        else
        {
            _S43 = false;
        }
        if(_S43)
        {
            _S43 = true;
        }
        else
        {
            if(faceY_0 > 0.0f)
            {
                _S43 = faceZ_0 > 0.0f;
            }
            else
            {
                _S43 = false;
            }
        }
        if(_S43)
        {
            _S43 = true;
        }
        else
        {
            if(faceZ_0 > 0.0f)
            {
                _S43 = _S42;
            }
            else
            {
                _S43 = false;
            }
        }
        if(_S43)
        {
            var faceX_1 : f32 = faceX_0 - _S36;
            var faceY_1 : f32 = faceY_0 - _S38;
            var faceZ_1 : f32 = faceZ_0 - _S40;
            var color_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
            if(faceX_1 > faceY_1)
            {
                _S43 = faceX_1 > faceZ_1;
            }
            else
            {
                _S43 = false;
            }
            if(_S43)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceY_1, faceZ_1)) * params_0.cellSizeInv_0.x;
            }
            if(faceY_1 > faceX_1)
            {
                _S43 = faceY_1 > faceZ_1;
            }
            else
            {
                _S43 = false;
            }
            if(_S43)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceX_1, faceZ_1)) * params_0.cellSizeInv_0.y;
            }
            if(faceZ_1 > faceX_1)
            {
                _S43 = faceZ_1 > faceY_1;
            }
            else
            {
                _S43 = false;
            }
            if(_S43)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceX_1, faceY_1)) * params_0.cellSizeInv_0.z;
            }
            color_0[i32(3)] = color_0[i32(3)] * color_0.w;
            color_0[i32(3)] = 1.0f - color_0.w;
            (*nominalT_0) = (*sum_0).w * (color_0.w * hitT_0) + (*nominalT_0);
            var _S44 : vec3<f32> = vec3<f32>((*sum_0).w) * (vec3<f32>(color_0.w) * color_0.xyz) + (*sum_0).xyz;
            (*sum_0).x = _S44.x;
            (*sum_0).y = _S44.y;
            (*sum_0).z = _S44.z;
            (*sum_0)[i32(3)] = (1.0f - color_0.w) * (*sum_0).w;
        }
    }
    return;
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S45 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S45, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S45 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowRayMarchAdvanceRay_0( blockSizeWorld_1 : vec3<f32>,  rayDir_5 : vec3<f32>,  rayDirInv_1 : vec3<f32>,  rayOrigin_1 : vec3<f32>,  location_2 : ptr<function, vec4<i32>>,  hitT_1 : ptr<function, f32>)
{
    var _S46 : i32 = (*location_2).x;
    var _S47 : f32 = rayDir_5.x;
    var _S48 : bool = _S47 > 0.0f;
    var _S49 : i32;
    if(_S48)
    {
        _S49 = i32(1);
    }
    else
    {
        _S49 = i32(0);
    }
    var hitTx_0 : f32 = (f32(_S46 + _S49) * blockSizeWorld_1.x - rayOrigin_1.x) * rayDirInv_1.x;
    var _S50 : i32 = (*location_2).y;
    var _S51 : f32 = rayDir_5.y;
    var _S52 : bool = _S51 > 0.0f;
    if(_S52)
    {
        _S49 = i32(1);
    }
    else
    {
        _S49 = i32(0);
    }
    var hitTy_0 : f32 = (f32(_S50 + _S49) * blockSizeWorld_1.y - rayOrigin_1.y) * rayDirInv_1.y;
    var _S53 : i32 = (*location_2).z;
    var _S54 : f32 = rayDir_5.z;
    var _S55 : bool = _S54 > 0.0f;
    if(_S55)
    {
        _S49 = i32(1);
    }
    else
    {
        _S49 = i32(0);
    }
    var hitTz_0 : f32 = (f32(_S53 + _S49) * blockSizeWorld_1.z - rayOrigin_1.z) * rayDirInv_1.z;
    var _S56 : bool;
    if(_S47 != 0.0f)
    {
        if(hitTx_0 <= hitTy_0)
        {
            _S56 = true;
        }
        else
        {
            _S56 = _S51 == 0.0f;
        }
    }
    else
    {
        _S56 = false;
    }
    if(_S56)
    {
        if(hitTx_0 <= hitTz_0)
        {
            _S56 = true;
        }
        else
        {
            _S56 = _S54 == 0.0f;
        }
    }
    else
    {
        _S56 = false;
    }
    if(_S56)
    {
        (*hitT_1) = hitTx_0;
        if(_S48)
        {
            _S49 = i32(1);
        }
        else
        {
            _S49 = i32(-1);
        }
        (*location_2)[i32(0)] = (*location_2)[i32(0)] + _S49;
    }
    else
    {
        if(_S51 != 0.0f)
        {
            if(hitTy_0 <= hitTx_0)
            {
                _S56 = true;
            }
            else
            {
                _S56 = _S47 == 0.0f;
            }
        }
        else
        {
            _S56 = false;
        }
        if(_S56)
        {
            if(hitTy_0 <= hitTz_0)
            {
                _S56 = true;
            }
            else
            {
                _S56 = _S54 == 0.0f;
            }
        }
        else
        {
            _S56 = false;
        }
        if(_S56)
        {
            (*hitT_1) = hitTy_0;
            if(_S52)
            {
                _S49 = i32(1);
            }
            else
            {
                _S49 = i32(-1);
            }
            (*location_2)[i32(1)] = (*location_2)[i32(1)] + _S49;
        }
        else
        {
            (*hitT_1) = hitTz_0;
            if(_S55)
            {
                _S49 = i32(1);
            }
            else
            {
                _S49 = i32(-1);
            }
            (*location_2)[i32(2)] = (*location_2)[i32(2)] + _S49;
        }
    }
    return;
}

fn NvFlowLocationToBlockIdx_0( _S57 : NvFlowSparseLevelParams_0,  _S58 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S58.xyz) & ((_S57.tableDimLessOne_0)));
    var _S59 : u32 = ((((((((bucketIdx_0.z) << ((_S57.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S57.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S60 : u32 = tableIn_0[_S59 + u32(1)];
    var _S61 : i32 = _S58.x;
    var _S62 : i32 = _S58.y;
    var _S63 : i32 = _S58.z;
    var _S64 : i32 = _S58.w;
    var blockIdx_0 : u32 = tableIn_0[_S59];
    for(;;)
    {
        if(blockIdx_0 < _S60)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_0 << (u32(2)))) + _S57.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(tableIn_0[compareLocationIdx_0 + u32(3)]);
        var _S65 : bool;
        if(i32(tableIn_0[compareLocationIdx_0]) == _S61)
        {
            _S65 = compareLocation_y_0 == _S62;
        }
        else
        {
            _S65 = false;
        }
        var _S66 : bool;
        if(_S65)
        {
            _S66 = compareLocation_z_0 == _S63;
        }
        else
        {
            _S66 = false;
        }
        var _S67 : bool;
        if(_S66)
        {
            _S67 = compareLocation_w_0 == _S64;
        }
        else
        {
            _S67 = false;
        }
        if(_S67)
        {
            outBlockIdx_0 = blockIdx_0;
            break;
        }
        blockIdx_0 = blockIdx_0 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToRealOffset_0( _S68 : NvFlowSparseLevelParams_0,  _S69 : vec4<i32>,  _S70 : u32) -> vec3<i32>
{
    var tableValue_0 : u32;
    if(_S70 != u32(4294967295))
    {
        tableValue_0 = tableIn_0[_S70 + _S68.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0(vec3<i32>(i32(0), i32(0), i32(0)), tableValue_0).xyz - (((_S69.xyz) << ((_S68.blockDimBits_0))));
}

fn NvFlowGlobalVirtualToReal_0( _S71 : NvFlowSparseLevelParams_0,  _S72 : vec4<i32>) -> vec4<i32>
{
    var _S73 : vec3<i32> = _S72.xyz;
    var _S74 : u32 = NvFlowLocationToBlockIdx_0(_S71, vec4<i32>((_S73 >> (vec3<u32>(vec3<i32>(_S71.blockDimBits_0)))), _S72.w));
    var tableValue_1 : u32;
    if(_S74 != u32(4294967295))
    {
        tableValue_1 = tableIn_0[_S74 + _S71.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_1 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S73 & (vec3<i32>(_S71.blockDimLessOne_0))), tableValue_1);
}

fn NvFlowGlobalReadLinear4f_0( _S75 : texture_3d<f32>,  _S76 : sampler,  _S77 : NvFlowSparseLevelParams_0,  _S78 : vec3<f32>,  _S79 : i32) -> vec4<f32>
{
    var vidx_0 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0(_S78), _S79);
    var _S80 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S77, vidx_0);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S80.xyz) + _S78 - vec3<f32>(vidx_0.xyz);
    var _S81 : vec4<f32>;
    if(bool(_S80.w))
    {
        _S81 = (textureSampleLevel((_S75), (_S76), (readIdxf_0 * _S77.dimInv_0), (0.0f)));
    }
    else
    {
        _S81 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S81;
}

fn NvFlowRayMarchBlockCloud_0( _S82 : texture_3d<f32>,  _S83 : sampler,  _S84 : texture_2d<f32>,  _S85 : sampler,  _S86 : NvFlowSparseLevelParams_0,  _S87 : NvFlowRayMarchLayerShaderParams_0,  _S88 : vec3<f32>,  _S89 : f32,  _S90 : vec3<f32>,  _S91 : f32,  _S92 : vec3<f32>,  _S93 : u32,  _S94 : vec4<i32>,  _S95 : ptr<function, vec4<f32>>,  _S96 : ptr<function, f32>) -> bool
{
    var _S97 : vec3<i32> = _S94.xyz;
    var _S98 : vec3<f32> = vec3<f32>(0.00009999999747379f) * _S87.cellSize_0;
    var boxMinT_0 : f32;
    var boxMaxT_0 : f32;
    var _S99 : bool = NvFlowIntersectBox_0(_S90, _S92, vec3<f32>(_S97) * _S87.blockSizeWorld_0 - _S88 - _S98, vec3<f32>(_S97 + vec3<i32>(i32(1), i32(1), i32(1))) * _S87.blockSizeWorld_0 - _S88 + _S98, &(boxMinT_0), &(boxMaxT_0));
    var _S100 : f32 = max(_S89, boxMinT_0);
    boxMinT_0 = _S100;
    var isHit_0 : bool;
    if(_S100 > boxMaxT_0)
    {
        isHit_0 = false;
    }
    else
    {
        isHit_0 = _S99;
    }
    var _S101 : bool = boxMaxT_0 > _S91;
    if(_S101)
    {
        boxMaxT_0 = _S91;
    }
    if(isHit_0)
    {
        var _S102 : bool = (_S87.enableBlockWireframe_0) != u32(0);
        if(_S102)
        {
            NvFlowRayMarchWireframe_0(_S86, _S87, _S88, _S89, _S90, boxMinT_0, _S94, 1.0f, &((*_S95)), &((*_S96)));
        }
        var shadowDensity_0 : f32;
        var shadowSamplePos_0 : vec3<f32>;
        var shadowStepIdx_0 : i32;
        var cellMinT_0 : f32 = round(_S87.stepSizeInv_0 * boxMinT_0);
        var _S103 : i32 = i32(round(_S87.stepSizeInv_0 * boxMaxT_0) - cellMinT_0);
        var currentT_0 : f32 = _S87.stepSize_0 * cellMinT_0;
        var _S104 : vec3<f32> = vec3<f32>(_S87.stepSize_0);
        var vidxf_0 : vec3<f32> = (_S88 + vec3<f32>(currentT_0) * _S90) * _S87.cellSizeInv_0;
        var vidxfStep_0 : vec3<f32> = _S104 * _S90 * _S87.cellSizeInv_0;
        var _S105 : vec3<f32> = vidxf_0 + vec3<f32>(NvFlowGlobalVirtualToRealOffset_0(_S86, _S94, _S93));
        const ambientSampleOffset_0 : vec3<f32> = vec3<f32>(0.0f, 0.20000000298023224f, 0.0f);
        var shadowStep_0 : vec3<f32> = _S104 * normalize(_S87.cloud_0.sunDirection_0) * _S87.cellSizeInv_0 * vec3<f32>(_S87.cloud_0.shadowStepMultiplier_0);
        var _S106 : f32 = f32(_S87.cloud_0.numShadowSteps_0);
        var stepIdx_0 : i32 = i32(0);
        var ridxf_0 : vec3<f32> = _S105;
        var vidxf_1 : vec3<f32> = vidxf_0;
        var currentT_1 : f32 = currentT_0;
        var _S107 : vec3<f32> = vec3<f32>(_S87.cloud_0.volumeColorMultiplier_0);
        var _S108 : vec3<f32> = vec3<f32>(_S87.cloud_0.ambientMultiplier_0);
        for(;;)
        {
            if(stepIdx_0 < _S103)
            {
            }
            else
            {
                break;
            }
            if(((*_S95).w) < 0.00100000004749745f)
            {
                break;
            }
            var densitySample_0 : f32 = (textureSampleLevel((_S82), (_S83), (ridxf_0 * _S86.dimInv_0), (0.0f))).w;
            if(densitySample_0 > 0.00100000004749745f)
            {
                var _S109 : vec3<f32> = vidxf_1 + shadowStep_0;
                var density_0 : f32 = clamp(densitySample_0 * _S87.cloud_0.densityMultiplier_0, 0.0f, 1.0f);
                var _S110 : f32 = 1.0f - density_0;
                var aoSamplePos_0 : vec3<f32> = vidxf_1 + ambientSampleOffset_0;
                shadowStepIdx_0 = i32(0);
                shadowSamplePos_0 = _S109;
                shadowDensity_0 = 0.0f;
                var _S111 : vec3<f32> = vec3<f32>(density_0);
                for(;;)
                {
                    if(shadowStepIdx_0 < (_S87.cloud_0.numShadowSteps_0))
                    {
                    }
                    else
                    {
                        break;
                    }
                    var shadowDensity_1 : f32 = shadowDensity_0 + NvFlowGlobalReadLinear4f_0(_S82, _S83, _S86, shadowSamplePos_0, _S87.layerAndLevel_0).w;
                    var shadowSamplePos_1 : vec3<f32> = shadowSamplePos_0 + shadowStep_0;
                    shadowStepIdx_0 = shadowStepIdx_0 + i32(1);
                    shadowSamplePos_0 = shadowSamplePos_1;
                    shadowDensity_0 = shadowDensity_1;
                }
                var _S112 : vec3<f32> = (*_S95).xyz + exp(vec3<f32>((- shadowDensity_0 / _S106)) * _S87.cloud_0.attenuationMultiplier_0) * _S111 * vec3<f32>((*_S95).w) * _S87.cloud_0.volumeBaseColor_0 * _S107;
                (*_S95).x = _S112.x;
                (*_S95).y = _S112.y;
                (*_S95).z = _S112.z;
                (*_S95)[i32(3)] = (*_S95)[i32(3)] * _S110;
                var _S113 : vec3<f32> = (*_S95).xyz + vec3<f32>((exp(- NvFlowGlobalReadLinear4f_0(_S82, _S83, _S86, aoSamplePos_0, _S87.layerAndLevel_0).w) * density_0 * (*_S95).w)) * _S87.cloud_0.ambientColor_0 * _S108;
                (*_S95).x = _S113.x;
                (*_S95).y = _S113.y;
                (*_S95).z = _S113.z;
            }
            var ridxf_1 : vec3<f32> = ridxf_0 + vidxfStep_0;
            var vidxf_2 : vec3<f32> = vidxf_1 + vidxfStep_0;
            var currentT_2 : f32 = currentT_1 + _S87.stepSize_0;
            stepIdx_0 = stepIdx_0 + i32(1);
            ridxf_0 = ridxf_1;
            vidxf_1 = vidxf_2;
            currentT_1 = currentT_2;
        }
        if(_S101)
        {
            if(((*_S95).w) > 0.00100000004749745f)
            {
                var densitySample_1 : f32 = (textureSampleLevel((_S82), (_S83), (ridxf_0 * _S86.dimInv_0), (0.0f))).w;
                if(densitySample_1 > 0.00100000004749745f)
                {
                    var _S114 : vec3<f32> = vidxf_1 + shadowStep_0;
                    var density_1 : f32 = clamp(densitySample_1 * _S87.cloud_0.densityMultiplier_0, 0.0f, 1.0f);
                    var _S115 : f32 = 1.0f - density_1;
                    var aoSamplePos_1 : vec3<f32> = vidxf_1 + ambientSampleOffset_0;
                    shadowStepIdx_0 = i32(0);
                    shadowSamplePos_0 = _S114;
                    shadowDensity_0 = 0.0f;
                    var _S116 : vec3<f32> = vec3<f32>(density_1);
                    for(;;)
                    {
                        if(shadowStepIdx_0 < (_S87.cloud_0.numShadowSteps_0))
                        {
                        }
                        else
                        {
                            break;
                        }
                        var shadowDensity_2 : f32 = shadowDensity_0 + NvFlowGlobalReadLinear4f_0(_S82, _S83, _S86, shadowSamplePos_0, _S87.layerAndLevel_0).w;
                        var shadowSamplePos_2 : vec3<f32> = shadowSamplePos_0 + shadowStep_0;
                        shadowStepIdx_0 = shadowStepIdx_0 + i32(1);
                        shadowSamplePos_0 = shadowSamplePos_2;
                        shadowDensity_0 = shadowDensity_2;
                    }
                    var _S117 : vec3<f32> = (*_S95).xyz + exp(vec3<f32>((- shadowDensity_0 / _S106)) * _S87.cloud_0.attenuationMultiplier_0) * _S116 * vec3<f32>((*_S95).w) * _S87.cloud_0.volumeBaseColor_0 * _S107;
                    (*_S95).x = _S117.x;
                    (*_S95).y = _S117.y;
                    (*_S95).z = _S117.z;
                    (*_S95)[i32(3)] = (*_S95)[i32(3)] * _S115;
                    var _S118 : vec3<f32> = (*_S95).xyz + vec3<f32>((exp(- NvFlowGlobalReadLinear4f_0(_S82, _S83, _S86, aoSamplePos_1, _S87.layerAndLevel_0).w) * density_1 * (*_S95).w)) * _S87.cloud_0.ambientColor_0 * _S108;
                    (*_S95).x = _S118.x;
                    (*_S95).y = _S118.y;
                    (*_S95).z = _S118.z;
                }
            }
        }
        if(_S102)
        {
            NvFlowRayMarchWireframe_0(_S86, _S87, _S88, _S89, _S90, boxMaxT_0, _S94, 0.30000001192092896f, &((*_S95)), &((*_S96)));
        }
    }
    return _S101;
}

fn NvFlowRayMarchBlock_0( _S119 : texture_3d<f32>,  _S120 : sampler,  _S121 : texture_2d<f32>,  _S122 : sampler,  _S123 : NvFlowSparseLevelParams_0,  _S124 : NvFlowRayMarchLayerShaderParams_0,  _S125 : vec3<f32>,  _S126 : f32,  _S127 : vec3<f32>,  _S128 : f32,  _S129 : vec3<f32>,  _S130 : f32,  _S131 : u32,  _S132 : vec4<i32>,  _S133 : ptr<function, vec4<f32>>,  _S134 : ptr<function, f32>) -> bool
{
    var _S135 : vec3<i32> = _S132.xyz;
    var _S136 : vec3<f32> = vec3<f32>(0.00009999999747379f) * _S124.cellSize_0;
    var boxMinT_1 : f32;
    var boxMaxT_1 : f32;
    var _S137 : bool = NvFlowIntersectBox_0(_S127, _S129, vec3<f32>(_S135) * _S124.blockSizeWorld_0 - _S125 - _S136, vec3<f32>(_S135 + vec3<i32>(i32(1), i32(1), i32(1))) * _S124.blockSizeWorld_0 - _S125 + _S136, &(boxMinT_1), &(boxMaxT_1));
    var _S138 : f32 = max(_S126, boxMinT_1);
    boxMinT_1 = _S138;
    var isHit_1 : bool;
    if(_S138 > boxMaxT_1)
    {
        isHit_1 = false;
    }
    else
    {
        isHit_1 = _S137;
    }
    var _S139 : bool = boxMaxT_1 > _S128;
    if(_S139)
    {
        boxMaxT_1 = _S128;
    }
    var hitMax_0 : bool;
    if(isHit_1)
    {
        var _S140 : bool = (_S124.enableBlockWireframe_0) != u32(0);
        if(_S140)
        {
            NvFlowRayMarchWireframe_0(_S123, _S124, _S125, _S126, _S127, boxMinT_1, _S132, 1.0f, &((*_S133)), &((*_S134)));
        }
        var cellMinT_1 : f32 = - floor(- (_S124.stepSizeInv_0 * boxMinT_1 + _S130)) - _S130;
        var _S141 : i32 = i32(- floor(- (_S124.stepSizeInv_0 * boxMaxT_1 + _S130)) - _S130 - cellMinT_1);
        var currentT_3 : f32 = _S124.stepSize_0 * cellMinT_1;
        var _S142 : vec3<f32> = vec3<f32>(_S124.stepSize_0) * _S127 * _S124.cellSizeInv_0;
        var _S143 : vec3<f32> = (_S125 + vec3<f32>(currentT_3) * _S127) * _S124.cellSizeInv_0 + vec3<f32>(NvFlowGlobalVirtualToRealOffset_0(_S123, _S132, _S131));
        var _S144 : bool = (_S124.enableRawMode_0) == u32(0);
        const _S145 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
        var _S146 : bool = (_S124.rawModeIsosurface_0) != u32(0);
        var _S147 : bool = (_S124.rawModeNormalize_0) != u32(0);
        var stepIdx_1 : i32 = i32(0);
        var ridxf_2 : vec3<f32> = _S143;
        var currentT_4 : f32 = currentT_3;
        var _S148 : vec3<f32> = vec3<f32>(_S124.colorScale_0);
        for(;;)
        {
            if(stepIdx_1 < _S141)
            {
            }
            else
            {
                break;
            }
            var value_0 : vec4<f32> = (textureSampleLevel((_S119), (_S120), (ridxf_2 * _S123.dimInv_0), (0.0f)));
            var color_1 : vec4<f32> = value_0;
            if(_S144)
            {
                var _S149 : vec4<f32> = (textureSampleLevel((_S121), (_S122), (vec2<f32>(_S124.colormapXScale_0 * value_0.x + _S124.colormapXOffset_0, _S124.layerAndLevelColormapV_0)), (0.0f)));
                color_1 = _S149;
                var _S150 : vec3<f32> = _S149.xyz * vec3<f32>((1.0f + _S124.shadowFactor_0 * (value_0.z - 1.0f)));
                color_1.x = _S150.x;
                color_1.y = _S150.y;
                color_1.z = _S150.z;
                color_1[i32(3)] = color_1[i32(3)] * value_0.w;
            }
            else
            {
                if(_S146)
                {
                    var _S151 : f32;
                    if((value_0.w) > 0.5f)
                    {
                        _S151 = 1.0f;
                    }
                    else
                    {
                        _S151 = 0.0f;
                    }
                    color_1[i32(3)] = _S151;
                }
                if(_S147)
                {
                    if((color_1.w) > 0.0f)
                    {
                        var _S152 : vec3<f32> = color_1.xyz * vec3<f32>((1.0f / value_0.w));
                        color_1.x = _S152.x;
                        color_1.y = _S152.y;
                        color_1.z = _S152.z;
                    }
                }
            }
            var _S153 : vec3<f32> = color_1.xyz * _S148;
            color_1.x = _S153.x;
            color_1.y = _S153.y;
            color_1.z = _S153.z;
            var _S154 : vec4<f32> = max(_S145, color_1);
            color_1 = _S154;
            color_1[i32(3)] = min(1.0f, _S154.w) * _S124.alphaScale_0;
            (*_S134) = (*_S133).w * (color_1.w * currentT_4) + (*_S134);
            var _S155 : vec3<f32> = vec3<f32>((*_S133).w) * (vec3<f32>(color_1.w) * color_1.xyz) + (*_S133).xyz;
            (*_S133).x = _S155.x;
            (*_S133).y = _S155.y;
            (*_S133).z = _S155.z;
            (*_S133)[i32(3)] = (1.0f - color_1.w) * (*_S133).w;
            var ridxf_3 : vec3<f32> = ridxf_2 + _S142;
            var currentT_5 : f32 = currentT_4 + _S124.stepSize_0;
            stepIdx_1 = stepIdx_1 + i32(1);
            ridxf_2 = ridxf_3;
            currentT_4 = currentT_5;
        }
        if(((*_S133).w) < 0.00004999999873689f)
        {
            hitMax_0 = true;
        }
        else
        {
            hitMax_0 = _S139;
        }
        if(_S140)
        {
            NvFlowRayMarchWireframe_0(_S123, _S124, _S125, _S126, _S127, boxMaxT_1, _S132, 0.30000001192092896f, &((*_S133)), &((*_S134)));
        }
    }
    else
    {
        hitMax_0 = _S139;
    }
    return hitMax_0;
}

fn NvFlowRayMarchBlocks_0( _S156 : texture_3d<f32>,  _S157 : sampler,  _S158 : texture_2d<f32>,  _S159 : sampler,  _S160 : NvFlowSparseLevelParams_0,  _S161 : NvFlowRayMarchLayerShaderParams_0,  _S162 : vec3<f32>,  _S163 : f32,  _S164 : vec3<f32>,  _S165 : f32,  _S166 : vec3<f32>,  _S167 : ptr<function, vec4<f32>>,  _S168 : ptr<function, f32>)
{
    var boxMinT_2 : f32;
    var boxMaxT_2 : f32;
    var _S169 : bool = NvFlowIntersectBox_0(_S164, _S166, _S161.worldMin_0 - _S162, _S161.worldMax_0 - _S162, &(boxMinT_2), &(boxMaxT_2));
    var _S170 : f32 = max(_S163, boxMinT_2);
    boxMinT_2 = _S170;
    var isHit_2 : bool;
    if(_S170 > boxMaxT_2)
    {
        isHit_2 = false;
    }
    else
    {
        isHit_2 = _S169;
    }
    if(isHit_2)
    {
        var _S171 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0((_S164 * vec3<f32>(boxMinT_2) + _S162) * _S161.blockSizeWorldInv_0), _S161.layerAndLevel_0);
        var location_3 : vec4<i32> = _S171;
        var _S172 : vec3<i32> = NvFlowRayMarchComputeFinalLocation_0(_S164, _S171, _S161.locationMin_0, _S161.locationMax_0);
        var _S173 : f32 = NvFlowRayMarchNoiseFromDir_0(_S164);
        var blockHitT_0 : f32 = boxMinT_2;
        var _S174 : i32 = _S172.x;
        var _S175 : i32 = _S172.y;
        var _S176 : i32 = _S172.z;
        var _S177 : bool = (_S161.cloud_0.enableCloudMode_0) != u32(0);
        var hitMax_1 : bool = false;
        for(;;)
        {
            if((location_3.x) != _S174)
            {
                isHit_2 = (location_3.y) != _S175;
            }
            else
            {
                isHit_2 = false;
            }
            var _S178 : bool;
            if(isHit_2)
            {
                _S178 = (location_3.z) != _S176;
            }
            else
            {
                _S178 = false;
            }
            var _S179 : bool;
            if(_S178)
            {
                _S179 = !hitMax_1;
            }
            else
            {
                _S179 = false;
            }
            if(_S179)
            {
            }
            else
            {
                break;
            }
            var _S180 : u32 = NvFlowLocationToBlockIdx_0(_S160, location_3);
            if(_S180 != u32(4294967295))
            {
                var hitMax_2 : bool;
                if(_S177)
                {
                    var _S181 : bool = NvFlowRayMarchBlockCloud_0(_S156, _S157, _S158, _S159, _S160, _S161, _S162, _S163, _S164, _S165, _S166, _S180, location_3, &((*_S167)), &((*_S168)));
                    hitMax_2 = _S181;
                }
                else
                {
                    var _S182 : bool = NvFlowRayMarchBlock_0(_S156, _S157, _S158, _S159, _S160, _S161, _S162, _S163, _S164, _S165, _S166, _S173, _S180, location_3, &((*_S167)), &((*_S168)));
                    hitMax_2 = _S182;
                }
                hitMax_1 = hitMax_2;
            }
            NvFlowRayMarchAdvanceRay_0(_S161.blockSizeWorld_0, _S164, _S166, _S162, &(location_3), &(blockHitT_0));
        }
    }
    return;
}

fn NvFlowRayMarchBlocksMotion_0( _S183 : texture_3d<f32>,  _S184 : sampler,  _S185 : texture_3d<f32>,  _S186 : sampler,  _S187 : texture_2d<f32>,  _S188 : sampler,  _S189 : NvFlowSparseLevelParams_0,  _S190 : NvFlowSparseLevelParams_0,  _S191 : NvFlowRayMarchLayerShaderParams_0,  _S192 : vec3<f32>,  _S193 : f32,  _S194 : vec3<f32>,  _S195 : f32,  _S196 : vec3<f32>,  _S197 : ptr<function, vec4<f32>>,  _S198 : ptr<function, f32>,  _S199 : ptr<function, vec3<f32>>)
{
    var localSum_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 1.0f);
    var localNominalT_0 : f32 = 0.0f;
    NvFlowRayMarchBlocks_0(_S185, _S186, _S187, _S188, _S190, _S191, _S192, _S193, _S194, _S195, _S196, &(localSum_0), &(localNominalT_0));
    if((localSum_0.w) < 1.0f)
    {
        (*_S199) = (*_S199) + vec3<f32>(((*_S197).w * (1.0f - localSum_0.w))) * (vec3<f32>(_S191.deltaTime_0) * NvFlowGlobalReadLinear4f_0(_S183, _S184, _S189, (_S194 * vec3<f32>((localNominalT_0 / (1.0f - localSum_0.w))) + _S192) * _S191.velocityCellSizeInv_0, _S191.layerAndLevel_0).xyz);
    }
    (*_S198) = (*_S198) + (*_S197).w * localNominalT_0;
    var _S200 : vec3<f32> = (*_S197).xyz + vec3<f32>((*_S197).w) * localSum_0.xyz;
    (*_S197).x = _S200.x;
    (*_S197).y = _S200.y;
    (*_S197).z = _S200.z;
    (*_S197)[i32(3)] = (*_S197)[i32(3)] * localSum_0.w;
    return;
}

fn NvFlowRayMarchBlocksLayered_0( _S201 : texture_3d<f32>,  _S202 : sampler,  _S203 : texture_3d<f32>,  _S204 : sampler,  _S205 : texture_2d<f32>,  _S206 : sampler,  _S207 : NvFlowSparseLevelParams_0,  _S208 : NvFlowSparseLevelParams_0,  _S209 : u32,  _S210 : vec3<f32>,  _S211 : f32,  _S212 : vec3<f32>,  _S213 : f32,  _S214 : vec3<f32>,  _S215 : ptr<function, vec4<f32>>,  _S216 : ptr<function, f32>,  _S217 : ptr<function, vec3<f32>>)
{
    const _S218 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 1.0f);
    const _S219 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var layerParamIdx_0 : u32 = u32(0);
    for(;;)
    {
        if(layerParamIdx_0 < _S209)
        {
        }
        else
        {
            break;
        }
        var sum_local_0 : vec4<f32> = _S218;
        var nominalT_local_0 : f32 = 0.0f;
        var nominalMotion_local_0 : vec3<f32> = _S219;
        NvFlowRayMarchBlocksMotion_0(_S201, _S202, _S203, _S204, _S205, _S206, _S207, _S208, unpackStorage_3(layerParamsIn_0[layerParamIdx_0]), _S210, _S211, _S212, _S213, _S214, &(sum_local_0), &(nominalT_local_0), &(nominalMotion_local_0));
        if(((*_S215).w) == 1.0f)
        {
            (*_S215) = sum_local_0;
            (*_S216) = nominalT_local_0;
            (*_S217) = nominalMotion_local_0;
        }
        else
        {
            if((sum_local_0.w) < 1.0f)
            {
                var w_0 : f32 = max(0.0f, min(1.0f, ((*_S216) / (1.0f - (*_S215).w) - nominalT_local_0 / (1.0f - sum_local_0.w)) * (0.125f * layerParamsIn_0[layerParamIdx_0].cellSizeInv_0.x) + 0.5f));
                var _S220 : f32 = 1.0f - w_0;
                var w_accum_0 : f32 = _S220 + w_0 * sum_local_0.w;
                var w_local_0 : f32 = w_0 + _S220 * (*_S215).w;
                (*_S216) = w_accum_0 * (*_S216) + w_local_0 * nominalT_local_0;
                var _S221 : vec3<f32> = vec3<f32>(w_accum_0);
                var _S222 : vec3<f32> = vec3<f32>(w_local_0);
                var _S223 : vec3<f32> = _S221 * (*_S215).xyz + _S222 * sum_local_0.xyz;
                (*_S215).x = _S223.x;
                (*_S215).y = _S223.y;
                (*_S215).z = _S223.z;
                (*_S217) = _S221 * (*_S217) + _S222 * nominalMotion_local_0;
                (*_S215)[i32(3)] = (*_S215)[i32(3)] * sum_local_0.w;
            }
        }
        layerParamIdx_0 = layerParamIdx_0 + u32(1);
    }
    return;
}

@compute
@workgroup_size(8, 4, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var _S224 : vec2<i32> = vec2<i32>(dispatchThreadID_0.xy);
    var _S225 : bool;
    if(f32(_S224.x) >= (globalParamsIn_0.width_0))
    {
        _S225 = true;
    }
    else
    {
        _S225 = f32(_S224.y) >= (globalParamsIn_0.height_0);
    }
    if(_S225)
    {
        return;
    }
    var inUV_1 : vec2<f32> = (vec2<f32>(_S224) + vec2<f32>(0.5f)) * vec2<f32>(globalParamsIn_0.widthInv_0, globalParamsIn_0.heightInv_0);
    var _S226 : f32 = inUV_1.x;
    var _S227 : f32 = 1.0f - _S226;
    var _S228 : f32 = inUV_1.y;
    var _S229 : f32 = 1.0f - _S228;
    var _S230 : vec3<f32> = vec3<f32>((_S227 * _S229));
    var _S231 : vec3<f32> = vec3<f32>((_S226 * _S229));
    var _S232 : vec3<f32> = vec3<f32>((_S227 * _S228));
    var _S233 : vec3<f32> = vec3<f32>((_S226 * _S228));
    var rayDir_6 : vec3<f32> = normalize(_S230 * globalParamsIn_0.rayDir00_0.xyz + _S231 * globalParamsIn_0.rayDir10_0.xyz + _S232 * globalParamsIn_0.rayDir01_0.xyz + _S233 * globalParamsIn_0.rayDir11_0.xyz);
    var rayOrigin_2 : vec3<f32> = _S230 * globalParamsIn_0.rayOrigin00_0.xyz + _S231 * globalParamsIn_0.rayOrigin10_0.xyz + _S232 * globalParamsIn_0.rayOrigin01_0.xyz + _S233 * globalParamsIn_0.rayOrigin11_0.xyz;
    var rayDirInv_2 : vec3<f32> = vec3<f32>(1.0f, 1.0f, 1.0f) / rayDir_6;
    var depthPosition_1 : vec4<f32>;
    var depthNormal_1 : vec3<f32>;
    computeDepthPositionAndNormal_0(&(depthPosition_1), &(depthNormal_1), rayDir_6, _S224);
    var _S234 : f32 = globalParamsIn_0.maxWorldDistance_0;
    var sceneT_0 : f32;
    if((depthPosition_1.w) != 0.0f)
    {
        var plane_denom_0 : f32 = dot(depthNormal_1, rayDir_6);
        if((abs(plane_denom_0)) > 0.00999999977648258f)
        {
            sceneT_0 = dot(depthNormal_1, depthPosition_1.xyz - rayOrigin_2) / plane_denom_0;
        }
        else
        {
            sceneT_0 = dot(rayDir_6, depthPosition_1.xyz - rayOrigin_2);
        }
    }
    else
    {
        sceneT_0 = _S234;
    }
    var maxWorldDistance_1 : f32 = min(globalParamsIn_0.maxWorldDistance_0, sceneT_0);
    var sum_1 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 1.0f);
    var nominalT_1 : f32 = 0.0f;
    var nominalMotion_0 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    NvFlowRayMarchBlocksLayered_0(velocityIn_0, velocitySampler_0, densityIn_0, densitySampler_0, colormapIn_0, colormapSampler_0, unpackStorage_1(globalParamsIn_0.levelParamsVelocity_0), unpackStorage_1(globalParamsIn_0.levelParamsDensity_0), globalParamsIn_0.numLayers_1, rayOrigin_2, 0.0f, rayDir_6, maxWorldDistance_1, rayDirInv_2, &(sum_1), &(nominalT_1), &(nominalMotion_0));
    var _S235 : vec2<u32> = vec2<u32>(_S224);
    var _S236 : vec3<i32> = vec3<i32>(vec3<u32>(_S235, u32(0)));
    var _S237 : vec4<f32> = (textureLoad((colorIn_0), ((_S236)).xy, ((_S236)).z));
    var color_2 : vec4<f32> = _S237;
    var _S238 : vec3<f32> = sum_1.xyz * vec3<f32>(globalParamsIn_0.compositeColorScale_0);
    sum_1.x = _S238.x;
    sum_1.y = _S238.y;
    sum_1.z = _S238.z;
    var _S239 : vec3<f32> = sum_1.xyz + vec3<f32>(sum_1.w) * _S237.xyz;
    color_2.x = _S239.x;
    color_2.y = _S239.y;
    color_2.z = _S239.z;
    textureStore((colorOut_0), (_S235), (color_2));
    return;
}

