// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct RayMarchUpdateColormapCS_GlobalParams_std140_0
{
    @align(16) totalPts_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) dim_0 : u32,
    @align(4) dimInv_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : RayMarchUpdateColormapCS_GlobalParams_std140_0;
@binding(3) @group(0) var gColormapOut_0 : texture_storage_2d<rgba32float, write>;

struct RayMarchUpdateColormapCS_LayerParams_std430_0
{
    @align(4) numPts_0 : u32,
    @align(4) beginPtIdx_0 : u32,
    @align(4) endPtIdx_0 : u32,
    @align(4) layerParamIdx_0 : u32,
    @align(4) colorScale_0 : f32,
    @align(4) pad1_0 : f32,
    @align(4) pad2_0 : f32,
    @align(4) pad3_0 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<RayMarchUpdateColormapCS_LayerParams_std430_0>;

struct RayMarchUpdateColormapCS_PointParams_std430_0
{
    @align(16) x_0 : f32,
    @align(4) pad1_1 : f32,
    @align(8) pad2_1 : f32,
    @align(4) pad3_1 : f32,
    @align(16) color_0 : vec4<f32>,
};

@binding(2) @group(0) var<storage, read> pointParamsIn_0 : array<RayMarchUpdateColormapCS_PointParams_std430_0>;

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    var threadIdx_0 : i32 = i32(dispatchThreadID_0.x);
    var layerParamIdx_1 : u32 = dispatchThreadID_0.y;
    if(threadIdx_0 >= i32(globalParamsIn_0.dim_0))
    {
        return;
    }
    if((globalParamsIn_0.numLayers_0) == u32(0))
    {
        textureStore((gColormapOut_0), (vec2<u32>(vec2<i32>(threadIdx_0, i32(0)))), (vec4<f32>(0.0f, 1.0f, 0.0f, 1.0f)));
        return;
    }
    var u_0 : f32 = (f32(threadIdx_0) + 0.5f) * globalParamsIn_0.dimInv_0;
    var _S1 : u32 = layerParamsIn_0[layerParamIdx_1].beginPtIdx_0;
    var _S2 : u32 = layerParamsIn_0[layerParamIdx_1].endPtIdx_0;
    var xlowVal_0 : f32 = 0.0f;
    var xlowIdx_0 : u32 = u32(4294967295);
    var xhighVal_0 : f32 = 0.0f;
    var xhighIdx_0 : u32 = u32(4294967295);
    var ptIdx_0 : u32 = _S1;
    for(;;)
    {
        if(ptIdx_0 < _S2)
        {
        }
        else
        {
            break;
        }
        var _S3 : f32 = pointParamsIn_0[ptIdx_0].x_0;
        var _S4 : bool;
        if((pointParamsIn_0[ptIdx_0].x_0) <= u_0)
        {
            if(_S3 >= xlowVal_0)
            {
                _S4 = true;
            }
            else
            {
                _S4 = xlowIdx_0 == u32(4294967295);
            }
        }
        else
        {
            _S4 = false;
        }
        if(_S4)
        {
            xlowVal_0 = _S3;
            xlowIdx_0 = ptIdx_0;
        }
        var _S5 : bool;
        if(_S3 >= u_0)
        {
            if(_S3 <= xhighVal_0)
            {
                _S5 = true;
            }
            else
            {
                _S5 = xhighIdx_0 == u32(4294967295);
            }
        }
        else
        {
            _S5 = false;
        }
        if(_S5)
        {
            xhighVal_0 = _S3;
            xhighIdx_0 = ptIdx_0;
        }
        ptIdx_0 = ptIdx_0 + u32(1);
    }
    var a_0 : vec4<f32>;
    if(xlowIdx_0 != u32(4294967295))
    {
        a_0 = pointParamsIn_0[xlowIdx_0].color_0;
    }
    else
    {
        a_0 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    var b_0 : vec4<f32>;
    if(xhighIdx_0 != u32(4294967295))
    {
        b_0 = pointParamsIn_0[xhighIdx_0].color_0;
    }
    else
    {
        b_0 = vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f);
    }
    var t_0 : f32 = (u_0 - xlowVal_0) / (xhighVal_0 - xlowVal_0);
    var _S6 : vec4<f32> = vec4<f32>((1.0f - t_0)) * a_0 + vec4<f32>(t_0) * b_0;
    var c_0 : vec4<f32> = _S6;
    var _S7 : vec3<f32> = _S6.xyz * vec3<f32>(layerParamsIn_0[layerParamIdx_1].colorScale_0);
    c_0.x = _S7.x;
    c_0.y = _S7.y;
    c_0.z = _S7.z;
    textureStore((gColormapOut_0), (vec2<u32>(vec2<i32>(threadIdx_0, i32(layerParamIdx_1)))), (c_0));
    return;
}

