// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct NvFlowSelfShadowShaderParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) coarseDensityTable_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) densityTable_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : NvFlowSelfShadowShaderParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

@binding(3) @group(0) var gInput_0 : texture_3d<f32>;

struct NvFlowRayMarchCloudLayerShaderParams_std430_0
{
    @align(16) densityMultiplier_0 : f32,
    @align(4) enableCloudMode_0 : u32,
    @align(8) pad1_2 : f32,
    @align(4) pad2_1 : f32,
    @align(16) ambientColor_0 : vec3<f32>,
    @align(4) ambientMultiplier_0 : f32,
    @align(16) volumeBaseColor_0 : vec3<f32>,
    @align(4) volumeColorMultiplier_0 : f32,
    @align(16) sunDirection_0 : vec3<f32>,
    @align(4) shadowStepMultiplier_0 : f32,
    @align(16) attenuationMultiplier_0 : vec3<f32>,
    @align(4) numShadowSteps_0 : i32,
};

struct NvFlowRayMarchLayerShaderParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) minBlockSizeWorld_0 : f32,
    @align(16) blockSizeWorldInv_0 : vec3<f32>,
    @align(4) maxBlockSizeWorld_0 : f32,
    @align(16) cellSize_0 : vec3<f32>,
    @align(4) stepSize_0 : f32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) stepSizeInv_0 : f32,
    @align(16) locationMin_0 : vec4<i32>,
    @align(16) locationMax_0 : vec4<i32>,
    @align(16) worldMin_0 : vec3<f32>,
    @align(4) enableBlockWireframe_0 : u32,
    @align(16) worldMax_0 : vec3<f32>,
    @align(4) enableRawMode_0 : u32,
    @align(16) velocityCellSizeInv_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) layerAndLevel_0 : i32,
    @align(4) layerAndLevelColormapV_0 : f32,
    @align(8) alphaScale_0 : f32,
    @align(4) colorScale_0 : f32,
    @align(16) shadowFactor_0 : f32,
    @align(4) rawModeIsosurface_0 : u32,
    @align(8) rawModeNormalize_0 : u32,
    @align(4) pad3_1 : f32,
    @align(16) colormapXOffset_0 : f32,
    @align(4) colormapXScale_0 : f32,
    @align(8) pad4_0 : f32,
    @align(4) pad5_0 : f32,
    @align(16) cloud_0 : NvFlowRayMarchCloudLayerShaderParams_std430_0,
};

struct NvFlowSelfShadowLayerShaderParams_std430_0
{
    @align(16) base_0 : NvFlowRayMarchLayerShaderParams_std430_0,
    @align(16) minIntensity_0 : f32,
    @align(4) numSteps_0 : u32,
    @align(8) isPointLight_0 : u32,
    @align(4) stepOffset_0 : f32,
    @align(16) lightDirection_0 : vec3<f32>,
    @align(4) enabled_0 : u32,
    @align(16) lightPosition_0 : vec3<f32>,
    @align(4) pad3_2 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<NvFlowSelfShadowLayerShaderParams_std430_0>;

@binding(7) @group(0) var alphaIn_0 : texture_3d<f32>;

@binding(4) @group(0) var gSampler_0 : sampler;

@binding(8) @group(0) var densityOut_0 : texture_storage_3d<rgba32float, write>;

@binding(5) @group(0) var gColormap_0 : texture_2d<f32>;

@binding(6) @group(0) var gColormapSampler_0 : sampler;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowSingleToIdx_0( blockIdx_0 : u32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + u32(13) + u32(5);
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowFloor_i_0( v_1 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_1));
}

fn NvFlowNeighborToIdx_0( blockIdx_1 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_1 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S10 < (_S9.numLocations_0))
    {
        layerParamIdx_0 = gTable_0[_S10 + _S9.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowSingleVirtualToReal_0( _S11 : NvFlowSparseLevelParams_0,  _S12 : u32,  _S13 : vec3<i32>) -> vec4<i32>
{
    return NvFlowTableValueToIndexRead_0(_S13, gTable_0[NvFlowSingleToIdx_0(_S12) + _S11.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalVirtualToReal_0( _S14 : NvFlowSparseLevelParams_0,  _S15 : u32,  _S16 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S16 >> (vec3<u32>(vec3<i32>(_S14.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S16, gTable_0[NvFlowNeighborToIdx_0(_S15, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S14.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalReadLinear1f_0( _S17 : texture_3d<f32>,  _S18 : sampler,  _S19 : NvFlowSparseLevelParams_0,  _S20 : u32,  _S21 : vec3<f32>) -> f32
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S21);
    var _S22 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S19, _S20, threadIdx_3);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S22.xyz) + _S21 - vec3<f32>(threadIdx_3);
    var _S23 : f32;
    if(bool(_S22.w))
    {
        _S23 = (textureSampleLevel((_S17), (_S18), (readIdxf_0 * _S19.dimInv_0), (0.0f)).x);
    }
    else
    {
        _S23 = 0.0f;
    }
    return _S23;
}

fn NvFlowLocalWriteNeighbor4f_0( _S24 : NvFlowSparseLevelParams_0,  _S25 : i32,  _S26 : i32,  _S27 : i32,  _S28 : u32,  _S29 : vec3<i32>,  _S30 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S29, gTable_0[NvFlowNeighborToIdx_0(_S28, _S25, _S26, _S27) + _S24.blockLevelOffsetLocal_0], _S25, _S26, _S27);
    var _S31 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S32 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S32 = _S30;
    }
    else
    {
        _S32 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((densityOut_0), (_S31), (_S32));
    return;
}

fn NvFlowLocalWrite4f_0( _S33 : NvFlowSparseLevelParams_0,  _S34 : u32,  _S35 : vec3<i32>,  _S36 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S33, _S35);
    NvFlowLocalWriteNeighbor4f_0(_S33, i32(0), i32(0), i32(0), _S34, _S35, _S36);
    var _S37 : i32 = neighbor_2.x;
    var _S38 : bool = _S37 != i32(0);
    if(_S38)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, _S37, i32(0), i32(0), _S34, _S35, _S36);
    }
    var _S39 : i32 = neighbor_2.y;
    var _S40 : bool = _S39 != i32(0);
    if(_S40)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, i32(0), _S39, i32(0), _S34, _S35, _S36);
    }
    var _S41 : i32 = neighbor_2.z;
    var _S42 : bool = _S41 != i32(0);
    if(_S42)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, i32(0), i32(0), _S41, _S34, _S35, _S36);
    }
    var _S43 : bool;
    if(_S38)
    {
        _S43 = _S40;
    }
    else
    {
        _S43 = false;
    }
    if(_S43)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, _S37, _S39, i32(0), _S34, _S35, _S36);
    }
    if(_S40)
    {
        _S43 = _S42;
    }
    else
    {
        _S43 = false;
    }
    if(_S43)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, i32(0), _S39, _S41, _S34, _S35, _S36);
    }
    if(_S38)
    {
        _S43 = _S42;
    }
    else
    {
        _S43 = false;
    }
    if(_S43)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, _S37, i32(0), _S41, _S34, _S35, _S36);
    }
    if(_S38)
    {
        _S43 = _S40;
    }
    else
    {
        _S43 = false;
    }
    if(_S43)
    {
        _S43 = _S42;
    }
    else
    {
        _S43 = false;
    }
    if(_S43)
    {
        NvFlowLocalWriteNeighbor4f_0(_S33, _S37, _S39, _S41, _S34, _S35, _S36);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_4 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.densityTable_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S44 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.densityTable_0), blockIdx_2);
    var _S45 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(NvFlowSingleVirtualToReal_0(unpackStorage_0(globalParamsIn_0.densityTable_0), blockIdx_2, threadIdx_4).xyz), u32(0)));
    var density4_0 : vec4<f32> = (textureLoad((gInput_0), ((_S45)).xyz, ((_S45)).w));
    if((layerParamsIn_0[_S44].enabled_0) != u32(0))
    {
        var sum_a_0 : f32 = (1.0f - layerParamsIn_0[_S44].minIntensity_0) * (1.0f - NvFlowLocalReadLinear1f_0(alphaIn_0, gSampler_0, unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), blockIdx_2, vec3<f32>(0.5f) * (vec3<f32>(threadIdx_4) + vec3<f32>(0.5f, 0.5f, 0.5f)))) + layerParamsIn_0[_S44].minIntensity_0;
        if((layerParamsIn_0[_S44].base_0.enableRawMode_0) != u32(0))
        {
            var _S46 : vec3<f32> = density4_0.xyz * vec3<f32>(sum_a_0);
            density4_0.x = _S46.x;
            density4_0.y = _S46.y;
            density4_0.z = _S46.z;
        }
        else
        {
            density4_0[i32(2)] = sum_a_0;
        }
    }
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.densityTable_0), blockIdx_2, threadIdx_4, density4_0);
    return;
}

