// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct NvFlowSelfShadowShaderParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) pad1_1 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) coarseDensityTable_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) densityTable_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : NvFlowSelfShadowShaderParams_std140_0;
@binding(2) @group(0) var<storage, read> gTable_0 : array<u32>;

struct NvFlowRayMarchCloudLayerShaderParams_std430_0
{
    @align(16) densityMultiplier_0 : f32,
    @align(4) enableCloudMode_0 : u32,
    @align(8) pad1_2 : f32,
    @align(4) pad2_1 : f32,
    @align(16) ambientColor_0 : vec3<f32>,
    @align(4) ambientMultiplier_0 : f32,
    @align(16) volumeBaseColor_0 : vec3<f32>,
    @align(4) volumeColorMultiplier_0 : f32,
    @align(16) sunDirection_0 : vec3<f32>,
    @align(4) shadowStepMultiplier_0 : f32,
    @align(16) attenuationMultiplier_0 : vec3<f32>,
    @align(4) numShadowSteps_0 : i32,
};

struct NvFlowRayMarchLayerShaderParams_std430_0
{
    @align(16) blockSizeWorld_0 : vec3<f32>,
    @align(4) minBlockSizeWorld_0 : f32,
    @align(16) blockSizeWorldInv_0 : vec3<f32>,
    @align(4) maxBlockSizeWorld_0 : f32,
    @align(16) cellSize_0 : vec3<f32>,
    @align(4) stepSize_0 : f32,
    @align(16) cellSizeInv_0 : vec3<f32>,
    @align(4) stepSizeInv_0 : f32,
    @align(16) locationMin_0 : vec4<i32>,
    @align(16) locationMax_0 : vec4<i32>,
    @align(16) worldMin_0 : vec3<f32>,
    @align(4) enableBlockWireframe_0 : u32,
    @align(16) worldMax_0 : vec3<f32>,
    @align(4) enableRawMode_0 : u32,
    @align(16) velocityCellSizeInv_0 : vec3<f32>,
    @align(4) deltaTime_0 : f32,
    @align(16) layerAndLevel_0 : i32,
    @align(4) layerAndLevelColormapV_0 : f32,
    @align(8) alphaScale_0 : f32,
    @align(4) colorScale_0 : f32,
    @align(16) shadowFactor_0 : f32,
    @align(4) rawModeIsosurface_0 : u32,
    @align(8) rawModeNormalize_0 : u32,
    @align(4) pad3_1 : f32,
    @align(16) colormapXOffset_0 : f32,
    @align(4) colormapXScale_0 : f32,
    @align(8) pad4_0 : f32,
    @align(4) pad5_0 : f32,
    @align(16) cloud_0 : NvFlowRayMarchCloudLayerShaderParams_std430_0,
};

struct NvFlowSelfShadowLayerShaderParams_std430_0
{
    @align(16) base_0 : NvFlowRayMarchLayerShaderParams_std430_0,
    @align(16) minIntensity_0 : f32,
    @align(4) numSteps_0 : u32,
    @align(8) isPointLight_0 : u32,
    @align(4) stepOffset_0 : f32,
    @align(16) lightDirection_0 : vec3<f32>,
    @align(4) enabled_0 : u32,
    @align(16) lightPosition_0 : vec3<f32>,
    @align(4) pad3_2 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<NvFlowSelfShadowLayerShaderParams_std430_0>;

@binding(3) @group(0) var gInput_0 : texture_3d<f32>;

@binding(4) @group(0) var gSampler_0 : sampler;

@binding(5) @group(0) var gColormap_0 : texture_2d<f32>;

@binding(6) @group(0) var gColormapSampler_0 : sampler;

@binding(7) @group(0) var alphaOut_0 : texture_storage_3d<r32float, write>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

struct NvFlowRayMarchCloudLayerShaderParams_0
{
     densityMultiplier_0 : f32,
     enableCloudMode_0 : u32,
     pad1_2 : f32,
     pad2_1 : f32,
     ambientColor_0 : vec3<f32>,
     ambientMultiplier_0 : f32,
     volumeBaseColor_0 : vec3<f32>,
     volumeColorMultiplier_0 : f32,
     sunDirection_0 : vec3<f32>,
     shadowStepMultiplier_0 : f32,
     attenuationMultiplier_0 : vec3<f32>,
     numShadowSteps_0 : i32,
};

fn unpackStorage_1( _S5 : NvFlowRayMarchCloudLayerShaderParams_std430_0) -> NvFlowRayMarchCloudLayerShaderParams_0
{
    var _S6 : NvFlowRayMarchCloudLayerShaderParams_0 = NvFlowRayMarchCloudLayerShaderParams_0( _S5.densityMultiplier_0, _S5.enableCloudMode_0, _S5.pad1_2, _S5.pad2_1, _S5.ambientColor_0, _S5.ambientMultiplier_0, _S5.volumeBaseColor_0, _S5.volumeColorMultiplier_0, _S5.sunDirection_0, _S5.shadowStepMultiplier_0, _S5.attenuationMultiplier_0, _S5.numShadowSteps_0 );
    return _S6;
}

struct NvFlowRayMarchLayerShaderParams_0
{
     blockSizeWorld_0 : vec3<f32>,
     minBlockSizeWorld_0 : f32,
     blockSizeWorldInv_0 : vec3<f32>,
     maxBlockSizeWorld_0 : f32,
     cellSize_0 : vec3<f32>,
     stepSize_0 : f32,
     cellSizeInv_0 : vec3<f32>,
     stepSizeInv_0 : f32,
     locationMin_0 : vec4<i32>,
     locationMax_0 : vec4<i32>,
     worldMin_0 : vec3<f32>,
     enableBlockWireframe_0 : u32,
     worldMax_0 : vec3<f32>,
     enableRawMode_0 : u32,
     velocityCellSizeInv_0 : vec3<f32>,
     deltaTime_0 : f32,
     layerAndLevel_0 : i32,
     layerAndLevelColormapV_0 : f32,
     alphaScale_0 : f32,
     colorScale_0 : f32,
     shadowFactor_0 : f32,
     rawModeIsosurface_0 : u32,
     rawModeNormalize_0 : u32,
     pad3_1 : f32,
     colormapXOffset_0 : f32,
     colormapXScale_0 : f32,
     pad4_0 : f32,
     pad5_0 : f32,
     cloud_0 : NvFlowRayMarchCloudLayerShaderParams_0,
};

fn unpackStorage_2( _S7 : NvFlowRayMarchLayerShaderParams_std430_0) -> NvFlowRayMarchLayerShaderParams_0
{
    var _S8 : NvFlowRayMarchLayerShaderParams_0 = NvFlowRayMarchLayerShaderParams_0( _S7.blockSizeWorld_0, _S7.minBlockSizeWorld_0, _S7.blockSizeWorldInv_0, _S7.maxBlockSizeWorld_0, _S7.cellSize_0, _S7.stepSize_0, _S7.cellSizeInv_0, _S7.stepSizeInv_0, _S7.locationMin_0, _S7.locationMax_0, _S7.worldMin_0, _S7.enableBlockWireframe_0, _S7.worldMax_0, _S7.enableRawMode_0, _S7.velocityCellSizeInv_0, _S7.deltaTime_0, _S7.layerAndLevel_0, _S7.layerAndLevelColormapV_0, _S7.alphaScale_0, _S7.colorScale_0, _S7.shadowFactor_0, _S7.rawModeIsosurface_0, _S7.rawModeNormalize_0, _S7.pad3_1, _S7.colormapXOffset_0, _S7.colormapXScale_0, _S7.pad4_0, _S7.pad5_0, unpackStorage_1(_S7.cloud_0) );
    return _S8;
}

fn NvFlowIntersectBox_0( rayDir_0 : vec3<f32>,  rayDirInv_0 : vec3<f32>,  boxMin_0 : vec3<f32>,  boxMax_0 : vec3<f32>,  tnear_0 : ptr<function, f32>,  tfar_0 : ptr<function, f32>) -> bool
{
    var tbot_0 : vec3<f32> = boxMin_0 * rayDirInv_0;
    var ttop_0 : vec3<f32> = boxMax_0 * rayDirInv_0;
    var tmin_0 : vec3<f32> = min(ttop_0, tbot_0);
    var tmax_0 : vec3<f32> = max(ttop_0, tbot_0);
    var _S9 : f32 = tmin_0.x;
    (*tnear_0) = max(max(_S9, tmin_0.y), max(_S9, tmin_0.z));
    var _S10 : f32 = tmax_0.x;
    var _S11 : f32 = min(min(_S10, tmax_0.y), min(_S10, tmax_0.z));
    (*tfar_0) = _S11;
    return _S11 > (*tnear_0);
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowRayMarchComputeFinalLocation_0( rayDir_1 : vec3<f32>,  location_0 : vec4<i32>,  locationMin_1 : vec4<i32>,  locationMax_1 : vec4<i32>) -> vec3<i32>
{
    var _S12 : i32;
    if((rayDir_1.x) > 0.0f)
    {
        _S12 = max(location_0.x, locationMax_1.x);
    }
    else
    {
        _S12 = min(location_0.x, locationMin_1.x - i32(1));
    }
    var _S13 : i32;
    if((rayDir_1.y) > 0.0f)
    {
        _S13 = max(location_0.y, locationMax_1.y);
    }
    else
    {
        _S13 = min(location_0.y, locationMin_1.y - i32(1));
    }
    var _S14 : i32;
    if((rayDir_1.z) > 0.0f)
    {
        _S14 = max(location_0.z, locationMax_1.z);
    }
    else
    {
        _S14 = min(location_0.z, locationMin_1.z - i32(1));
    }
    return vec3<i32>(_S12, _S13, _S14);
}

fn NvFlowRayMarchHash_0( inputValue_0 : u32) -> u32
{
    var state_0 : u32 = inputValue_0 * u32(747796405) + u32(2891336453);
    var word_0 : u32 = ((((state_0 >> ((((state_0 >> (u32(28)))) + u32(4))))) ^ (state_0))) * u32(277803737);
    return (((word_0 >> (u32(22)))) ^ (word_0));
}

fn NvFlowRayMarchRandNorm_0( inputValue_1 : u32) -> f32
{
    return f32(((NvFlowRayMarchHash_0(inputValue_1)) & (u32(65535)))) * 0.00001525902189314f;
}

fn NvFlowRayMarchNoiseFromDir_0( rayDir_2 : vec3<f32>) -> f32
{
    var _S15 : f32 = abs(rayDir_2.x);
    var _S16 : f32 = abs(rayDir_2.y);
    var _S17 : bool;
    if(_S15 > _S16)
    {
        _S17 = _S15 > (abs(rayDir_2.z));
    }
    else
    {
        _S17 = false;
    }
    var uv_0 : vec2<f32>;
    if(_S17)
    {
        uv_0 = rayDir_2.yz;
    }
    else
    {
        if(_S16 > _S15)
        {
            _S17 = _S16 > (abs(rayDir_2.z));
        }
        else
        {
            _S17 = false;
        }
        if(_S17)
        {
            uv_0 = rayDir_2.xz;
        }
        else
        {
            uv_0 = rayDir_2.xy;
        }
    }
    var maxAxis_0 : f32 = max(_S15, max(_S16, abs(rayDir_2.z)));
    if(maxAxis_0 > 0.0f)
    {
        uv_0 = uv_0 * vec2<f32>((1.0f / maxAxis_0));
    }
    var _S18 : vec2<f32> = vec2<f32>(0.5f);
    var uv_1 : vec2<f32> = _S18 * uv_0 + _S18;
    return NvFlowRayMarchRandNorm_0((u32(65535.0f * uv_1.x) ^ (((u32(65535.0f * uv_1.y) << (u32(16)))))));
}

fn NvFlowRayMarchWireframe_0( paramsTable_0 : NvFlowSparseLevelParams_0,  params_0 : NvFlowRayMarchLayerShaderParams_0,  rayOrigin_0 : vec3<f32>,  rayMinT_0 : f32,  rayDir_3 : vec3<f32>,  hitT_0 : f32,  location_1 : vec4<i32>,  brightness_0 : f32,  sum_0 : ptr<function, vec4<f32>>,  nominalT_0 : ptr<function, f32>)
{
    if(hitT_0 > rayMinT_0)
    {
        var blockFrac_0 : vec3<f32> = params_0.blockSizeWorld_0 * ((rayOrigin_0 + vec3<f32>(hitT_0) * rayDir_3) * params_0.blockSizeWorldInv_0 - vec3<f32>(location_1.xyz));
        var _S19 : f32 = params_0.cellSize_0.x;
        var _S20 : f32 = blockFrac_0.x;
        var faceX_0 : f32 = max(2.0f * _S19 - _S20, _S20 - f32(paramsTable_0.blockDimLessOne_0.x - u32(1)) * _S19);
        var _S21 : f32 = params_0.cellSize_0.y;
        var _S22 : f32 = blockFrac_0.y;
        var faceY_0 : f32 = max(2.0f * _S21 - _S22, _S22 - f32(paramsTable_0.blockDimLessOne_0.y - u32(1)) * _S21);
        var _S23 : f32 = params_0.cellSize_0.z;
        var _S24 : f32 = blockFrac_0.z;
        var faceZ_0 : f32 = max(2.0f * _S23 - _S24, _S24 - f32(paramsTable_0.blockDimLessOne_0.z - u32(1)) * _S23);
        var _S25 : bool = faceX_0 > 0.0f;
        var _S26 : bool;
        if(_S25)
        {
            _S26 = faceY_0 > 0.0f;
        }
        else
        {
            _S26 = false;
        }
        if(_S26)
        {
            _S26 = true;
        }
        else
        {
            if(faceY_0 > 0.0f)
            {
                _S26 = faceZ_0 > 0.0f;
            }
            else
            {
                _S26 = false;
            }
        }
        if(_S26)
        {
            _S26 = true;
        }
        else
        {
            if(faceZ_0 > 0.0f)
            {
                _S26 = _S25;
            }
            else
            {
                _S26 = false;
            }
        }
        if(_S26)
        {
            var faceX_1 : f32 = faceX_0 - _S19;
            var faceY_1 : f32 = faceY_0 - _S21;
            var faceZ_1 : f32 = faceZ_0 - _S23;
            var color_0 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
            if(faceX_1 > faceY_1)
            {
                _S26 = faceX_1 > faceZ_1;
            }
            else
            {
                _S26 = false;
            }
            if(_S26)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceY_1, faceZ_1)) * params_0.cellSizeInv_0.x;
            }
            if(faceY_1 > faceX_1)
            {
                _S26 = faceY_1 > faceZ_1;
            }
            else
            {
                _S26 = false;
            }
            if(_S26)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceX_1, faceZ_1)) * params_0.cellSizeInv_0.y;
            }
            if(faceZ_1 > faceX_1)
            {
                _S26 = faceZ_1 > faceY_1;
            }
            else
            {
                _S26 = false;
            }
            if(_S26)
            {
                color_0[i32(1)] = brightness_0;
                color_0[i32(3)] = abs(max(faceX_1, faceY_1)) * params_0.cellSizeInv_0.z;
            }
            color_0[i32(3)] = color_0[i32(3)] * color_0.w;
            color_0[i32(3)] = 1.0f - color_0.w;
            (*nominalT_0) = (*sum_0).w * (color_0.w * hitT_0) + (*nominalT_0);
            var _S27 : vec3<f32> = vec3<f32>((*sum_0).w) * (vec3<f32>(color_0.w) * color_0.xyz) + (*sum_0).xyz;
            (*sum_0).x = _S27.x;
            (*sum_0).y = _S27.y;
            (*sum_0).z = _S27.z;
            (*sum_0)[i32(3)] = (1.0f - color_0.w) * (*sum_0).w;
        }
    }
    return;
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S28 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S28, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S28 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowRayMarchAdvanceRay_0( blockSizeWorld_1 : vec3<f32>,  rayDir_4 : vec3<f32>,  rayDirInv_1 : vec3<f32>,  rayOrigin_1 : vec3<f32>,  location_2 : ptr<function, vec4<i32>>,  hitT_1 : ptr<function, f32>)
{
    var _S29 : i32 = (*location_2).x;
    var _S30 : f32 = rayDir_4.x;
    var _S31 : bool = _S30 > 0.0f;
    var _S32 : i32;
    if(_S31)
    {
        _S32 = i32(1);
    }
    else
    {
        _S32 = i32(0);
    }
    var hitTx_0 : f32 = (f32(_S29 + _S32) * blockSizeWorld_1.x - rayOrigin_1.x) * rayDirInv_1.x;
    var _S33 : i32 = (*location_2).y;
    var _S34 : f32 = rayDir_4.y;
    var _S35 : bool = _S34 > 0.0f;
    if(_S35)
    {
        _S32 = i32(1);
    }
    else
    {
        _S32 = i32(0);
    }
    var hitTy_0 : f32 = (f32(_S33 + _S32) * blockSizeWorld_1.y - rayOrigin_1.y) * rayDirInv_1.y;
    var _S36 : i32 = (*location_2).z;
    var _S37 : f32 = rayDir_4.z;
    var _S38 : bool = _S37 > 0.0f;
    if(_S38)
    {
        _S32 = i32(1);
    }
    else
    {
        _S32 = i32(0);
    }
    var hitTz_0 : f32 = (f32(_S36 + _S32) * blockSizeWorld_1.z - rayOrigin_1.z) * rayDirInv_1.z;
    var _S39 : bool;
    if(_S30 != 0.0f)
    {
        if(hitTx_0 <= hitTy_0)
        {
            _S39 = true;
        }
        else
        {
            _S39 = _S34 == 0.0f;
        }
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        if(hitTx_0 <= hitTz_0)
        {
            _S39 = true;
        }
        else
        {
            _S39 = _S37 == 0.0f;
        }
    }
    else
    {
        _S39 = false;
    }
    if(_S39)
    {
        (*hitT_1) = hitTx_0;
        if(_S31)
        {
            _S32 = i32(1);
        }
        else
        {
            _S32 = i32(-1);
        }
        (*location_2)[i32(0)] = (*location_2)[i32(0)] + _S32;
    }
    else
    {
        if(_S34 != 0.0f)
        {
            if(hitTy_0 <= hitTx_0)
            {
                _S39 = true;
            }
            else
            {
                _S39 = _S30 == 0.0f;
            }
        }
        else
        {
            _S39 = false;
        }
        if(_S39)
        {
            if(hitTy_0 <= hitTz_0)
            {
                _S39 = true;
            }
            else
            {
                _S39 = _S37 == 0.0f;
            }
        }
        else
        {
            _S39 = false;
        }
        if(_S39)
        {
            (*hitT_1) = hitTy_0;
            if(_S35)
            {
                _S32 = i32(1);
            }
            else
            {
                _S32 = i32(-1);
            }
            (*location_2)[i32(1)] = (*location_2)[i32(1)] + _S32;
        }
        else
        {
            (*hitT_1) = hitTz_0;
            if(_S38)
            {
                _S32 = i32(1);
            }
            else
            {
                _S32 = i32(-1);
            }
            (*location_2)[i32(2)] = (*location_2)[i32(2)] + _S32;
        }
    }
    return;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S40 : i32 = threadIdx_1.x;
    if(_S40 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S40 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S41 : i32 = threadIdx_1.y;
    if(_S41 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S41 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S42 : i32 = threadIdx_1.z;
    if(_S42 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S42 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowGetLayerParamIdx_0( _S43 : NvFlowSparseLevelParams_0,  _S44 : u32) -> u32
{
    var layerParamIdx_0 : u32;
    if(_S44 < (_S43.numLocations_0))
    {
        layerParamIdx_0 = gTable_0[_S44 + _S43.layerParamIdxOffset_0];
    }
    else
    {
        layerParamIdx_0 = u32(0);
    }
    return layerParamIdx_0;
}

fn NvFlowBlockIdxToLocation_0( _S45 : NvFlowSparseLevelParams_0,  _S46 : u32,  _S47 : ptr<function, vec4<i32>>) -> bool
{
    var _S48 : bool = _S46 < (_S45.numLocations_0);
    if(_S48)
    {
        var locationIdx_0 : u32 = ((_S46 << (u32(2)))) + _S45.locationOffset_0;
        (*_S47)[i32(0)] = i32(gTable_0[locationIdx_0]);
        (*_S47)[i32(1)] = i32(gTable_0[locationIdx_0 + u32(1)]);
        (*_S47)[i32(2)] = i32(gTable_0[locationIdx_0 + u32(2)]);
        (*_S47)[i32(3)] = i32(gTable_0[locationIdx_0 + u32(3)]);
    }
    else
    {
        (*_S47)[i32(0)] = i32(1073741824);
        (*_S47)[i32(1)] = i32(1073741824);
        (*_S47)[i32(2)] = i32(1073741824);
        (*_S47)[i32(3)] = i32(1073741824);
    }
    return _S48;
}

fn NvFlowRealToVirtual_0( _S49 : NvFlowSparseLevelParams_0,  _S50 : u32,  _S51 : vec3<i32>,  _S52 : ptr<function, vec4<i32>>) -> bool
{
    var location_3 : vec4<i32>;
    var _S53 : bool = NvFlowBlockIdxToLocation_0(_S49, _S50, &(location_3));
    (*_S52) = vec4<i32>((((location_3.xyz) << (vec3<u32>(vec3<i32>(_S49.blockDimBits_0))))) + _S51, location_3.w);
    return _S53;
}

fn NvFlowLocationToBlockIdx_0( _S54 : NvFlowSparseLevelParams_0,  _S55 : vec4<i32>) -> u32
{
    var outBlockIdx_0 : u32;
    var bucketIdx_0 : vec3<u32> = (vec3<u32>(_S55.xyz) & ((_S54.tableDimLessOne_0)));
    var _S56 : u32 = ((((((((bucketIdx_0.z) << ((_S54.tableDimBits_xy_0)))) | ((((bucketIdx_0.y) << ((_S54.tableDimBits_x_0))))))) | ((bucketIdx_0.x)))) << (u32(1)));
    var _S57 : u32 = gTable_0[_S56 + u32(1)];
    var _S58 : i32 = _S55.x;
    var _S59 : i32 = _S55.y;
    var _S60 : i32 = _S55.z;
    var _S61 : i32 = _S55.w;
    var blockIdx_1 : u32 = gTable_0[_S56];
    for(;;)
    {
        if(blockIdx_1 < _S57)
        {
        }
        else
        {
            outBlockIdx_0 = u32(4294967295);
            break;
        }
        var compareLocationIdx_0 : u32 = ((blockIdx_1 << (u32(2)))) + _S54.locationOffset_0;
        var compareLocation_y_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(1)]);
        var compareLocation_z_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(2)]);
        var compareLocation_w_0 : i32 = i32(gTable_0[compareLocationIdx_0 + u32(3)]);
        var _S62 : bool;
        if(i32(gTable_0[compareLocationIdx_0]) == _S58)
        {
            _S62 = compareLocation_y_0 == _S59;
        }
        else
        {
            _S62 = false;
        }
        var _S63 : bool;
        if(_S62)
        {
            _S63 = compareLocation_z_0 == _S60;
        }
        else
        {
            _S63 = false;
        }
        var _S64 : bool;
        if(_S63)
        {
            _S64 = compareLocation_w_0 == _S61;
        }
        else
        {
            _S64 = false;
        }
        if(_S64)
        {
            outBlockIdx_0 = blockIdx_1;
            break;
        }
        blockIdx_1 = blockIdx_1 + u32(1);
    }
    return outBlockIdx_0;
}

fn NvFlowGlobalVirtualToRealOffset_0( _S65 : NvFlowSparseLevelParams_0,  _S66 : vec4<i32>,  _S67 : u32) -> vec3<i32>
{
    var tableValue_0 : u32;
    if(_S67 != u32(4294967295))
    {
        tableValue_0 = gTable_0[_S67 + _S65.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_0 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0(vec3<i32>(i32(0), i32(0), i32(0)), tableValue_0).xyz - (((_S66.xyz) << ((_S65.blockDimBits_0))));
}

fn NvFlowGlobalVirtualToReal_0( _S68 : NvFlowSparseLevelParams_0,  _S69 : vec4<i32>) -> vec4<i32>
{
    var _S70 : vec3<i32> = _S69.xyz;
    var _S71 : u32 = NvFlowLocationToBlockIdx_0(_S68, vec4<i32>((_S70 >> (vec3<u32>(vec3<i32>(_S68.blockDimBits_0)))), _S69.w));
    var tableValue_1 : u32;
    if(_S71 != u32(4294967295))
    {
        tableValue_1 = gTable_0[_S71 + _S68.blockLevelOffsetGlobal_0];
    }
    else
    {
        tableValue_1 = u32(0);
    }
    return NvFlowTableValueToIndexRead_0((_S70 & (vec3<i32>(_S68.blockDimLessOne_0))), tableValue_1);
}

fn NvFlowGlobalReadLinear4f_0( _S72 : texture_3d<f32>,  _S73 : sampler,  _S74 : NvFlowSparseLevelParams_0,  _S75 : vec3<f32>,  _S76 : i32) -> vec4<f32>
{
    var vidx_0 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0(_S75), _S76);
    var _S77 : vec4<i32> = NvFlowGlobalVirtualToReal_0(_S74, vidx_0);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S77.xyz) + _S75 - vec3<f32>(vidx_0.xyz);
    var _S78 : vec4<f32>;
    if(bool(_S77.w))
    {
        _S78 = (textureSampleLevel((_S72), (_S73), (readIdxf_0 * _S74.dimInv_0), (0.0f)));
    }
    else
    {
        _S78 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S78;
}

fn NvFlowRayMarchBlockCloud_0( _S79 : texture_3d<f32>,  _S80 : sampler,  _S81 : texture_2d<f32>,  _S82 : sampler,  _S83 : NvFlowSparseLevelParams_0,  _S84 : NvFlowRayMarchLayerShaderParams_0,  _S85 : vec3<f32>,  _S86 : f32,  _S87 : vec3<f32>,  _S88 : f32,  _S89 : vec3<f32>,  _S90 : u32,  _S91 : vec4<i32>,  _S92 : ptr<function, vec4<f32>>,  _S93 : ptr<function, f32>) -> bool
{
    var _S94 : vec3<i32> = _S91.xyz;
    var _S95 : vec3<f32> = vec3<f32>(0.00009999999747379f) * _S84.cellSize_0;
    var boxMinT_0 : f32;
    var boxMaxT_0 : f32;
    var _S96 : bool = NvFlowIntersectBox_0(_S87, _S89, vec3<f32>(_S94) * _S84.blockSizeWorld_0 - _S85 - _S95, vec3<f32>(_S94 + vec3<i32>(i32(1), i32(1), i32(1))) * _S84.blockSizeWorld_0 - _S85 + _S95, &(boxMinT_0), &(boxMaxT_0));
    var _S97 : f32 = max(_S86, boxMinT_0);
    boxMinT_0 = _S97;
    var isHit_0 : bool;
    if(_S97 > boxMaxT_0)
    {
        isHit_0 = false;
    }
    else
    {
        isHit_0 = _S96;
    }
    var _S98 : bool = boxMaxT_0 > _S88;
    if(_S98)
    {
        boxMaxT_0 = _S88;
    }
    if(isHit_0)
    {
        var _S99 : bool = (_S84.enableBlockWireframe_0) != u32(0);
        if(_S99)
        {
            NvFlowRayMarchWireframe_0(_S83, _S84, _S85, _S86, _S87, boxMinT_0, _S91, 1.0f, &((*_S92)), &((*_S93)));
        }
        var shadowDensity_0 : f32;
        var shadowSamplePos_0 : vec3<f32>;
        var shadowStepIdx_0 : i32;
        var cellMinT_0 : f32 = round(_S84.stepSizeInv_0 * boxMinT_0);
        var _S100 : i32 = i32(round(_S84.stepSizeInv_0 * boxMaxT_0) - cellMinT_0);
        var currentT_0 : f32 = _S84.stepSize_0 * cellMinT_0;
        var _S101 : vec3<f32> = vec3<f32>(_S84.stepSize_0);
        var vidxf_0 : vec3<f32> = (_S85 + vec3<f32>(currentT_0) * _S87) * _S84.cellSizeInv_0;
        var vidxfStep_0 : vec3<f32> = _S101 * _S87 * _S84.cellSizeInv_0;
        var _S102 : vec3<f32> = vidxf_0 + vec3<f32>(NvFlowGlobalVirtualToRealOffset_0(_S83, _S91, _S90));
        const ambientSampleOffset_0 : vec3<f32> = vec3<f32>(0.0f, 0.20000000298023224f, 0.0f);
        var shadowStep_0 : vec3<f32> = _S101 * normalize(_S84.cloud_0.sunDirection_0) * _S84.cellSizeInv_0 * vec3<f32>(_S84.cloud_0.shadowStepMultiplier_0);
        var _S103 : f32 = f32(_S84.cloud_0.numShadowSteps_0);
        var stepIdx_0 : i32 = i32(0);
        var ridxf_0 : vec3<f32> = _S102;
        var vidxf_1 : vec3<f32> = vidxf_0;
        var currentT_1 : f32 = currentT_0;
        var _S104 : vec3<f32> = vec3<f32>(_S84.cloud_0.volumeColorMultiplier_0);
        var _S105 : vec3<f32> = vec3<f32>(_S84.cloud_0.ambientMultiplier_0);
        for(;;)
        {
            if(stepIdx_0 < _S100)
            {
            }
            else
            {
                break;
            }
            if(((*_S92).w) < 0.00100000004749745f)
            {
                break;
            }
            var densitySample_0 : f32 = (textureSampleLevel((_S79), (_S80), (ridxf_0 * _S83.dimInv_0), (0.0f))).w;
            if(densitySample_0 > 0.00100000004749745f)
            {
                var _S106 : vec3<f32> = vidxf_1 + shadowStep_0;
                var density_0 : f32 = clamp(densitySample_0 * _S84.cloud_0.densityMultiplier_0, 0.0f, 1.0f);
                var _S107 : f32 = 1.0f - density_0;
                var aoSamplePos_0 : vec3<f32> = vidxf_1 + ambientSampleOffset_0;
                shadowStepIdx_0 = i32(0);
                shadowSamplePos_0 = _S106;
                shadowDensity_0 = 0.0f;
                var _S108 : vec3<f32> = vec3<f32>(density_0);
                for(;;)
                {
                    if(shadowStepIdx_0 < (_S84.cloud_0.numShadowSteps_0))
                    {
                    }
                    else
                    {
                        break;
                    }
                    var shadowDensity_1 : f32 = shadowDensity_0 + NvFlowGlobalReadLinear4f_0(_S79, _S80, _S83, shadowSamplePos_0, _S84.layerAndLevel_0).w;
                    var shadowSamplePos_1 : vec3<f32> = shadowSamplePos_0 + shadowStep_0;
                    shadowStepIdx_0 = shadowStepIdx_0 + i32(1);
                    shadowSamplePos_0 = shadowSamplePos_1;
                    shadowDensity_0 = shadowDensity_1;
                }
                var _S109 : vec3<f32> = (*_S92).xyz + exp(vec3<f32>((- shadowDensity_0 / _S103)) * _S84.cloud_0.attenuationMultiplier_0) * _S108 * vec3<f32>((*_S92).w) * _S84.cloud_0.volumeBaseColor_0 * _S104;
                (*_S92).x = _S109.x;
                (*_S92).y = _S109.y;
                (*_S92).z = _S109.z;
                (*_S92)[i32(3)] = (*_S92)[i32(3)] * _S107;
                var _S110 : vec3<f32> = (*_S92).xyz + vec3<f32>((exp(- NvFlowGlobalReadLinear4f_0(_S79, _S80, _S83, aoSamplePos_0, _S84.layerAndLevel_0).w) * density_0 * (*_S92).w)) * _S84.cloud_0.ambientColor_0 * _S105;
                (*_S92).x = _S110.x;
                (*_S92).y = _S110.y;
                (*_S92).z = _S110.z;
            }
            var ridxf_1 : vec3<f32> = ridxf_0 + vidxfStep_0;
            var vidxf_2 : vec3<f32> = vidxf_1 + vidxfStep_0;
            var currentT_2 : f32 = currentT_1 + _S84.stepSize_0;
            stepIdx_0 = stepIdx_0 + i32(1);
            ridxf_0 = ridxf_1;
            vidxf_1 = vidxf_2;
            currentT_1 = currentT_2;
        }
        if(_S98)
        {
            if(((*_S92).w) > 0.00100000004749745f)
            {
                var densitySample_1 : f32 = (textureSampleLevel((_S79), (_S80), (ridxf_0 * _S83.dimInv_0), (0.0f))).w;
                if(densitySample_1 > 0.00100000004749745f)
                {
                    var _S111 : vec3<f32> = vidxf_1 + shadowStep_0;
                    var density_1 : f32 = clamp(densitySample_1 * _S84.cloud_0.densityMultiplier_0, 0.0f, 1.0f);
                    var _S112 : f32 = 1.0f - density_1;
                    var aoSamplePos_1 : vec3<f32> = vidxf_1 + ambientSampleOffset_0;
                    shadowStepIdx_0 = i32(0);
                    shadowSamplePos_0 = _S111;
                    shadowDensity_0 = 0.0f;
                    var _S113 : vec3<f32> = vec3<f32>(density_1);
                    for(;;)
                    {
                        if(shadowStepIdx_0 < (_S84.cloud_0.numShadowSteps_0))
                        {
                        }
                        else
                        {
                            break;
                        }
                        var shadowDensity_2 : f32 = shadowDensity_0 + NvFlowGlobalReadLinear4f_0(_S79, _S80, _S83, shadowSamplePos_0, _S84.layerAndLevel_0).w;
                        var shadowSamplePos_2 : vec3<f32> = shadowSamplePos_0 + shadowStep_0;
                        shadowStepIdx_0 = shadowStepIdx_0 + i32(1);
                        shadowSamplePos_0 = shadowSamplePos_2;
                        shadowDensity_0 = shadowDensity_2;
                    }
                    var _S114 : vec3<f32> = (*_S92).xyz + exp(vec3<f32>((- shadowDensity_0 / _S103)) * _S84.cloud_0.attenuationMultiplier_0) * _S113 * vec3<f32>((*_S92).w) * _S84.cloud_0.volumeBaseColor_0 * _S104;
                    (*_S92).x = _S114.x;
                    (*_S92).y = _S114.y;
                    (*_S92).z = _S114.z;
                    (*_S92)[i32(3)] = (*_S92)[i32(3)] * _S112;
                    var _S115 : vec3<f32> = (*_S92).xyz + vec3<f32>((exp(- NvFlowGlobalReadLinear4f_0(_S79, _S80, _S83, aoSamplePos_1, _S84.layerAndLevel_0).w) * density_1 * (*_S92).w)) * _S84.cloud_0.ambientColor_0 * _S105;
                    (*_S92).x = _S115.x;
                    (*_S92).y = _S115.y;
                    (*_S92).z = _S115.z;
                }
            }
        }
        if(_S99)
        {
            NvFlowRayMarchWireframe_0(_S83, _S84, _S85, _S86, _S87, boxMaxT_0, _S91, 0.30000001192092896f, &((*_S92)), &((*_S93)));
        }
    }
    return _S98;
}

fn NvFlowRayMarchBlock_0( _S116 : texture_3d<f32>,  _S117 : sampler,  _S118 : texture_2d<f32>,  _S119 : sampler,  _S120 : NvFlowSparseLevelParams_0,  _S121 : NvFlowRayMarchLayerShaderParams_0,  _S122 : vec3<f32>,  _S123 : f32,  _S124 : vec3<f32>,  _S125 : f32,  _S126 : vec3<f32>,  _S127 : f32,  _S128 : u32,  _S129 : vec4<i32>,  _S130 : ptr<function, vec4<f32>>,  _S131 : ptr<function, f32>) -> bool
{
    var _S132 : vec3<i32> = _S129.xyz;
    var _S133 : vec3<f32> = vec3<f32>(0.00009999999747379f) * _S121.cellSize_0;
    var boxMinT_1 : f32;
    var boxMaxT_1 : f32;
    var _S134 : bool = NvFlowIntersectBox_0(_S124, _S126, vec3<f32>(_S132) * _S121.blockSizeWorld_0 - _S122 - _S133, vec3<f32>(_S132 + vec3<i32>(i32(1), i32(1), i32(1))) * _S121.blockSizeWorld_0 - _S122 + _S133, &(boxMinT_1), &(boxMaxT_1));
    var _S135 : f32 = max(_S123, boxMinT_1);
    boxMinT_1 = _S135;
    var isHit_1 : bool;
    if(_S135 > boxMaxT_1)
    {
        isHit_1 = false;
    }
    else
    {
        isHit_1 = _S134;
    }
    var _S136 : bool = boxMaxT_1 > _S125;
    if(_S136)
    {
        boxMaxT_1 = _S125;
    }
    var hitMax_0 : bool;
    if(isHit_1)
    {
        var _S137 : bool = (_S121.enableBlockWireframe_0) != u32(0);
        if(_S137)
        {
            NvFlowRayMarchWireframe_0(_S120, _S121, _S122, _S123, _S124, boxMinT_1, _S129, 1.0f, &((*_S130)), &((*_S131)));
        }
        var cellMinT_1 : f32 = - floor(- (_S121.stepSizeInv_0 * boxMinT_1 + _S127)) - _S127;
        var _S138 : i32 = i32(- floor(- (_S121.stepSizeInv_0 * boxMaxT_1 + _S127)) - _S127 - cellMinT_1);
        var currentT_3 : f32 = _S121.stepSize_0 * cellMinT_1;
        var _S139 : vec3<f32> = vec3<f32>(_S121.stepSize_0) * _S124 * _S121.cellSizeInv_0;
        var _S140 : vec3<f32> = (_S122 + vec3<f32>(currentT_3) * _S124) * _S121.cellSizeInv_0 + vec3<f32>(NvFlowGlobalVirtualToRealOffset_0(_S120, _S129, _S128));
        var _S141 : bool = (_S121.enableRawMode_0) == u32(0);
        const _S142 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
        var _S143 : bool = (_S121.rawModeIsosurface_0) != u32(0);
        var _S144 : bool = (_S121.rawModeNormalize_0) != u32(0);
        var stepIdx_1 : i32 = i32(0);
        var ridxf_2 : vec3<f32> = _S140;
        var currentT_4 : f32 = currentT_3;
        var _S145 : vec3<f32> = vec3<f32>(_S121.colorScale_0);
        for(;;)
        {
            if(stepIdx_1 < _S138)
            {
            }
            else
            {
                break;
            }
            var value_0 : vec4<f32> = (textureSampleLevel((_S116), (_S117), (ridxf_2 * _S120.dimInv_0), (0.0f)));
            var color_1 : vec4<f32> = value_0;
            if(_S141)
            {
                var _S146 : vec4<f32> = (textureSampleLevel((_S118), (_S119), (vec2<f32>(_S121.colormapXScale_0 * value_0.x + _S121.colormapXOffset_0, _S121.layerAndLevelColormapV_0)), (0.0f)));
                color_1 = _S146;
                var _S147 : vec3<f32> = _S146.xyz * vec3<f32>((1.0f + _S121.shadowFactor_0 * (value_0.z - 1.0f)));
                color_1.x = _S147.x;
                color_1.y = _S147.y;
                color_1.z = _S147.z;
                color_1[i32(3)] = color_1[i32(3)] * value_0.w;
            }
            else
            {
                if(_S143)
                {
                    var _S148 : f32;
                    if((value_0.w) > 0.5f)
                    {
                        _S148 = 1.0f;
                    }
                    else
                    {
                        _S148 = 0.0f;
                    }
                    color_1[i32(3)] = _S148;
                }
                if(_S144)
                {
                    if((color_1.w) > 0.0f)
                    {
                        var _S149 : vec3<f32> = color_1.xyz * vec3<f32>((1.0f / value_0.w));
                        color_1.x = _S149.x;
                        color_1.y = _S149.y;
                        color_1.z = _S149.z;
                    }
                }
            }
            var _S150 : vec3<f32> = color_1.xyz * _S145;
            color_1.x = _S150.x;
            color_1.y = _S150.y;
            color_1.z = _S150.z;
            var _S151 : vec4<f32> = max(_S142, color_1);
            color_1 = _S151;
            color_1[i32(3)] = min(1.0f, _S151.w) * _S121.alphaScale_0;
            (*_S131) = (*_S130).w * (color_1.w * currentT_4) + (*_S131);
            var _S152 : vec3<f32> = vec3<f32>((*_S130).w) * (vec3<f32>(color_1.w) * color_1.xyz) + (*_S130).xyz;
            (*_S130).x = _S152.x;
            (*_S130).y = _S152.y;
            (*_S130).z = _S152.z;
            (*_S130)[i32(3)] = (1.0f - color_1.w) * (*_S130).w;
            var ridxf_3 : vec3<f32> = ridxf_2 + _S139;
            var currentT_5 : f32 = currentT_4 + _S121.stepSize_0;
            stepIdx_1 = stepIdx_1 + i32(1);
            ridxf_2 = ridxf_3;
            currentT_4 = currentT_5;
        }
        if(((*_S130).w) < 0.00004999999873689f)
        {
            hitMax_0 = true;
        }
        else
        {
            hitMax_0 = _S136;
        }
        if(_S137)
        {
            NvFlowRayMarchWireframe_0(_S120, _S121, _S122, _S123, _S124, boxMaxT_1, _S129, 0.30000001192092896f, &((*_S130)), &((*_S131)));
        }
    }
    else
    {
        hitMax_0 = _S136;
    }
    return hitMax_0;
}

fn NvFlowRayMarchBlocks_0( _S153 : texture_3d<f32>,  _S154 : sampler,  _S155 : texture_2d<f32>,  _S156 : sampler,  _S157 : NvFlowSparseLevelParams_0,  _S158 : NvFlowRayMarchLayerShaderParams_0,  _S159 : vec3<f32>,  _S160 : f32,  _S161 : vec3<f32>,  _S162 : f32,  _S163 : vec3<f32>,  _S164 : ptr<function, vec4<f32>>,  _S165 : ptr<function, f32>)
{
    var boxMinT_2 : f32;
    var boxMaxT_2 : f32;
    var _S166 : bool = NvFlowIntersectBox_0(_S161, _S163, _S158.worldMin_0 - _S159, _S158.worldMax_0 - _S159, &(boxMinT_2), &(boxMaxT_2));
    var _S167 : f32 = max(_S160, boxMinT_2);
    boxMinT_2 = _S167;
    var isHit_2 : bool;
    if(_S167 > boxMaxT_2)
    {
        isHit_2 = false;
    }
    else
    {
        isHit_2 = _S166;
    }
    if(isHit_2)
    {
        var _S168 : vec4<i32> = vec4<i32>(NvFlowFloor_i_0((_S161 * vec3<f32>(boxMinT_2) + _S159) * _S158.blockSizeWorldInv_0), _S158.layerAndLevel_0);
        var location_4 : vec4<i32> = _S168;
        var _S169 : vec3<i32> = NvFlowRayMarchComputeFinalLocation_0(_S161, _S168, _S158.locationMin_0, _S158.locationMax_0);
        var _S170 : f32 = NvFlowRayMarchNoiseFromDir_0(_S161);
        var blockHitT_0 : f32 = boxMinT_2;
        var _S171 : i32 = _S169.x;
        var _S172 : i32 = _S169.y;
        var _S173 : i32 = _S169.z;
        var _S174 : bool = (_S158.cloud_0.enableCloudMode_0) != u32(0);
        var hitMax_1 : bool = false;
        for(;;)
        {
            if((location_4.x) != _S171)
            {
                isHit_2 = (location_4.y) != _S172;
            }
            else
            {
                isHit_2 = false;
            }
            var _S175 : bool;
            if(isHit_2)
            {
                _S175 = (location_4.z) != _S173;
            }
            else
            {
                _S175 = false;
            }
            var _S176 : bool;
            if(_S175)
            {
                _S176 = !hitMax_1;
            }
            else
            {
                _S176 = false;
            }
            if(_S176)
            {
            }
            else
            {
                break;
            }
            var _S177 : u32 = NvFlowLocationToBlockIdx_0(_S157, location_4);
            if(_S177 != u32(4294967295))
            {
                var hitMax_2 : bool;
                if(_S174)
                {
                    var _S178 : bool = NvFlowRayMarchBlockCloud_0(_S153, _S154, _S155, _S156, _S157, _S158, _S159, _S160, _S161, _S162, _S163, _S177, location_4, &((*_S164)), &((*_S165)));
                    hitMax_2 = _S178;
                }
                else
                {
                    var _S179 : bool = NvFlowRayMarchBlock_0(_S153, _S154, _S155, _S156, _S157, _S158, _S159, _S160, _S161, _S162, _S163, _S170, _S177, location_4, &((*_S164)), &((*_S165)));
                    hitMax_2 = _S179;
                }
                hitMax_1 = hitMax_2;
            }
            NvFlowRayMarchAdvanceRay_0(_S158.blockSizeWorld_0, _S161, _S163, _S159, &(location_4), &(blockHitT_0));
        }
    }
    return;
}

fn NvFlowLocalWriteNeighbor1f_0( _S180 : NvFlowSparseLevelParams_0,  _S181 : i32,  _S182 : i32,  _S183 : i32,  _S184 : u32,  _S185 : vec3<i32>,  _S186 : f32)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S185, gTable_0[NvFlowNeighborToIdx_0(_S184, _S181, _S182, _S183) + _S180.blockLevelOffsetLocal_0], _S181, _S182, _S183);
    var _S187 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S188 : f32;
    if(bool(index_0.w))
    {
        _S188 = _S186;
    }
    else
    {
        _S188 = 0.0f;
    }
    textureStore((alphaOut_0), (_S187), vec4<f32>((_S188), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S189 : NvFlowSparseLevelParams_0,  _S190 : u32,  _S191 : vec3<i32>,  _S192 : f32)
{
    var neighbor_1 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S189, _S191);
    NvFlowLocalWriteNeighbor1f_0(_S189, i32(0), i32(0), i32(0), _S190, _S191, _S192);
    var _S193 : i32 = neighbor_1.x;
    var _S194 : bool = _S193 != i32(0);
    if(_S194)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, _S193, i32(0), i32(0), _S190, _S191, _S192);
    }
    var _S195 : i32 = neighbor_1.y;
    var _S196 : bool = _S195 != i32(0);
    if(_S196)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, i32(0), _S195, i32(0), _S190, _S191, _S192);
    }
    var _S197 : i32 = neighbor_1.z;
    var _S198 : bool = _S197 != i32(0);
    if(_S198)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, i32(0), i32(0), _S197, _S190, _S191, _S192);
    }
    var _S199 : bool;
    if(_S194)
    {
        _S199 = _S196;
    }
    else
    {
        _S199 = false;
    }
    if(_S199)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, _S193, _S195, i32(0), _S190, _S191, _S192);
    }
    if(_S196)
    {
        _S199 = _S198;
    }
    else
    {
        _S199 = false;
    }
    if(_S199)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, i32(0), _S195, _S197, _S190, _S191, _S192);
    }
    if(_S194)
    {
        _S199 = _S198;
    }
    else
    {
        _S199 = false;
    }
    if(_S199)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, _S193, i32(0), _S197, _S190, _S191, _S192);
    }
    if(_S194)
    {
        _S199 = _S196;
    }
    else
    {
        _S199 = false;
    }
    if(_S199)
    {
        _S199 = _S198;
    }
    else
    {
        _S199 = false;
    }
    if(_S199)
    {
        NvFlowLocalWriteNeighbor1f_0(_S189, _S193, _S195, _S197, _S190, _S191, _S192);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var threadIdx_3 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), dispatchThreadID_0.x);
    var blockIdx_2 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S200 : u32 = NvFlowGetLayerParamIdx_0(unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), blockIdx_2);
    var alpha_0 : f32;
    if((layerParamsIn_0[_S200].enabled_0) != u32(0))
    {
        var vidx_1 : vec4<i32>;
        var _S201 : bool = NvFlowRealToVirtual_0(unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), blockIdx_2, threadIdx_3, &(vidx_1));
        var maxWorldDistance_0 : f32 = f32(layerParamsIn_0[_S200].numSteps_0) * layerParamsIn_0[_S200].base_0.stepSize_0;
        var worldOrigin_0 : vec3<f32> = (vec3<f32>(vidx_1.xyz) + vec3<f32>(0.5f, 0.5f, 0.5f)) * layerParamsIn_0[_S200].base_0.cellSize_0;
        var rayDir_5 : vec3<f32>;
        if(bool(layerParamsIn_0[_S200].isPointLight_0))
        {
            rayDir_5 = layerParamsIn_0[_S200].lightPosition_0 - worldOrigin_0;
        }
        else
        {
            rayDir_5 = layerParamsIn_0[_S200].lightDirection_0;
        }
        var rayDir_6 : vec3<f32> = normalize(rayDir_5);
        var rayDirInv_2 : vec3<f32> = vec3<f32>(1.0f, 1.0f, 1.0f) / rayDir_6;
        var worldOrigin_1 : vec3<f32> = worldOrigin_0 + vec3<f32>(layerParamsIn_0[_S200].stepOffset_0) * rayDir_6;
        var sum_1 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 1.0f);
        var nominalT_1 : f32 = 0.0f;
        NvFlowRayMarchBlocks_0(gInput_0, gSampler_0, gColormap_0, gColormapSampler_0, unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), unpackStorage_2(layerParamsIn_0[_S200].base_0), worldOrigin_1, 0.0f, rayDir_6, maxWorldDistance_0, rayDirInv_2, &(sum_1), &(nominalT_1));
        alpha_0 = 1.0f - sum_1.w;
    }
    else
    {
        alpha_0 = 0.0f;
    }
    NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.coarseDensityTable_0), blockIdx_2, threadIdx_3, alpha_0);
    return;
}

