// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct VoxelInterpolateCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) levelIdx_0 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) sampleTable_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : VoxelInterpolateCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(3) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(4) @group(0) var voxelWeightIn_0 : texture_3d<f32>;

@binding(5) @group(0) var samplerIn_0 : sampler;

@binding(6) @group(0) var densityOut_0 : texture_storage_3d<rgba32float, write>;

@binding(7) @group(0) var voxelWeightOut_0 : texture_storage_3d<r32float, write>;

struct VoxelInterpolateCS_LayerParams_std430_0
{
    @align(4) enabled_0 : u32,
    @align(4) threshold_0 : f32,
    @align(4) pad1_1 : f32,
    @align(4) pad2_1 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<VoxelInterpolateCS_LayerParams_std430_0>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_0 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_0 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_0 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_0 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_0 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_0) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowFloor_i_0( v_1 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_1));
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowLocalVirtualToReal_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32,  _S11 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S11 >> (vec3<u32>(vec3<i32>(_S9.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S11, tableIn_0[NvFlowNeighborToIdx_0(_S10, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S9.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalRead4f_0( _S12 : texture_3d<f32>,  _S13 : NvFlowSparseLevelParams_0,  _S14 : u32,  _S15 : vec3<i32>) -> vec4<f32>
{
    var _S16 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S13, _S14, _S15);
    var _S17 : vec4<f32>;
    if(bool(_S16.w))
    {
        var _S18 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S16.xyz), u32(0)));
        _S17 = (textureLoad((_S12), ((_S18)).xyz, ((_S18)).w));
    }
    else
    {
        _S17 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S17;
}

fn NvFlowLocalRead1f_0( _S19 : texture_3d<f32>,  _S20 : NvFlowSparseLevelParams_0,  _S21 : u32,  _S22 : vec3<i32>) -> f32
{
    var _S23 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S20, _S21, _S22);
    var _S24 : f32;
    if(bool(_S23.w))
    {
        var _S25 : vec4<i32> = vec4<i32>(vec4<u32>(vec3<u32>(_S23.xyz), u32(0)));
        _S24 = (textureLoad((_S19), ((_S25)).xyz, ((_S25)).w).x);
    }
    else
    {
        _S24 = 0.0f;
    }
    return _S24;
}

fn NvFlowLocalReadLinear4f_0( _S26 : texture_3d<f32>,  _S27 : sampler,  _S28 : NvFlowSparseLevelParams_0,  _S29 : u32,  _S30 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S30);
    var _S31 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S28, _S29, threadIdx_3);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S31.xyz) + _S30 - vec3<f32>(threadIdx_3);
    var _S32 : vec4<f32>;
    if(bool(_S31.w))
    {
        _S32 = (textureSampleLevel((_S26), (_S27), (readIdxf_0 * _S28.dimInv_0), (0.0f)));
    }
    else
    {
        _S32 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S32;
}

fn NvFlowLocalReadLinear1f_0( _S33 : texture_3d<f32>,  _S34 : sampler,  _S35 : NvFlowSparseLevelParams_0,  _S36 : u32,  _S37 : vec3<f32>) -> f32
{
    var threadIdx_4 : vec3<i32> = NvFlowFloor_i_0(_S37);
    var _S38 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S35, _S36, threadIdx_4);
    var readIdxf_1 : vec3<f32> = vec3<f32>(_S38.xyz) + _S37 - vec3<f32>(threadIdx_4);
    var _S39 : f32;
    if(bool(_S38.w))
    {
        _S39 = (textureSampleLevel((_S33), (_S34), (readIdxf_1 * _S35.dimInv_0), (0.0f)).x);
    }
    else
    {
        _S39 = 0.0f;
    }
    return _S39;
}

fn NvFlowLocalWriteNeighbor4f_0( _S40 : NvFlowSparseLevelParams_0,  _S41 : i32,  _S42 : i32,  _S43 : i32,  _S44 : u32,  _S45 : vec3<i32>,  _S46 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S45, tableIn_0[NvFlowNeighborToIdx_0(_S44, _S41, _S42, _S43) + _S40.blockLevelOffsetLocal_0], _S41, _S42, _S43);
    var _S47 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S48 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S48 = _S46;
    }
    else
    {
        _S48 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((densityOut_0), (_S47), (_S48));
    return;
}

fn NvFlowLocalWrite4f_0( _S49 : NvFlowSparseLevelParams_0,  _S50 : u32,  _S51 : vec3<i32>,  _S52 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S49, _S51);
    NvFlowLocalWriteNeighbor4f_0(_S49, i32(0), i32(0), i32(0), _S50, _S51, _S52);
    var _S53 : i32 = neighbor_2.x;
    var _S54 : bool = _S53 != i32(0);
    if(_S54)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, _S53, i32(0), i32(0), _S50, _S51, _S52);
    }
    var _S55 : i32 = neighbor_2.y;
    var _S56 : bool = _S55 != i32(0);
    if(_S56)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, i32(0), _S55, i32(0), _S50, _S51, _S52);
    }
    var _S57 : i32 = neighbor_2.z;
    var _S58 : bool = _S57 != i32(0);
    if(_S58)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, i32(0), i32(0), _S57, _S50, _S51, _S52);
    }
    var _S59 : bool;
    if(_S54)
    {
        _S59 = _S56;
    }
    else
    {
        _S59 = false;
    }
    if(_S59)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, _S53, _S55, i32(0), _S50, _S51, _S52);
    }
    if(_S56)
    {
        _S59 = _S58;
    }
    else
    {
        _S59 = false;
    }
    if(_S59)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, i32(0), _S55, _S57, _S50, _S51, _S52);
    }
    if(_S54)
    {
        _S59 = _S58;
    }
    else
    {
        _S59 = false;
    }
    if(_S59)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, _S53, i32(0), _S57, _S50, _S51, _S52);
    }
    if(_S54)
    {
        _S59 = _S56;
    }
    else
    {
        _S59 = false;
    }
    if(_S59)
    {
        _S59 = _S58;
    }
    else
    {
        _S59 = false;
    }
    if(_S59)
    {
        NvFlowLocalWriteNeighbor4f_0(_S49, _S53, _S55, _S57, _S50, _S51, _S52);
    }
    return;
}

fn NvFlowLocalWriteNeighbor1f_0( _S60 : NvFlowSparseLevelParams_0,  _S61 : i32,  _S62 : i32,  _S63 : i32,  _S64 : u32,  _S65 : vec3<i32>,  _S66 : f32)
{
    var index_1 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S65, tableIn_0[NvFlowNeighborToIdx_0(_S64, _S61, _S62, _S63) + _S60.blockLevelOffsetLocal_0], _S61, _S62, _S63);
    var _S67 : vec3<u32> = vec3<u32>(index_1.xyz);
    var _S68 : f32;
    if(bool(index_1.w))
    {
        _S68 = _S66;
    }
    else
    {
        _S68 = 0.0f;
    }
    textureStore((voxelWeightOut_0), (_S67), vec4<f32>((_S68), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S69 : NvFlowSparseLevelParams_0,  _S70 : u32,  _S71 : vec3<i32>,  _S72 : f32)
{
    var neighbor_3 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S69, _S71);
    NvFlowLocalWriteNeighbor1f_0(_S69, i32(0), i32(0), i32(0), _S70, _S71, _S72);
    var _S73 : i32 = neighbor_3.x;
    var _S74 : bool = _S73 != i32(0);
    if(_S74)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, _S73, i32(0), i32(0), _S70, _S71, _S72);
    }
    var _S75 : i32 = neighbor_3.y;
    var _S76 : bool = _S75 != i32(0);
    if(_S76)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, i32(0), _S75, i32(0), _S70, _S71, _S72);
    }
    var _S77 : i32 = neighbor_3.z;
    var _S78 : bool = _S77 != i32(0);
    if(_S78)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, i32(0), i32(0), _S77, _S70, _S71, _S72);
    }
    var _S79 : bool;
    if(_S74)
    {
        _S79 = _S76;
    }
    else
    {
        _S79 = false;
    }
    if(_S79)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, _S73, _S75, i32(0), _S70, _S71, _S72);
    }
    if(_S76)
    {
        _S79 = _S78;
    }
    else
    {
        _S79 = false;
    }
    if(_S79)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, i32(0), _S75, _S77, _S70, _S71, _S72);
    }
    if(_S74)
    {
        _S79 = _S78;
    }
    else
    {
        _S79 = false;
    }
    if(_S79)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, _S73, i32(0), _S77, _S70, _S71, _S72);
    }
    if(_S74)
    {
        _S79 = _S76;
    }
    else
    {
        _S79 = false;
    }
    if(_S79)
    {
        _S79 = _S78;
    }
    else
    {
        _S79 = false;
    }
    if(_S79)
    {
        NvFlowLocalWriteNeighbor1f_0(_S69, _S73, _S75, _S77, _S70, _S71, _S72);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var _S80 : u32 = dispatchThreadID_0.x;
    if(_S80 >= (globalParamsIn_0.table_0.threadsPerBlock_0))
    {
        return;
    }
    var threadIdx_5 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), _S80);
    var blockIdx_1 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var _S81 : vec3<f32> = vec3<f32>(threadIdx_5) + vec3<f32>(0.5f);
    var _S82 : vec4<f32> = NvFlowLocalRead4f_0(densityIn_0, unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5);
    var _S83 : f32 = NvFlowLocalRead1f_0(voxelWeightIn_0, unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5);
    var density4_0 : vec4<f32>;
    var voxelWeight_0 : f32;
    if(_S83 == 0.0f)
    {
        var k_0 : i32 = i32(0);
        density4_0 = _S82;
        voxelWeight_0 = _S83;
        for(;;)
        {
            if(k_0 < i32(2))
            {
            }
            else
            {
                break;
            }
            var _S84 : f32 = f32(k_0) - 0.5f;
            var j_0 : i32 = i32(0);
            for(;;)
            {
                if(j_0 < i32(2))
                {
                }
                else
                {
                    break;
                }
                var _S85 : f32 = f32(j_0) - 0.5f;
                var i_0 : i32 = i32(0);
                var density4_1 : vec4<f32> = density4_0;
                var voxelWeight_1 : f32 = voxelWeight_0;
                for(;;)
                {
                    if(i_0 < i32(2))
                    {
                    }
                    else
                    {
                        break;
                    }
                    var _S86 : vec3<f32> = _S81 + vec3<f32>(f32(i_0) - 0.5f, _S85, _S84);
                    var density4_2 : vec4<f32> = density4_1 + NvFlowLocalReadLinear4f_0(densityIn_0, samplerIn_0, unpackStorage_0(globalParamsIn_0.sampleTable_0), blockIdx_1, _S86);
                    var voxelWeight_2 : f32 = voxelWeight_1 + NvFlowLocalReadLinear1f_0(voxelWeightIn_0, samplerIn_0, unpackStorage_0(globalParamsIn_0.sampleTable_0), blockIdx_1, _S86);
                    i_0 = i_0 + i32(1);
                    density4_1 = density4_2;
                    voxelWeight_1 = voxelWeight_2;
                }
                j_0 = j_0 + i32(1);
                density4_0 = density4_1;
                voxelWeight_0 = voxelWeight_1;
            }
            k_0 = k_0 + i32(1);
        }
    }
    else
    {
        voxelWeight_0 = _S83;
        density4_0 = _S82;
    }
    if(voxelWeight_0 > 0.0f)
    {
        density4_0 = density4_0 * vec4<f32>((1.0f / voxelWeight_0));
        voxelWeight_0 = 1.0f;
    }
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5, density4_0);
    NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5, voxelWeight_0);
    return;
}

