// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
@binding(0) @group(0) var value0_0 : texture_storage_3d<rgba32float, read_write>;

@binding(1) @group(0) var value1_0 : texture_storage_3d<rgba32float, read_write>;

@binding(2) @group(0) var value2_0 : texture_storage_3d<rgba32float, read_write>;

@binding(3) @group(0) var value3_0 : texture_storage_3d<rgba32float, read_write>;

@binding(4) @group(0) var value4_0 : texture_storage_3d<rgba32float, read_write>;

@binding(5) @group(0) var value5_0 : texture_storage_3d<rgba32float, read_write>;

@binding(6) @group(0) var value6_0 : texture_storage_3d<rgba32float, read_write>;

@binding(7) @group(0) var value7_0 : texture_storage_3d<rgba32float, read_write>;

@binding(8) @group(0) var weight0_0 : texture_storage_3d<r32float, read_write>;

@binding(9) @group(0) var weight1_0 : texture_storage_3d<r32float, read_write>;

@binding(10) @group(0) var weight2_0 : texture_storage_3d<r32float, read_write>;

@binding(11) @group(0) var weight3_0 : texture_storage_3d<r32float, read_write>;

@binding(12) @group(0) var weight4_0 : texture_storage_3d<r32float, read_write>;

@binding(13) @group(0) var weight5_0 : texture_storage_3d<r32float, read_write>;

@binding(14) @group(0) var weight6_0 : texture_storage_3d<r32float, read_write>;

@binding(15) @group(0) var weight7_0 : texture_storage_3d<r32float, read_write>;

@compute
@workgroup_size(32, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    return;
}

