// SPDX-FileCopyrightText: Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Generated by pinned Slang; see manifest.json.
struct NvFlowSparseLevelParams_std140_0
{
    @align(16) blockDimLessOne_0 : vec3<u32>,
    @align(4) threadsPerBlock_0 : u32,
    @align(16) blockDimBits_0 : vec3<u32>,
    @align(4) numLocations_0 : u32,
    @align(16) tableDimLessOne_0 : vec3<u32>,
    @align(4) tableDim3_0 : u32,
    @align(16) tableDimBits_x_0 : u32,
    @align(4) tableDimBits_xy_0 : u32,
    @align(8) tableDimBits_z_0 : u32,
    @align(4) locationOffset_0 : u32,
    @align(16) allocationOffset_0 : u32,
    @align(4) newListOffset_0 : u32,
    @align(8) blockLevelOffsetGlobal_0 : u32,
    @align(4) blockLevelOffsetLocal_0 : u32,
    @align(16) layerParamIdxOffset_0 : u32,
    @align(4) numLayers_0 : u32,
    @align(8) pad0_0 : u32,
    @align(4) pad1_0 : u32,
    @align(16) dim_0 : vec3<u32>,
    @align(4) maxLocations_0 : u32,
    @align(16) dimInv_0 : vec3<f32>,
    @align(4) numNewLocations_0 : u32,
    @align(16) globalLocationMin_0 : vec4<i32>,
    @align(16) globalLocationMax_0 : vec4<i32>,
};

struct VoxelInterpolateCS_GlobalParams_std140_0
{
    @align(16) blockIdxOffset_0 : u32,
    @align(4) levelIdx_0 : u32,
    @align(8) pad2_0 : u32,
    @align(4) pad3_0 : u32,
    @align(16) table_0 : NvFlowSparseLevelParams_std140_0,
    @align(16) sampleTable_0 : NvFlowSparseLevelParams_std140_0,
};

@binding(0) @group(0) var<uniform> globalParamsIn_0 : VoxelInterpolateCS_GlobalParams_std140_0;
@binding(2) @group(0) var<storage, read> tableIn_0 : array<u32>;

@binding(3) @group(0) var densityIn_0 : texture_3d<f32>;

@binding(5) @group(0) var samplerIn_0 : sampler;

@binding(4) @group(0) var voxelWeightIn_0 : texture_3d<f32>;

@binding(6) @group(0) var densityOut_0 : texture_storage_3d<rgba32float, write>;

@binding(7) @group(0) var voxelWeightOut_0 : texture_storage_3d<r32float, write>;

struct VoxelInterpolateCS_LayerParams_std430_0
{
    @align(4) enabled_0 : u32,
    @align(4) threshold_0 : f32,
    @align(4) pad1_1 : f32,
    @align(4) pad2_1 : f32,
};

@binding(1) @group(0) var<storage, read> layerParamsIn_0 : array<VoxelInterpolateCS_LayerParams_std430_0>;

struct NvFlowSparseLevelParams_0
{
     blockDimLessOne_0 : vec3<u32>,
     threadsPerBlock_0 : u32,
     blockDimBits_0 : vec3<u32>,
     numLocations_0 : u32,
     tableDimLessOne_0 : vec3<u32>,
     tableDim3_0 : u32,
     tableDimBits_x_0 : u32,
     tableDimBits_xy_0 : u32,
     tableDimBits_z_0 : u32,
     locationOffset_0 : u32,
     allocationOffset_0 : u32,
     newListOffset_0 : u32,
     blockLevelOffsetGlobal_0 : u32,
     blockLevelOffsetLocal_0 : u32,
     layerParamIdxOffset_0 : u32,
     numLayers_0 : u32,
     pad0_0 : u32,
     pad1_0 : u32,
     dim_0 : vec3<u32>,
     maxLocations_0 : u32,
     dimInv_0 : vec3<f32>,
     numNewLocations_0 : u32,
     globalLocationMin_0 : vec4<i32>,
     globalLocationMax_0 : vec4<i32>,
};

fn unpackStorage_0( _S1 : NvFlowSparseLevelParams_std140_0) -> NvFlowSparseLevelParams_0
{
    var _S2 : NvFlowSparseLevelParams_0 = NvFlowSparseLevelParams_0( _S1.blockDimLessOne_0, _S1.threadsPerBlock_0, _S1.blockDimBits_0, _S1.numLocations_0, _S1.tableDimLessOne_0, _S1.tableDim3_0, _S1.tableDimBits_x_0, _S1.tableDimBits_xy_0, _S1.tableDimBits_z_0, _S1.locationOffset_0, _S1.allocationOffset_0, _S1.newListOffset_0, _S1.blockLevelOffsetGlobal_0, _S1.blockLevelOffsetLocal_0, _S1.layerParamIdxOffset_0, _S1.numLayers_0, _S1.pad0_0, _S1.pad1_0, _S1.dim_0, _S1.maxLocations_0, _S1.dimInv_0, _S1.numNewLocations_0, _S1.globalLocationMin_0, _S1.globalLocationMax_0 );
    return _S2;
}

fn NvFlowComputeThreadIdx_0( tableParams_0 : NvFlowSparseLevelParams_0,  threadIdx1D_0 : u32) -> vec3<i32>
{
    var _S3 : i32 = i32(threadIdx1D_0);
    var _S4 : u32 = tableParams_0.blockDimBits_0.x;
    return vec3<i32>((_S3 & (i32(tableParams_0.blockDimLessOne_0.x))), (((_S3 >> (u32(i32(_S4))))) & (i32(tableParams_0.blockDimLessOne_0.y))), (((_S3 >> (u32(i32(_S4 + tableParams_0.blockDimBits_0.y))))) & (i32(tableParams_0.blockDimLessOne_0.z))));
}

fn NvFlowFloor_i_0( v_0 : vec3<f32>) -> vec3<i32>
{
    return vec3<i32>(floor(v_0));
}

fn NvFlowNeighborToIdx_0( blockIdx_0 : u32,  x_0 : i32,  y_0 : i32,  z_0 : i32) -> u32
{
    return ((blockIdx_0 << (u32(5)))) + ((u32(((z_0 << (u32(3)))) + z_0 + (((y_0 << (u32(1)))) + y_0) + x_0 + i32(13) + i32(5)) & (u32(31))));
}

fn NvFlowTableValueToIndexRead_0( threadIdx_0 : vec3<i32>,  v_1 : u32) -> vec4<i32>
{
    var _S5 : i32 = ((threadIdx_0.x + i32((((v_1 << (u32(1)))) | (u32(1))))) & (i32(4095)));
    var ridx_0 : vec4<i32> = vec4<i32>(_S5, ((threadIdx_0.y + i32((((v_1 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_0.z + i32((((v_1 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_1 >> (u32(31)))));
    ridx_0[i32(0)] = (_S5 | (i32(((~v_1) & (u32(2147483648))))));
    return ridx_0;
}

fn NvFlowLocalComputeNeighbor_0( tableParams_1 : NvFlowSparseLevelParams_0,  threadIdx_1 : vec3<i32>) -> vec3<i32>
{
    var neighbor_0 : vec3<i32> = vec3<i32>(i32(0), i32(0), i32(0));
    var _S6 : i32 = threadIdx_1.x;
    if(_S6 == i32(0))
    {
        neighbor_0[i32(0)] = i32(-1);
    }
    if(_S6 == i32(tableParams_1.blockDimLessOne_0.x))
    {
        neighbor_0[i32(0)] = i32(1);
    }
    var _S7 : i32 = threadIdx_1.y;
    if(_S7 == i32(0))
    {
        neighbor_0[i32(1)] = i32(-1);
    }
    if(_S7 == i32(tableParams_1.blockDimLessOne_0.y))
    {
        neighbor_0[i32(1)] = i32(1);
    }
    var _S8 : i32 = threadIdx_1.z;
    if(_S8 == i32(0))
    {
        neighbor_0[i32(2)] = i32(-1);
    }
    if(_S8 == i32(tableParams_1.blockDimLessOne_0.z))
    {
        neighbor_0[i32(2)] = i32(1);
    }
    return neighbor_0;
}

fn NvFlowTableValueToIndexWrite_0( threadIdx_2 : vec3<i32>,  v_2 : u32,  x_1 : i32,  y_1 : i32,  z_1 : i32) -> vec4<i32>
{
    var ridx_1 : vec4<i32> = vec4<i32>(((threadIdx_2.x + i32((((v_2 << (u32(1)))) | (u32(1))))) & (i32(4095))), ((threadIdx_2.y + i32((((v_2 >> (u32(10)))) | (u32(1))))) & (i32(2047))), ((threadIdx_2.z + i32((((v_2 >> (u32(20)))) | (u32(1))))) & (i32(2047))), i32((v_2 >> (u32(31)))));
    var mask_0 : i32 = (i32(~v_2) >> (u32(31)));
    ridx_1[i32(0)] = ridx_1[i32(0)] + ((mask_0 & (x_1)));
    ridx_1[i32(1)] = ridx_1[i32(1)] + ((mask_0 & (y_1)));
    ridx_1[i32(2)] = ridx_1[i32(2)] + ((mask_0 & (z_1)));
    return ridx_1;
}

fn NvFlowLocalVirtualToReal_0( _S9 : NvFlowSparseLevelParams_0,  _S10 : u32,  _S11 : vec3<i32>) -> vec4<i32>
{
    var neighbor_1 : vec3<i32> = (_S11 >> (vec3<u32>(vec3<i32>(_S9.blockDimBits_0))));
    return NvFlowTableValueToIndexRead_0(_S11, tableIn_0[NvFlowNeighborToIdx_0(_S10, neighbor_1.x, neighbor_1.y, neighbor_1.z) + _S9.blockLevelOffsetLocal_0]);
}

fn NvFlowLocalReadLinear4f_0( _S12 : texture_3d<f32>,  _S13 : sampler,  _S14 : NvFlowSparseLevelParams_0,  _S15 : u32,  _S16 : vec3<f32>) -> vec4<f32>
{
    var threadIdx_3 : vec3<i32> = NvFlowFloor_i_0(_S16);
    var _S17 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S14, _S15, threadIdx_3);
    var readIdxf_0 : vec3<f32> = vec3<f32>(_S17.xyz) + _S16 - vec3<f32>(threadIdx_3);
    var _S18 : vec4<f32>;
    if(bool(_S17.w))
    {
        _S18 = (textureSampleLevel((_S12), (_S13), (readIdxf_0 * _S14.dimInv_0), (0.0f)));
    }
    else
    {
        _S18 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    return _S18;
}

fn NvFlowLocalReadLinear1f_0( _S19 : texture_3d<f32>,  _S20 : sampler,  _S21 : NvFlowSparseLevelParams_0,  _S22 : u32,  _S23 : vec3<f32>) -> f32
{
    var threadIdx_4 : vec3<i32> = NvFlowFloor_i_0(_S23);
    var _S24 : vec4<i32> = NvFlowLocalVirtualToReal_0(_S21, _S22, threadIdx_4);
    var readIdxf_1 : vec3<f32> = vec3<f32>(_S24.xyz) + _S23 - vec3<f32>(threadIdx_4);
    var _S25 : f32;
    if(bool(_S24.w))
    {
        _S25 = (textureSampleLevel((_S19), (_S20), (readIdxf_1 * _S21.dimInv_0), (0.0f)).x);
    }
    else
    {
        _S25 = 0.0f;
    }
    return _S25;
}

fn NvFlowLocalWriteNeighbor4f_0( _S26 : NvFlowSparseLevelParams_0,  _S27 : i32,  _S28 : i32,  _S29 : i32,  _S30 : u32,  _S31 : vec3<i32>,  _S32 : vec4<f32>)
{
    var index_0 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S31, tableIn_0[NvFlowNeighborToIdx_0(_S30, _S27, _S28, _S29) + _S26.blockLevelOffsetLocal_0], _S27, _S28, _S29);
    var _S33 : vec3<u32> = vec3<u32>(index_0.xyz);
    var _S34 : vec4<f32>;
    if(bool(index_0.w))
    {
        _S34 = _S32;
    }
    else
    {
        _S34 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    }
    textureStore((densityOut_0), (_S33), (_S34));
    return;
}

fn NvFlowLocalWrite4f_0( _S35 : NvFlowSparseLevelParams_0,  _S36 : u32,  _S37 : vec3<i32>,  _S38 : vec4<f32>)
{
    var neighbor_2 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S35, _S37);
    NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), i32(0), i32(0), _S36, _S37, _S38);
    var _S39 : i32 = neighbor_2.x;
    var _S40 : bool = _S39 != i32(0);
    if(_S40)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, i32(0), i32(0), _S36, _S37, _S38);
    }
    var _S41 : i32 = neighbor_2.y;
    var _S42 : bool = _S41 != i32(0);
    if(_S42)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), _S41, i32(0), _S36, _S37, _S38);
    }
    var _S43 : i32 = neighbor_2.z;
    var _S44 : bool = _S43 != i32(0);
    if(_S44)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), i32(0), _S43, _S36, _S37, _S38);
    }
    var _S45 : bool;
    if(_S40)
    {
        _S45 = _S42;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, _S41, i32(0), _S36, _S37, _S38);
    }
    if(_S42)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, i32(0), _S41, _S43, _S36, _S37, _S38);
    }
    if(_S40)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, i32(0), _S43, _S36, _S37, _S38);
    }
    if(_S40)
    {
        _S45 = _S42;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        _S45 = _S44;
    }
    else
    {
        _S45 = false;
    }
    if(_S45)
    {
        NvFlowLocalWriteNeighbor4f_0(_S35, _S39, _S41, _S43, _S36, _S37, _S38);
    }
    return;
}

fn NvFlowLocalWriteNeighbor1f_0( _S46 : NvFlowSparseLevelParams_0,  _S47 : i32,  _S48 : i32,  _S49 : i32,  _S50 : u32,  _S51 : vec3<i32>,  _S52 : f32)
{
    var index_1 : vec4<i32> = NvFlowTableValueToIndexWrite_0(_S51, tableIn_0[NvFlowNeighborToIdx_0(_S50, _S47, _S48, _S49) + _S46.blockLevelOffsetLocal_0], _S47, _S48, _S49);
    var _S53 : vec3<u32> = vec3<u32>(index_1.xyz);
    var _S54 : f32;
    if(bool(index_1.w))
    {
        _S54 = _S52;
    }
    else
    {
        _S54 = 0.0f;
    }
    textureStore((voxelWeightOut_0), (_S53), vec4<f32>((_S54), 0, 0, 1));
    return;
}

fn NvFlowLocalWrite1f_0( _S55 : NvFlowSparseLevelParams_0,  _S56 : u32,  _S57 : vec3<i32>,  _S58 : f32)
{
    var neighbor_3 : vec3<i32> = NvFlowLocalComputeNeighbor_0(_S55, _S57);
    NvFlowLocalWriteNeighbor1f_0(_S55, i32(0), i32(0), i32(0), _S56, _S57, _S58);
    var _S59 : i32 = neighbor_3.x;
    var _S60 : bool = _S59 != i32(0);
    if(_S60)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, _S59, i32(0), i32(0), _S56, _S57, _S58);
    }
    var _S61 : i32 = neighbor_3.y;
    var _S62 : bool = _S61 != i32(0);
    if(_S62)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, i32(0), _S61, i32(0), _S56, _S57, _S58);
    }
    var _S63 : i32 = neighbor_3.z;
    var _S64 : bool = _S63 != i32(0);
    if(_S64)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, i32(0), i32(0), _S63, _S56, _S57, _S58);
    }
    var _S65 : bool;
    if(_S60)
    {
        _S65 = _S62;
    }
    else
    {
        _S65 = false;
    }
    if(_S65)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, _S59, _S61, i32(0), _S56, _S57, _S58);
    }
    if(_S62)
    {
        _S65 = _S64;
    }
    else
    {
        _S65 = false;
    }
    if(_S65)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, i32(0), _S61, _S63, _S56, _S57, _S58);
    }
    if(_S60)
    {
        _S65 = _S64;
    }
    else
    {
        _S65 = false;
    }
    if(_S65)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, _S59, i32(0), _S63, _S56, _S57, _S58);
    }
    if(_S60)
    {
        _S65 = _S62;
    }
    else
    {
        _S65 = false;
    }
    if(_S65)
    {
        _S65 = _S64;
    }
    else
    {
        _S65 = false;
    }
    if(_S65)
    {
        NvFlowLocalWriteNeighbor1f_0(_S55, _S59, _S61, _S63, _S56, _S57, _S58);
    }
    return;
}

@compute
@workgroup_size(128, 1, 1)
fn main(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>, @builtin(workgroup_id) groupID_0 : vec3<u32>)
{
    var _S66 : u32 = dispatchThreadID_0.x;
    if(_S66 >= (globalParamsIn_0.table_0.threadsPerBlock_0))
    {
        return;
    }
    var threadIdx_5 : vec3<i32> = NvFlowComputeThreadIdx_0(unpackStorage_0(globalParamsIn_0.table_0), _S66);
    var blockIdx_1 : u32 = groupID_0.y + globalParamsIn_0.blockIdxOffset_0;
    var fineThreadIdxf_0 : vec3<f32> = vec3<f32>(2.0f) * (vec3<f32>(threadIdx_5) + vec3<f32>(0.5f));
    var _S67 : vec4<f32> = NvFlowLocalReadLinear4f_0(densityIn_0, samplerIn_0, unpackStorage_0(globalParamsIn_0.sampleTable_0), blockIdx_1, fineThreadIdxf_0);
    var _S68 : f32 = NvFlowLocalReadLinear1f_0(voxelWeightIn_0, samplerIn_0, unpackStorage_0(globalParamsIn_0.sampleTable_0), blockIdx_1, fineThreadIdxf_0);
    var voxelWeight_0 : f32;
    var density4_0 : vec4<f32>;
    if(_S68 > 0.0f)
    {
        var density4_1 : vec4<f32> = _S67 * vec4<f32>((1.0f / _S68));
        voxelWeight_0 = 1.0f;
        density4_0 = density4_1;
    }
    else
    {
        voxelWeight_0 = _S68;
        density4_0 = _S67;
    }
    NvFlowLocalWrite4f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5, density4_0);
    NvFlowLocalWrite1f_0(unpackStorage_0(globalParamsIn_0.table_0), blockIdx_1, threadIdx_5, voxelWeight_0);
    return;
}

