#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel) <https://github.com/BTSpaniel>
#
# SPDX-License-Identifier: LicenseRef-ParticleRealms-Alpha
"""Generate browser-importable JS modules for raw compute WGSL sources."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[2]
COMPUTE_SHADER_DIR = REPO_ROOT / "engine/core/shaders/compute"
COMPUTE_SHADER_ID_PREFIX = "engine/core/shaders/compute"
METADATA_TARGET = COMPUTE_SHADER_DIR / "compute_shader_sources.generated.js"


@dataclass(frozen=True)
class ComputeShaderSource:
    stem: str
    export_name: str
    source_path_export_name: str
    registry_id: str
    tags: tuple[str, ...]

    @property
    def source_path(self) -> Path:
        return COMPUTE_SHADER_DIR / f"{self.stem}.wgsl"

    @property
    def target_path(self) -> Path:
        return COMPUTE_SHADER_DIR / f"{self.stem}.generated.js"

    @property
    def source_id(self) -> str:
        return f"{COMPUTE_SHADER_ID_PREFIX}/{self.stem}.wgsl"

    @property
    def target_id(self) -> str:
        return f"{COMPUTE_SHADER_ID_PREFIX}/{self.stem}.generated.js"


def export_name_for_stem(stem: str) -> str:
    if stem == "dispatch_gen":
        return "DISPATCH_GEN_SHADER"
    return f"{stem.upper()}_WGSL"


def source_path_export_name_for_stem(stem: str) -> str:
    if stem == "dispatch_gen":
        return "DISPATCH_GEN_SHADER_SOURCE_PATH"
    return f"{export_name_for_stem(stem)}_SOURCE_PATH"


REGISTRY_ID_OVERRIDES = {
    "dispatch_gen": "dispatch_gen_runtime",
}

TAG_OVERRIDES = {
    "bezier_distance": ("bezier", "compute"),
    "dispatch_gen": ("dispatch", "compute"),
    "doppler_color": ("doppler", "compute"),
    "fdtd_update": ("fdtd", "compute"),
    "flood_fill": ("flood-fill", "compute"),
    "mc33_mesher": ("mc33", "compute"),
    "mpm_g2p": ("mpm", "compute"),
    "mpm_grid": ("mpm", "compute"),
    "mpm_p2g": ("mpm", "compute"),
    "pbd_solve": ("pbd", "compute"),
    "ptc_modulate": ("ptc", "compute"),
    "volume_raymarch": ("volume", "compute"),
}


def registry_id_for_stem(stem: str) -> str:
    return REGISTRY_ID_OVERRIDES.get(stem, f"{stem}_core")


def tags_for_stem(stem: str) -> tuple[str, ...]:
    if stem in TAG_OVERRIDES:
        return TAG_OVERRIDES[stem]
    return (stem.split("_", 1)[0].replace("-", "_"), "compute")


def discover_compute_shader_sources() -> tuple[ComputeShaderSource, ...]:
    sources = []
    for path in sorted(COMPUTE_SHADER_DIR.glob("*.wgsl"), key=lambda item: item.name):
        stem = path.stem
        sources.append(
            ComputeShaderSource(
                stem=stem,
                export_name=export_name_for_stem(stem),
                source_path_export_name=source_path_export_name_for_stem(stem),
                registry_id=registry_id_for_stem(stem),
                tags=tags_for_stem(stem),
            )
        )
    return tuple(sources)


def generated_module_body(source: ComputeShaderSource) -> str:
    wgsl = source.source_path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    payload = json.dumps(wgsl, ensure_ascii=True)
    return "\n".join(
        [
            "// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel) <https://github.com/BTSpaniel>",
            "//",
            "// SPDX-License-Identifier: LicenseRef-ParticleRealms-Alpha",
            "",
            "// Generated by engine/tools/generate_compute_shader_modules.py.",
            f"// Source: {source.source_id}",
            "",
            f"export const {source.source_path_export_name} = '{source.source_id}';",
            f"export const {source.export_name} = {payload};",
            "",
            f"export default {source.export_name};",
            "",
        ]
    )


def generated_metadata_body(sources: Sequence[ComputeShaderSource]) -> str:
    lines = [
        "// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel) <https://github.com/BTSpaniel>",
        "//",
        "// SPDX-License-Identifier: LicenseRef-ParticleRealms-Alpha",
        "",
        "// Generated by engine/tools/generate_compute_shader_modules.py.",
        "",
        "export const COMPUTE_SHADER_SOURCE_MODULES = Object.freeze({",
    ]
    for source in sources:
        lines.extend(
            [
                f"  {json.dumps(source.stem)}: Object.freeze({{",
                f"    sourcePath: {json.dumps(source.source_id)},",
                f"    modulePath: {json.dumps(source.target_id)},",
                f"    exportName: {json.dumps(source.export_name)},",
                f"    sourcePathExportName: {json.dumps(source.source_path_export_name)},",
                f"    registryId: {json.dumps(source.registry_id)},",
                f"    tags: Object.freeze({json.dumps(list(source.tags))}),",
                "  }),",
            ]
        )
    lines.extend(
        [
            "});",
            "",
            "export default COMPUTE_SHADER_SOURCE_MODULES;",
            "",
        ]
    )
    return "\n".join(lines)


def selected_sources(only: Iterable[str] | None = None) -> tuple[ComputeShaderSource, ...]:
    compute_shader_sources = discover_compute_shader_sources()
    if only is None:
        return compute_shader_sources
    wanted = set(only)
    sources = tuple(source for source in compute_shader_sources if source.stem in wanted)
    missing = sorted(wanted - {source.stem for source in sources})
    if missing:
        raise ValueError(f"Unknown compute shader source(s): {', '.join(missing)}")
    return sources


def generate(only: Iterable[str] | None = None, include_metadata: bool = True) -> None:
    sources = selected_sources(only)
    for source in sources:
        source.target_path.write_text(generated_module_body(source), encoding="utf-8", newline="\n")
    if include_metadata:
        METADATA_TARGET.write_text(generated_metadata_body(discover_compute_shader_sources()), encoding="utf-8", newline="\n")


def generated_paths(only: Iterable[str] | None = None, include_metadata: bool = True) -> tuple[Path, ...]:
    paths = tuple(source.target_path for source in selected_sources(only))
    if include_metadata:
        return (*paths, METADATA_TARGET)
    return paths


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any generated module is stale")
    parser.add_argument("--only", action="append", default=None, help="only generate one source stem; may be repeated")
    parser.add_argument("--no-metadata", action="store_true", help="skip compute_shader_sources.generated.js")
    args = parser.parse_args(argv)

    include_metadata = not args.no_metadata
    paths = generated_paths(args.only, include_metadata)
    before = {path: path.read_text(encoding="utf-8") if path.exists() else None for path in paths}
    generate(args.only, include_metadata)

    if args.check:
        stale = [str(path.relative_to(REPO_ROOT)).replace("\\", "/") for path in paths if before[path] != path.read_text(encoding="utf-8")]
        if stale:
            raise SystemExit("generated compute shader module(s) were stale: " + ", ".join(stale))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
